address_de = R6Class(
  "address_de",
  inherit = address_init,
  cloneable = FALSE,
  private = list(
    countries = c(
      "Afghanistan", "Alandinseln", "Albanien", "Algerien",
      "Amerikanisch-Ozeanien", "Amerikanisch-Samoa",
      "Amerikanische Jungferninseln", "Andorra",
      "Angola", "Anguilla", "Antarktis", "Antigua und Barbuda",
      "Argentinien", "Armenien", "Aruba", "Aserbaidschan",
      "Australien", "Bahamas", "Bahrain",
      "Bangladesch", "Barbados", "Belarus", "Belgien", "Belize",
      "Benin", "Bermuda", "Bhutan", "Bolivien", "Bosnien und Herzegowina",
      "Botsuana", "Bouvetinsel", "Brasilien", "Britische Jungferninseln",
      "Britisches Territorium im Indischen Ozean", "Brunei Darussalam",
      "Bulgarien", "Burkina Faso", "Burundi", "Chile", "China",
      "Cookinseln", "Costa Rica", "C\u00f4te d\u2019Ivoire",
      "Demokratische Republik Kongo", "Demokratische Volksrepublik Korea",
      "Deutschland", "Dominica", "Dominikanische Republik", "Dschibuti",
      "D\u00e4nemark", "Ecuador", "El Salvador", "Eritrea",
      "Estland", "Falklandinseln", "Fidschi", "Finnland", "Frankreich",
      "Franz\u00f6sisch-Guayana", "Franz\u00f6sisch-Polynesien", "F\u00e4r\u00f6er",
      "Gabun", "Gambia", "Georgien", "Ghana", "Gibraltar", "Grenada",
      "Griechenland", "Gr\u00f6nland", "Guadeloupe", "Guam", "Guatemala", "Guernsey",
      "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard- und McDonald-Inseln",
      "Honduras", "Indien", "Indonesien", "Irak", "Iran", "Irland", "Island",
      "Isle of Man", "Israel", "Italien", "Jamaika", "Japan", "Jemen", "Jersey",
      "Jordanien", "Kaimaninseln", "Kambodscha", "Kamerun", "Kanada", "Kap Verde",
      "Kasachstan", "Katar", "Kenia", "Kirgisistan", "Kiribati", "Kokosinseln",
      "Kolumbien", "Komoren", "Kongo", "Kroatien", "Kuba", "Kuwait",
      "Laos", "Lesotho", "Lettland", "Libanon", "Liberia", "Libyen", "Liechtenstein",
      "Litauen", "Luxemburg", "Madagaskar", "Malawi", "Malaysia",
      "Malediven", "Mali", "Malta", "Marokko", "Marshallinseln", "Martinique",
      "Mauretanien", "Mauritius", "Mayotte", "Mazedonien", "Mexiko",
      "Mikronesien", "Monaco", "Mongolei", "Montenegro", "Montserrat",
      "Mosambik", "Myanmar", "Namibia", "Nauru", "Nepal", "Neukaledonien",
      "Neuseeland", "Nicaragua", "Niederlande", "Niederl\u00e4ndische Antillen",
      "Niger", "Nigeria", "Niue", "Norfolkinsel", "Norwegen", "N\u00f6rdliche Marianen",
      "Oman", "Osttimor", "Pakistan", "Palau", "Pal\u00e4stinensische Gebiete",
      "Panama", "Papua-Neuguinea", "Paraguay", "Peru", "Philippinen", "Pitcairn",
      "Polen", "Portugal", "Puerto Rico", "Republik Korea", "Republik Moldau",
      "Ruanda", "Rum\u00e4nien", "Russische F\u00f6deration", "R\u00e9union",
      "Salomonen", "Sambia", "Samoa", "San Marino", "Saudi-Arabien", "Schweden",
      "Schweiz", "Senegal", "Serbien", "Serbien und Montenegro", "Seychellen",
      "Sierra Leone", "Simbabwe", "Singapur", "Slowakei", "Slowenien", "Somalia",
      "Sonderverwaltungszone Hongkong", "Sonderverwaltungszone Macao", "Spanien",
      "Sri Lanka", "St. Barth\u00e9lemy", "St. Helena", "St. Kitts und Nevis",
      "St. Lucia", "St. Martin", "St. Pierre und Miquelon",
      "St. Vincent und die Grenadinen", "Sudan", "Suriname",
      "Svalbard und Jan Mayen", "Swasiland", "Syrien",
      "S\u00e3o Tom\u00e9 und Pr\u00edncipe",
      "S\u00fcdafrika", "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln",
      "Tadschikistan", "Taiwan", "Tansania", "Thailand", "Togo", "Tokelau",
      "Tonga", "Trinidad und Tobago", "Tschad", "Tschechische Republik",
      "Tunesien", "Turkmenistan", "Turks- und Caicosinseln", "Tuvalu", "T\u00fcrkei",
      "Uganda", "Ukraine", "Ungarn", "Uruguay", "Usbekistan", "Vanuatu",
      "Vatikanstadt", "Venezuela", "Vereinigte Arabische Emirate", "Vereinigte Staaten",
      "Vereinigtes K\u00f6nigreich", "Vietnam", "Wallis und Futuna",
      "Weihnachtsinsel", "Westsahara", "Zentralafrikanische Republik", "Zypern",
      "\u00c4gypten", "\u00c4quatorialguinea", "\u00c4thiopien",
      "\u00c4u\u00dferes Ozeanien", "\u00d6sterreich")
  )
)
