## person ----------------------------
person_de_CH = R6Class(
  "person_de_CH",
  inherit = person_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}',
      '{first_name} {last_name}-{last_name}',
      '{first_name_female} {last_name} {last_name}',
      '{prefix} {first_name} {last_name}'
    ),

    first_names_male = c(
      "Peter", "Hans", "Daniel", "Thomas", "Andreas", "Martin",
      "Markus", "Michael", "Christian", "Stefan", "Walter", "Urs",
      "Marco", "Bruno", "Patrick", "Werner", "Ren\u00e9", "Marcel",
      "Beat", "Roland", "Kurt", "Josef", "David", "Simon", "Rolf",
      "Heinz", "Rudolf", "Paul", "Roger", "Christoph", "Ernst",
      "Pascal", "Adrian", "Lukas", "Marc", "Robert", "Reto", "Manuel",
      "Fabian", "Alfred", "Philipp", "J\u00fcrg", "Matthias",
      "Stephan", "Franz", "Anton", "Andr\u00e9", "Alexander", "Samuel",
      "Jan", "Johann", "Luca", "Max", "Roman", "Mario", "Fritz",
      "Ulrich", "Dominik", "Karl", "Tobias", "Oliver", "Florian",
      "Antonio", "Benjamin", "Sandro", "Bernhard", "Jonas", "Felix",
      "Raphael", "Kevin", "Erich", "Fabio", "Jakob", "Sven", "Dario",
      "Giuseppe", "Remo", "Nicolas", "Albert", "Erwin", "Richard",
      "Nico", "Michel", "Jos\u00e9", "Claudio", "Tim", "Noah", "Joel",
      "Heinrich", "J\u00f6rg", "Robin", "Sebastian", "Armin", "Guido",
      "Silvan", "Lars", "Ivan", "Julian", "Alois", "Francesco",
      "Sascha", "Dominic", "Johannes", "Georg", "Gabriel", "Manfred",
      "Herbert", "Otto", "Alessandro", "Gerhard", "Patrik", "Gian",
      "Mathias", "Leon", "Willi", "Eduard", "Nicola", "Hugo", "Ali",
      "Yves", "Elias", "Hermann", "Philippe", "Leo", "Emil", "Frank",
      "Dieter", "Friedrich", "Luis", "Giovanni", "Niklaus", "Alex",
      "Roberto", "Rafael", "Hanspeter", "Diego", "Nils", "Leandro",
      "Ramon", "Severin", "Salvatore", "Mike", "Alain", "Timo",
      "Carlos", "Arthur", "Yannick", "Eric", "Angelo", "Ivo",
      "Wolfgang", "Matteo", "Jo\u00ebl", "Andrin", "Pius", "Moritz",
      "Valentin", "Louis", "Wilhelm", "Renato", "Levin", "Silvio",
      "Willy", "Andrea", "Jonathan", "Jean", "Livio", "Loris",
      "Damian", "Theodor", "Michele", "Vincenzo", "Elia", "Ralph",
      "Klaus", "Eugen", "Mark", "Konrad", "Denis", "Norbert", "Lorenz",
      "Viktor", "Mehmet", "Marko", "Kilian", "Hans-Peter",
      "C\u00e9dric", "Ralf", "Aaron", "Maximilian", "Carlo", "Alessio",
      "Olivier", "J\u00fcrgen", "Luigi", "Philip", "Lucas", "Mauro",
      "Janis", "Cyrill", "Linus", "Davide", "Othmar", "Flavio", "Nino",
      "Arnold", "Nick", "Rainer", "Domenico", "Adolf", "Emanuel",
      "Oskar", "Ben", "Joshua", "Leonardo", "Franco", "Pierre", "John",
      "Gregor", "Fernando", "Marius", "Claude", "Edwin", "Colin",
      "Mustafa", "Pedro", "Stefano", "Sergio", "Dominique", "Juan",
      "Nikola", "Enrico", "Jens", "Daniele", "Thierry", "Jose", "Liam",
      "Francisco", "Ricardo", "Rico", "Christof", "Aleksandar",
      "Dennis", "Mohamed", "Joseph", "Charles", "Noel", "Miguel",
      "Laurin", "Milan", "Reinhard", "Lionel", "Dragan", "Hasan",
      "Paulo", "Edgar", "Silas", "Hubert", "Helmut", "Ibrahim",
      "Ruben", "Timon", "Vincent", "Christopher", "Finn", "Ronny",
      "Kaspar", "Mattia", "Lorenzo", "Pietro", "Bj\u00f6rn",
      "Hansruedi", "Gottfried", "Joachim", "Benno", "Harald", "Jorge",
      "Cedric", "Nevio", "Paolo", "Gianluca", "Boris", "Kai",
      "Maurizio", "Steven", "Mischa", "Patric", "Zoran", "Mirco",
      "Marvin", "Dirk", "Benedikt", "Uwe", "Hans-Rudolf", "Maurice",
      "Massimo", "Hansj\u00f6rg", "Jeremy", "Niklas", "Ahmet",
      "Fridolin", "Dejan", "Goran", "Micha", "Mohammad", "Ronald",
      "Bernd", "Mirko", "Erik", "Jason", "Tiago", "Riccardo",
      "J\u00e9r\u00f4me", "Igor", "Siegfried", "Pasquale", "Andri",
      "Tom", "Ueli", "Amir", "Cyril", "Adriano", "Alberto",
      "Ferdinand", "Justin", "Raffael", "Julien", "Lenny", "Luka",
      "Marcus", "Pirmin", "Janik", "Julius", "Meinrad", "Adam",
      "James", "H\u00fcseyin", "Alexandre", "Rocco", "Luc", "Victor",
      "Jo\u00e3o", "Andres", "Luan", "Flurin", "Filip", "Ismail",
      "Danilo", "Laurent", "Raffaele", "Ahmed", "G\u00fcnter", "Joao",
      "Rui", "Xaver", "Fabrizio", "William", "Vito", "Miroslav",
      "Lino", "Albin", "Jean-Pierre", "Basil", "Till", "Horst",
      "Romeo", "Aldo", "Murat", "Harry", "Alfons", "Pablo", "Bernard",
      "No\u00e9", "Luciano", "August", "Levi", "Nando", "Fabrice",
      "Raymond", "Jamie", "Georges", "Steffen", "Serge", "Cristian",
      "Samir", "Ant\u00f3nio", "Marlon", "Omar", "Lian", "Oscar",
      "Yanick", "Armando", "Nikolaus", "Dylan", "Hannes", "Sacha",
      "Nuno", "Toni", "Dino", "Elmar", "Arno", "Joaquim", "Sasa",
      "Henry", "Vladimir", "Arben", "Ryan", "Bekim", "Milos",
      "Giorgio", "Ludwig", "Leonard", "Adnan", "Gilbert", "Yannik",
      "Aron", "Iwan", "Maik", "Dimitri", "Erhard", "Fran\u00e7ois",
      "Gabriele", "Sami", "Elio", "Antonino", "Fynn", "Simone",
      "Andrew", "Alan", "Nenad", "Fr\u00e9d\u00e9ric", "Etienne",
      "Janick", "Steve", "Christophe", "Gianni", "Urban", "Anthony",
      "Deniz", "Jon", "Alejandro", "Axel", "Ian", "Theo", "Andrej",
      "Brian", "Lucien", "Gino", "Clemens", "Yanik", "Adem", "Emir",
      "Tino", "Miro", "Enis", "Gregory", "Danijel", "Osman", "Michal",
      "Carmine", "Orlando", "Enes", "Giuliano", "Timothy", "Fredy",
      "Besnik", "Vitor", "Holger", "Kim", "Eduardo", "Petar",
      "Jacques", "Karim", "Darko", "Gustav", "Emilio", "Mateo",
      "Alban", "Marek", "Oswald", "No\u00ebl", "Donato", "Mohammed",
      "Roy", "Kay", "Nathan", "Enea", "Silvano", "Josip", "Valerio",
      "Artur", "Besim", "Mika", "Torsten", "Romano", "Heiko", "Yusuf",
      "Chris", "Naim", "Burim", "Gaetano", "Hans-Ulrich", "Olaf",
      "Maurus", "Volker", "Jean-Claude", "Henri", "Nik", "Rodrigo",
      "Florin", "Mael", "Amar", "Agron", "Muhamed", "Tristan", "Valon",
      "Ahmad", "Ilir", "Javier", "Lorin", "Yanis", "Fatmir", "Bajram",
      "Carmelo", "Agim", "Enzo", "Moreno", "Cornel", "Andy", "Jeton",
      "Blerim", "Bojan", "Federico", "Attila", "Juri", "Tomas",
      "Valentino", "Ismet", "Jannik", "Ruedi", "Afrim", "Yannic",
      "Ramadan", "Alfredo", "Josua", "Cosimo", "Gerardo", "Bastian",
      "Filippo", "Raoul", "Halil", "Yann", "Georgios", "Jannis",
      "Nicholas", "Sean", "Wilfried", "G\u00fcnther", "Dusan", "Beda",
      "Gerold", "Gottlieb", "Filipe", "Ilija", "Carl", "Ardian",
      "Marcello", "Enver", "Dean", "Dion", "Tenzin", "Zeljko",
      "Carsten", "Diogo", "Alen", "Egon", "Aurel", "Yannis", "Edin",
      "Hans-J\u00f6rg", "Tomislav", "Mohamad", "Bujar", "Raul",
      "Slobodan", "Driton", "Maxim", "Francis", "Hansueli", "Ivica",
      "Nelson", "Emanuele", "Konstantin", "Fred", "Naser", "Gerd",
      "Kristian", "Selim", "Corsin", "Dietmar", "George", "Piotr",
      "Giacomo", "Ingo", "Andre", "Malik", "Lothar", "Jochen", "Sinan",
      "Thorsten", "Tiziano", "Gilles", "Avni", "Jann", "Lio", "Niels",
      "Emmanuel", "Leonhard", "Lorik", "Aurelio", "Gion", "Liridon",
      "Marino", "Can", "Kenan", "Ewald", "St\u00e9phane", "Dalibor",
      "Jozef", "Noe", "Bryan", "Dan", "Santiago", "Damiano", "Arian",
      "Rosario", "Giancarlo", "Nathanael", "Emre", "Stephen", "Hassan",
      "Jovan", "Egzon", "Reinhold", "Tomasz", "Vittorio", "Patrice",
      "Tibor", "Jost", "Elvis", "Lean", "Henrik", "Musa", "Noa", "Udo",
      "Almir", "Van", "Dietrich", "Mladen", "Armend", "Arlind", "Milo",
      "Arsim", "Bashkim", "Dimitrios", "Matthew", "\u00d6mer",
      "Abdullah", "Hakan", "Gerald", "Tommaso", "Joris", "Damir",
      "Vinzenz", "Marcos", "Rapha\u00ebl", "Ennio", "Melvin",
      "Leander", "Kuno", "Massimiliano", "Ma\u00ebl", "Anto", "Branko",
      "Fadil", "Kemal", "Muhammed", "Hendrik", "Pawel", "Jeremias",
      "L\u00e9on", "Leano", "R\u00e9my", "Giulio", "Muhamet", "Lulzim",
      "Konstantinos", "Pavel", "Rinaldo", "Omer", "Simeon",
      "Gian-Luca", "Maurin", "Antoine", "Frederik", "Janic", "Faton",
      "Marcin", "S\u00e9bastien", "Cem", "Curdin", "Endrit", "Nemanja",
      "Karsten", "Renzo", "Jerome", "Krzysztof", "Jeffrey",
      "Sebastiano", "Ernesto", "Lazar", "Ramazan", "G\u00e9rard",
      "Ajan", "Emin", "Ioannis", "Jesus", "Alfonso", "Yasin", "Jaron",
      "Alexis", "Orhan", "Artan", "Morris", "Angel", "Janosch", "Rene",
      "Shaban", "Jakub", "Lo\u00efc", "Kristijan", "Enrique",
      "Skender", "Gianfranco", "Mathieu", "Xavier", "Mathis", "Didier",
      "Arif", "Hamza", "Jacob", "Leart", "Laszlo", "Predrag", "Mentor",
      "Wendelin", "Lu\u00eds", "Constantin", "Erion", "Berat",
      "Dardan", "Melchior", "Serkan", "Dorian", "Eren", "Fatih",
      "Luzius", "Nebojsa", "Metin", "Diar", "Rino", "Ekrem", "Isa",
      "Jetmir", "Edward", "Nikolaos", "Gazmend", "Haris", "Kian",
      "Ensar", "Mirsad", "Danny", "Senad", "Donat", "Bilal", "Ron",
      "Nael", "Guy", "Julio", "Kujtim", "Kushtrim", "Lutz",
      "Balthasar", "Rouven", "Lias", "Neil", "Abraham", "Magnus",
      "S\u00e9rgio", "Hansj\u00fcrg", "Said", "Ismael", "Detlef",
      "Umberto", "Admir", "Jayden", "Jaime", "Karl-Heinz",
      "Tom\u00e1s", "Florim", "Achim", "Devin", "Maxime", "Fitim",
      "Jean-Marc", "Rayan", "Sadik", "Tarik", "Abdul", "Jack",
      "Mergim", "Nelio", "Sam", "Flamur", "Ignaz", "Samuele", "Tony",
      "Petr", "Waldemar", "Arda", "Ardit", "Lukasz", "Milorad",
      "Nicolai", "Ramiz", "Aziz", "Kamil", "Rinor", "Safet", "Piero",
      "Erkan", "Niko", "Zsolt", "Ernest", "Miodrag", "Alvaro",
      "Astrit", "Edmund", "Jules", "Cristiano", "Ivano", "Kenneth",
      "Saverio", "Semir", "Burak", "Theophil", "Altin", "Andrzej",
      "Jonah", "Jiri", "Salih", "Zolt\u00e1n", "Ferenc", "Grzegorz",
      "Irfan", "Johan", "Kaan", "S\u00fcleyman", "Hussein", "Rexhep",
      "Besart", "Janos", "Labinot", "Onur", "Stjepan", "Domenic",
      "Siro", "Abel", "Florent", "Christos", "Swen", "Branislav",
      "Mato", "Amin", "Matej", "Slavko", "Jusuf", "Luke", "Slavisa",
      "Erol", "Gabor", "Jasmin", "Visar", "Sinisa", "Isidor", "Merlin",
      "Claus", "Marin", "Zoltan", "Muhammad", "Neo", "Zeno", "Istvan",
      "Adis", "Edon", "Gil", "Leopold", "Hartmut", "Raimund", "Ken",
      "Csaba", "Kerim", "Norman", "Lucio", "L\u00e1szl\u00f3",
      "Marjan", "Damjan", "Eugenio", "Domingos", "Reiner", "Augusto",
      "Gzim", "Nazmi", "Laurenz", "Zlatko", "Jaroslav", "Nevin",
      "Biagio", "Felice", "Balz", "Boban", "Marcelo", "Caspar",
      "Ledion", "Rodolfo", "Aldin", "Matti", "Remzi", "Ljubisa", "Til",
      "P\u00e9ter", "Umut", "Baris", "Lirim", "Mehdi", "Edmond",
      "Gon\u00e7alo", "Jasin", "Niclas", "Jordan", "Mahmoud",
      "Stanislav", "Cornelius", "Jona", "Khaled", "Quentin",
      "G\u00f6khan", "Imer", "Volkan", "Harun", "Miran", "Damien",
      "Gennaro", "Jari", "Marian", "R\u00fcdiger", "Albrecht", "Mile",
      "Thiago", "Yvan", "Alwin", "Gani", "Mahmut", "Pero", "Evan",
      "Fisnik", "Idriz", "Sergej", "Sabri", "Felipe", "Istv\u00e1n",
      "Dave", "Hans-J\u00fcrgen", "Jean-Luc", "Kastriot", "Mariusz",
      "Arne", "Faruk", "Gebhard", "German", "Tam\u00e1s", "Anes",
      "Arbnor", "Mats", "Drilon", "F\u00e1bio", "Mihajlo", "Sedat",
      "Tahir"),

    # extracted from https://www.bfs.admin.ch/bfs/it/home/statistiche/popolazione/nascite-decessi/nomi-svizzera.assetdetail.3243318.html # noqa E501
    first_names_female = c(
      "Maria", "Anna", "Ursula", "Ruth", "Elisabeth", "Sandra", "Monika",
      "Claudia", "Verena", "Nicole", "Barbara", "Silvia", "Andrea",
      "Marie", "Daniela", "Christine", "Karin", "Marianne", "Erika",
      "Margrit", "Brigitte", "Susanne", "Rita", "Laura", "Sarah",
      "Katharina", "Rosmarie", "Esther", "Heidi", "Anita", "Manuela",
      "Rosa", "Doris", "Sonja", "Beatrice", "Yvonne", "Gertrud",
      "Jacqueline", "Sara", "Irene", "Ana", "Franziska", "Cornelia",
      "Fabienne", "Gabriela", "Patricia", "Martina", "Julia", "Edith",
      "Eva", "Isabelle", "Sabrina", "Nathalie", "Alexandra", "Corinne",
      "Angela", "Melanie", "Alice", "Nadine", "Jessica", "Denise",
      "Elena", "Vanessa", "Simone", "Anne", "Regula", "Susanna", "Carmen",
      "Sophie", "Caroline", "Emma", "Nina", "Tanja", "Catherine",
      "Sabine", "Lara", "Petra", "Lea", "C\u00e9line", "Jasmin",
      "Therese", "Stefanie", "Johanna", "Nadia", "Tamara", "Chantal",
      "Martha", "Michelle", "Christina", "Marina", "Adelheid", "Dora",
      "Monique", "Rahel", "Hedwig", "Lisa", "Janine", "Pia", "Anja",
      "Elsbeth", "Madeleine", "Eveline", "Judith", "Diana",
      "Fran\u00e7oise", "Charlotte", "Maja", "Eliane", "Renate",
      "Christiane", "Mich\u00e8le", "Jennifer", "Bettina", "Chiara",
      "Bernadette", "Aline", "Carla", "Helena", "Brigitta", "Mirjam",
      "Theresia", "Astrid", "Nadja", "Jana", "Selina", "Priska", "Lena",
      "Stephanie", "Lucia", "Linda", "Regina", "Agnes", "Olivia", "Sonia",
      "Val\u00e9rie", "Klara", "Ramona", "Lina", "Elsa", "Helene",
      "Monica", "Iris", "Hanna", "Valentina", "Annemarie", "Elisa",
      "Margrith", "Dominique", "Beatrix", "Cristina", "Paula",
      "Magdalena", "Livia", "Sofia", "Patrizia", "Liliane", "Nelly",
      "Marion", "Ida", "Alina", "Isabel", "Vera", "St\u00e9phanie",
      "Giulia", "Leonie", "Jeannette", "Christa", "Alessia",
      "V\u00e9ronique", "Myriam", "Emilie", "Olga", "Nora", "Julie",
      "Sylvia", "Margaretha", "Claudine", "Marlise", "Miriam", "Sibylle",
      "Sylvie", "Lydia", "Katja", "Lorena", "Jolanda", "Rebecca", "Mia",
      "Irma", "Larissa", "Luana", "Martine", "Deborah", "Francesca",
      "Veronika", "Isabella", "Noemi", "Ingrid", "Frieda", "Suzanne",
      "Liselotte", "Michaela", "Florence", "Evelyne", "Hildegard",
      "Corina", "Danielle", "Laurence", "Carole", "Milena", "C\u00e9cile",
      "Mara", "Luzia", "Sandrine", "Gisela", "Simona", "M\u00e9lanie",
      "B\u00e9atrice", "Marta", "Antonia", "Erna", "Gabriele", "Katrin",
      "Kathrin", "Melissa", "Camille", "Adriana", "Fiona", "Lucie",
      "Natalie", "Teresa", "Renata", "Josiane", "Sophia", "Clara",
      "Luisa", "Silvana", "Jeannine", "Pascale", "H\u00e9l\u00e8ne",
      "Emilia", "Jo\u00eblle", "Gabriella", "Maya", "Marianna", "Ines",
      "L\u00e9a", "Claire", "Marisa", "Sina", "Lia", "Paola", "Mathilde",
      "Sabina", "Alessandra", "Ivana", "Anne-Marie", "Elvira", "Bianca",
      "Samira", "Cindy", "Am\u00e9lie", "Chlo\u00e9", "Kim", "Victoria",
      "Annette", "Angelina", "Dorothea", "Antoinette", "Tina", "Tania",
      "Angelika", "Valeria", "Flavia", "Margaritha", "Rachel",
      "Marguerite", "Jeanne", "Yvette", "Natalia", "Alicia", "Giovanna",
      "Mireille", "Liliana", "Pauline", "Seraina", "Elodie", "Ariane",
      "Helga", "Zo\u00e9", "Natascha", "Muriel", "Francine", "Joana",
      "Melina", "Aur\u00e9lie", "Thi", "Giuseppina", "Tatiana",
      "Margareta", "Louise", "Marija", "Debora", "Salome", "Viviane",
      "Fanny", "Katia", "Carolina", "Irina", "Bertha", "Marlene",
      "No\u00e9mie", "Amanda", "Sarina", "Marlies", "Lilian",
      "Ir\u00e8ne", "Laetitia", "Kristina", "Jasmine", "Ella", "Jenny",
      "Gabrielle", "Carmela", "Manon", "Helen", "Fatima", "Stefania",
      "Virginie", "Ladina", "Jelena", "Berta", "Antonella", "Rebekka",
      "Audrey", "Ana\u00efs", "Tatjana", "Annina", "Margot", "Carina",
      "Samantha", "Evelyn", "Annamarie", "Tiziana", "Arlette", "Emily",
      "Kerstin", "Svenja", "Caterina", "Christelle", "Saskia", "Elin",
      "Lilly", "Anouk", "Rose", "Fatma", "Lynn", "Elina", "Colette",
      "Josette", "Leila", "Gerda", "Susana", "Genevi\u00e8ve",
      "D\u00e9sir\u00e9e", "Naomi", "Stella", "Romina", "Delphine",
      "Aurora", "Estelle", "Juliette", "Tabea", "Anina",
      "Th\u00e9r\u00e8se", "Mariana", "Beatriz", "Hilda", "Lotti",
      "S\u00e9verine", "Delia", "Ronja", "Gina", "Mila", "Antonietta",
      "Veronica", "Aleksandra", "Gis\u00e8le", "Lidia", "Natacha",
      "Laure", "Pamela", "Rosemarie", "Marie-Louise", "Jael", "Eleonora",
      "Zoe", "Franca", "Hannah", "Yolanda", "Birgit", "Amina", "Leandra",
      "Elise", "Alma", "Anastasia", "Marlis", "Fernanda", "Irmgard",
      "Micheline", "Elfriede", "Selma", "Ilona", "Dani\u00e8le",
      "Justine", "Magali", "Georgette", "Graziella", "Cynthia",
      "C\u00e4cilia", "Loredana", "G\u00e9raldine", "Sylviane", "Heidy",
      "Alexia", "Mary", "Ingeborg", "Emine", "Yara", "Ursina",
      "Marl\u00e8ne", "Morgane", "Michela", "Katarina", "Marine",
      "Ulrike", "Daria", "Bruna", "Jasmina", "Mira", "Soraya", "Juliana",
      "Marlyse", "Agn\u00e8s", "Carine", "Gloria", "Alena", "Svetlana",
      "Josefina", "Annelise", "Myrta", "Roberta", "Pierrette", "Celine",
      "Annika", "Mirjana", "Andr\u00e9e", "C\u00e9lia", "Serena",
      "Christel", "Susan", "Jocelyne", "Ren\u00e9e", "Vesna", "Andreia",
      "Elizabeth", "Cinzia", "Karen", "Cecilia", "Karine", "Marlen",
      "Ilaria", "Virginia", "Suzana", "Rose-Marie", "Jeanine",
      "Margarita", "Joanna", "Coralie", "Elif", "Dina", "Janina",
      "Josefine", "Mina", "Hannelore", "Gordana", "Luciana", "Heike",
      "Aurelia", "Luna", "Dagmar", "Filomena", "Dolores", "Raymonde",
      "Prisca", "Annick", "Huguette", "Elisabetha", "Dragana", "Leona",
      "Elke", "In\u00e8s", "Valerie", "Ayse", "Amelia", "Flurina",
      "Marie-Th\u00e9r\u00e8se", "Roswitha", "Rosanna", "Ginette",
      "Matilde", "M\u00e9lissa", "Yolande", "Oc\u00e9ane", "Giada",
      "Murielle", "Danijela", "Sanja", "Slavica", "Adelina", "Valentine",
      "Catarina", "Raquel", "Emmanuelle", "Dana", "Erica", "Marcelle",
      "Nancy", "Germaine", "Concetta", "Gianna", "Jade", "Lucienne",
      "Letizia", "Fatime", "Odette", "Solange", "Lily", "Nada", "Lucy",
      "Margherita", "Hana", "Elisabetta", "Leana", "Vivienne", "Viola",
      "Ljiljana", "Yasmin", "Agatha", "Jutta", "Anabela", "Laila",
      "Romana", "Ga\u00eblle", "Belinda", "Aida", "Federica", "Giuliana",
      "Marie-Claire", "Mirella", "Eliana", "Paulina", "Diane", "Paulette",
      "Mona", "Milica", "Corinna", "Yasmine", "Annalise", "Hatice",
      "Alyssa", "Ellen", "Kelly", "Biljana", "Noelia", "Alisha",
      "L\u00e9onie", "Amandine", "Amelie", "Amy", "Lilli", "Nelli",
      "Margaux", "Melisa", "Anneliese", "Marie-Claude", "Sheila",
      "Dragica", "Xenia", "Violeta", "Annie", "Lou", "Meret", "Ute",
      "Irena", "Catia", "Giuseppa", "Sybille", "Lana", "Celina", "Aylin",
      "Zita", "Karolina", "Louisa", "Luise", "Rosina", "Jeanette",
      "Sharon", "Henriette", "Joy", "Inge", "Carola", "Tiffany",
      "Margarete", "Marietta", "Josefa", "Leyla", "Nuria", "Anne-Lise",
      "Gilberte", "Giorgia", "Emanuela", "Daisy", "Angelica", "Josephine",
      "Ilse", "Natasa", "Andrina", "Fabiana", "Flora", "Maude", "Melinda",
      "Silke", "Enya", "Amira", "Beate", "Viktoria", "Francisca",
      "Merita", "Odile", "Snezana", "Ariana", "Carol", "Medina", "Romy",
      "No\u00eblle", "Alissa", "Elisabete", "Camilla", "Miranda",
      "Leonora", "Lejla", "Zeynep", "Maeva", "Domenica", "Raffaella",
      "Salom\u00e9", "Ornella", "Rosaria", "Alisa", "Alba", "Zorica",
      "Roxane", "Raphaela", "In\u00eas", "Hermine", "Waltraud", "Aude",
      "Selin", "Claude", "Arianna", "Ang\u00e9lique", "Leticia", "Malin",
      "Viviana", "Annelies", "Damaris", "Liv", "Ma\u00eblle", "Sigrid",
      "Jill", "Karina", "Liana", "Eline", "Lotte", "Lise", "Rina",
      "Morena", "Marilena", "Leonor", "Annamaria", "Albina", "Dijana",
      "Grazia", "Ester", "Vivien", "K\u00e4thi", "Tara", "Aurore",
      "Katarzyna", "Amalia", "Celia", "Seline", "Anisa", "Azra",
      "Adeline", "Fabiola", "Agnieszka", "Greta", "Jane", "Vincenza",
      "Rosalia", "Marie-Christine", "Marijana", "Jara", "Gudrun", "Edona",
      "Gioia", "Marcia", "Myrtha", "Ekaterina", "Lucette", "Gertrude",
      "Ljubica", "Adrienne", "Malika", "Ava", "Yael", "Lola", "Marinette",
      "Teuta", "Joelle", "Beata", "Line", "Priscilla", "Rosalie",
      "Mariette", "Ada", "Marielle", "Juliane", "Emina", "Arta",
      "Margarida", "Claire-Lise", "Gaia", "Antje", "Raffaela", "Mercedes",
      "Vlora", "Arlinda", "Nicoletta", "Alison", "Ottilia",
      "Cl\u00e9mence", "Lisbeth", "Shqipe", "Adele", "Maryline",
      "S\u00f3nia", "Ewa", "Drita", "Gladys", "Dilara", "Malgorzata",
      "Eleni", "Sandy", "Marika", "Marthe", "Norma", "Carolin", "Ina",
      "Agathe", "Alea", "Anke", "Zora", "Cristiana", "Marie-Jos\u00e9",
      "Liridona", "Romane", "Noa", "Shpresa", "Esma", "Assunta",
      "Vittoria", "Blerta", "Ema", "Elma", "Anika", "Marie-France",
      "Samanta", "Mariella", "Meryem", "Tania", "Ghislaine", "Marica",
      "Desir\u00e9e", "Britta", "Jos\u00e9phine", "Moira", "Maud",
      "Gemma", "Silja", "Sladjana", "Sanela", "Iva", "Ann", "Nad\u00e8ge",
      "Corine", "Frida", "Cheyenne", "Theres", "Lilia", "Matilda",
      "Geraldine", "Lisette", "Margaret", "Elo\u00efse", "Felicia",
      "Hulda", "Kathleen", "Erina", "Jovana", "Timea", "Sofie", "Wanda",
      "Anne-Sophie", "Zahra", "Florentina", "Alexa", "Ruzica", "Ganimete",
      "Herta", "Agata", "Yasemin", "Fr\u00e9d\u00e9rique", "Nicola",
      "Norah", "Lorenza", "Ilenia", "Khadija", "Elda", "Felicitas",
      "Charline", "Ela", "Eliza", "Katalin", "Rafaela", "Tanya",
      "Theresa", "Floriane", "Katherine", "Asia", "Mathilda", "Fabia",
      "Fatmire", "Imelda", "Susi", "Zuzana", "Cassandra", "Donatella",
      "Antonina", "Luz", "Yasmina", "Eleonore", "Bluette", "Malea",
      "Danica", "Dunja", "Kirsten", "Eileen", "Mirela", "Vanesa",
      "Filipa", "L\u00e9na", "Jaqueline", "Evelin", "Violette", "Vjollca",
      "Mariam", "Maryam", "Amela", "Luigia", "No\u00ebmi", "Joyce",
      "Pierina", "Aferdita", "C\u00e1tia", "Mandy", "Regine", "Branka",
      "Radmila", "Vreneli", "Marcella", "Grace", "Ludivine", "Natasha",
      "Olena", "Elea", "Jil", "Anne-Laure", "El\u00e9onore", "Ayla",
      "M\u00e9gane", "Maddalena", "Sereina", "Tenzin", "Dafina", "Eve",
      "Leslie", "Alix", "Kiara", "Ardita", "Aisha", "Margit", "Janet",
      "Kira", "Margreth", "Amra", "Marcela", "Sol\u00e8ne", "Kristin",
      "Fitore", "Rosalba", "Edina", "Mariangela", "Agnese", "Albulena",
      "Joanne", "Ylenia", "Clarissa", "Magda", "Marie-Laure",
      "Anna-Maria", "Luljeta", "Marjorie", "Annalisa", "Lidija", "Ajla",
      "Sanije", "Wendy", "Wilma", "Layla", "Thea", "Esra", "Ja\u00ebl",
      "Fernande", "Vania", "Lindita", "Tessa", "Mimoza", "Kata", "Maryse",
      "Dalia", "K\u00e4the", "Blanka", "Katerina", "Oph\u00e9lie", "Leni",
      "Egzona", "Eugenia", "Lavinia", "L\u00e9ane", "Bukurije", "Cordula",
      "Teodora", "Nikolina", "\u00d6zlem", "Lauriane", "Milka",
      "Patr\u00edcia", "Aloisia", "Lya", "Derya", "Margret", "Juana",
      "Vilma", "Annabelle", "Besarta", "Norina", "Cl\u00e1udia", "Nives",
      "Hanife", "Blerina", "Lydie", "Gerlinde", "D\u00e9borah",
      "Mirlinda", "Vivian", "Mar\u00eda", "Shania", "Romaine", "Tuana",
      "Berthe", "Friederike", "Susann", "Rosetta", "Hava", "Kaltrina",
      "Marie-Jeanne", "Iryna", "Mihaela"),

    first_names = c(
      "Peter", "Hans", "Daniel", "Thomas", "Andreas", "Martin",
      "Markus", "Michael", "Christian", "Stefan", "Walter", "Urs",
      "Marco", "Bruno", "Patrick", "Werner", "Ren\u00e9", "Marcel",
      "Beat", "Roland", "Kurt", "Josef", "David", "Simon", "Rolf",
      "Heinz", "Rudolf", "Paul", "Roger", "Christoph", "Ernst",
      "Pascal", "Adrian", "Lukas", "Marc", "Robert", "Reto", "Manuel",
      "Fabian", "Alfred", "Philipp", "J\u00fcrg", "Matthias",
      "Stephan", "Franz", "Anton", "Andr\u00e9", "Alexander", "Samuel",
      "Jan", "Johann", "Luca", "Max", "Roman", "Mario", "Fritz",
      "Ulrich", "Dominik", "Karl", "Tobias", "Oliver", "Florian",
      "Antonio", "Benjamin", "Sandro", "Bernhard", "Jonas", "Felix",
      "Raphael", "Kevin", "Erich", "Fabio", "Jakob", "Sven", "Dario",
      "Giuseppe", "Remo", "Nicolas", "Albert", "Erwin", "Richard",
      "Nico", "Michel", "Jos\u00e9", "Claudio", "Tim", "Noah", "Joel",
      "Heinrich", "J\u00f6rg", "Robin", "Sebastian", "Armin", "Guido",
      "Silvan", "Lars", "Ivan", "Julian", "Alois", "Francesco",
      "Sascha", "Dominic", "Johannes", "Georg", "Gabriel", "Manfred",
      "Herbert", "Otto", "Alessandro", "Gerhard", "Patrik", "Gian",
      "Mathias", "Leon", "Willi", "Eduard", "Nicola", "Hugo", "Ali",
      "Yves", "Elias", "Hermann", "Philippe", "Leo", "Emil", "Frank",
      "Dieter", "Friedrich", "Luis", "Giovanni", "Niklaus", "Alex",
      "Roberto", "Rafael", "Hanspeter", "Diego", "Nils", "Leandro",
      "Ramon", "Severin", "Salvatore", "Mike", "Alain", "Timo",
      "Carlos", "Arthur", "Yannick", "Eric", "Angelo", "Ivo",
      "Wolfgang", "Matteo", "Jo\u00ebl", "Andrin", "Pius", "Moritz",
      "Valentin", "Louis", "Wilhelm", "Renato", "Levin", "Silvio",
      "Willy", "Andrea", "Jonathan", "Jean", "Livio", "Loris",
      "Damian", "Theodor", "Michele", "Vincenzo", "Elia", "Ralph",
      "Klaus", "Eugen", "Mark", "Konrad", "Denis", "Norbert", "Lorenz",
      "Viktor", "Mehmet", "Marko", "Kilian", "Hans-Peter",
      "C\u00e9dric", "Ralf", "Aaron", "Maximilian", "Carlo", "Alessio",
      "Olivier", "J\u00fcrgen", "Luigi", "Philip", "Lucas", "Mauro",
      "Janis", "Cyrill", "Linus", "Davide", "Othmar", "Flavio", "Nino",
      "Arnold", "Nick", "Rainer", "Domenico", "Adolf", "Emanuel",
      "Oskar", "Ben", "Joshua", "Leonardo", "Franco", "Pierre", "John",
      "Gregor", "Fernando", "Marius", "Claude", "Edwin", "Colin",
      "Mustafa", "Pedro", "Stefano", "Sergio", "Dominique", "Juan",
      "Nikola", "Enrico", "Jens", "Daniele", "Thierry", "Jose", "Liam",
      "Francisco", "Ricardo", "Rico", "Christof", "Aleksandar",
      "Dennis", "Mohamed", "Joseph", "Charles", "Noel", "Miguel",
      "Laurin", "Milan", "Reinhard", "Lionel", "Dragan", "Hasan",
      "Paulo", "Edgar", "Silas", "Hubert", "Helmut", "Ibrahim",
      "Ruben", "Timon", "Vincent", "Christopher", "Finn", "Ronny",
      "Kaspar", "Mattia", "Lorenzo", "Pietro", "Bj\u00f6rn",
      "Hansruedi", "Gottfried", "Joachim", "Benno", "Harald", "Jorge",
      "Cedric", "Nevio", "Paolo", "Gianluca", "Boris", "Kai",
      "Maurizio", "Steven", "Mischa", "Patric", "Zoran", "Mirco",
      "Marvin", "Dirk", "Benedikt", "Uwe", "Hans-Rudolf", "Maurice",
      "Massimo", "Hansj\u00f6rg", "Jeremy", "Niklas", "Ahmet",
      "Fridolin", "Dejan", "Goran", "Micha", "Mohammad", "Ronald",
      "Bernd", "Mirko", "Erik", "Jason", "Tiago", "Riccardo",
      "J\u00e9r\u00f4me", "Igor", "Siegfried", "Pasquale", "Andri",
      "Tom", "Ueli", "Amir", "Cyril", "Adriano", "Alberto",
      "Ferdinand", "Justin", "Raffael", "Julien", "Lenny", "Luka",
      "Marcus", "Pirmin", "Janik", "Julius", "Meinrad", "Adam",
      "James", "H\u00fcseyin", "Alexandre", "Rocco", "Luc", "Victor",
      "Jo\u00e3o", "Andres", "Luan", "Flurin", "Filip", "Ismail",
      "Danilo", "Laurent", "Raffaele", "Ahmed", "G\u00fcnter", "Joao",
      "Rui", "Xaver", "Fabrizio", "William", "Vito", "Miroslav",
      "Lino", "Albin", "Jean-Pierre", "Basil", "Till", "Horst",
      "Romeo", "Aldo", "Murat", "Harry", "Alfons", "Pablo", "Bernard",
      "No\u00e9", "Luciano", "August", "Levi", "Nando", "Fabrice",
      "Raymond", "Jamie", "Georges", "Steffen", "Serge", "Cristian",
      "Samir", "Ant\u00f3nio", "Marlon", "Omar", "Lian", "Oscar",
      "Yanick", "Armando", "Nikolaus", "Dylan", "Hannes", "Sacha",
      "Nuno", "Toni", "Dino", "Elmar", "Arno", "Joaquim", "Sasa",
      "Henry", "Vladimir", "Arben", "Ryan", "Bekim", "Milos",
      "Giorgio", "Ludwig", "Leonard", "Adnan", "Gilbert", "Yannik",
      "Aron", "Iwan", "Maik", "Dimitri", "Erhard", "Fran\u00e7ois",
      "Gabriele", "Sami", "Elio", "Antonino", "Fynn", "Simone",
      "Andrew", "Alan", "Nenad", "Fr\u00e9d\u00e9ric", "Etienne",
      "Janick", "Steve", "Christophe", "Gianni", "Urban", "Anthony",
      "Deniz", "Jon", "Alejandro", "Axel", "Ian", "Theo", "Andrej",
      "Brian", "Lucien", "Gino", "Clemens", "Yanik", "Adem", "Emir",
      "Tino", "Miro", "Enis", "Gregory", "Danijel", "Osman", "Michal",
      "Carmine", "Orlando", "Enes", "Giuliano", "Timothy", "Fredy",
      "Besnik", "Vitor", "Holger", "Kim", "Eduardo", "Petar",
      "Jacques", "Karim", "Darko", "Gustav", "Emilio", "Mateo",
      "Alban", "Marek", "Oswald", "No\u00ebl", "Donato", "Mohammed",
      "Roy", "Kay", "Nathan", "Enea", "Silvano", "Josip", "Valerio",
      "Artur", "Besim", "Mika", "Torsten", "Romano", "Heiko", "Yusuf",
      "Chris", "Naim", "Burim", "Gaetano", "Hans-Ulrich", "Olaf",
      "Maurus", "Volker", "Jean-Claude", "Henri", "Nik", "Rodrigo",
      "Florin", "Mael", "Amar", "Agron", "Muhamed", "Tristan", "Valon",
      "Ahmad", "Ilir", "Javier", "Lorin", "Yanis", "Fatmir", "Bajram",
      "Carmelo", "Agim", "Enzo", "Moreno", "Cornel", "Andy", "Jeton",
      "Blerim", "Bojan", "Federico", "Attila", "Juri", "Tomas",
      "Valentino", "Ismet", "Jannik", "Ruedi", "Afrim", "Yannic",
      "Ramadan", "Alfredo", "Josua", "Cosimo", "Gerardo", "Bastian",
      "Filippo", "Raoul", "Halil", "Yann", "Georgios", "Jannis",
      "Nicholas", "Sean", "Wilfried", "G\u00fcnther", "Dusan", "Beda",
      "Gerold", "Gottlieb", "Filipe", "Ilija", "Carl", "Ardian",
      "Marcello", "Enver", "Dean", "Dion", "Tenzin", "Zeljko",
      "Carsten", "Diogo", "Alen", "Egon", "Aurel", "Yannis", "Edin",
      "Hans-J\u00f6rg", "Tomislav", "Mohamad", "Bujar", "Raul",
      "Slobodan", "Driton", "Maxim", "Francis", "Hansueli", "Ivica",
      "Nelson", "Emanuele", "Konstantin", "Fred", "Naser", "Gerd",
      "Kristian", "Selim", "Corsin", "Dietmar", "George", "Piotr",
      "Giacomo", "Ingo", "Andre", "Malik", "Lothar", "Jochen", "Sinan",
      "Thorsten", "Tiziano", "Gilles", "Avni", "Jann", "Lio", "Niels",
      "Emmanuel", "Leonhard", "Lorik", "Aurelio", "Gion", "Liridon",
      "Marino", "Can", "Kenan", "Ewald", "St\u00e9phane", "Dalibor",
      "Jozef", "Noe", "Bryan", "Dan", "Santiago", "Damiano", "Arian",
      "Rosario", "Giancarlo", "Nathanael", "Emre", "Stephen", "Hassan",
      "Jovan", "Egzon", "Reinhold", "Tomasz", "Vittorio", "Patrice",
      "Tibor", "Jost", "Elvis", "Lean", "Henrik", "Musa", "Noa", "Udo",
      "Almir", "Van", "Dietrich", "Mladen", "Armend", "Arlind", "Milo",
      "Arsim", "Bashkim", "Dimitrios", "Matthew", "\u00d6mer",
      "Abdullah", "Hakan", "Gerald", "Tommaso", "Joris", "Damir",
      "Vinzenz", "Marcos", "Rapha\u00ebl", "Ennio", "Melvin",
      "Leander", "Kuno", "Massimiliano", "Ma\u00ebl", "Anto", "Branko",
      "Fadil", "Kemal", "Muhammed", "Hendrik", "Pawel", "Jeremias",
      "L\u00e9on", "Leano", "R\u00e9my", "Giulio", "Muhamet", "Lulzim",
      "Konstantinos", "Pavel", "Rinaldo", "Omer", "Simeon",
      "Gian-Luca", "Maurin", "Antoine", "Frederik", "Janic", "Faton",
      "Marcin", "S\u00e9bastien", "Cem", "Curdin", "Endrit", "Nemanja",
      "Karsten", "Renzo", "Jerome", "Krzysztof", "Jeffrey",
      "Sebastiano", "Ernesto", "Lazar", "Ramazan", "G\u00e9rard",
      "Ajan", "Emin", "Ioannis", "Jesus", "Alfonso", "Yasin", "Jaron",
      "Alexis", "Orhan", "Artan", "Morris", "Angel", "Janosch", "Rene",
      "Shaban", "Jakub", "Lo\u00efc", "Kristijan", "Enrique",
      "Skender", "Gianfranco", "Mathieu", "Xavier", "Mathis", "Didier",
      "Arif", "Hamza", "Jacob", "Leart", "Laszlo", "Predrag", "Mentor",
      "Wendelin", "Lu\u00eds", "Constantin", "Erion", "Berat",
      "Dardan", "Melchior", "Serkan", "Dorian", "Eren", "Fatih",
      "Luzius", "Nebojsa", "Metin", "Diar", "Rino", "Ekrem", "Isa",
      "Jetmir", "Edward", "Nikolaos", "Gazmend", "Haris", "Kian",
      "Ensar", "Mirsad", "Danny", "Senad", "Donat", "Bilal", "Ron",
      "Nael", "Guy", "Julio", "Kujtim", "Kushtrim", "Lutz",
      "Balthasar", "Rouven", "Lias", "Neil", "Abraham", "Magnus",
      "S\u00e9rgio", "Hansj\u00fcrg", "Said", "Ismael", "Detlef",
      "Umberto", "Admir", "Jayden", "Jaime", "Karl-Heinz",
      "Tom\u00e1s", "Florim", "Achim", "Devin", "Maxime", "Fitim",
      "Jean-Marc", "Rayan", "Sadik", "Tarik", "Abdul", "Jack",
      "Mergim", "Nelio", "Sam", "Flamur", "Ignaz", "Samuele", "Tony",
      "Petr", "Waldemar", "Arda", "Ardit", "Lukasz", "Milorad",
      "Nicolai", "Ramiz", "Aziz", "Kamil", "Rinor", "Safet", "Piero",
      "Erkan", "Niko", "Zsolt", "Ernest", "Miodrag", "Alvaro",
      "Astrit", "Edmund", "Jules", "Cristiano", "Ivano", "Kenneth",
      "Saverio", "Semir", "Burak", "Theophil", "Altin", "Andrzej",
      "Jonah", "Jiri", "Salih", "Zolt\u00e1n", "Ferenc", "Grzegorz",
      "Irfan", "Johan", "Kaan", "S\u00fcleyman", "Hussein", "Rexhep",
      "Besart", "Janos", "Labinot", "Onur", "Stjepan", "Domenic",
      "Siro", "Abel", "Florent", "Christos", "Swen", "Branislav",
      "Mato", "Amin", "Matej", "Slavko", "Jusuf", "Luke", "Slavisa",
      "Erol", "Gabor", "Jasmin", "Visar", "Sinisa", "Isidor", "Merlin",
      "Claus", "Marin", "Zoltan", "Muhammad", "Neo", "Zeno", "Istvan",
      "Adis", "Edon", "Gil", "Leopold", "Hartmut", "Raimund", "Ken",
      "Csaba", "Kerim", "Norman", "Lucio", "L\u00e1szl\u00f3",
      "Marjan", "Damjan", "Eugenio", "Domingos", "Reiner", "Augusto",
      "Gzim", "Nazmi", "Laurenz", "Zlatko", "Jaroslav", "Nevin",
      "Biagio", "Felice", "Balz", "Boban", "Marcelo", "Caspar",
      "Ledion", "Rodolfo", "Aldin", "Matti", "Remzi", "Ljubisa", "Til",
      "P\u00e9ter", "Umut", "Baris", "Lirim", "Mehdi", "Edmond",
      "Gon\u00e7alo", "Jasin", "Niclas", "Jordan", "Mahmoud",
      "Stanislav", "Cornelius", "Jona", "Khaled", "Quentin",
      "G\u00f6khan", "Imer", "Volkan", "Harun", "Miran", "Damien",
      "Gennaro", "Jari", "Marian", "R\u00fcdiger", "Albrecht", "Mile",
      "Thiago", "Yvan", "Alwin", "Gani", "Mahmut", "Pero", "Evan",
      "Fisnik", "Idriz", "Sergej", "Sabri", "Felipe", "Istv\u00e1n",
      "Dave", "Hans-J\u00fcrgen", "Jean-Luc", "Kastriot", "Mariusz",
      "Arne", "Faruk", "Gebhard", "German", "Tam\u00e1s", "Anes",
      "Arbnor", "Mats", "Drilon", "F\u00e1bio", "Mihajlo", "Sedat",
      "Tahir",
      "Maria", "Anna", "Ursula", "Ruth", "Elisabeth", "Sandra", "Monika",
      "Claudia", "Verena", "Nicole", "Barbara", "Silvia", "Andrea",
      "Marie", "Daniela", "Christine", "Karin", "Marianne", "Erika",
      "Margrit", "Brigitte", "Susanne", "Rita", "Laura", "Sarah",
      "Katharina", "Rosmarie", "Esther", "Heidi", "Anita", "Manuela",
      "Rosa", "Doris", "Sonja", "Beatrice", "Yvonne", "Gertrud",
      "Jacqueline", "Sara", "Irene", "Ana", "Franziska", "Cornelia",
      "Fabienne", "Gabriela", "Patricia", "Martina", "Julia", "Edith",
      "Eva", "Isabelle", "Sabrina", "Nathalie", "Alexandra", "Corinne",
      "Angela", "Melanie", "Alice", "Nadine", "Jessica", "Denise",
      "Elena", "Vanessa", "Simone", "Anne", "Regula", "Susanna", "Carmen",
      "Sophie", "Caroline", "Emma", "Nina", "Tanja", "Catherine",
      "Sabine", "Lara", "Petra", "Lea", "C\u00e9line", "Jasmin",
      "Therese", "Stefanie", "Johanna", "Nadia", "Tamara", "Chantal",
      "Martha", "Michelle", "Christina", "Marina", "Adelheid", "Dora",
      "Monique", "Rahel", "Hedwig", "Lisa", "Janine", "Pia", "Anja",
      "Elsbeth", "Madeleine", "Eveline", "Judith", "Diana",
      "Fran\u00e7oise", "Charlotte", "Maja", "Eliane", "Renate",
      "Christiane", "Mich\u00e8le", "Jennifer", "Bettina", "Chiara",
      "Bernadette", "Aline", "Carla", "Helena", "Brigitta", "Mirjam",
      "Theresia", "Astrid", "Nadja", "Jana", "Selina", "Priska", "Lena",
      "Stephanie", "Lucia", "Linda", "Regina", "Agnes", "Olivia", "Sonia",
      "Val\u00e9rie", "Klara", "Ramona", "Lina", "Elsa", "Helene",
      "Monica", "Iris", "Hanna", "Valentina", "Annemarie", "Elisa",
      "Margrith", "Dominique", "Beatrix", "Cristina", "Paula",
      "Magdalena", "Livia", "Sofia", "Patrizia", "Liliane", "Nelly",
      "Marion", "Ida", "Alina", "Isabel", "Vera", "St\u00e9phanie",
      "Giulia", "Leonie", "Jeannette", "Christa", "Alessia",
      "V\u00e9ronique", "Myriam", "Emilie", "Olga", "Nora", "Julie",
      "Sylvia", "Margaretha", "Claudine", "Marlise", "Miriam", "Sibylle",
      "Sylvie", "Lydia", "Katja", "Lorena", "Jolanda", "Rebecca", "Mia",
      "Irma", "Larissa", "Luana", "Martine", "Deborah", "Francesca",
      "Veronika", "Isabella", "Noemi", "Ingrid", "Frieda", "Suzanne",
      "Liselotte", "Michaela", "Florence", "Evelyne", "Hildegard",
      "Corina", "Danielle", "Laurence", "Carole", "Milena", "C\u00e9cile",
      "Mara", "Luzia", "Sandrine", "Gisela", "Simona", "M\u00e9lanie",
      "B\u00e9atrice", "Marta", "Antonia", "Erna", "Gabriele", "Katrin",
      "Kathrin", "Melissa", "Camille", "Adriana", "Fiona", "Lucie",
      "Natalie", "Teresa", "Renata", "Josiane", "Sophia", "Clara",
      "Luisa", "Silvana", "Jeannine", "Pascale", "H\u00e9l\u00e8ne",
      "Emilia", "Jo\u00eblle", "Gabriella", "Maya", "Marianna", "Ines",
      "L\u00e9a", "Claire", "Marisa", "Sina", "Lia", "Paola", "Mathilde",
      "Sabina", "Alessandra", "Ivana", "Anne-Marie", "Elvira", "Bianca",
      "Samira", "Cindy", "Am\u00e9lie", "Chlo\u00e9", "Kim", "Victoria",
      "Annette", "Angelina", "Dorothea", "Antoinette", "Tina", "Tania",
      "Angelika", "Valeria", "Flavia", "Margaritha", "Rachel",
      "Marguerite", "Jeanne", "Yvette", "Natalia", "Alicia", "Giovanna",
      "Mireille", "Liliana", "Pauline", "Seraina", "Elodie", "Ariane",
      "Helga", "Zo\u00e9", "Natascha", "Muriel", "Francine", "Joana",
      "Melina", "Aur\u00e9lie", "Thi", "Giuseppina", "Tatiana",
      "Margareta", "Louise", "Marija", "Debora", "Salome", "Viviane",
      "Fanny", "Katia", "Carolina", "Irina", "Bertha", "Marlene",
      "No\u00e9mie", "Amanda", "Sarina", "Marlies", "Lilian",
      "Ir\u00e8ne", "Laetitia", "Kristina", "Jasmine", "Ella", "Jenny",
      "Gabrielle", "Carmela", "Manon", "Helen", "Fatima", "Stefania",
      "Virginie", "Ladina", "Jelena", "Berta", "Antonella", "Rebekka",
      "Audrey", "Ana\u00efs", "Tatjana", "Annina", "Margot", "Carina",
      "Samantha", "Evelyn", "Annamarie", "Tiziana", "Arlette", "Emily",
      "Kerstin", "Svenja", "Caterina", "Christelle", "Saskia", "Elin",
      "Lilly", "Anouk", "Rose", "Fatma", "Lynn", "Elina", "Colette",
      "Josette", "Leila", "Gerda", "Susana", "Genevi\u00e8ve",
      "D\u00e9sir\u00e9e", "Naomi", "Stella", "Romina", "Delphine",
      "Aurora", "Estelle", "Juliette", "Tabea", "Anina",
      "Th\u00e9r\u00e8se", "Mariana", "Beatriz", "Hilda", "Lotti",
      "S\u00e9verine", "Delia", "Ronja", "Gina", "Mila", "Antonietta",
      "Veronica", "Aleksandra", "Gis\u00e8le", "Lidia", "Natacha",
      "Laure", "Pamela", "Rosemarie", "Marie-Louise", "Jael", "Eleonora",
      "Zoe", "Franca", "Hannah", "Yolanda", "Birgit", "Amina", "Leandra",
      "Elise", "Alma", "Anastasia", "Marlis", "Fernanda", "Irmgard",
      "Micheline", "Elfriede", "Selma", "Ilona", "Dani\u00e8le",
      "Justine", "Magali", "Georgette", "Graziella", "Cynthia",
      "C\u00e4cilia", "Loredana", "G\u00e9raldine", "Sylviane", "Heidy",
      "Alexia", "Mary", "Ingeborg", "Emine", "Yara", "Ursina",
      "Marl\u00e8ne", "Morgane", "Michela", "Katarina", "Marine",
      "Ulrike", "Daria", "Bruna", "Jasmina", "Mira", "Soraya", "Juliana",
      "Marlyse", "Agn\u00e8s", "Carine", "Gloria", "Alena", "Svetlana",
      "Josefina", "Annelise", "Myrta", "Roberta", "Pierrette", "Celine",
      "Annika", "Mirjana", "Andr\u00e9e", "C\u00e9lia", "Serena",
      "Christel", "Susan", "Jocelyne", "Ren\u00e9e", "Vesna", "Andreia",
      "Elizabeth", "Cinzia", "Karen", "Cecilia", "Karine", "Marlen",
      "Ilaria", "Virginia", "Suzana", "Rose-Marie", "Jeanine",
      "Margarita", "Joanna", "Coralie", "Elif", "Dina", "Janina",
      "Josefine", "Mina", "Hannelore", "Gordana", "Luciana", "Heike",
      "Aurelia", "Luna", "Dagmar", "Filomena", "Dolores", "Raymonde",
      "Prisca", "Annick", "Huguette", "Elisabetha", "Dragana", "Leona",
      "Elke", "In\u00e8s", "Valerie", "Ayse", "Amelia", "Flurina",
      "Marie-Th\u00e9r\u00e8se", "Roswitha", "Rosanna", "Ginette",
      "Matilde", "M\u00e9lissa", "Yolande", "Oc\u00e9ane", "Giada",
      "Murielle", "Danijela", "Sanja", "Slavica", "Adelina", "Valentine",
      "Catarina", "Raquel", "Emmanuelle", "Dana", "Erica", "Marcelle",
      "Nancy", "Germaine", "Concetta", "Gianna", "Jade", "Lucienne",
      "Letizia", "Fatime", "Odette", "Solange", "Lily", "Nada", "Lucy",
      "Margherita", "Hana", "Elisabetta", "Leana", "Vivienne", "Viola",
      "Ljiljana", "Yasmin", "Agatha", "Jutta", "Anabela", "Laila",
      "Romana", "Ga\u00eblle", "Belinda", "Aida", "Federica", "Giuliana",
      "Marie-Claire", "Mirella", "Eliana", "Paulina", "Diane", "Paulette",
      "Mona", "Milica", "Corinna", "Yasmine", "Annalise", "Hatice",
      "Alyssa", "Ellen", "Kelly", "Biljana", "Noelia", "Alisha",
      "L\u00e9onie", "Amandine", "Amelie", "Amy", "Lilli", "Nelli",
      "Margaux", "Melisa", "Anneliese", "Marie-Claude", "Sheila",
      "Dragica", "Xenia", "Violeta", "Annie", "Lou", "Meret", "Ute",
      "Irena", "Catia", "Giuseppa", "Sybille", "Lana", "Celina", "Aylin",
      "Zita", "Karolina", "Louisa", "Luise", "Rosina", "Jeanette",
      "Sharon", "Henriette", "Joy", "Inge", "Carola", "Tiffany",
      "Margarete", "Marietta", "Josefa", "Leyla", "Nuria", "Anne-Lise",
      "Gilberte", "Giorgia", "Emanuela", "Daisy", "Angelica", "Josephine",
      "Ilse", "Natasa", "Andrina", "Fabiana", "Flora", "Maude", "Melinda",
      "Silke", "Enya", "Amira", "Beate", "Viktoria", "Francisca",
      "Merita", "Odile", "Snezana", "Ariana", "Carol", "Medina", "Romy",
      "No\u00eblle", "Alissa", "Elisabete", "Camilla", "Miranda",
      "Leonora", "Lejla", "Zeynep", "Maeva", "Domenica", "Raffaella",
      "Salom\u00e9", "Ornella", "Rosaria", "Alisa", "Alba", "Zorica",
      "Roxane", "Raphaela", "In\u00eas", "Hermine", "Waltraud", "Aude",
      "Selin", "Claude", "Arianna", "Ang\u00e9lique", "Leticia", "Malin",
      "Viviana", "Annelies", "Damaris", "Liv", "Ma\u00eblle", "Sigrid",
      "Jill", "Karina", "Liana", "Eline", "Lotte", "Lise", "Rina",
      "Morena", "Marilena", "Leonor", "Annamaria", "Albina", "Dijana",
      "Grazia", "Ester", "Vivien", "K\u00e4thi", "Tara", "Aurore",
      "Katarzyna", "Amalia", "Celia", "Seline", "Anisa", "Azra",
      "Adeline", "Fabiola", "Agnieszka", "Greta", "Jane", "Vincenza",
      "Rosalia", "Marie-Christine", "Marijana", "Jara", "Gudrun", "Edona",
      "Gioia", "Marcia", "Myrtha", "Ekaterina", "Lucette", "Gertrude",
      "Ljubica", "Adrienne", "Malika", "Ava", "Yael", "Lola", "Marinette",
      "Teuta", "Joelle", "Beata", "Line", "Priscilla", "Rosalie",
      "Mariette", "Ada", "Marielle", "Juliane", "Emina", "Arta",
      "Margarida", "Claire-Lise", "Gaia", "Antje", "Raffaela", "Mercedes",
      "Vlora", "Arlinda", "Nicoletta", "Alison", "Ottilia",
      "Cl\u00e9mence", "Lisbeth", "Shqipe", "Adele", "Maryline",
      "S\u00f3nia", "Ewa", "Drita", "Gladys", "Dilara", "Malgorzata",
      "Eleni", "Sandy", "Marika", "Marthe", "Norma", "Carolin", "Ina",
      "Agathe", "Alea", "Anke", "Zora", "Cristiana", "Marie-Jos\u00e9",
      "Liridona", "Romane", "Noa", "Shpresa", "Esma", "Assunta",
      "Vittoria", "Blerta", "Ema", "Elma", "Anika", "Marie-France",
      "Samanta", "Mariella", "Meryem", "Tania", "Ghislaine", "Marica",
      "Desir\u00e9e", "Britta", "Jos\u00e9phine", "Moira", "Maud",
      "Gemma", "Silja", "Sladjana", "Sanela", "Iva", "Ann", "Nad\u00e8ge",
      "Corine", "Frida", "Cheyenne", "Theres", "Lilia", "Matilda",
      "Geraldine", "Lisette", "Margaret", "Elo\u00efse", "Felicia",
      "Hulda", "Kathleen", "Erina", "Jovana", "Timea", "Sofie", "Wanda",
      "Anne-Sophie", "Zahra", "Florentina", "Alexa", "Ruzica", "Ganimete",
      "Herta", "Agata", "Yasemin", "Fr\u00e9d\u00e9rique", "Nicola",
      "Norah", "Lorenza", "Ilenia", "Khadija", "Elda", "Felicitas",
      "Charline", "Ela", "Eliza", "Katalin", "Rafaela", "Tanya",
      "Theresa", "Floriane", "Katherine", "Asia", "Mathilda", "Fabia",
      "Fatmire", "Imelda", "Susi", "Zuzana", "Cassandra", "Donatella",
      "Antonina", "Luz", "Yasmina", "Eleonore", "Bluette", "Malea",
      "Danica", "Dunja", "Kirsten", "Eileen", "Mirela", "Vanesa",
      "Filipa", "L\u00e9na", "Jaqueline", "Evelin", "Violette", "Vjollca",
      "Mariam", "Maryam", "Amela", "Luigia", "No\u00ebmi", "Joyce",
      "Pierina", "Aferdita", "C\u00e1tia", "Mandy", "Regine", "Branka",
      "Radmila", "Vreneli", "Marcella", "Grace", "Ludivine", "Natasha",
      "Olena", "Elea", "Jil", "Anne-Laure", "El\u00e9onore", "Ayla",
      "M\u00e9gane", "Maddalena", "Sereina", "Tenzin", "Dafina", "Eve",
      "Leslie", "Alix", "Kiara", "Ardita", "Aisha", "Margit", "Janet",
      "Kira", "Margreth", "Amra", "Marcela", "Sol\u00e8ne", "Kristin",
      "Fitore", "Rosalba", "Edina", "Mariangela", "Agnese", "Albulena",
      "Joanne", "Ylenia", "Clarissa", "Magda", "Marie-Laure",
      "Anna-Maria", "Luljeta", "Marjorie", "Annalisa", "Lidija", "Ajla",
      "Sanije", "Wendy", "Wilma", "Layla", "Thea", "Esra", "Ja\u00ebl",
      "Fernande", "Vania", "Lindita", "Tessa", "Mimoza", "Kata", "Maryse",
      "Dalia", "K\u00e4the", "Blanka", "Katerina", "Oph\u00e9lie", "Leni",
      "Egzona", "Eugenia", "Lavinia", "L\u00e9ane", "Bukurije", "Cordula",
      "Teodora", "Nikolina", "\u00d6zlem", "Lauriane", "Milka",
      "Patr\u00edcia", "Aloisia", "Lya", "Derya", "Margret", "Juana",
      "Vilma", "Annabelle", "Besarta", "Norina", "Cl\u00e1udia", "Nives",
      "Hanife", "Blerina", "Lydie", "Gerlinde", "D\u00e9borah",
      "Mirlinda", "Vivian", "Mar\u00eda", "Shania", "Romaine", "Tuana",
      "Berthe", "Friederike", "Susann", "Rosetta", "Hava", "Kaltrina",
      "Marie-Jeanne", "Iryna", "Mihaela"),

    last_names = c(
      "Ackermann", "Aebi", "Albrecht", "Ammann", "Amrein", "Arnold",
      "Bachmann", "Bader", "B\u00e4r", "B\u00e4ttig", "Bauer", "Baumann",
      "Baumgartner", "Baur", "Beck", "Benz", "Berger", "Bernasconi",
      "Betschart", "Bianchi", "Bieri", "Blaser", "Blum", "Bolliger",
      "Bosshard", "Braun", "Brun", "Brunner", "Bucher", "B\u00fchler",
      "B\u00fchlmann", "Burri", "Christen", "Egger", "Egli", "Eichenberger",
      "Erni", "Ernst", "Eugster", "Fankhauser", "Favre", "Fehr", "Felber",
      "Felder", "Ferrari", "Fischer", "Fl\u00fcckiger", "Forster", "Frei",
      "Frey", "Frick", "Friedli", "Fuchs", "Furrer", "Gasser", "Geiger",
      "Gerber", "Gfeller", "Giger", "Gloor", "Graf", "Grob", "Gross", "Gut",
      "Haas", "H\u00e4fliger", "Hafner", "Hartmann", "Hasler", "Hauser",
      "Hermann", "Herzog", "Hess", "Hirt", "Hodel", "Hofer", "Hoffmann",
      "Hofmann", "Hofstetter", "Hotz", "Huber", "Hug", "Hunziker",
      "H\u00fcrlimann", "Imhof", "Isler", "Iten", "J\u00e4ggi", "Jenni",
      "Jost", "K\u00e4gi", "Kaiser", "K\u00e4lin", "K\u00e4ser", "Kaufmann",
      "Keller", "Kern", "Kessler", "Knecht", "Koch", "Kohler", "Kuhn",
      "K\u00fcng", "Kunz", "Lang", "Lanz", "Lehmann", "Leu", "Leunberger",
      "L\u00fcscher", "Lustenberger", "L\u00fcthi", "Lutz", "M\u00e4der",
      "Maier", "Marti", "Martin", "Maurer", "Mayer", "Meier", "Meili",
      "Meister", "Merz", "Mettler", "Meyer", "Michel", "Moser",
      "M\u00fcller", "N\u00e4f", "Ott", "Peter", "Pfister", "Portmann",
      "Probst", "Rey", "Ritter", "Roos", "Roth", "R\u00fcegg",
      "Sch\u00e4fer", "Schaller", "Sch\u00e4r", "Sch\u00e4rer", "Schaub",
      "Scheidegger", "Schenk", "Scherrer", "Schlatter", "Schmid", "Schmidt",
      "Schneider", "Schnyder", "Schoch", "Schuler", "Schumacher",
      "Sch\u00fcrch", "Schwab", "Schwarz", "Schweizer", "Seiler", "Senn",
      "Sidler", "Siegrist", "Sigrist", "Sp\u00f6rri", "Stadelmann",
      "Stalder", "Staub", "Stauffer", "Steffen", "Steiger", "Steiner",
      "Steinmann", "Stettler", "Stocker", "St\u00f6ckli", "Stucki",
      "Studer", "Stutz", "Suter", "Sutter", "Tanner", "Thommen", "Tobler",
      "Vogel", "Vogt", "Wagner", "Walder", "Walter", "Weber", "Wegmann",
      "Wehrli", "Weibel", "Wenger", "Wettstein", "Widmer", "Winkler",
      "Wirth", "Wirz", "Wolf", "W\u00fcthrich", "Wyss", "Zbinden",
      "Zehnder", "Ziegler", "Zimmermann", "Zingg", "Zollinger", "Z\u00fcrcher"),

    prefixes = c('Dr.', 'Prof.')

  )
)

## ssn -------------------------------------
ssn_de_CH = R6Class(
  "ssn_de_CH",
  inherit = ssn_fr_CH,
  cloneable = FALSE
)




## company ---------------------------------
company_de_CH = R6Class(
  "company_de_CH",
  inherit = company_en_US,
  cloneable = FALSE,
  private = list(
    last_names = (person_de_CH$new())$.__enclos_env__$private$last_names,
    last_name = (person_de_CH$new())$last_name
  )
)
## credit_card -----------------
credit_card_de_CH = R6Class(
  "credit_card_de_CH",
  inherit = credit_card_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_de_CH$new())$.__enclos_env__$private$first_names,
    first_name = (person_de_CH$new())$first_name,
    last_names = (person_de_CH$new())$.__enclos_env__$private$last_names,
    last_name = (person_de_CH$new())$last_name
  )
)



## address -----------------------
address_de_CH = R6Class(
  "address_de_CH",
  inherit = address_en_US,
  cloneable = FALSE,
  private = list(
    first_names = (person_de_CH$new())$.__enclos_env__$private$first_names,
    first_name = (person_de_CH$new())$first_name,
    last_names = (person_de_CH$new())$.__enclos_env__$private$last_names,
    last_name = (person_de_CH$new())$last_name
  )
)


## internet -----------------
internet_de_CH = R6Class(
  "internet_de_CH",
  inherit = internet_en_US,
  cloneable = FALSE,
  private = list(
    first_names = (person_de_CH$new())$.__enclos_env__$private$first_names,
    last_names = (person_de_CH$new())$.__enclos_env__$private$last_names,
    first_name = (person_de_CH$new())$first_name,
    last_name = (person_de_CH$new())$last_name
  ),
  public = list(
    domain_word = function() {
      company = (company_de_CH$new())$company()
      company_elements = str_split(company, " ")[[1]]
      company = private$to_ascii(company_elements[1])
      return(private$slugify(company, allow_unicode = FALSE))
    }
  )
)
## profile ------------------
profile_de_CH = R6Class(
  "profile_de_CH",
  inherit = profile_init,
  cloneable = FALSE,
  public = list(
    simple_profile = function(sex) {
      # Generates a basic profile with personal informations
      SEX = c("F", "M")
      if (missing(sex)) {
        sex = sample(SEX, 1)
      }
      if (!(sex %in% SEX)) {
        sex = sample(SEX, 1)
      }

      name = ifelse(sex == "F",
                    (person_de_CH$new())$name_female(),
                    (person_de_CH$new())$name_male())
      temp = list(
        "username" = (internet_de_CH$new())$user_name(),
        "name" = name,
        "sex" = sex,
        "address" = (address_de_CH$new())$address(),
        "mail" = (internet_de_CH$new())$free_email(),
        "birthdate" = (date_time_init$new())$date_of_birth()
      )
      return(temp)
    },

    profile = function(fields, sex) {
      # Generates a complete profile.
      # If "fields" is not empty, only the fields in the list will be returned

      if (missing(fields)) fields = c()

      field = list(
        "job" = (job_init$new())$job(),
        "company" = (company_de_CH$new())$company(),
        "ssn" = (ssn_de_CH$new())$ssn(),
        "residence" = (address_de_CH$new())$address(),
        "current_location" = c((geo_init$new())$latitude(),
                               (geo_init$new())$longitude()),
        "blood_group" = sample(c(
          "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"), 1),
        "website" = replicate(sample(seq(4), 1), (internet_de_CH$new())$url())
      )

      field = append(field, self$simple_profile(sex))
      # field selection

      if (length(fields)) {
        nms = intersect(names(field), fields)
        field = field[nms]
      }
      return(field)
    }

  )
)







