# address -------------------------------------
address_es = R6Class(
  "address_es",
  inherit = address_init,
  cloneable = FALSE,
  private = list(
    countries = c(
      "Afganist\u00e1n",
      "Albania",
      "Alemania",
      "Andorra",
      "Angola",
      "Antigua y Barbuda",
      "Arabia Saudita",
      "Argelia",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaiy\u00e1n",
      "Bahamas",
      "Bahrein",
      "Bangladesh",
      "Barbados",
      "Belar\u00fas",
      "B\u00e9lgica",
      "Belice",
      "Benin",
      "Bhut\u00e1n",
      "Bolivia",
      "Bosnia y Herzegovina",
      "Botswana",
      "Brasil",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Camboya",
      "Camer\u00fan",
      "Canad\u00e1",
      "Chad",
      "Chile",
      "China",
      "Chipre",
      "Colombia",
      "Comoras",
      "Congo",
      "Costa Rica",
      "C\u00f4te d\'Ivoire",
      "Croacia",
      "Cuba",
      "Dinamarca",
      "Djibouti",
      "Dominicana",
      "Ecuador",
      "Egipto",
      "El Salvador",
      "Emiratos \u00e1rabes Unidos",
      "Eritrea",
      "Eslovaquia",
      "Eslovenia",
      "Espa\u00f1a",
      "Estados Unidos de Am\u00e9rica",
      "Estonia",
      "Etiop\u00eda",
      "ex Rep\u00fablica Yugoslava de Macedonia",
      "Federaci\u00f3n de Rusia",
      "Fiji",
      "Filipinas",
      "Finlandia",
      "Francia",
      "Gab\u00f3n",
      "Gambia",
      "Georgia",
      "Ghana",
      "Granada",
      "Grecia",
      "Guatemala",
      "Guinea",
      "Guinea Bissau",
      "Guinea Ecuatorial",
      "Guyana",
      "Hait\u00ed",
      "Honduras",
      "Hungr\u00eda",
      "India",
      "Indonesia",
      "Ir\u00e1n",
      "Iraq",
      "Irlanda",
      "Islandia",
      "Islas Marshall",
      "Islas Salom\u00f3n",
      "Israel",
      "Italia",
      "Jamaica",
      "Jap\u00f3n",
      "Jordania",
      "Kazajst\u00e1n",
      "Kenya",
      "Kirguist\u00e1n",
      "Kiribati",
      "Kuwait",
      "Lesotho",
      "Letonia",
      "L\u00edbano",
      "Liberia",
      "Libia",
      "Liechtenstein",
      "Lituania",
      "Luxemburgo",
      "Madagascar",
      "Malasia",
      "Malawi",
      "Maldivas",
      "Mali",
      "Malta",
      "Marruecos",
      "Mauricio",
      "Mauritania",
      "M\u00e9xico",
      "Micronesia",
      "M\u00f3naco",
      "Mongolia",
      "Montenegro",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Noruega",
      "Nueva Zelandia",
      "Om\u00e1n",
      "Pa\u00edses Bajos",
      "Pakist\u00e1n",
      "Palau",
      "Panam\u00e1",
      "Papua Nueva Guinea",
      "Paraguay",
      "Per\u00fa",
      "Polonia",
      "Portugal",
      "Qatar",
      "Reino Unido de Gran Breta\u00f1a e Irlanda del Norte",
      "Rep\u00fablica \u00e1rabe Siria",
      "Rep\u00fablica Centroafricana",
      "Rep\u00fablica Checa",
      "Rep\u00fablica de Corea",
      "Rep\u00fablica de Moldova",
      "Rep\u00fablica Democr\u00e1tica del Congo",
      "Rep\u00fablica Democr\u00e1tica Popular Lao",
      "Rep\u00fablica Dominicana",
      "Rep\u00fablica Federal Democr\u00e1tica de Nepal",
      "Rep\u00fablica Popular Democr\u00e1tica de Corea",
      "Rep\u00fablica Unida de Tanzan\u00eda",
      "Rumania",
      "Rwanda",
      "Saint Kitts y Nevis",
      "Samoa",
      "San Marino",
      "Santa Luc\u00eda",
      "Santo Tom\u00e9 y Pr\u00edncipe",
      "San Vicente y las Granadinas",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leona",
      "Singapur",
      "Somalia",
      "Sri Lanka",
      "Sud\u00e1frica",
      "Sud\u00e1n",
      "Sud\u00e1n del Sur",
      "Suecia",
      "Suiza",
      "Suriname",
      "Swazilandia",
      "Tailandia",
      "Tayikist\u00e1n",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad y Tabago",
      "T\u00fanez",
      "Turkmenist\u00e1n",
      "Turqu\u00eda",
      "Tuvalu",
      "Ucrania",
      "Uganda",
      "Uruguay",
      "Uzbekist\u00e1n",
      "Vanuatu",
      "Venezuela",
      "Vietman",
      "Yemen",
      "Zambia",
      "Zimbabwe"
    )
  )
)
