# color --------------------------------------------------
color_hr_HR = R6Class(
  "color_hr_HR",
  inherit = color_init,
  cloneable = FALSE,
  private = list(
    all_colors = list(
      c("Akvamarin","#7FFFD4"),
      c("Antikna bijela","#FAEBD7"),
      c("Azurna","#F0FFFF"),
      c("Be\u017e","#F5F5DC"),
      c("Bijela","#FFFFFF"),
      c("Bijelo bilje","#FFFAF0"),
      c("Bjelokost","#FFFFF0"),
      c("Blijeda kudelja","#EEE8AA"),
      c("Blijedi badem","#FFEBCD"),
      c("Blijedoljubi\u010dasta","#DB7093"),
      c("Blijedotirkizna","#AFEEEE"),
      c("Blijedozelena","#98FB98"),
      c("Breskva","#FFDAB9"),
      c("Bron\u010dana","#D2B48C"),
      c("\u010celi\u010dnoplava","#4682B4"),
      c("\u010ci\u010dak","#D8BFD8"),
      c("Cijan","#00FFFF"),
      c("\u010cipka","#FDF5E6"),
      c("\u010cokoladna","#D2691E"),
      c("Crna","#000000"),
      c("Crvena","#FF0000"),
      c("Dim","#F5F5F5"),
      c("Dodger plava","#1E90FF"),
      c("Duboko ru\u017ei\u010dasta","#FF1493"),
      c("Fuksija","#FF00FF"),
      c("Gainsboro","#DCDCDC"),
      c("Grimizna","#DC143C"),
      c("Indigo","#4B0082"),
      c("Jelenska ko\u017ea","#FFE4B5"),
      c("Kadetski plava","#5F9EA0"),
      c("Kestenjasta","#800000"),
      c("Koraljna","#FF7F50"),
      c("Kraljevski plava","#4169E1"),
      c("Kudelja","#DAA520"),
      c("Lan","#FAF0E6"),
      c("Lavanda","#E6E6FA"),
      c("Limun","#FFFACD"),
      c("Lipa","#00FF00"),
      c("Ljubi\u010dasta","#EE82EE"),
      c("Magenta","#FF00FF"),
      c("Maslinasta","#808000"),
      c("Medljika","#F0FFF0"),
      c("Menta","#F5FFFA"),
      c("Modro nebo","#00BFFF"),
      c("Modrozelena","#008080"),
      c("Mornarska","#000080"),
      c("Morskozelena","#2E8B57"),
      c("Mra\u010dno siva","#696969"),
      c("Naran\u010dasta","#FFA500"),
      c("Naran\u010dastocrvena","#FF4500"),
      c("Naran\u010dastoru\u017ei\u010dasta","#FA8072"),
      c("No\u0107no plava","#191970"),
      c("Orhideja","#DA70D6"),
      c("Papaja","#FFEFD5"),
      c("Peru","#CD853F"),
      c("Plava","#0000FF"),
      c("Plavi prah","#B0E0E6"),
      c("Plavi \u0161kriljevac","#6A5ACD"),
      c("Plavkasta","#F0F8FF"),
      c("Plavo cvije\u0107e","#6495ED"),
      c("Plavo nebo","#87CEEB"),
      c("Plavoljubi\u010dasta","#8A2BE2"),
      c("Porculanska","#FFE4C4"),
      c("Prljavomaslinasta","#6B8E23"),
      c("Proljetnozelena","#00FF7F"),
      c("Prozirno bijela","#F8F8FF"),
      c("P\u0161enica","#F5DEB3"),
      c("Purpurna","#800080"),
      c("Raj\u010dica","#FF6347"),
      c("Rumena lavanda","#FFF0F5"),
      c("Ru\u017ei\u010dasta","#FFC0CB"),
      c("Ru\u017ei\u010dastosme\u0111a","#BC8F8F"),
      c("Siva","#808080"),
      c("Sivi \u0161kriljevac","#708090"),
      c("Sivo\u017euta","#F0E68C"),
      c("Sme\u0111a","#A52A2A"),
      c("Sme\u0111e sedlo","#8B4513"),
      c("Sme\u0111i pijesak","#F4A460"),
      c("Sme\u0111kasto bijela","#FFDEAD"),
      c("Snijeg","#FFFAFA"),
      c("Srebrna","#C0C0C0"),
      c("Srednja akvamarin","#66CDAA"),
      c("Srednja crvenoljubi\u010dasta","#C71585"),
      c("Srednja morskozelena","#3CB371"),
      c("Srednja orhideja","#BA55D3"),
      c("Srednja plava","#0000CD"),
      c("Srednja proljetnozelena","#00FA9A"),
      c("Srednja purpurna","#9370DB"),
      c("Srednja tirkizna","#48D1CC"),
      c("Srednje plavi \u0161kriljevac","#7B68EE"),
      c("Svijetla \u010deli\u010dnoplava","#B0C4DE"),
      c("Svijetla naran\u010dastoru\u017ei\u010dasta","#FFA07A"),
      c("Svijetli cijan","#E0FFFF"),
      c("Svijetlo drvo","#DEB887"),
      c("Svijetlokoraljna","#F08080"),
      c("Svijetlomorskozelena","#20B2AA"),
      c("Svijetloplava","#ADD8E6"),
      c("Svijetloru\u017ei\u010dasta","#FFB6C1"),
      c("Svijetlosiva","#D3D3D3"),
      c("Svijetlosivi \u0161kriljevac","#778899"),
      c("Svijetlozelena","#90EE90"),
      c("Svijetlo\u017euta kudelja","#FAFAD2"),
      c("Svijetlo\u017euta","#FFFFE0"),
      c("\u0160amotna opeka","#B22222"),
      c("\u0160koljka","#FFF5EE"),
      c("\u0160ljiva","#DDA0DD"),
      c("Tamna kudelja","#B8860B"),
      c("Tamna magenta","#8B008B"),
      c("Tamna naran\u010dastoru\u017ei\u010dasta","#E9967A"),
      c("Tamna orhideja","#9932CC"),
      c("Tamna sivo\u017euta","#BDB76B"),
      c("Tamni cijan","#008B8B"),
      c("Tamno zelena","#006400"),
      c("Tamnocrvena","#8B0000"),
      c("Tamnoljubi\u010dasta","#9400D3"),
      c("Tamnomaslinasta","#556B2F"),
      c("Tamnonaran\u010dasta","#FF8C00"),
      c("Tamnoplava","#00008B"),
      c("Tamnoplavi \u0161kriljevac","#483D8B"),
      c("Tamnosiva","#A9A9A9"),
      c("Tamnosivi \u0161kriljevac","#2F4F4F"),
      c("Tamnotirkizna","#00CED1"),
      c("Tamnozelena","#8FBC8F"),
      c("Tirkizna","#40E0D0"),
      c("Topla ru\u017ei\u010dasta","#FF69B4"),
      c("Vedro nebo","#87CEFA"),
      c("Voda","#00FFFF"),
      c("Zelena lipa","#32CD32"),
      c("Zelena \u0161uma","#228B22"),
      c("Zelena tratina","#7CFC00"),
      c("Zelena","#008000"),
      c("Zeleni liker","#7FFF00"),
      c("Zeleno\u017euta","#ADFF2F"),
      c("Zlatna","#FFD700"),
      c("\u017du\u0107kastocrvena zemlja","#CD5C5C"),
      c("\u017du\u0107kastoru\u017ei\u010dasta","#FFE4E1"),
      c("\u017du\u0107kastosme\u0111a glina","#A0522D"),
      c("\u017duta svila","#FFF8DC"),
      c("\u017duta","#FFFF00"),
      c("\u017dutozelena","#9ACD32")
    ),

    safe_colors = c(
      'crna', 'kestenjasta', 'zelena', 'mornarska', 'maslinasta',
      'purpurna', 'modrozelena', 'lipa', 'plava', 'srebrna',
      'siva', '\u017euta', 'fuksija', 'voda', 'bijela')
  )
)
# person --------------------------------------
person_hr_HR = R6Class(
  "person_hr_HR",
  inherit = person_init,
  cloneable = FALSE,
  private = list(
    formats = '{first_name} {last_name}',
    first_names_male = c(
      "Aldo",
      "Alen",
      "Andrija",
      "Ante",
      "Anto",
      "Anton",
      "Antonio",
      "Antun",
      "Boris",
      "Bo\u017eo",
      "Branko",
      "Bruno",
      "Dalibor",
      "Damir",
      "Danijel",
      "Dario",
      "Darko",
      "David",
      "Davor",
      "Dejan",
      "Denis",
      "Dino",
      "Domagoj",
      "Dominik",
      "Dragan",
      "Dragutin",
      "Dra\u017een",
      "Duje",
      "Du\u0161an",
      "Elvis",
      "Erik",
      "Filip",
      "Fran",
      "Franjo",
      "Goran",
      "Hrvoje",
      "Igor",
      "Ilija",
      "Ivan",
      "Ivica",
      "Ivo",
      "Jakov",
      "Janko",
      "Josip",
      "Joso",
      "Jozo",
      "Jo\u0161ko",
      "Juraj",
      "Jure",
      "Karlo",
      "Kristijan",
      "Leon",
      "Lovre",
      "Lovro",
      "Luka",
      "Marijan",
      "Marin",
      "Mario",
      "Marko",
      "Martin",
      "Mate",
      "Matej",
      "Mateo",
      "Matija",
      "Mato",
      "Mihael",
      "Mijo",
      "Milan",
      "Mile",
      "Mirko",
      "Miroslav",
      "Mislav",
      "Mladen",
      "Nenad",
      "Niko",
      "Nikola",
      "Nik\u0161a",
      "Patrik",
      "Pavao",
      "Pero",
      "Petar",
      "Robert",
      "Roko",
      "Romano",
      "Rudolf",
      "Sa\u0161a",
      "Sini\u0161a",
      "Slavko",
      "Stjepan",
      "Tomislav",
      "Tomo",
      "Toni",
      "Valter",
      "Vedran",
      "Viktor",
      "Vjekoslav",
      "Vladimir",
      "Vlado",
      "Zdravko",
      "Zlatko",
      "Zoran",
      "Zvonko",
      "\u0110uro",
      "\u0160ime",
      "\u017deljko"
    ),

    first_names_female = c(
      "Albina",
      "Ana",
      "Andrea",
      "Ane",
      "Anica",
      "Anita",
      "Anka",
      "Ankica",
      "Antonija",
      "An\u0111a",
      "An\u0111ela",
      "Bara",
      "Barbara",
      "Barica",
      "Biljana",
      "Biserka",
      "Bo\u017eena",
      "Bo\u017eica",
      "Branka",
      "Danica",
      "Danijela",
      "Dora",
      "Draga",
      "Dragica",
      "Elizabeta",
      "Ema",
      "Eva",
      "Franciska",
      "Fuma",
      "Gordana",
      "Hana",
      "Ika",
      "Iva",
      "Ivana",
      "Ivanka",
      "Ivka",
      "Jadranka",
      "Jana",
      "Janja",
      "Jasminka",
      "Jasna",
      "Jele",
      "Jelena",
      "Josipa",
      "Julijana",
      "Karla",
      "Kata",
      "Katarina",
      "Kate",
      "Katica",
      "Kristina",
      "Lana",
      "Lara",
      "Laura",
      "Lea",
      "Lidija",
      "Ljiljana",
      "Ljubica",
      "Lorena",
      "Lucija",
      "Maja",
      "Manda",
      "Mara",
      "Mare",
      "Maria",
      "Marica",
      "Marija",
      "Marijana",
      "Marina",
      "Marta",
      "Martina",
      "Matea",
      "Mateja",
      "Matija",
      "Mia",
      "Milena",
      "Milica",
      "Milka",
      "Mira",
      "Mirjana",
      "Nada",
      "Nata\u0161a",
      "Nevenka",
      "Nika",
      "Nikolina",
      "Nina",
      "Petra",
      "Renata",
      "Rozalija",
      "Ru\u017ea",
      "Ru\u017eica",
      "Sandra",
      "Sanja",
      "Sara",
      "Slavica",
      "Snje\u017eana",
      "Stana",
      "Suzana",
      "Tatjana",
      "Tea",
      "Terezija",
      "Valentina",
      "Vera",
      "Veronika",
      "Vesna",
      "Zdenka",
      "Zora",
      "Zorka",
      "\u0110ur\u0111ica",
      "\u0160tefanija",
      "\u0160tefica",
      "\u017deljka"
    ),

    first_names = c(
      "Aldo",
      "Alen",
      "Andrija",
      "Ante",
      "Anto",
      "Anton",
      "Antonio",
      "Antun",
      "Boris",
      "Bo\u017eo",
      "Branko",
      "Bruno",
      "Dalibor",
      "Damir",
      "Danijel",
      "Dario",
      "Darko",
      "David",
      "Davor",
      "Dejan",
      "Denis",
      "Dino",
      "Domagoj",
      "Dominik",
      "Dragan",
      "Dragutin",
      "Dra\u017een",
      "Duje",
      "Du\u0161an",
      "Elvis",
      "Erik",
      "Filip",
      "Fran",
      "Franjo",
      "Goran",
      "Hrvoje",
      "Igor",
      "Ilija",
      "Ivan",
      "Ivica",
      "Ivo",
      "Jakov",
      "Janko",
      "Josip",
      "Joso",
      "Jozo",
      "Jo\u0161ko",
      "Juraj",
      "Jure",
      "Karlo",
      "Kristijan",
      "Leon",
      "Lovre",
      "Lovro",
      "Luka",
      "Marijan",
      "Marin",
      "Mario",
      "Marko",
      "Martin",
      "Mate",
      "Matej",
      "Mateo",
      "Matija",
      "Mato",
      "Mihael",
      "Mijo",
      "Milan",
      "Mile",
      "Mirko",
      "Miroslav",
      "Mislav",
      "Mladen",
      "Nenad",
      "Niko",
      "Nikola",
      "Nik\u0161a",
      "Patrik",
      "Pavao",
      "Pero",
      "Petar",
      "Robert",
      "Roko",
      "Romano",
      "Rudolf",
      "Sa\u0161a",
      "Sini\u0161a",
      "Slavko",
      "Stjepan",
      "Tomislav",
      "Tomo",
      "Toni",
      "Valter",
      "Vedran",
      "Viktor",
      "Vjekoslav",
      "Vladimir",
      "Vlado",
      "Zdravko",
      "Zlatko",
      "Zoran",
      "Zvonko",
      "\u0110uro",
      "\u0160ime",
      "\u017deljko",
      "Albina",
      "Ana",
      "Andrea",
      "Ane",
      "Anica",
      "Anita",
      "Anka",
      "Ankica",
      "Antonija",
      "An\u0111a",
      "An\u0111ela",
      "Bara",
      "Barbara",
      "Barica",
      "Biljana",
      "Biserka",
      "Bo\u017eena",
      "Bo\u017eica",
      "Branka",
      "Danica",
      "Danijela",
      "Dora",
      "Draga",
      "Dragica",
      "Elizabeta",
      "Ema",
      "Eva",
      "Franciska",
      "Fuma",
      "Gordana",
      "Hana",
      "Ika",
      "Iva",
      "Ivana",
      "Ivanka",
      "Ivka",
      "Jadranka",
      "Jana",
      "Janja",
      "Jasminka",
      "Jasna",
      "Jele",
      "Jelena",
      "Josipa",
      "Julijana",
      "Karla",
      "Kata",
      "Katarina",
      "Kate",
      "Katica",
      "Kristina",
      "Lana",
      "Lara",
      "Laura",
      "Lea",
      "Lidija",
      "Ljiljana",
      "Ljubica",
      "Lorena",
      "Lucija",
      "Maja",
      "Manda",
      "Mara",
      "Mare",
      "Maria",
      "Marica",
      "Marija",
      "Marijana",
      "Marina",
      "Marta",
      "Martina",
      "Matea",
      "Mateja",
      "Matija",
      "Mia",
      "Milena",
      "Milica",
      "Milka",
      "Mira",
      "Mirjana",
      "Nada",
      "Nata\u0161a",
      "Nevenka",
      "Nika",
      "Nikolina",
      "Nina",
      "Petra",
      "Renata",
      "Rozalija",
      "Ru\u017ea",
      "Ru\u017eica",
      "Sandra",
      "Sanja",
      "Sara",
      "Slavica",
      "Snje\u017eana",
      "Stana",
      "Suzana",
      "Tatjana",
      "Tea",
      "Terezija",
      "Valentina",
      "Vera",
      "Veronika",
      "Vesna",
      "Zdenka",
      "Zora",
      "Zorka",
      "\u0110ur\u0111ica",
      "\u0160tefanija",
      "\u0160tefica",
      "\u017deljka"
    ),

    last_names = c(
      "Abi\u010di\u0107",
      "Abramovi\u0107",
      "Ad\u017eijevi\u0107",
      "Akma\u010di\u0107",
      "Alkovi\u0107",
      "Amanovi\u0107",
      "Amid\u017ei\u0107",
      "Andra\u0161ek",
      "Andrija\u0161evi\u0107",
      "Andrijevi\u0107",
      "Ani\u010di\u0107",
      "Anti\u0107",
      "Antolkovi\u0107",
      "Antoni\u0107",
      "Babi\u0107",
      "Bajan",
      "Baksa",
      "Balatinac",
      "Balin\u010di\u0107",
      "Bali\u0107",
      "Baljak",
      "Ban",
      "Bani\u010devi\u0107",
      "Banko",
      "Banovac",
      "Barac",
      "Bara\u0107",
      "Barbieri",
      "Barbir",
      "Barbi\u0107",
      "Bare\u0161i\u0107",
      "Bari\u0107",
      "Bari\u010devi\u0107",
      "Bari\u0161i\u0107",
      "Barkovi\u0107",
      "Barnaba",
      "Baru\u0161i\u0107",
      "Batrac",
      "Batrnek",
      "Bazjak",
      "Ba\u010dak",
      "Ba\u010di\u0107",
      "Ba\u0161i\u0107",
      "Ba\u0161nec",
      "Bebi\u0107",
      "Begonja",
      "Beleti\u0107",
      "Belo\u0161evi\u0107",
      "Beni\u0107",
      "Ben\u010di\u0107",
      "Berakovi\u0107",
      "Bernardi\u0107",
      "Berto\u0161a",
      "Bezi\u0107",
      "Bijeli\u0107",
      "Bingula",
      "Birki\u0107",
      "Birti\u0107",
      "Bi\u0107ani\u0107",
      "Bi\u010dak",
      "Bi\u010dani\u0107",
      "Bjeli\u0161",
      "Blagai\u0107",
      "Bla\u017eek",
      "Bla\u017eevi\u0107",
      "Bla\u017ei\u010dko",
      "Boban",
      "Bobanovi\u0107",
      "Bogadi",
      "Bogdan",
      "Bogovi\u0107",
      "Bojani\u0107",
      "Boljkovac",
      "Bol\u010devi\u0107",
      "Borak",
      "Borojevi\u0107",
      "Boro\u0161ak",
      "Bosilj",
      "Botica",
      "Boti\u0107",
      "Bo\u0161njak",
      "Bo\u0161njakovi\u0107",
      "Bo\u017eani\u0107",
      "Bo\u017eanovi\u0107",
      "Bo\u017eikovi\u0107",
      "Bo\u017ei\u0107",
      "Bo\u017ei\u010devi\u0107",
      "Bo\u017ei\u010dkovi\u0107",
      "Bradi\u0107",
      "Brajkovi\u0107",
      "Brali\u0107",
      "Brandi\u0107",
      "Brankovi\u0107",
      "Bra\u010dun",
      "Brcko",
      "Brezjan",
      "Britvec",
      "Brlas",
      "Brlek",
      "Brleti\u0107",
      "Bukvi\u0107",
      "Buljan",
      "Bungi\u0107",
      "Buni\u0107",
      "Bun\u010di\u0107",
      "Buri\u0107",
      "Bur\u010dul",
      "Bur\u0161i\u0107",
      "Butkovi\u0107",
      "Buzov",
      "Bu\u010danac",
      "Bu\u010dar",
      "Bu\u0161ljeta",
      "Cafuk",
      "Car",
      "Cari\u0107",
      "Cestari\u0107",
      "Ciganovi\u0107",
      "Cik",
      "Cindri\u0107",
      "Coli\u0107",
      "Crevar",
      "Crnekovi\u0107",
      "Crnkovi\u0107",
      "Cukon",
      "Culi",
      "Cveni\u0107",
      "Cvetkovi\u0107",
      "Cvetni\u0107",
      "Cvitan",
      "Cvrtila",
      "Dabo",
      "Damijani\u0107",
      "Damjanovi\u0107",
      "Darojkovi\u0107",
      "Dautanec",
      "Dautovi\u0107",
      "Debeli\u0107",
      "Dere\u017ei\u0107",
      "De\u017ee",
      "Didovi\u0107",
      "Dizdar",
      "Dobri\u0107",
      "Dolinar",
      "Doli\u0107",
      "Dominikovi\u0107",
      "Dominkovi\u0107",
      "Don\u010devi\u0107",
      "Dragi\u010devi\u0107",
      "Dragobratovi\u0107",
      "Dragojevi\u0107",
      "Drakuli\u0107",
      "Drandi\u0107",
      "Dra\u017ei\u0107",
      "Dretvi\u0107",
      "Dubove\u010dak",
      "Dujmovi\u0107",
      "Duki\u0107",
      "Duvan\u010di\u0107",
      "Dvojak",
      "D\u017eapo",
      "Erceg",
      "Ercegovi\u0107",
      "Ergoti\u0107",
      "Er\u0161ek",
      "Eterovi\u0107",
      "Fabijani\u0107",
      "Ferenac",
      "Filar",
      "Filipovi\u0107",
      "Filip\u010di\u0107",
      "Flego",
      "Forjan",
      "Frani\u0107",
      "Frani\u010devi\u0107",
      "Franji\u0107",
      "Franu\u0161i\u0107",
      "Fri\u0161\u010di\u0107",
      "Frketi\u0107",
      "Fu\u010dek",
      "Gabud",
      "Gale\u0161i\u0107",
      "Gali\u0107",
      "Galovi\u0107",
      "Gegi\u0107",
      "Gelemanovi\u0107",
      "Glasnovi\u0107",
      "Glavan",
      "Glavor",
      "Gligora",
      "Godini\u0107",
      "Golubi\u0107",
      "Goti\u0107",
      "Govor\u010dinovi\u0107",
      "Gracin",
      "Grba",
      "Grbac",
      "Gredi\u010dak",
      "Gregov",
      "Grgi\u0107",
      "Grgurevi\u0107",
      "Grguri\u0107",
      "Grgurovac",
      "Grubi\u0161i\u0107",
      "Gr\u017eeti\u0107",
      "Gr\u017ein\u010di\u0107",
      "Guberovi\u0107",
      "Gudelj",
      "Gulan",
      "Gu\u0161tin",
      "Hadrovi\u0107",
      "Had\u017ei\u0107",
      "Halambek",
      "Halapir",
      "Han\u017eek",
      "Harapin",
      "Hardi",
      "Herceg",
      "Herout",
      "He\u0107imovi\u0107",
      "Hini\u0107",
      "Hodak",
      "Horak",
      "Horvat",
      "Horvatek",
      "Horvatinec",
      "Horvati\u0107",
      "Hrabar",
      "Hrani\u0107",
      "Hranj",
      "Hrastinski",
      "Hren",
      "Hrvoji\u0107",
      "Hr\u0161ak",
      "Hr\u017eenjak",
      "Huljev",
      "Husnjak",
      "Ignac",
      "Iliji\u0107",
      "Ilinovi\u0107",
      "Ili\u0107",
      "Ivandi\u0107",
      "Ivanovi\u0107",
      "Ivan\u010dan",
      "Iv\u0161i\u0107",
      "Jagarinec",
      "Jage\u010di\u0107",
      "Jakopec",
      "Jakopovi\u0107",
      "Jakovac",
      "Jakovi\u0107",
      "Jakovljevi\u0107",
      "Jakupi\u0107",
      "Jaku\u0161",
      "Jasprica",
      "Jelavi\u0107",
      "Jeli\u0107",
      "Jemri\u0107",
      "Jerkovi\u0107",
      "Jonji\u0107",
      "Josipovi\u0107",
      "Jovanovac",
      "Jovanovi\u0107",
      "Jovi\u0107",
      "Jozi\u0107",
      "Jugovac",
      "Juki\u0107",
      "Jureti\u0107",
      "Jure\u0161ko",
      "Juri\u0107",
      "Juri\u0161i\u0107",
      "Jurjevi\u0107",
      "Jurkovi\u0107",
      "Jurlina",
      "Jur\u010di\u0107",
      "Kadija",
      "Kahlina",
      "Kalanjo\u0161",
      "Kalazi\u0107",
      "Kani\u0161ki",
      "Karagi\u0107",
      "Karamarko",
      "Karlovi\u0107",
      "Karmeli\u0107",
      "Karuza",
      "Kati\u0107",
      "Kauzlari\u0107",
      "Kelekovi\u0107",
      "Kele\u010di\u0107",
      "Keli\u0107",
      "Kerekovi\u0107",
      "Kevo",
      "Kinkela",
      "Kirin\u010di\u0107",
      "Klanac",
      "Klarin",
      "Klari\u0107",
      "Klasi\u0107",
      "Kligl",
      "Knezovi\u0107",
      "Kne\u017eevi\u0107",
      "Kocijan\u010di\u0107",
      "Kokanovi\u0107",
      "Kokori\u0107",
      "Kolarec",
      "Kolega",
      "Koli\u0107",
      "Komar",
      "Komljenovi\u0107",
      "Kopjar",
      "Kos",
      "Kosanovi\u0107",
      "Kosi\u0107",
      "Kostani\u0107",
      "Kostelac",
      "Kova\u010d",
      "Kova\u010dek",
      "Kova\u010devi\u0107",
      "Kova\u010di\u0107",
      "Ko\u0161ki",
      "Ko\u0161\u010devi\u0107",
      "Krajcar",
      "Kralj",
      "Kraljevi\u0107",
      "Kralji\u0107",
      "Kramari\u0107",
      "Kresonja",
      "Kri\u017ean",
      "Krpan",
      "Krznari\u0107",
      "Kr\u010deli\u0107",
      "Kr\u0161anac",
      "Kr\u017eelj",
      "Kujund\u017ei\u0107",
      "Kuku\u010dka",
      "Kunac",
      "Kupsjak",
      "Kurtoi\u0107",
      "Kuve\u017edi\u0107",
      "Kuzmi\u0107",
      "Ku\u010di\u0107",
      "Ku\u0161\u010devi\u0107",
      "Laba\u0161",
      "Labinjan",
      "Ladavac",
      "Lako\u0161eljac",
      "Lasi\u0107",
      "Lazar",
      "Legovi\u0107",
      "Lelas",
      "Leni\u0107",
      "Le\u0161i\u0107",
      "Le\u0161kovi\u0107",
      "Le\u0161\u010di\u0107",
      "Liber",
      "Licul",
      "Liovi\u0107",
      "Lisica",
      "Ljubeti\u0107",
      "Ljubi\u0107",
      "Ljubi\u010di\u0107",
      "Lojen",
      "Lorencin",
      "Lovri\u0107",
      "Luci\u0107",
      "Lukini\u0107",
      "Luki\u0107",
      "Luk\u0161a",
      "Luk\u0161i\u0107",
      "Lu\u010di\u0107",
      "Macan",
      "Maduni\u0107",
      "Magi\u0107",
      "Mahnet",
      "Majdeni\u0107",
      "Majstorovi\u0107",
      "Makovac",
      "Maleti\u0107",
      "Malnar",
      "Malo\u010da",
      "Mami\u0107",
      "Mamula",
      "Maras",
      "Marasovi\u0107",
      "Mara\u0161",
      "Marde\u0161i\u0107",
      "Mareti\u0107",
      "Marijanovi\u0107",
      "Marin",
      "Marinkovi\u0107",
      "Marinovi\u0107",
      "Mari\u0107",
      "Mari\u010devi\u0107",
      "Marjanovi\u0107",
      "Markanjevi\u0107",
      "Markovac",
      "Markovi\u0107",
      "Marku\u0161",
      "Martini\u0107",
      "Martinovi\u0107",
      "Martin\u010devi\u0107",
      "Marti\u0107",
      "Maru\u0161i\u0107",
      "Mar\u0161i\u0107",
      "Mar\u017ei\u0107",
      "Matahlija",
      "Matana",
      "Matas",
      "Mate\u0161a",
      "Matija\u0161",
      "Matijevi\u0107",
      "Mati\u0107",
      "Matko",
      "Matkovi\u0107",
      "Matokanovi\u0107",
      "Matovina",
      "Mato\u0161evi\u0107",
      "Matulin",
      "Matuli\u0107",
      "Mavra",
      "Ma\u0107e\u0161i\u0107",
      "Meda\u010d",
      "Medi\u0107",
      "Medved",
      "Mei\u0107",
      "Merka\u0161",
      "Mesari\u0107",
      "Mesi\u0107",
      "Mihali\u0107",
      "Mihaljevi\u0107",
      "Mihel\u010di\u0107",
      "Mihi\u0107",
      "Miki\u0107",
      "Mikle\u010di\u0107",
      "Mikulandra",
      "Mikulec",
      "Mikul\u010di\u0107",
      "Milas",
      "Milati\u0107",
      "Mileti\u0107",
      "Milevoj",
      "Milina",
      "Mili\u010di\u0107",
      "Miloslavi\u0107",
      "Miloti\u0107",
      "Milovac",
      "Mimica",
      "Mio\u010di\u0107",
      "Mirosavljevi\u0107",
      "Mirt",
      "Mi\u010deti\u0107",
      "Mi\u0161ak",
      "Mi\u0161e",
      "Mi\u0161kovi\u0107",
      "Modri\u0107",
      "Mofardin",
      "Mori\u0107",
      "Moscarda",
      "Moslavac",
      "Mo\u010dibob",
      "Mraovi\u0107",
      "Mudri",
      "Mudronja",
      "Mustapi\u0107",
      "Musta\u010d",
      "Mu\u0161\u0107et",
      "Mu\u017eina",
      "Mu\u017ei\u0107",
      "Naki\u0107",
      "Na\u010dinovi\u0107",
      "Nedi\u0107",
      "Nikoli\u0107",
      "Nimac",
      "Ni\u0161evi\u0107",
      "Ni\u017eeti\u0107",
      "Norac",
      "Novak",
      "Novosel",
      "Obradovi\u0107",
      "Obratov",
      "Odoba\u0161i\u0107",
      "Orbani\u0107",
      "Ore\u0161kovi\u0107",
      "Orli\u0107",
      "Orlovi\u0107",
      "Or\u0161oli\u0107",
      "Or\u0161o\u0161",
      "Or\u0161uli\u0107",
      "Ozimec",
      "Pajur",
      "Pali\u0107",
      "Pami\u0107",
      "Panduri\u0107",
      "Papak",
      "Papari\u0107",
      "Paradi",
      "Paveli\u0107",
      "Pavin",
      "Pavi\u0107",
      "Pavi\u010di\u0107",
      "Pavkovi\u0107",
      "Pavlovi\u0107",
      "Pecoti\u0107",
      "Pedi\u0161i\u0107",
      "Peharda",
      "Peni\u0107",
      "Perak",
      "Peri\u0107",
      "Peri\u0161i\u0107",
      "Perkov",
      "Perkovi\u0107",
      "Pero\u0161",
      "Peru\u0161ko",
      "Per\u010di\u0107",
      "Petek",
      "Peterlik",
      "Petri\u0107",
      "Petri\u010devi\u0107",
      "Petrovi\u0107",
      "Pe\u010dur",
      "Pe\u0161a",
      "Pe\u0161i\u0107",
      "Pikec",
      "Piljek",
      "Pintari\u0107",
      "Plantak",
      "Plantek",
      "Pla\u017eanin",
      "Ple\u0161e",
      "Pokas",
      "Pokos",
      "Poli\u0107",
      "Poljak",
      "Polonijo",
      "Polovi\u0107",
      "Pongrac",
      "Popovi\u0107",
      "Poropat",
      "Poslon",
      "Pozder",
      "Po\u017eega",
      "Predovan",
      "Prelec",
      "Preo\u010danin",
      "Pribani\u0107",
      "Priselac",
      "Prpi\u0107",
      "Prskalo",
      "Prtenja\u010da",
      "Puhari\u0107",
      "Puljiz",
      "Putinja",
      "Pu\u0161kari\u0107",
      "Radeli\u0107",
      "Radin",
      "Radinovi\u0107",
      "Radi\u0107",
      "Radman",
      "Radojkovi\u0107",
      "Radolovi\u0107",
      "Radovi\u0107",
      "Rado\u010daj",
      "Rado\u0161evi\u0107",
      "Ragu\u017e",
      "Rahija",
      "Rajn",
      "Raj\u010di\u0107",
      "Rakela",
      "Rakulji\u0107",
      "Raljevi\u0107",
      "Raspor",
      "Rastija",
      "Ra\u0111enovi\u0107",
      "Ra\u0161eta",
      "Ra\u0161i\u0107",
      "Ra\u017eov",
      "Rebi\u0107",
      "Renduli\u0107",
      "Resanovi\u0107",
      "Ribari\u0107",
      "Ribi\u0107",
      "Ribi\u010di\u0107",
      "Rijetkovi\u0107",
      "Risek",
      "Rito\u0161a",
      "Ri\u010dko",
      "Roca",
      "Roce",
      "Rogo\u0161i\u0107",
      "Rojni\u0107",
      "Roso",
      "Rube\u0161a",
      "Rubini\u0107",
      "Rukavina",
      "Rumora",
      "Sabljak",
      "Sabol",
      "Saka\u010d",
      "Salopek",
      "Sardeli\u0107",
      "Sedlar",
      "Semialjac",
      "Seni\u010di\u0107",
      "Ser\u0161i\u0107",
      "Sever",
      "Sikiri\u0107",
      "Simi\u0107",
      "Sino\u017ei\u0107",
      "Siroti\u0107",
      "Skupnjak",
      "Sladonja",
      "Slavica",
      "Smokovi\u0107",
      "Smoli\u0107",
      "Sobota",
      "Soka\u010d",
      "Soki\u0107",
      "Sokol",
      "Soldo",
      "Solomun",
      "Sori\u0107",
      "So\u0161i\u0107",
      "Sr\u0161en",
      "Stani\u0107",
      "Stani\u010di\u0107",
      "Stan\u010din",
      "Star\u010devi\u0107",
      "Stipanovi\u0107",
      "Stiperski",
      "Stojanov",
      "Stojni\u0107",
      "Stoj\u010devi\u0107",
      "Stolnik",
      "Sto\u0161i\u0107",
      "Stra\u017ei\u010di\u0107",
      "Strinavi\u0107",
      "Stupalo",
      "Sura\u0107",
      "Svetli\u010di\u0107",
      "Tepe\u0161",
      "Terlevi\u0107",
      "Terzi\u0107",
      "Te\u0161ija",
      "Tisaj",
      "Toi\u0107",
      "Tolj",
      "Tomi\u0107",
      "Tomi\u010di\u0107",
      "Tomljanovi\u0107",
      "Tonc",
      "Topi\u0107",
      "Toti\u0107",
      "Trbovi\u0107",
      "Trgov\u010di\u0107",
      "Triplat",
      "Trnski",
      "Trutani\u0107",
      "Tudi\u0107",
      "Tudor",
      "Tuksar",
      "Turina",
      "Turk",
      "Turudi\u0107",
      "Tur\u010dinov",
      "Tu\u0111a",
      "Tu\u0161ek",
      "Tu\u0161kan",
      "Ugrini\u0107",
      "Uki\u0107",
      "Urli\u0107",
      "U\u0161i\u0107",
      "Vaci",
      "Valenti\u0107",
      "Valjeti\u0107",
      "Varga",
      "Vei\u0107",
      "Vela",
      "Vidakovi\u0107",
      "Vidas",
      "Vidov",
      "Vidovi\u0107",
      "Viljevac",
      "Vinceti\u0107",
      "Vitasovi\u0107",
      "Vi\u017eintin",
      "Vladislavi\u0107",
      "Vla\u0161i\u0107",
      "Vojkovi\u0107",
      "Volarevi\u0107",
      "Volari\u0107",
      "Vorkapi\u0107",
      "Vozila",
      "Vrabelj",
      "Vrani\u0107",
      "Vrban",
      "Vretenar",
      "Vrhovec",
      "Vugdelija",
      "Vugec",
      "Vuk",
      "Vukman",
      "Vukobratovi\u0107",
      "Vukovi\u0107",
      "Vuku\u0161i\u0107",
      "Vuljak",
      "Vu\u010deti\u0107",
      "Vu\u010din",
      "Vu\u010dkovi\u0107",
      "Zakinja",
      "Zano\u0161ki",
      "Zeba",
      "Zebec",
      "Zeli\u0107",
      "Zgorelec",
      "Zmai\u0107",
      "Zrili\u0107",
      "Zrinski",
      "Zub\u010di\u0107",
      "\u0106ori\u0107",
      "\u0106osi\u0107",
      "\u0106uri\u0107",
      "\u010cagalj",
      "\u010cargonja",
      "\u010cizmi\u0107",
      "\u010ci\u0161",
      "\u010ci\u017eme\u0161ija",
      "\u010cop",
      "\u010coti\u0107",
      "\u010covi\u0107",
      "\u010cubri\u0107",
      "\u010cudi\u0107",
      "\u010cukman",
      "\u010culina",
      "\u010culjak",
      "\u010cupi\u0107",
      "\u010cu\u010dek",
      "\u0110ura\u0161evi\u0107",
      "\u0110urini\u0107",
      "\u0160ali\u0107",
      "\u0160anti\u0107",
      "\u0160arga\u010d",
      "\u0160ari\u0107",
      "\u0160arlija",
      "\u0160egovi\u0107",
      "\u0160elendi\u0107",
      "\u0160eparovi\u0107",
      "\u0160estak",
      "\u0160estan",
      "\u0160ibali\u0107",
      "\u0160imara",
      "\u0160imi\u0107",
      "\u0160imi\u010di\u0107",
      "\u0160imuni\u0107",
      "\u0160imunovi\u0107",
      "\u0160inkovi\u0107",
      "\u0160ipek",
      "\u0160ipi\u0107",
      "\u0160itum",
      "\u0160kara",
      "\u0160koda",
      "\u0160krlin",
      "\u0160krni\u010dki",
      "\u0160krti\u0107",
      "\u0160kugor",
      "\u0160kunca",
      "\u0160ok\u010devi\u0107",
      "\u0160o\u0161i\u0107",
      "\u0160o\u0161tari\u0107",
      "\u0160pika",
      "\u0160pi\u0161i\u0107",
      "\u0160poljari\u0107",
      "\u0160pralja",
      "\u0160tefanec",
      "\u0160tefovi\u0107",
      "\u0160tifani\u0107",
      "\u0160timac",
      "\u0160trbac",
      "\u0160trlji\u0107",
      "\u0160turlan",
      "\u0160unji\u0107",
      "\u0160upraha",
      "\u0160uran",
      "\u0160urbek",
      "\u0160urina",
      "\u0160verko",
      "\u017dabja\u010dan",
      "\u017dagar",
      "\u017derjav",
      "\u017de\u017eeli\u0107",
      "\u017dic",
      "\u017dikovi\u0107",
      "\u017divi\u0107",
      "\u017divkovi\u0107",
      "\u017dufika",
      "\u017dugec",
      "\u017dunec",
      "\u017dupani\u0107",
      "\u017duvela",
      "\u017du\u017ei\u0107"
    )
  )
)

# company --------------------------------------------
company_hr_HR = R6Class(
  "company_hr_HR",
  inherit = company_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_hr_HR$new())$.__enclos_env__$private$first_names,
    last_names = (person_hr_HR$new())$.__enclos_env__$private$last_names,
    first_name = (person_hr_HR$new())$first_name,
    last_name = (person_hr_HR$new())$last_name,

    formats = c(
      '{last_name} {company_suffix}',
      '{last_name} {last_name} {company_suffix}',
      '{last_name}'),

    company_suffixes = c(
      'd.o.o.', 'd.d.', 'j.d.o.o.')
  )
)

# date_time ------------------------------------------
date_time_hr_HR = R6Class(
  "date_time_hr_HR",
  inherit = date_time_init,
  cloneable = FALSE,
  private = list(
    DAY_NAMES = c(
      "0" = "Nedjelja",
      "1" = "Ponedjeljak",
      "2" = "Utorak",
      "3" = "Srijeda",
      "4" = "\u010cetvrtak",
      "5" = "Petak",
      "6" = "Subota"
    ),

    MONTH_NAMES = c(
      "01" = "Sije\u010danj",
      "02" = "Velja\u010da",
      "03" = "O\u017eujak",
      "04" = "Travanj",
      "05" = "Svibanj",
      "06" = "Lipanj",
      "07" = "Srpanj",
      "08" = "Kolovoz",
      "09" = "Rujan",
      "10" = "Listopad",
      "11" = "Studeni",
      "12" = "Prosinac"
    )
  )
)
# address -----------------------------------------------
address_hr_HR = R6Class(
  "address_hr_HR",
  inherit = address_init,
  cloneable = FALSE,
  private = list(

    first_names = (person_hr_HR$new())$.__enclos_env__$private$first_names,
    last_names = (person_hr_HR$new())$.__enclos_env__$private$last_names,
    first_name = (person_hr_HR$new())$first_name,
    last_name = (person_hr_HR$new())$last_name,

    city_formats = '{city_name}',

    street_name_formats = '{street_name}',
    street_address_formats = '{street_name} {building_number}',
    address_formats = '{street_address}\n{postcode} {city}',

    building_number_formats = c(
      '###', '##', '#', '#a', '#b', '#c',
      '#a/#', '#b/#', '#c/#'),

    postcode_formats = '#####',

    street_suffixes_long = c('', 'ulica', 'cesta', 'put', 'avenija'),

    street_suffixes_short = c('', 'ul.', 'c.', 'a.'),

    cities = c(
      "Bakar",
      "Beli Manastir",
      "Beli\u0161\u0107e",
      "Benkovac",
      "Biograd na Moru",
      "Bjelovar",
      "Buje",
      "Buzet",
      "Cres",
      "Crikvenica",
      "\u010cabar",
      "\u010cakovec",
      "\u010cazma",
      "Daruvar",
      "Delnice",
      "Donja Stubica",
      "Donji Miholjac",
      "Drni\u0161",
      "Dubrovnik",
      "Duga Resa",
      "Dugo Selo",
      "\u0110akovo",
      "\u0110ur\u0111evac",
      "Gare\u0161nica",
      "Glina",
      "Gospi\u0107",
      "Grubi\u0161no Polje",
      "Hrvatska Kostajnica",
      "Hvar",
      "Ilok",
      "Imotski",
      "Ivanec",
      "Ivani\u0107-Grad",
      "Jastrebarsko",
      "Karlovac",
      "Kastav",
      "Ka\u0161tela",
      "Klanjec",
      "Knin",
      "Komi\u017ea",
      "Koprivnica",
      "Kor\u010dula",
      "Kraljevica",
      "Krapina",
      "Kri\u017eevci",
      "Krk",
      "Kutina",
      "Kutjevo",
      "Labin",
      "Lepoglava",
      "Lipik",
      "Ludbreg",
      "Makarska",
      "Mali Lo\u0161inj",
      "Metkovi\u0107",
      "Mursko Sredi\u0161\u0107e",
      "Na\u0161ice",
      "Nin",
      "Nova Gradi\u0161ka",
      "Novalja",
      "Novi Marof",
      "Novi Vinodolski",
      "Novigrad",
      "Novska",
      "Obrovac",
      "Ogulin",
      "Omi\u0161",
      "Opatija",
      "Opuzen",
      "Orahovica",
      "Oroslavje",
      "Osijek",
      "Oto\u010dac",
      "Otok",
      "Ozalj",
      "Pag",
      "Pakrac",
      "Pazin",
      "Petrinja",
      "Pleternica",
      "Plo\u010de",
      "Popova\u010da",
      "Pore\u010d",
      "Po\u017eega",
      "Pregrada",
      "Prelog",
      "Pula",
      "Rab",
      "Rijeka",
      "Rovinj",
      "Samobor",
      "Senj",
      "Sinj",
      "Sisak",
      "Skradin",
      "Slatina",
      "Slavonski Brod",
      "Slunj",
      "Solin",
      "Split",
      "Stari Grad",
      "Supetar",
      "Sveta Nedelja",
      "Sveti Ivan Zelina",
      "\u0160ibenik",
      "Trilj",
      "Trogir",
      "Umag",
      "Valpovo",
      "Vara\u017edin",
      "Vara\u017edinske Toplice",
      "Velika Gorica",
      "Vinkovci",
      "Virovitica",
      "Vis",
      "Vodice",
      "Vodnjan",
      "Vrbovec",
      "Vrbovsko",
      "Vrgorac",
      "Vrlika",
      "Vukovar",
      "Zabok",
      "Zadar",
      "Zagreb",
      "Zapre\u0161i\u0107",
      "Zlatar"
    ),

    streets = c(
      "Arnoldova",
      "Baka\u010deva",
      "Bijeni\u010dka",
      "Bosanska",
      "Bu\u010darova",
      "Cmrok",
      "\u010ca\u010dkovi\u0107eva",
      "Davor",
      "Demetrova",
      "Dolac",
      "Donje Prekri\u017eje",
      "Dra\u0161kovi\u0107eva",
      "Dubravkin",
      "Dverce",
      "Dvoranski pre\u010dac",
      "Glogovac",
      "Golubovac",
      "Golja\u010dke",
      "Goljak",
      "Gornje Prekri\u017eje",
      "Gra\u010danska",
      "Gradec",
      "Gri\u010d",
      "Gup\u010deva zvijezda",
      "Harmica",
      "Hercegova\u010dka",
      "Horvatovac",
      "Ilica",
      "Istarska",
      "Jabukovac",
      "Jadranska",
      "Jagodnjak",
      "Javorovac",
      "Jezuitski trg",
      "Juri\u0161i\u0107eva",
      "Jurjeve",
      "Jurjevska",
      "Jurkovi\u0107eva",
      "Kamaufova",
      "Kamenita",
      "Kamenjak",
      "Kaptol",
      "Kapucinske",
      "Klanac Grgura Tepe\u010di\u0107a",
      "Klenovac",
      "Klesarski put",
      "Kozar\u010dev vijenac",
      "Ko\u017earska",
      "Kraljevec",
      "Kraljevec II.",
      "Kraljeve\u010dki odvojak",
      "Kraljeve\u010dki ogranak",
      "Krle\u017ein gvozd",
      "Krvavi most",
      "Ksaver",
      "Ksaverska",
      "Kurel\u010deva",
      "Lisinskoga",
      "Lobmayerove",
      "Ljubinkovac",
      "Magdi\u0107eve",
      "Mala",
      "Male",
      "Ma\u0161ekova",
      "Medvedgradska",
      "Medve\u0161\u010dak",
      "Mesni\u010dka",
      "Mihaljevac",
      "Mirogojska",
      "Mleta\u010dka",
      "Mlinarska",
      "Mlinovi",
      "Mlinske",
      "Naumovac",
      "Nemetova",
      "Nova Ves",
      "Novi Goljak",
      "Opati\u010dka",
      "Opatovina",
      "Orlovac",
      "Palmoti\u0107eva",
      "Pantov\u010dak",
      "Paunovac",
      "Perivoj biskupa Stjepana II.",
      "Perivoj srpanjskih \u017ertava",
      "Petrova",
      "Pod zidom",
      "Podgaj",
      "Radni\u010dki dol",
      "Remetska",
      "Ribnjak",
      "Rikardove",
      "Rockefellerova",
      "Rokov perivoj",
      "Rokova",
      "Ru\u017ei\u010dnjak",
      "Skalinska",
      "Slavujevac",
      "Splavnica",
      "Srebrnjak",
      "Strelja\u010dka",
      "Strossmayerovo \u0161etali\u0161te",
      "Svibovac",
      "Svibovac",
      "\u0160alata",
      "\u0160estinski vijenac",
      "\u0160estinski vrh",
      "\u0160ilobodov put",
      "\u0160umski pre\u010dac",
      "Tkal\u010di\u0107eva",
      "To\u0161ovac",
      "Tu\u0161kanac",
      "Vijenac",
      "Vinogradska",
      "Visoka",
      "Vi\u0161njica",
      "Vi\u0161nji\u010dke",
      "Vitezovi\u0107eva",
      "Vla\u0161ka",
      "Vo\u0107arska",
      "Vo\u0107arsko naselje",
      "Von\u010dinina",
      "Vrazovo \u0161etali\u0161te",
      "Wickerhauserova",
      "Zamenhofova",
      "Zamenhofove",
      "Zavojna",
      "Zelengaj",
      "Zeleni dol",
      "Zelenjak",
      "Zmajevac",
      "Zvonarni\u010dka"
    ),

    states = c(
      "Zagreba\u010dka",
      "Krapinsko-zagorska",
      "Sisa\u010dko-moslava\u010dka",
      "Karlova\u010dka",
      "Vara\u017edinska",
      "Koprivni\u010dko-kri\u017eeva\u010dka",
      "Bjelovarsko-bilogorska",
      "Primorsko-goranska",
      "Li\u010dko-senjska",
      "Viroviti\u010dko-podravska",
      "Po\u017ee\u0161ko-slavonska",
      "Brodsko-posavska",
      "Zadarska",
      "Osje\u010dko-baranjska",
      "\u0160ibensko-kninska",
      "Vukovarsko-srijemska",
      "Splitsko-dalmatinska",
      "Istarska",
      "Dubrova\u010dko-neretvanska",
      "Me\u0111imurska",
      "Grad Zagreb"
    ),

    countries = c(
      "Afganistan",
      "Alandski otoci",
      "Albanija",
      "Al\u017eir",
      "Ameri\u010dka Samoa",
      "Ameri\u010dki Djevi\u010danski Otoci",
      "Andora",
      "Angola",
      "Anguila",
      "Antarktik",
      "Antigua i Barbuda",
      "Argentina",
      "Armenija",
      "Aruba",
      "Australija",
      "Austrija",
      "Azerbajd\u017ean",
      "Bahami",
      "Bahrein",
      "Banglade\u0161",
      "Barbados",
      "Belgija",
      "Belize",
      "Benin",
      "Bermuda",
      "Bjelorusija",
      "Bocvana",
      "Bolivija",
      "Bosna i Hercegovina",
      "Bo\u017ei\u0107ni Otok",
      "Brazil",
      "Britanski Djevi\u010danski Otoci",
      "Britanski Teritorij Indijskog Oceana",
      "Brunei Darussalam",
      "Bugarska",
      "Burkina Faso",
      "Burundi",
      "Butan",
      "Cipar",
      "Crna Gora",
      "Curacao",
      "\u010cad",
      "\u010cile",
      "Danska",
      "Dominika",
      "Dominikanska Republika",
      "D\u017eibuti",
      "Egipat",
      "Ekvador",
      "Ekvatorska Gvineja",
      "El Salvador",
      "Eritreja",
      "Estonija",
      "Etiopija",
      "Falklandi",
      "Farski Otoci",
      "Fid\u017ei",
      "Filipini",
      "Finska",
      "Francuska",
      "Francuska Gvajana",
      "Francuska Polinezija",
      "Francuski Ju\u017eni Teritoriji",
      "Gabon",
      "Gambija",
      "Gana",
      "Gibraltar",
      "Vatikan",
      "Gr\u010dka",
      "Grenada",
      "Grenland",
      "Gruzija",
      "Guadeloupe",
      "Guam",
      "Guernsey",
      "Gvajana",
      "Gvatemala",
      "Gvineja",
      "Gvineja Bisau",
      "Haiti",
      "Honduras",
      "Hong Kong",
      "Hrvatska",
      "Indija",
      "Indonezija",
      "Irak",
      "Iran, Islamska Republika",
      "Irska",
      "Island",
      "Isle Of Man",
      "Isto\u010dni Timor",
      "Italija",
      "Izrael",
      "Jamajka",
      "Japan",
      "Jemen",
      "Jersey",
      "Jordan",
      "Ju\u017ena Afrika",
      "Ju\u017ena Gruzija i Ju\u017eni Sendvi\u010d Otoci",
      "Kajmanski Otoci",
      "Kambod\u017ea",
      "Kamerun",
      "Kanada",
      "Katar",
      "Kazakstan",
      "Kenija",
      "Kina",
      "Kirgistan",
      "Kiribati",
      "Kokosovi Otoci",
      "Kolumbija",
      "Komori",
      "Kongo",
      "Kongo, Demokratska Republika",
      "Koreja, Ju\u017ena",
      "Koreja, Sjeverna",
      "Kosovo",
      "Kostarika",
      "Kuba",
      "Kukovi Otoci",
      "Kuvajt",
      "Laoska Narodna Demokratska Republika",
      "Latvija",
      "Lesoto",
      "Libanon",
      "Liberija",
      "Libijska Arapska D\u017eamahirija",
      "Lihten\u0161tajn",
      "Litva",
      "Luksemburg",
      "Madagaskar",
      "Ma\u0111arska",
      "Majote",
      "Makao",
      "Makedonija",
      "Malavi",
      "Maldivi Maldives",
      "Malezija",
      "Mali",
      "Malta",
      "Maroko",
      "Mar\u0161alovi Otoci",
      "Martinik",
      "Mauricijus",
      "Mauritanija",
      "Meksiko",
      "Mijanmar",
      "Mikronezija",
      "Moldavija, Republika",
      "Monako",
      "Mongolija",
      "Montserat",
      "Mozambik",
      "Namibija",
      "Nauru",
      "Nepal",
      "Niger",
      "Nigerija",
      "Nikaragva",
      "Niue",
      "Nizozemska",
      "Norve\u0161ka",
      "Nova Kaledonija",
      "Novi Zeland",
      "Njema\u010dka",
      "Obala Slonova\u010de",
      "Oman",
      "Otok Bouvet",
      "Otok Heard i Otoci McDonald",
      "Otok Norfolk",
      "Pakistan",
      "Palau",
      "Palestinsko Podru\u010dje",
      "Panama",
      "Papua Nova Gvineja",
      "Paragvaj",
      "Peru",
      "Pitcairn",
      "Poljska Poland",
      "Portoriko",
      "Portugal",
      "Republika \u010ce\u0161ka",
      "Reunion",
      "Ruanda",
      "Rumunjska",
      "Rusija",
      "Salamunovi Otoci",
      "Samoa",
      "San Marino",
      "S\u00e3o Tom\u00e9 ai Pr\u00edncipe",
      "Saudijska Arabija",
      "Sej\u0161eli",
      "Senegal",
      "Sijera Leone",
      "Singapur",
      "Sint Maarten",
      "Sirija",
      "Sjedinjene Ameri\u010dke Dr\u017eave",
      "Sjeverni Marijanski Otoci",
      "Slova\u010dka",
      "Slovenija",
      "Somalija",
      "Ju\u017eni Sudan",
      "Srbija",
      "Srednjoafri\u010dka Republika",
      "Sudan",
      "Surinam",
      "Svalbard i Jan Mayen",
      "Svaziland",
      "Sveta Helena",
      "Sveti Bartolomej",
      "Sveti Martin",
      "Sveti Petar i Miguel",
      "Sv. Kristofor i Nevis",
      "Sv. Lucija",
      "Sv. Vincent i Grenadini",
      "\u0160panjolska",
      "\u0160ri Lanka",
      "\u0160vedska",
      "\u0160vicarska",
      "Tad\u017eikistan",
      "Tajland",
      "Tajvan",
      "Tanzanija",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad i Tobago",
      "Tunis",
      "Turkmenistan",
      "Turkski i Kaikos Otoci",
      "Turska",
      "Tuvalu",
      "Uganda",
      "Ujedinjene Dr\u017eave Manjih Pacifi\u010dkih Otoka",
      "Ujedinjeni Arapski Emirati",
      "Ukrajina",
      "Urugvaj",
      "Uzbekistan",
      "Vanuatu",
      "Velika Britanija",
      "Venezuela",
      "Vijetnam",
      "Wallis i Futuna",
      "Zambija",
      "Zapadna Sahara",
      "Zeleni Rt"
    )
  ),

  public = list(
    city_name = function(){
      return(private$random_element(private$cities))
    },

    street_name = function(){
      return(private$random_element(private$streets))
    },

    state = function(){
      return(private$random_element(private$states))
    }
  )
)
# internet ------------------------------------------------
internet_hr_HR = R6Class(
  "internet_hr_HR",
  inherit = internet_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_hr_HR$new())$.__enclos_env__$private$first_names,
    last_names = (person_hr_HR$new())$.__enclos_env__$private$last_names,
    first_name = (person_hr_HR$new())$first_name,
    last_name = (person_hr_HR$new())$last_name,

    free_email_domains = c(
      'gmail.com', 'hotmail.com', 'yahoo.com',
      'net.hr', 'zg.t-com.hr', 'inet.hr', 't.ht.hr', 'vip.hr',
      'globalnet.hr', 'xnet.hr', 'yahoo.hr', 'zagreb.hr'),

    tlds = c('hr', 'com', 'com.hr', 'info', 'org', 'net', 'biz'),

    replacements = list(
      c("\u010d","c"),
      c("\u010c","C"),
      c("\u0107","c"),
      c("\u0106","C"),
      c("\u0111","dj"),
      c("\u0110","Dj"),
      c("\u0161","s"),
      c("\u0160","S"),
      c("\u017e","z"),
      c("\u017d","Z")
    )
  ),
  public = list(
    domain_word = function() {
      company = (company_hr_HR$new())$company()
      company_elements = str_split(company, " ")[[1]]
      company = private$to_ascii(company_elements[1])
      return(private$slugify(company, allow_unicode = TRUE))
    }
  )
)
# job --------------------------------------------
job_hr_HR = R6Class(
  "job_hr_HR",
  inherit = job_init,
  cloneable = FALSE,
  private = list(
    jobs = c(
      "Agent posredovanja u prometu nekretnina",
      "Alatni\u010dar",
      "Arhivist",
      "Arhivski savjetnik",
      "Arhivski tehni\u010dar",
      "Autoelektri\u010dar",
      "Autolakirer",
      "Autolimar",
      "Automehani\u010dar",
      "Autoserviser",
      "Bravar",
      "Brodostrojarski inspektor",
      "Brodski mehani\u010dar",
      "Dentalni asistent",
      "Dentalni tehni\u010dar",
      "Dimnja\u010dar",
      "Diplomirana medicinska sestra/medicinski tehni\u010dar",
      "Diplomirani fizioterapeut",
      "Diplomirani knji\u017eni\u010dar",
      "Diplomirani sanitarni in\u017eenjer",
      "Direktor predstavni\u0161tva",
      "Direktor turisti\u010dkog ureda turisti\u010dke zajednice",
      "Dispe\u010der leta / operativni kontrolor prometa",
      "Djelatnik koji obavlja poslove izvo\u0111enja glasnog pucnja",
      "Djelatnik koji obavlja poslove izvo\u0111enja javnog vatrometa",
      "Djelatnik koji obavlja poslove miniranja",
      "Djelatnik koji obavlja poslove miniranja pri razminiranju",
      "Djelatnik koji obavlja poslove podzemnih miniranja",
      "Djelatnik koji obavlja poslove pripreme miniranja",
      "Djelatnik koji obavlja poslove specijalnih miniranja",
      "Djelatnik slu\u017ebe za za\u0161titu od po\u017eara",
      "Djelatnik za obavljanje poslova za\u0161tite od po\u017eara i unapre\u0111enje stanja za\u0161tite od po\u017eara",
      "Doktor dentalne medicine",
      "Doktor dentalne medicine specijalist",
      "Doktor medicine",
      "Doktor medicine specijalist",
      "Dokumentarist",
      "Dokumentarist savjetnik",
      "Do\u010dasnik",
      "Edukacijski rehabilitator",
      "Elektroinstalater",
      "Elektromehani\u010dar",
      "Elektroni\u010dar \u2013 mehani\u010dar",
      "Farmaceutski tehni\u010dar",
      "Fasader",
      "Fizioterapeutski tehni\u010dar",
      "Fotograf",
      "Frizer",
      "Galanterist",
      "Geolo\u0161ki tehni\u010dar",
      "Glavni inspektor za\u0161tite okoli\u0161a",
      "Glavni nadzornik",
      "Glazbalar",
      "Graditelj brodova",
      "Graditelj orgulja",
      "Hidrogra\u0111evinski  inspektor",
      "Informati\u010dar",
      "Informati\u010dar savjetnik",
      "Inspektor sigurnosti unutarnje plovidbe",
      "Inspektor za\u0161tite okoli\u0161a",
      "Inspektor za\u0161tite prirode",
      "Instalater grijanja i klimatizacije",
      "Instruktor vo\u017enje",
      "In\u017eenjer geologije",
      "In\u017eenjer gradili\u0161ta",
      "In\u017eenjer medicinske radiologije",
      "In\u017eenjer medicinsko- laboratorijske dijagnostike",
      "In\u017eenjer naftnog rudarstva",
      "In\u017eenjer rudarstva",
      "Kemijski \u010dista\u010d",
      "Klesar",
      "Klobu\u010dar",
      "Knji\u017eni\u010dar",
      "Knji\u017eni\u010darski savjetnik",
      "Kondukter",
      "Kontrolor zra\u010dnog prometa",
      "Konzervator",
      "Konzervator savjetnik",
      "Konzervator tehni\u010dar",
      "Konzervator \u2013 restaurator savjetnik",
      "Konzervator \u2013  restaurator",
      "Koordinator za\u0161tite na radu",
      "Kormilar",
      "Kotlar",
      "Kova\u010d",
      "Kozmeti\u010dar",
      "Kriminalist",
      "Kroja\u010d mu\u0161ke odje\u0107e",
      "Kroja\u010d \u017eenske odje\u0107e",
      "Krovopokriva\u010d",
      "Krznar",
      "Kuhar",
      "Kustos",
      "Lektor hrvatskog jezika na stranim visoko\u0161kolskim ustanovama",
      "Limar",
      "Ljekarnik",
      "Ljekarnik specijalist",
      "Ljeva\u010d",
      "Lovac",
      "Lovo\u010duvar",
      "Magistar sanitarnog in\u017eenjerstva",
      "Magistar sestrinstva",
      "Maser \u2013 kupeljar",
      "Medicinska sestra op\u0107e njege",
      "Medicinska sestra-medicinski tehni\u010dar",
      "Medicinska sestra/medicinski tehni\u010dar specijalist",
      "Medicinski biokemi\u010dar",
      "Medicinski biokemi\u010dar specijalist",
      "Mehani\u010dar poljoprivredne mehanizacije",
      "Mesar",
      "Mlinar",
      "Mljekar",
      "Mornar",
      "Muzejski pedagog",
      "Muzejski pedagog savjetnik",
      "Muzejski savjetnik",
      "Muzejski tehni\u010dar",
      "Nadzornik",
      "Nadzornik tehni\u010dke ispravnosti vozila",
      "Nadzornik za okoli\u0161",
      "Nastavnik predmetne nastave u srednjoj \u0161koli",
      "Natkonobar",
      "Nauti\u010dki inspektor",
      "Obu\u0107ar",
      "Ocjenjiva\u010d lova\u010dkih trofeja",
      "Odgajatelj u u\u010deni\u010dkom domu",
      "Odgojitelj djece pred\u0161kolske dobi",
      "Odgovorna osoba za ocjenjivanje sukladnosti gra\u0111evinskih proizvoda",
      "Odvjetnik",
      "Ortopedski obu\u0107ar",
      "Osoba koja provodi energetske preglede gra\u0111evina i/ili energetsko certificiranje zgrada",
      "Osoba stru\u010dno osposobljena za gospodarski ribolov",
      "Osoba stru\u010dno osposobljena za obavljanje akvakulture",
      "Osoba stru\u010dno osposobljena za uzgoj riba i drugih morskih organizama",
      "Osoblje za odr\u017eavanje  zrakoplova (mehani\u010dari, tehni\u010dari i in\u017eenjeri)",
      "Ovla\u0161tena osoba za izradu elaborata za\u0161tite od po\u017eara",
      "Ovla\u0161teni arhitekt",
      "Ovla\u0161teni arhitekt \u2013 urbanist",
      "Ovla\u0161teni carinski slu\u017ebenik",
      "Ovla\u0161teni carinski zastupnik",
      "Ovla\u0161teni in\u017eenjer drvne tehnologije",
      "Ovla\u0161teni in\u017eenjer elektrotehnike",
      "Ovla\u0161teni in\u017eenjer geodezije",
      "Ovla\u0161teni in\u017eenjer gra\u0111evinarstva",
      "Ovla\u0161teni in\u017eenjer strojarstva",
      "Ovla\u0161teni in\u017eenjer tehnologije prometa i transporta",
      "Ovla\u0161teni in\u017eenjer \u0161umarstva",
      "Ovla\u0161teni ispitiva\u010d",
      "Ovla\u0161teni revident iz za\u0161tite od po\u017eara",
      "Ovla\u0161teni revizor",
      "Ovla\u0161teni unutarnji revizor za javni sektor",
      "O\u010dni opti\u010dar",
      "Pediker",
      "Pekar",
      "Pe\u0107ar",
      "Pirotehni\u010dar",
      "Pirotehni\u010dki nadglednik",
      "Pirotehni\u010dki nadzornik",
      "Pismoslikar",
      "Plinoinstalater",
      "Policajac",
      "Pomo\u0107ni djelatnik",
      "Pomo\u0107ni knji\u017eni\u010dar",
      "Pomo\u0107nik strojovo\u0111e",
      "Porezni savjetnik",
      "Precizni mehani\u010dar",
      "Predava\u010d",
      "Pregleda\u010d vagona",
      "Preparator",
      "Primalja",
      "Primalja \u2013 asistentica",
      "Privatni detektiv",
      "Profesionalni diplomat",
      "Profesionalni pilot aviona",
      "Profesionalni pilot helikoptera",
      "Prometni pilot aviona",
      "Prometni pilot helikoptera",
      "Prometnik vlakova",
      "Prvostupnik fizioterapije",
      "Prvostupnik medicinske radiologije",
      "Prvostupnik medicinsko- laboratorijske dijagnostike",
      "Prvostupnik primaljstva",
      "Prvostupnik radiolo\u0161ke tehnologije",
      "Prvostupnik radne terapije",
      "Prvostupnik sanitarnog in\u017eenjerstva",
      "Prvostupnik sestrinstva",
      "Prvostupnik sestrinstva specijalist",
      "Psiholog",
      "Pu\u0161kar",
      "Radio inspektor sigurnosti plovidbe",
      "Radiolo\u0161ki tehni\u010dar",
      "Radnik na stru\u010dnim poslovima na izvr\u0161enju zada\u0107a turisti\u010dke zajednice",
      "Radnik zaposlen na rukovode\u0107im poslovima",
      "Ravnatelj ustanove za pred\u0161kolski odgoj i naobrazbu",
      "Ravnatelj \u0161kolske ustanove",
      "Referent za poslove registracije vozila",
      "Restaurator",
      "Restaurator majstor",
      "Restaurator savjetnik",
      "Restaurator tehni\u010dar",
      "Revident",
      "Rudarski tehni\u010dar",
      "Rukovatelj eksplozivnim tvarima",
      "Rukovoditelj tehni\u010dkog plovila",
      "Sanitarni tehni\u010dar",
      "Sigurnosni savjetnik",
      "Slasti\u010dar",
      "Soboslikar \u2013 li\u010dilac",
      "Socijalni radnik",
      "Sportski trener",
      "Sportski u\u010ditelj / instruktor",
      "Sportski voditelj",
      "Staklar",
      "Stalni sudski procjenitelj",
      "Stalni sudski tuma\u010d",
      "Stalni sudski vje\u0161tak",
      "Stolar",
      "Strojar unutarnje plovidbe",
      "Strojobravar",
      "Strojovo\u0111a",
      "Strukovni u\u010ditelj u srednjoj \u0161koli",
      "Stru\u010dni radnik u djelatnosti socijalne skrbi",
      "Stru\u010dni radnik u ustanovi socijalne skrbi",
      "Stru\u010dni suradnik ovla\u0161tenog in\u017eenjera geodezije",
      "Stru\u010dni suradnik u pred\u0161kolskoj ustanovi",
      "Stru\u010dni suradnik u \u0161kolskoj ustanovi",
      "Stru\u010dni voditelj auto\u0161kole",
      "Stru\u010dnjak za\u0161tite na radu",
      "Suradnik ovla\u0161tenog in\u017eenjera geodezije",
      "Suradnik u nastavi",
      "Tapetar",
      "Tesar",
      "Tokar",
      "Turisti\u010dki pratitelj",
      "Turisti\u010dki vodi\u010d",
      "Upravitelj prijevoza (osoba odgovorna za prijevoz)",
      "Urar",
      "U\u010ditelj predmetne nastave u osnovnoj \u0161koli",
      "U\u010ditelj razredne nastave u osnovnoj \u0161koli",
      "U\u010ditelj stru\u010dnih predmeta",
      "Veterinar",
      "Veterinarski tehni\u010dar",
      "Vi\u0161i arhivist",
      "Vi\u0161i arhivski tehni\u010dar",
      "Vi\u0161i dokumentarist",
      "Vi\u0161i fotograf",
      "Vi\u0161i informati\u010dar",
      "Vi\u0161i inspektor",
      "Vi\u0161i inspektor cestovnog prometa i cesta",
      "Vi\u0161i inspektor za\u0161tite okoli\u0161a",
      "Vi\u0161i inspektor za\u0161tite prirode",
      "Vi\u0161i knji\u017eni\u010dar",
      "Vi\u0161i konzervator",
      "Vi\u0161i konzervator tehni\u010dar",
      "Vi\u0161i konzervator tehni\u010dar II stupnja",
      "Vi\u0161i konzervator \u2013  restaurator",
      "Vi\u0161i kustos",
      "Vi\u0161i muzejski pedagog",
      "Vi\u0161i muzejski tehni\u010dar",
      "Vi\u0161i preparator",
      "Vi\u0161i restaurator",
      "Vi\u0161i restaurator tehni\u010dar",
      "Vlakovo\u0111a",
      "Voditelj ispostave",
      "Voditelj poslovnice turisti\u010dke agencije",
      "Voditelj projekta",
      "Voditelj radili\u0161ta",
      "Voditelj radova",
      "Voditelj skele u nacionalnoj plovidbi",
      "Vodoinstalater",
      "Vodoinstalater, instalater grijanja i klimatizacije",
      "Vojnik",
      "Voza\u010d teretnog motornog vozila i autobusa",
      "Vo\u0111a palube",
      "Zapovjednik plovila (vrsta A, vrsta B, vrsta C)",
      "Za\u0161titar",
      "Za\u0161titar-tehni\u010dar",
      "Zdravstveno laboratorijski tehni\u010dar",
      "Zidar",
      "Zlatar",
      "\u010casnik",
      "\u010clan kabinske posade zrakoplova",
      "\u010cuvar",
      "\u010cuvar prirode"
    )
  )
)
# phone_number --------------------------------------------------
phone_number_hr_HR = R6Class(
  "phone_number_hr_HR",
  inherit = phone_number_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '01 #### ###',
      '020 ### ###',
      '021 ### ###',
      '022 ### ###',
      '023 ### ###',
      '031 ### ###',
      '032 ### ###',
      '033 ### ###',
      '034 ### ###',
      '035 ### ###',
      '040 ### ###',
      '042 ### ###',
      '043 ### ###',
      '044 ### ###',
      '047 ### ###',
      '048 ### ###',
      '049 ### ###',
      '051 ### ###',
      '052 ### ###',
      '053 ### ###',
      '060 ### ###',
      '072 ### ###',
      '074 ### ###',
      '091 #### ###',
      '092 #### ###',
      '095 #### ###',
      '097 #### ###',
      '098 #### ###',
      '099 #### ###',
      '0800 ## ##'
    )
  )
)
# ssn ------------------------------------------------
ssn_hr_HR = R6Class(
  "ssn_hr_HR",
  inherit = ssn_init,
  cloneable = FALSE,
  private = list(
    vat_id_formats = 'HR###########',
    checksum = function(digits) {
      # Calculate and return control digit for given list of digits based on
      # ISO7064, MOD 11,10 standard.
      remainder = 10
      for (digit in digits) {
        remainder = (remainder + digit) %% 10
        if (remainder == 0) remainder = 10
        remainder = (remainder * 2) %% 11
      }

      control_digit = 11 - remainder
      if (control_digit == 10) control_digit = 0
      return(control_digit)
    }
  ),

  public = list(
    ssn = function(){
      digits = sample(seq(0, 9), 10)
      digits = c(digits, checksum(digits))
      return(str_c(digits, collapse = ""))
    },

    vat_id = function(){
      # http://ec.europa.eu/taxation_customs/vies/faq.html#item_11
      # :return: A random Croatian VAT ID
      return(private$bothify(private$random_element(private$vat_id_formats)))
    }
  )
)
# credit_card -----------------
credit_card_hr_HR = R6Class(
  "credit_card_hr_HR",
  inherit = credit_card_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_hr_HR$new())$.__enclos_env__$private$first_names,
    first_name = (person_hr_HR$new())$first_name,
    last_names = (person_hr_HR$new())$.__enclos_env__$private$last_names,
    last_name = (person_hr_HR$new())$last_name
  )
)




## profile ------------------
profile_hr_HR = R6Class(
  "profile_hr_HR",
  inherit = profile_init,
  cloneable = FALSE,
  public = list(
    simple_profile = function(sex) {
      # Generates a basic profile with personal informations
      SEX = c("F", "M")
      if (missing(sex)) {
        sex = sample(SEX, 1)
      }
      if (!(sex %in% SEX)) {
        sex = sample(SEX, 1)
      }

      name = ifelse(sex == "F",
                    (person_hr_HR$new())$name_female(),
                    (person_hr_HR$new())$name_male())
      temp = list(
        "username" = (internet_hr_HR$new())$user_name(),
        "name" = name,
        "sex" = sex,
        "address" = (address_hr_HR$new())$address(),
        "mail" = (internet_hr_HR$new())$free_email(),
        "birthdate" = (date_time_init$new())$date_of_birth()
      )
      return(temp)
    },

    profile = function(fields, sex) {
      # Generates a complete profile.
      # If "fields" is not empty, only the fields in the list will be returned

      if (missing(fields)) fields = c()

      field = list(
        "job" = (job_hr_HR$new())$job(),
        "company" = (company_hr_HR$new())$company(),
        "ssn" = (ssn_hr_HR$new())$ssn(),
        "residence" = (address_hr_HR$new())$address(),
        "current_location" = c((geo_init$new())$latitude(),
                               (geo_init$new())$longitude()),
        "blood_group" = sample(c(
          "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"), 1),
        "website" = replicate(sample(seq(4), 1), (internet_hr_HR$new())$url())
      )

      field = append(field, self$simple_profile(sex))
      # field selection

      if (length(fields)) {
        nms = intersect(names(field), fields)
        field = field[nms]
      }
      return(field)
    }

  )
)



