# address ----------------------------------------
address_nl_BE = R6Class(
  "address_nl_BE",
  inherit = address_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_en_US$new())$.__enclos_env__$private$first_names,
    last_names = (person_en_US$new())$.__enclos_env__$private$last_names,
    first_name = (person_en_US$new())$first_name,
    last_name = (person_en_US$new())$last_name,


    building_number_formats = c('#', '##', '###', '#', '##', '###'),

    street_suffixes = c(
      'baan', 'boulevard', 'dreef', 'hof', 'laan', 'lei', 'pad',
      'ring', 'singel', 'steeg', 'straat', 'weg'),

    # the 4 digit numerical part of Belgium postal codes is between 1000 and 9999;
    # see https://nl.wikipedia.org/wiki/Postcode#Postnummers_in_Belgi\u00eb
    postcode_formats = '%###',

    city_formats = '{city}',

    # countries are from http://nl.wikipedia.org/wiki/ISO_3166-1
    countries = c(
      "Afghanistan",
      "Albani\u00eb",
      "Algerije",
      "Amerikaans-Samoa",
      "Amerikaanse Maagdeneilanden",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua en Barbuda",
      "Argentini\u00eb",
      "Armeni\u00eb",
      "Aruba",
      "Australi\u00eb",
      "Azerbeidzjan",
      "Bahama\\'s",
      "Bahrein",
      "Bangladesh",
      "Barbados",
      "Belgi\u00eb",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bonaire, Sint Eustatius en Saba",
      "Bosni\u00eb en Herzegovina",
      "Botswana",
      "Bouveteiland",
      "Brazili\u00eb",
      "Brits Indische Oceaanterritorium",
      "Britse Maagdeneilanden",
      "Brunei",
      "Bulgarije",
      "Burkina Faso",
      "Burundi",
      "Cambodja",
      "Canada",
      "Centraal-Afrikaanse Republiek",
      "Chili",
      "China",
      "Christmaseiland",
      "Cocoseilanden",
      "Colombia",
      "Comoren",
      "Congo-Brazzaville",
      "Congo-Kinshasa",
      "Cookeilanden",
      "Costa Rica",
      "Cuba",
      "Cura\u00e7ao",
      "Cyprus",
      "Denemarken",
      "Djibouti",
      "Dominica",
      "Dominicaanse Republiek",
      "Duitsland",
      "Ecuador",
      "Egypte",
      "El Salvador",
      "Equatoriaal-Guinea",
      "Eritrea",
      "Estland",
      "Ethiopi\u00eb",
      "Faer\u00f6er",
      "Falklandeilanden",
      "Fiji",
      "Filipijnen",
      "Finland",
      "Frankrijk",
      "Frans-Guyana",
      "Frans-Polynesi\u00eb",
      "Franse Zuidelijke en Antarctische Gebieden",
      "Gabon",
      "Gambia",
      "Georgi\u00eb",
      "Ghana",
      "Gibraltar",
      "Grenada",
      "Griekenland",
      "Groenland",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinee",
      "Guinee-Bissau",
      "Guyana",
      "Ha\u00efti",
      "Heard en McDonaldeilanden",
      "Honduras",
      "Hongarije",
      "Hongkong",
      "IJsland",
      "Ierland",
      "India",
      "Indonesi\u00eb",
      "Irak",
      "Iran",
      "Isra\u00ebl",
      "Itali\u00eb",
      "Ivoorkust",
      "Jamaica",
      "Japan",
      "Jemen",
      "Jersey",
      "Jordani\u00eb",
      "Kaaimaneilanden",
      "Kaapverdi\u00eb",
      "Kameroen",
      "Kazachstan",
      "Kenia",
      "Kirgizi\u00eb",
      "Kiribati",
      "Kleine Pacifische eilanden van de Verenigde Staten",
      "Koeweit",
      "Kroati\u00eb",
      "Laos",
      "Lesotho",
      "Letland",
      "Libanon",
      "Liberia",
      "Libi\u00eb",
      "Liechtenstein",
      "Litouwen",
      "Luxemburg",
      "Macau",
      "Macedoni\u00eb",
      "Madagaskar",
      "Malawi",
      "Maldiven",
      "Maleisi\u00eb",
      "Mali",
      "Malta",
      "Man",
      "Marokko",
      "Marshalleilanden",
      "Martinique",
      "Mauritani\u00eb",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia",
      "Moldavi\u00eb",
      "Monaco",
      "Mongoli\u00eb",
      "Montenegro",
      "Montserrat",
      "Mozambique",
      "Myanmar",
      "Namibi\u00eb",
      "Nauru",
      "Nederland",
      "Nepal",
      "Nicaragua",
      "Nieuw-Caledoni\u00eb",
      "Nieuw-Zeeland",
      "Niger",
      "Nigeria",
      "Niue",
      "Noord-Korea",
      "Noordelijke Marianen",
      "Noorwegen",
      "Norfolk",
      "Oeganda",
      "Oekra\u00efne",
      "Oezbekistan",
      "Oman",
      "Oost-Timor",
      "Oostenrijk",
      "Pakistan",
      "Palau",
      "Palestina",
      "Panama",
      "Papoea-Nieuw-Guinea",
      "Paraguay",
      "Peru",
      "Pitcairneilanden",
      "Polen",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Roemeni\u00eb",
      "Rusland",
      "Rwanda",
      "R\u00e9union",
      "Saint Kitts en Nevis",
      "Saint Lucia",
      "Saint Vincent en de Grenadines",
      "Saint-Barth\u00e9lemy",
      "Saint-Pierre en Miquelon",
      "Salomonseilanden",
      "Samoa",
      "San Marino",
      "Sao Tom\u00e9 en Principe",
      "Saoedi-Arabi\u00eb",
      "Senegal",
      "Servi\u00eb",
      "Seychellen",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten",
      "Sint-Helena, Ascension en Tristan da Cunha",
      "Sint-Maarten",
      "Sloveni\u00eb",
      "Slowakije",
      "Soedan",
      "Somali\u00eb",
      "Spanje",
      "Spitsbergen en Jan Mayen",
      "Sri Lanka",
      "Suriname",
      "Swaziland",
      "Syri\u00eb",
      "Tadzjikistan",
      "Taiwan",
      "Tanzania",
      "Thailand",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad en Tobago",
      "Tsjaad",
      "Tsjechi\u00eb",
      "Tunesi\u00eb",
      "Turkije",
      "Turkmenistan",
      "Turks- en Caicoseilanden",
      "Tuvalu",
      "Uruguay",
      "Vanuatu",
      "Vaticaanstad",
      "Venezuela",
      "Verenigd Koninkrijk",
      "Verenigde Arabische Emiraten",
      "Verenigde Staten",
      "Vietnam",
      "Wallis en Futuna",
      "Westelijke Sahara",
      "Wit-Rusland",
      "Zambia",
      "Zimbabwe",
      "Zuid-Afrika",
      "Zuid-Georgia en de Zuidelijke Sandwicheilanden",
      "Zuid-Korea",
      "Zuid-Soedan",
      "Zweden",
      "Zwitserland",
      "\u00c5land"
    ),

    # cities as listed on "postcodezoeker"
    # http://www.postcodes-maps.be/postcodelijst.php
    cities = c(
      "\'s Herenelderen", "\'s-Gravenvoeren", "\'s-Gravenwezel",
      "Aaigem", "Aalbeke", "Aalst", "Aalter", "Aarschot", "Aarsele",
      "Aartrijke", "Aartselaar", "Abolens", "Ab\u00e9e", "Achel",
      "Achet", "Ach\u00eane", "Acosse", "Acoz", "Adegem", "Adinkerke",
      "Affligem", "Afsnee", "Agimont", "Aineffe", "Aische-en-Refail",
      "Aiseau", "Aiseau-Presles", "Aisemont", "Alken", "Alle", "Alleur",
      "Alsemberg", "Alveringem", "Amay", "Amberloup", "Ambly",
      "Ambresin", "Amel", "Amonines", "Amougies", "Ampsin", "Andenne",
      "Anderlecht", "Anderlues", "Andrimont", "Angleur", "Angre",
      "Angreau", "Anh\u00e9e", "Anlier", "Anloy", "Annevoie-Rouillon",
      "Ans", "Anseremme", "Anseroeul", "Antheit", "Anthisnes",
      "Anth\u00e9e", "Antoing", "Antwerpen", "Anvaing", "Anzegem",
      "Appels", "Appelterre-Eichem", "Arbre", "Arbrefontaine",
      "Arc-Aini\u00e8res", "Arc-Wattripont", "Archennes", "Ardooie",
      "Arendonk", "Argenteau", "Arlon", "Arquennes", "Arsimont",
      "Arville", "As", "Aspelare", "Asper", "Asquillies", "Asse",
      "Assebroek", "Assenede", "Assenois", "Assent", "Assesse", "Astene"
      , "Ath", "Athis", "Athus", "Attenhoven", "Attenrode", "Attert",
      "Attre", "Aubange", "Aubechies", "Aubel", "Aublain",
      "Auby-sur-Semois", "Audregnies", "Aulnois", "Autelbas",
      "Autre-Eglise", "Autreppe", "Auvelais", "Ave-et-Auffe",
      "Avekapelle", "Avelgem", "Avennes", "Averbode",
      "Avernas-le-Bauduin", "Avin", "Awans", "Awenne", "Awirs", "Aye",
      "Ayeneux", "Aywaille", "Baaigem", "Baal", "Baardegem",
      "Baarle-Hertog", "Baasrode", "Bachte-Maria-Leerne", "Baelen",
      "Bagimont", "Baileux", "Baili\u00e8vre", "Baillamont", "Bailleul",
      "Baillonville", "Baisieux", "Baisy-Thy", "Balegem", "Balen",
      "Balatre", "Bambrugge", "Bande", "Barben\u00e7on", "Barchon",
      "Baronville", "Barry", "Barvaux-Condroz", "Barvaux-sur-Ourthe",
      "Bas-Oha", "Basse-Bodeux", "Bassenge", "Bassevelde", "Bassilly",
      "Bastogne", "Bas\u00e8cles", "Batsheers", "Battice", "Battignies",
      "Baudour", "Bauffe", "Baugnies", "Baulers", "Bavegem",
      "Bavikhove", "Bazel", "Beaufays", "Beaumont", "Beauraing",
      "Beausaint", "Beauvoorde", "Beauwelz", "Beclers", "Beek",
      "Beerlegem", "Beernem", "Beerse", "Beersel", "Beerst", "Beert",
      "Beervelde", "Beerzel", "Beez", "Beffe", "Begijnendijk", "Beho",
      "Beigem", "Bekegem", "Bekkerzeel", "Bekkevoort", "Belgrade",
      "Bellaire", "Bellecourt", "Bellefontaine", "Bellegem", "Bellem",
      "Bellevaux", "Bellevaux-Ligneuville", "Bellingen", "Beloeil",
      "Belsele", "Ben-Ahin", "Bende", "Berbroek", "Berchem",
      "Berendrecht", "Berg", "Bergilers", "Beringen", "Berlaar",
      "Berlare", "Berlingen", "Berloz", "Berneau", "Bernissart",
      "Bersillies-l\'Abbaye", "Bertem", "Bertogne", "Bertrix",
      "Bertr\u00e9e", "Berz\u00e9e", "Beselare", "Betekom",
      "Bettincourt", "Beuzet", "Bevekom", "Bevel", "Bever",
      "Beverc\u00e9", "Bevere", "Beveren-Leie", "Beveren-Roeselare",
      "Beveren-Waas", "Beveren-aan-den-Ijzer", "Beverlo", "Beverst",
      "Beyne-Heusay", "Bienne-lez-Happart", "Bierbeek", "Bierc\u00e9e",
      "Bierges", "Bierghes", "Bierset", "Bierwart", "Biesme",
      "Biesme-sous-Thuin", "Biesmer\u00e9e", "Biez", "Bihain",
      "Bikschote", "Bilstain", "Bilzen", "Binche", "Binderveld",
      "Binkom", "Bioul", "Bissegem", "Bizet", "Bi\u00e8vre", "Blaasveld"
      , "Blaimont", "Blandain", "Blanden", "Blankenberge", "Blaregnies",
      "Blaton", "Blaugies", "Blehen", "Bleid", "Bleret", "Blicquy",
      "Bl\u00e9gny", "Bl\u00e9haries", "Bocholt", "Boechout", "Boekhout"
      , "Boekhoute", "Boezinge", "Bogaarden", "Bohan", "Boign\u00e9e",
      "Boirs", "Bois-d\'Haine", "Bois-de-Lessines", "Bois-de-Villers",
      "Bois-et-Borsu", "Bolinne", "Bolland", "Bomal", "Bomal-sur-Ourthe"
      , "Bombaye", "Bommershoven", "Bon-Secours", "Boncelles", "Boneffe"
      , "Bonheiden", "Boninne", "Bonlez", "Bonnert", "Bonneville",
      "Bonsin", "Booischot", "Booitshoeke", "Boom", "Boorsem",
      "Boortmeerbeek", "Borchtlombeek", "Borgerhout", "Borgloon",
      "Borlez", "Borlo", "Borlon", "Bornem", "Bornival", "Borsbeek",
      "Borsbeke", "Bossi\u00e8re", "Bossuit", "Bossut-Gottechain",
      "Bost", "Bothey", "Bottelare", "Bouffioulx", "Bouge", "Bougnies",
      "Bouillon", "Bourlers", "Bourseigne-Neuve", "Bourseigne-Vieille",
      "Boussoit", "Boussu", "Boussu-en-Fagne", "Boussu-lez-Walcourt",
      "Bousval", "Boutersem", "Bouvignes-sur-Meuse", "Bouvignies",
      "Bouwel", "Bovekerke", "Bovelingen", "Bovenistier", "Bovesse",
      "Bovigny", "Bo\u00eblhe", "Bra", "Braffe", "Braibant",
      "Braine-l\'Alleud", "Braine-le-Chateau", "Braine-le-Comte",
      "Braives", "Brakel", "Branchon", "Bras", "Brasmenil", "Brasschaat"
      , "Bray", "Brecht", "Bredene", "Bree", "Breendonk", "Bressoux",
      "Briegden", "Brielen", "Broechem", "Broekom", "Brugelette",
      "Brugge", "Brunehaut", "Brussegem", "Brussel", "Brustem",
      "Bruyelle", "Brye", "Br\u00fbly", "Br\u00fbly-de-Pesche",
      "Budingen", "Buggenhout", "Buissenal", "Buissonville", "Buizingen"
      , "Buken", "Bulskamp", "Bunsbeek", "Burcht", "Burdinne", "Bure",
      "Burg-Reuland", "Burst", "Bury", "Buvingen", "Buvrinnes",
      "Buzenol", "Buzet", "B\u00fcllingen", "B\u00fctgenbach",
      "Callenelle", "Calonne", "Cambron-Casteau",
      "Cambron-Saint-Vincent", "Carlsbourg", "Carni\u00e8res", "Casteau"
      , "Castillon", "Celles", "Cerfontaine", "Chaineux",
      "Chairi\u00e8re", "Champion", "Champlon", "Chanly", "Chantemelle",
      "Chapelle-lez-Herlaimont", "Chapelle-\u00e0-Oie",
      "Chapelle-\u00e0-Wattines", "Chapon-Seraing", "Charleroi",
      "Charneux", "Chassepierre", "Chastre",
      "Chastre-Villeroux-Blanmont", "Chastr\u00e8s", "Chaudfontaine",
      "Chaumont-Gistoux", "Chauss\u00e9e-Notre-Dame-Louvignies",
      "Cherain", "Cheratte", "Chercq", "Chevetogne", "Chevron", "Chimay"
      , "Chiny", "Chi\u00e8vres", "Chokier", "Chatelet", "Chatelineau",
      "Chatillon", "Ch\u00ean\u00e9e", "Ciergnon", "Ciney", "Ciplet",
      "Ciply", "Clabecq", "Clavier", "Clermont", "Clermont-sous-Huy",
      "Cognel\u00e9e", "Colfontaine", "Comblain-Fairon",
      "Comblain-au-Pont", "Comblain-la-Tour", "Conneux", "Corbais",
      "Corbion", "Cordes", "Corenne", "Cornesse", "Cornimont",
      "Corroy-le-Chateau", "Corroy-le-Grand", "Corswarem",
      "Cortil-Noirmont", "Cortil-Wodon", "Couillet", "Cour-sur-Heure",
      "Courcelles", "Courri\u00e8re", "Court-Saint-Etienne", "Couthuin",
      "Coutisse", "Couture-Saint-Germain", "Couvin", "Cras-Avernas",
      "Crehen", "Crisn\u00e9e", "Croix-lez-Rouveroy", "Crombach",
      "Crupet", "Cuesmes", "Cugnon", "Cul-des-Sarts", "Custinne",
      "C\u00e9rexhe-Heuseux", "C\u00e9roux-Mousty", "Dadizele", "Dailly"
      , "Daknam", "Dalhem", "Damme", "Dampicourt", "Dampremy", "Darion",
      "Daussois", "Daussoulx", "Dave", "Daverdisse", "De Haan", "De Klinge", "De Moeren", "De Panne", "De Pinte", "Deerlijk",
      "Deftinge", "Deinze", "Denderbelle", "Denderhoutem", "Denderleeuw"
      , "Dendermonde", "Denderwindeke", "Dentergem", "Den\u00e9e",
      "Dergneau", "Dessel", "Desselgem", "Destelbergen", "Desteldonk",
      "Deurle", "Deurne", "Deux-Acren", "Dhuy", "Diepenbeek", "Diest",
      "Diets-Heur", "Dikkebus", "Dikkele", "Dikkelvenne", "Diksmuide",
      "Dilbeek", "Dilsen-Stokkem", "Dinant", "Dion", "Dion-Valmont",
      "Dison", "Dochamps", "Doel", "Dohan", "Doische", "Dolembreux",
      "Donceel", "Dongelberg", "Donk", "Donstiennes", "Dorinne",
      "Dormaal", "Dottenijs", "Dour", "Dourbes", "Dranouter",
      "Driekapellen", "Drieslinter", "Drogenbos", "Drongen",
      "Dr\u00e9hance", "Dudzele", "Duffel", "Duisburg", "Duras",
      "Durbuy", "Durnal", "Dworp", "Eben-Emael", "Ebly", "Ecaussinnes",
      "Ecaussinnes-Lalaing", "Ecaussinnes-d\'Enghien", "Edegem",
      "Edelare", "Edingen", "Eeklo", "Eernegem", "Egem",
      "Eggewaartskapelle", "Eghez\u00e9e", "Ehein", "Eigenbilzen",
      "Eindhout", "Eine", "Eisden", "Eke", "Ekeren", "Eksaarde", "Eksel"
      , "Elen", "Elene", "Elewijt", "Eliksem", "Elingen", "Ellemelle",
      "Ellezelles", "Ellignies-Sainte-Anne", "Ellignies-lez-Frasnes",
      "Ellikom", "Elouges", "Elsegem", "Elsenborn", "Elsene", "Elst",
      "Elverdinge", "Elversele", "Emblem", "Embourg", "Emelgem",
      "Emines", "Emptinne", "Ename", "Engelmanshoven", "Engis", "Enines"
      , "Ensival", "Epinois", "Eppegem", "Eprave", "Erbaut", "Erbisoeul"
      , "Ere", "Erembodegem", "Erez\u00e9e", "Ermeton-sur-Biert",
      "Ernage", "Erneuville", "Ernonheid", "Erondegem", "Erpe",
      "Erpe-Mere", "Erpent", "Erpion", "Erps-Kwerps", "Erquelinnes",
      "Erquennes", "Ertvelde", "Erwetegem", "Escanaffles", "Esen",
      "Esneux", "Esplechin", "Esquelmes", "Essen", "Essene",
      "Estaimbourg", "Estaimpuis", "Estinnes", "Estinnes-au-Mont",
      "Estinnes-au-Val", "Etalle", "Ethe", "Etikhove", "Ettelgem",
      "Etterbeek", "Eugies", "Eupen", "Evegn\u00e9e", "Evelette",
      "Everbeek", "Everberg", "Evere", "Evergem", "Evregnies",
      "Evrehailles", "Eynatten", "Ezemaal", "Fagnolle", "Faimes",
      "Fala\u00ebn", "Falisolle", "Fallais", "Falmagne", "Falmignoul",
      "Familleureux", "Farciennes", "Faulx-les-Tombes", "Fauroeulx",
      "Fauvillers", "Faymonville", "Fays-les-Veneurs", "Fayt-le-Franc",
      "Fayt-lez-Manage", "Felenne", "Feluy", "Feneur", "Fernelmont",
      "Ferri\u00e8res", "Feschaux", "Fexhe-Slins",
      "Fexhe-le-Haut-Clocher", "Filot", "Finnevaux", "Fize-Fontaine",
      "Fize-le-Marsal", "Flamierge", "Flavion", "Flawinne", "Fleurus",
      "Floreffe", "Florennes", "Florenville", "Floriffoux",
      "Flor\u00e9e", "Flostoy", "Fl\u00e9malle", "Fl\u00e9malle-Grande",
      "Fl\u00e9malle-Haute", "Fl\u00e9nu", "Fl\u00e9ron", "Fl\u00f4ne",
      "Focant", "Folx-les-Caves", "Fontaine-Valmont",
      "Fontaine-l\'Ev\u00eaque", "Fontenelle", "Fontenoille", "Fontenoy"
      , "Fooz", "Forchies-la-Marche", "Forest", "Forges",
      "Forges-Philippe", "Forri\u00e8res", "Forville", "For\u00eat",
      "Fosse", "Fosses-la-Ville", "Fouleng", "Fourbechies",
      "Foy-Notre-Dame", "Fraipont", "Fraire", "Fraiture", "Frameries",
      "Framont", "Franc-Waret", "Franchimont", "Francorchamps",
      "Frani\u00e8re", "Frasnes", "Frasnes-lez-Anvaing",
      "Frasnes-lez-Buissenal", "Frasnes-lez-Gosselies", "Freloux",
      "Freux", "Froidchapelle", "Froidfontaine", "Froidmont",
      "Fronville", "Froyennes", "Fumal", "Furfooz", "Furnaux",
      "Gaasbeek", "Gages", "Gallaix", "Galmaarden", "Ganshoren",
      "Gaurain-Ramecroix", "Gavere", "Gedinne", "Geel", "Geer",
      "Geest-G\u00e9rompont-Petit-Rosi\u00e8re", "Geetbets",
      "Gelbress\u00e9e", "Gelinden", "Gellik", "Gelrode", "Geluveld",
      "Geluwe", "Gembes", "Gembloux", "Gemmenich", "Genappe", "Genk",
      "Genly", "Genoelselderen", "Gent", "Gentbrugge", "Gentinnes",
      "Genval", "Geraardsbergen", "Gerdingen", "Gerin", "Gerpinnes",
      "Gestel", "Gesves", "Ghislenghien", "Ghlin", "Ghoy", "Gibecq",
      "Gierle", "Gijverinkhove", "Gijzegem", "Gijzelbrechtegem",
      "Gijzenzele", "Gilly", "Gimn\u00e9e", "Gingelom", "Gistel", "Gits"
      , "Givry", "Glabais", "Glabbeek-Zuurbemde", "Glain", "Gleixhe",
      "Glimes", "Glons", "Gochen\u00e9e", "Godarville", "Godinne",
      "Godveerdegem", "Goeferdinge", "Goegnies-Chauss\u00e9e", "Goesnes"
      , "Goetsenhoven", "Gomz\u00e9-Andoumont", "Gondregnies",
      "Gonrieux", "Gontrode", "Gooik", "Gors-Opleeuw", "Gorsem",
      "Gosselies", "Gotem", "Gottem", "Gottignies", "Gougnies",
      "Gourdinne", "Goutroux", "Gouvy", "Gouy-lez-Pi\u00e9ton",
      "Goz\u00e9e", "Go\u00e9", "Graide", "Grammene", "Grand-Axhe",
      "Grand-Hallet", "Grand-Halleux", "Grand-Leez", "Grand-Manil",
      "Grand-Rechain", "Grand-Reng", "Grand-Rosi\u00e8re-Hottomont",
      "Grandglise", "Grandhan", "Grandmenil", "Grandmetz", "Grandrieu",
      "Grandville", "Grandvoir", "Grapfontaine", "Graty", "Graux",
      "Grazen", "Grembergen", "Grez-Doiceau", "Grimbergen", "Grimminge",
      "Grivegn\u00e9e", "Grobbendonk", "Groot-Bijgaarden",
      "Groot-Gelmen", "Groot-Loon", "Gros-Fays", "Grosage",
      "Grote-Brogel", "Grote-Spouwen", "Grotenberge", "Gruitrode",
      "Grune", "Grupont", "Grace-Berleur", "Grace-Hollogne", "Guignies",
      "Guigoven", "Guirsch", "Gullegem", "Gutschoven", "G\u00e9rompont"
      , "G\u00e9rouville", "Haacht", "Haaltert", "Haasdonk", "Haasrode",
      "Habay", "Habay-la-Neuve", "Habay-la-Vieille", "Habergy",
      "Haccourt", "Hachy", "Hacquegnies", "Haillot", "Haine-Saint-Paul",
      "Haine-Saint-Pierre", "Hainin", "Hakendover", "Halanzy", "Halen",
      "Hallaar", "Halle", "Halle-Booienhoven", "Halleux", "Halma",
      "Halmaal", "Haltinne", "Ham", "Ham-sur-Heure",
      "Ham-sur-Heure-Nalinnes", "Ham-sur-Sambre", "Hamipr\u00e9",
      "Hamme", "Hamme-Mille", "Hamoir", "Hamois", "Hamont",
      "Hamont-Achel", "Hampteau", "Han-sur-Lesse", "Handzame", "Haneffe"
      , "Hannut", "Hann\u00eache", "Hanret", "Hansbeke",
      "Hantes-Wih\u00e9ries", "Hanzinelle", "Hanzinne", "Harchies",
      "Harelbeke", "Haren", "Haren-Borgloon", "Haren-Tongeren",
      "Hargimont", "Harmignies", "Harnoncourt", "Harre", "Harsin",
      "Harveng", "Harz\u00e9", "Hasselt", "Hasti\u00e8re",
      "Hasti\u00e8re-Lavaux", "Hasti\u00e8re-par-Del\u00e0", "Hatrival",
      "Haulchin", "Hauset", "Haut-Fays", "Haut-Ittre", "Haut-le-Wastia"
      , "Hautrage", "Havay", "Havelange", "Haversin", "Havinnes",
      "Havr\u00e9", "Hechtel", "Hechtel-Eksel", "Heer", "Heers", "Hees",
      "Heestert", "Heffen", "Heikruis", "Heindonk", "Heinsch",
      "Heist-aan-Zee", "Heist-op-den-Berg", "Hekelgem", "Heks",
      "Helchteren", "Heldergem", "Helen-Bos", "Helkijn", "Hellebecq",
      "Hemelveerdegem", "Hemiksem", "Hemptinne",
      "Hemptinne-lez-Florennes", "Hendrieken", "Henis",
      "Hennuy\u00e8res", "Henri-Chapelle", "Henripont", "Hensies",
      "Heppen", "Heppenbach", "Heppignies", "Herbeumont", "Herchies",
      "Herderen", "Herdersem", "Herent", "Herentals", "Herenthout",
      "Herfelingen", "Hergenrath", "Herk-de-Stad",
      "Hermalle-sous-Argenteau", "Hermalle-sous-Huy",
      "Hermeton-sur-Meuse", "Herm\u00e9e", "Herne", "Herquegies",
      "Herseaux", "Herselt", "Herstal", "Herstappe", "Hertain", "Herten"
      , "Hertsberge", "Herve", "Herzele", "Heule", "Heure",
      "Heure-le-Romain", "Heurne", "Heusden", "Heusden-Zolder", "Heusy",
      "Heuvelland", "Hever", "Heverlee", "Heyd", "Hillegem", "Hingene",
      "Hingeon", "Hives", "Hoboken", "Hodeige", "Hodister", "Hody",
      "Hoegaarden", "Hoeilaart", "Hoeke", "Hoelbeek", "Hoeleden",
      "Hoepertingen", "Hoeselt", "Hoevenen", "Hofstade", "Hogne",
      "Hognoul", "Hollain", "Hollange", "Hollebeke",
      "Hollogne-aux-Pierres", "Hollogne-sur-Geer", "Holsbeek", "Hombeek"
      , "Hombourg", "Hompr\u00e9", "Hondelange", "Honnay", "Honnelles",
      "Hooglede", "Hoogstade", "Hoogstraten", "Horebeke",
      "Horion-Hoz\u00e9mont", "Hornu", "Horpmaal", "Horrues", "Hotton",
      "Houdemont", "Houdeng-Aimeries", "Houdeng-Goegnies", "Houdremont",
      "Houffalize", "Hour", "Housse", "Houtain-Saint-Sim\u00e9on",
      "Houtain-le-Val", "Houtaing", "Houtave", "Houtem", "Houthalen",
      "Houthalen-Helchteren", "Houthem", "Houthulst", "Houtvenne",
      "Houwaart", "Houx", "Houyet", "Hove", "Hoves", "Howardries",
      "Huccorgne", "Huise", "Huissignies", "Huizingen", "Huldenberg",
      "Hulshout", "Hulsonniaux", "Hulste", "Humain", "Humbeek",
      "Hundelgem", "Huppaye", "Huy", "Hyon", "H\u00e9l\u00e9cine",
      "H\u00e9rinnes-lez-Pecq", "H\u00e9ron", "H\u00e9villers",
      "Ichtegem", "Iddergem", "Idegem", "Ieper", "Impe", "Incourt",
      "Ingelmunster", "Ingooigem", "Irchonwelz", "Isi\u00e8res", "Isnes"
      , "Itegem", "Itterbeek", "Ittre", "Ivoz-Ramet", "Izegem", "Izel",
      "Izenberge", "Izier", "Jabbeke", "Jalhay", "Jallet", "Jamagne",
      "Jambes", "Jamiolle", "Jamioulx", "Jamoigne",
      "Jandrain-Jandrenouille", "Jauche", "Jauchelette", "Javingue",
      "Jehay", "Jehonville", "Jemappes", "Jemelle", "Jemeppe-sur-Meuse",
      "Jemeppe-sur-Sambre", "Jeneffe", "Jesseren", "Jette", "Jeuk",
      "Jodoigne", "Jodoigne-Souveraine", "Jollain-Merlin", "Joncret",
      "Jul\u00e9mont", "Jumet", "Jupille-sur-Meuse", "Juprelle",
      "Jurbise", "Juseret", "Kaaskerke", "Kachtem", "Kaggevinne", "Kain"
      , "Kalken", "Kallo", "Kallo-Kieldrecht", "Kalmthout", "Kampenhout"
      , "Kanegem", "Kanne", "Kapelle-op-den-Bos", "Kapellen", "Kaprijke"
      , "Kaster", "Kasterlee", "Kaulille", "Keerbergen", "Keiem",
      "Kelmis", "Kemexhe", "Kemmel", "Kemzeke", "Kerkhove", "Kerkom",
      "Kerkom-bij-Sint-Truiden", "Kerksken", "Kermt", "Kerniel",
      "Kersbeek-Miskom", "Kessel", "Kessel-Lo", "Kessenich", "Kester",
      "Kettenis", "Keumi\u00e9e", "Kieldrecht", "Kinrooi",
      "Klein-Gelmen", "Kleine-Brogel", "Kleine-Spouwen", "Klemskerke",
      "Klerken", "Kluisbergen", "Kluizen", "Knesselare", "Knokke",
      "Knokke-Heist", "Kobbegem", "Koekelare", "Koekelberg", "Koersel",
      "Koksijde", "Kolmont-Borgloon", "Kolmont-Tongeren", "Komen",
      "Komen-Waasten", "Koningshooikt", "Koninksem", "Kontich",
      "Kooigem", "Koolkerke", "Koolskamp", "Korbeek-Dijle", "Korbeek-Lo"
      , "Kortemark", "Kortenaken", "Kortenberg", "Kortessem", "Kortijs",
      "Kortrijk", "Kortrijk-Dutsel", "Kozen", "Kraainem", "Krombeke",
      "Kruibeke", "Kruishoutem", "Kumtich", "Kuringen", "Kuttekoven",
      "Kuurne", "Kwaadmechelen", "Kwaremont", "La", "La Bruy\u00e8re",
      "La Glanerie", "La Gleize", "La Hestre", "La Hulpe", "La Louvi\u00e8re", "La bouverie", "La-Roche-en-Ardenne", "Laakdal",
      "Laar", "Laarne", "Labuissi\u00e8re", "Lacuisine", "Ladeuze",
      "Lafor\u00eat", "Lahamaide", "Laken", "Lamain", "Lambermont",
      "Lambusart", "Lamine", "Lamontz\u00e9e", "Lamorteau",
      "Lampernisse", "Lanaken", "Lanaye", "Landegem", "Landelies",
      "Landen", "Landenne", "Landskouter", "Laneffe", "Langdorp",
      "Langemark", "Langemark-Poelkapelle", "Lanklaar", "Lanquesaint",
      "Lantin", "Lantremange", "Laplaigne", "Lapscheure", "Lasne",
      "Lasne-Chapelle-Saint-Lambert", "Lathuy", "Latinne", "Latour",
      "Lauw", "Lauwe", "Lavacherie", "Lavaux-Sainte-Anne", "Lavoir",
      "Le Mesniel", "Le Roeulx", "Le Roux", "Lebbeke", "Lede",
      "Ledeberg", "Ledegem", "Leefdaal", "Leerbeek", "Leernes",
      "Leers-Nord", "Leers-et-Fosteau", "Leest", "Leeuwergem",
      "Leffinge", "Leignon", "Leisele", "Leke", "Lembeek", "Lembeke",
      "Lemberge", "Lendelede", "Lennik", "Lens", "Lens-Saint-Remy",
      "Lens-Saint-Servais", "Lens-sur-Geer", "Leopoldsburg", "Les Avins"
      , "Les Bons", "Les Bulles", "Les Hayons", "Les Waleffes",
      "Lesdain", "Lessines", "Lessive", "Lesterny", "Lesve",
      "Lettelingen", "Letterhoutem", "Leugnies", "Leupegem", "Leut",
      "Leuven", "Leuze", "Leuze-en-Hainaut", "Leval-Chaudeville",
      "Leval-Trahegnies", "Liberchies", "Libin", "Libramont",
      "Libramont-Chevigny", "Lichtaart", "Lichtervelde", "Liedekerke",
      "Lieferinge", "Lier", "Lierde", "Lierneux", "Liernu", "Liers",
      "Liezele", "Ligne", "Ligney", "Ligny", "Lille", "Lillo",
      "Lillois-Witterz\u00e9e", "Limal", "Limbourg", "Limelette",
      "Limerl\u00e9", "Limont", "Lincent", "Linden", "Linkebeek",
      "Linkhout", "Linsmeau", "Lint", "Linter", "Lippelo", "Lisogne",
      "Lissewege", "Lives-sur-Meuse", "Lixhe", "Li\u00e8ge", "Lo",
      "Lo-Reninge", "Lobbes", "Lochristi", "Lodelinsart", "Loenhout",
      "Loker", "Lokeren", "Loksbergen", "Lombardsijde", "Lombise",
      "Lommel", "Lommersweiler", "Lompret", "Lomprez", "Loncin",
      "Londerzeel", "Longchamps", "Longlier", "Longueville", "Longvilly"
      , "Lontzen", "Lonz\u00e9e", "Loonbeek", "Loppem", "Lorc\u00e9",
      "Lot", "Lotenhulle", "Louette-Saint-Denis", "Louette-Saint-Pierre"
      , "Loupoigne", "Louvain-la-Neuve", "Louveign\u00e9", "Lovendegem",
      "Lovenjoel", "Loverval", "Loyers", "Lubbeek", "Luingne", "Lummen"
      , "Lustin", "Luttre", "L\u00e9glise", "Maarke-Kerkem", "Maarkedal"
      , "Maaseik", "Maasmechelen", "Mabompr\u00e9", "Machelen", "Macon",
      "Macquenoise", "Maffe", "Maffle", "Magn\u00e9e", "Maillen",
      "Mainvault", "Maisi\u00e8res", "Maissin", "Maizeret", "Mal",
      "Maldegem", "Malderen", "Malempr\u00e9", "Malle", "Malmedy",
      "Malonne", "Malvoisin", "Mal\u00e8ves-Sainte-Marie-Wastines",
      "Manage", "Manderfeld", "Manhay", "Mannekensvere", "Maransart",
      "Marbais", "Marbaix", "Marbehan", "Marche-en-Famenne",
      "Marche-les-Dames", "Marche-lez-Ecaussinnes", "Marchienne-au-Pont"
      , "Marchin", "Marchipont", "Marchovelette", "Marcinelle",
      "Marcourt", "Marenne", "Mariakerke", "Mariekerke", "Mariembourg",
      "Marilles", "Mark", "Marke", "Markegem", "Marneffe", "Marquain",
      "Martelange", "Martenslinde", "Martouzin-Neuville", "Masbourg",
      "Masnuy-Saint-Jean", "Masnuy-Saint-Pierre", "Massemen",
      "Massenhoven", "Matagne-la-Grande", "Matagne-la-Petite", "Mater",
      "Maubray", "Maulde", "Maurage", "Mazenzele", "Mazy", "Maz\u00e9e",
      "Mechelen", "Mechelen-Bovelingen", "Mechelen-aan-de-Maas",
      "Meeffe", "Meensel-Kiezegem", "Meer", "Meerbeek", "Meerbeke",
      "Meerdonk", "Meerhout", "Meerle", "Meeswijk", "Meetkerke",
      "Meeuwen", "Meeuwen-Gruitrode", "Mehaigne", "Meigem", "Meilegem",
      "Meise", "Meix-devant-Virton", "Meix-le-Tige", "Melden", "Meldert"
      , "Melen", "Melkwezer", "Melle", "Mellery", "Melles", "Mellet",
      "Mellier", "Melsbroek", "Melsele", "Melsen", "Membach", "Membre",
      "Membruggen", "Mendonk", "Menen", "Merbes-Sainte-Marie",
      "Merbes-le-Chateau", "Merchtem", "Merdorp", "Mere", "Merelbeke",
      "Merendree", "Merkem", "Merksem", "Merksplas", "Merlemont",
      "Mesen", "Meslin-l\'Ev\u00eaque", "Mesnil-Eglise",
      "Mesnil-Saint-Blaise", "Mespelare", "Messancy", "Messelbroek",
      "Mesvin", "Mettekoven", "Mettet", "Meulebeke", "Meux", "Meyerode",
      "Michelbeke", "Micheroux", "Middelburg", "Middelkerke",
      "Mielen-boven-Aalst", "Mignault", "Millen", "Milmort",
      "Minderhout", "Mirwart", "Mi\u00e9cret", "Modave", "Moelingen",
      "Moen", "Moerbeke", "Moerbeke-Waas", "Moere", "Moerkerke",
      "Moerzeke", "Moeskroen", "Moha", "Mohiville", "Moignel\u00e9e",
      "Moircy", "Mol", "Molenbaix", "Molenbeek-Wersbeek", "Molenbeersel"
      , "Molenstede", "Mollem", "Momalle", "Momignies",
      "Monceau-Imbrechies", "Monceau-en-Ardenne", "Monceau-sur-Sambre",
      "Mons", "Mons-lez-Li\u00e8ge", "Monstreux", "Mont",
      "Mont-Gauthier", "Mont-Saint-Andr\u00e9", "Mont-Saint-Aubert",
      "Mont-Saint-Guibert", "Mont-Sainte-Aldegonde",
      "Mont-Sainte-Genevi\u00e8ve", "Mont-de-l\'Enclus",
      "Mont-sur-Marchienne", "Montbliart", "Montegn\u00e9e",
      "Montenaken", "Montignies-Saint-Christophe", "Montignies-lez-Lens"
      , "Montignies-sur-Roc", "Montignies-sur-Sambre",
      "Montigny-le-Tilleul", "Montleban", "Montroeul-au-Bois",
      "Montroeul-sur-Haine", "Montzen", "Moorsel", "Moorsele",
      "Moorslede", "Moortsele", "Mopertingen", "Moregem", "Moresnet",
      "Morhet", "Morialm\u00e9", "Morkhoven", "Morlanwelz",
      "Morlanwelz-Mariemont", "Mormont", "Mornimont", "Mortier",
      "Mortroux", "Mortsel", "Morville", "Moulbaix", "Mourcourt",
      "Moustier", "Moustier-sur-Sambre", "Mouzaive", "Moxhe", "Mozet",
      "Muizen", "Mullem", "Munkzwalm", "Muno", "Munsterbilzen", "Munte",
      "Musson", "Mussy-la-Ville", "My", "M\u00e9an", "M\u00e9lin",
      "M\u00e9vergnies-lez-Lens", "Naast", "Nadrin", "Nafraiture",
      "Nalinnes", "Namur", "Nam\u00eache", "Nandrin", "Naninne",
      "Naom\u00e9", "Nassogne", "Natoye", "Nazareth",
      "Neder-over-Heembeek", "Nederboelare", "Nederbrakel", "Nederename"
      , "Nederhasselt", "Nederokkerzeel", "Nederzwalm-Hermelgem",
      "Neerglabbeek", "Neerharen", "Neerhespen", "Neerheylissem",
      "Neerijse", "Neerlanden", "Neerlinter", "Neeroeteren", "Neerpelt",
      "Neerrepen", "Neervelp", "Neerwaasten", "Neerwinden", "Neigem",
      "Nerem", "Nessonvaux", "Nethen", "Nettinne", "Neu-Moresnet",
      "Neufchateau", "Neufmaison", "Neufvilles", "Neupr\u00e9",
      "Neuville", "Neuville-en-Condroz", "Nevele", "Niel", "Niel-bij-As"
      , "Niel-bij-Sint-Truiden", "Nieuwenhove", "Nieuwenrode",
      "Nieuwerkerken", "Nieuwkapelle", "Nieuwkerke", "Nieuwkerken-Waas",
      "Nieuwmunster", "Nieuwpoort", "Nieuwrode", "Nijlen",
      "Nil-Saint-Vincent-Saint-Martin", "Nimy", "Ninove", "Nismes",
      "Nivelles", "Niverl\u00e9e", "Nives", "Nobressart", "Nodebais",
      "Noduwez", "Noirchain", "Noirefontaine", "Noiseux", "Nokere",
      "Nollevaux", "Noorderwijk", "Noordschote", "Nossegem", "Nothomb",
      "Nouvelles", "Noville", "Noville-les-Bois",
      "Noville-sur-M\u00e9haigne", "Nukerke", "N\u00e9chin", "Obaix",
      "Obigies", "Obourg", "Ochamps", "Ocquier", "Odeigne", "Odeur",
      "Oedelem", "Oekene", "Oelegem", "Oeren", "Oeselgem", "Oetingen",
      "Oeudeghien", "Oevel", "Offagne", "Ogy", "Ohain", "Ohey",
      "Oignies-en-Thi\u00e9rache", "Oisquercq", "Oizy", "Okegem", "Olen"
      , "Oleye", "Ollignies", "Olloy-sur-Viroin", "Olmen", "Olne",
      "Olsene", "Omal", "Ombret", "Omez\u00e9e", "On", "Onhaye",
      "Onkerzele", "Onnezies", "Onoz", "Onze-Lieve-Vrouw-Lombeek",
      "Onze-Lieve-Vrouw-Waver", "Ooigem", "Ooike", "Oombergen",
      "Oorbeek", "Oordegem", "Oostakker", "Oostduinkerke", "Oosteeklo",
      "Oostende", "Oosterzele", "Oostham", "Oostkamp", "Oostkerke-Damme"
      , "Oostkerke-Diksmuide", "Oostmalle", "Oostnieuwkerke",
      "Oostrozebeke", "Oostvleteren", "Oostwinkel", "Opbrakel", "Opdorp"
      , "Opglabbeek", "Opgrimbie", "Ophain-Bois-Seigneur-Isaac",
      "Ophasselt", "Opheers", "Opheylissem", "Ophoven", "Opitter",
      "Oplinter", "Opoeteren", "Opont", "Opprebais", "Oppuurs", "Opvelp"
      , "Opwijk", "Orbais", "Orchimont", "Orcq", "Ordingen", "Oret",
      "Oreye", "Orgeo", "Ormeignies", "Orp-Jauche", "Orp-le-Grand",
      "Orroir", "Orsmaal-Gussenhoven", "Ortho", "Ostiches", "Otegem",
      "Oteppe", "Oth\u00e9e", "Otrange", "Ottenburg", "Ottergem",
      "Ottignies", "Ottignies-Louvain-la-Neuve", "Oud-Heverlee",
      "Oud-Turnhout", "Oudegem", "Oudekapelle", "Oudenaarde",
      "Oudenaken", "Oudenburg", "Oudergem", "Ouffet", "Ougr\u00e9e",
      "Oupeye", "Outer", "Outgaarden", "Outrelouxhe", "Outrijve",
      "Ouwegem", "Overboelare", "Overhespen", "Overijse", "Overmere",
      "Overpelt", "Overrepen", "Overwinden", "Paal", "Paifve", "Pailhe",
      "Paliseul", "Pamel", "Papignies", "Parike", "Passendale",
      "Patignies", "Paturages", "Paulatem", "Pecq", "Peer", "Peissant",
      "Pellaines", "Pellenberg", "Pepingen", "Pepinster", "Perk",
      "Pervijze", "Perwez", "Perwez-Haillot", "Pesche", "Pessoux",
      "Petegem-aan-de-Leie", "Petegem-aan-de-Schelde", "Petigny",
      "Petit-Fays", "Petit-Hallet", "Petit-Rechain",
      "Petit-Roeulx-lez-Braine", "Petit-Roeulx-lez-Nivelles",
      "Petit-Thier", "Petite-Chapelle", "Peutie", "Philippeville",
      "Pipaix", "Piringen", "Pironchamps", "Pittem", "Pi\u00e9ton",
      "Pi\u00e9train", "Pi\u00e9trebais", "Plainevaux", "Plancenoit",
      "Ploegsteert", "Plombi\u00e8res", "Poederlee", "Poeke",
      "Poelkapelle", "Poesele", "Pollare", "Polleur", "Pollinkhove",
      "Pommeroeul", "Pondr\u00f4me", "Pont-de-Loup",
      "Pont-\u00e0-Celles", "Pontillas", "Poperinge", "Poppel",
      "Popuelles", "Porcheresse", "Pottes", "Poucet", "Poulseur",
      "Poupehan", "Pousset", "Presgaux", "Presles", "Profondeville",
      "Proven", "Pry", "Pulderbos", "Pulle", "Purnode", "Pussemange",
      "Putte", "Puurs", "P\u00e9ronnes-lez-Antoing",
      "P\u00e9ronnes-lez-Binche", "P\u00e9ruwelz", "Quaregnon",
      "Quartes", "Quenast", "Queue-du-Bois", "Quevaucamps",
      "Qui\u00e9vrain", "Qu\u00e9vy", "Qu\u00e9vy-le-Grand",
      "Qu\u00e9vy-le-Petit", "Rachecourt", "Racour", "Raeren", "Ragnies"
      , "Rahier", "Ramegnies", "Ramegnies-Chin", "Ramelot",
      "Ramillies-Offus", "Ramsdonk", "Ramsel",
      "Ramskapelle-Knokke-Heist", "Ramskapelle-Nieuwpoort", "Rance",
      "Ransart", "Ransberg", "Ranst", "Ravels", "Rebaix", "Rebecq",
      "Rebecq-Rognon", "Recht", "Recogne", "Redu", "Reet", "Rekem",
      "Rekkem", "Relegem", "Remagne", "Remersdaal", "Remicourt",
      "Rendeux", "Reninge", "Reningelst", "Renlies", "Reppel", "Ressaix"
      , "Ressegem", "Resteigne", "Retie", "Retinne", "Reuland",
      "Rhisnes", "Richelle", "Riemst", "Rienne", "Rijkel", "Rijkevorsel"
      , "Rijkhoven", "Rijmenam", "Riksingen", "Rillaar", "Rivi\u00e8re",
      "Rixensart", "Ri\u00e8zes", "Robechies", "Robelmont",
      "Robertville", "Roborst", "Rochefort", "Rochehaut", "Rocherath",
      "Roclenge-sur-Geer", "Rocourt", "Roesbrugge-Haringe", "Roeselare",
      "Rogn\u00e9e", "Roisin", "Roksem", "Rollegem", "Rollegem-Kapelle"
      , "Roloux", "Roly", "Romedenne", "Romershoven", "Romer\u00e9e",
      "Roms\u00e9e", "Rongy", "Ronqui\u00e8res", "Ronse", "Ronsele",
      "Roosbeek", "Roosdaal", "Roselies", "Rosi\u00e8res", "Rosmeer",
      "Rosoux-Crenwick", "Rossignol", "Ros\u00e9e", "Rotem",
      "Rotheux-Rimi\u00e8re", "Rotselaar", "Roucourt", "Rouveroy",
      "Rouvreux", "Rouvroy", "Roux", "Roux-Miroir", "Roy", "Rozebeke",
      "Ruddervoorde", "Ruette", "Ruien", "Ruisbroek", "Ruiselede",
      "Rukkelingen-Loon", "Rulles", "Rumbeke", "Rumes", "Rumillies",
      "Rummen", "Rumsdorp", "Rumst", "Runkelen", "Rupelmonde",
      "Russeignies", "Rutten", "R\u00e8ves", "Saint-Amand",
      "Saint-Andr\u00e9", "Saint-Aubin", "Saint-Denis",
      "Saint-Denis-Bovesse", "Saint-Georges-sur-Meuse", "Saint-Germain",
      "Saint-Ghislain", "Saint-G\u00e9rard", "Saint-G\u00e9ry",
      "Saint-Hubert", "Saint-Jean-Geest", "Saint-L\u00e9ger",
      "Saint-Marc", "Saint-Mard", "Saint-Martin", "Saint-Maur",
      "Saint-M\u00e9dard", "Saint-Nicolas", "Saint-Pierre", "Saint-Remy"
      , "Saint-Remy-Geest", "Saint-Sauveur", "Saint-Servais",
      "Saint-Symphorien", "Saint-S\u00e9verin", "Saint-Vaast",
      "Saint-Vincent", "Sainte-C\u00e9cile", "Sainte-Marie-Chevigny",
      "Sainte-Marie-sur-Semois", "Sainte-Ode", "Saintes", "Saive",
      "Salles", "Samart", "Sambreville", "Samr\u00e9e", "Sankt-Vith",
      "Sars-la-Bruy\u00e8re", "Sars-la-Buissi\u00e8re", "Sart-Bernard",
      "Sart-Custinne", "Sart-Dames-Avelines", "Sart-Eustache",
      "Sart-Saint-Laurent", "Sart-en-Fagne", "Sart-lez-Spa", "Sautin",
      "Sautour", "Sauveni\u00e8re", "Schaarbeek", "Schaffen",
      "Schalkhoven", "Schaltin", "Schelderode", "Scheldewindeke",
      "Schelle", "Schellebelle", "Schendelbeke", "Schepdaal",
      "Scherpenheuvel", "Scherpenheuvel-Zichem", "Schilde",
      "Schoonaarde", "Schore", "Schorisse", "Schoten", "Schriek",
      "Schuiferskapelle", "Schulen", "Sch\u00f6nberg", "Sclayn", "Scy",
      "Seilles", "Seloignes", "Semmerzake", "Seneffe", "Sensenruth",
      "Seny", "Senzeille", "Septon", "Seraing", "Seraing-le-Chateau",
      "Serinchamps", "Serskamp", "Serville", "Sibret", "Signeulx",
      "Sijsele", "Silenrieux", "Silly", "Sinaai-Waas", "Sinsin",
      "Sint-Agatha-Berchem", "Sint-Agatha-Rode", "Sint-Amands",
      "Sint-Amandsberg", "Sint-Andries", "Sint-Antelinks",
      "Sint-Baafs-Vijve", "Sint-Blasius-Boekel", "Sint-Denijs",
      "Sint-Denijs-Boekel", "Sint-Denijs-Westrem", "Sint-Eloois-Vijve",
      "Sint-Eloois-Winkel", "Sint-Genesius-Rode", "Sint-Gillis",
      "Sint-Gillis-Waas", "Sint-Gillis-bij-Dendermonde",
      "Sint-Goriks-Oudenhove", "Sint-Huibrechts-Hern",
      "Sint-Huibrechts-Lille", "Sint-Jacobs-Kapelle", "Sint-Jan",
      "Sint-Jan-in-Eremo", "Sint-Jans-Molenbeek", "Sint-Job-in-\'t-Goor"
      , "Sint-Joost-ten-Node", "Sint-Joris-Beernem",
      "Sint-Joris-Nieuwpoort", "Sint-Joris-Weert", "Sint-Joris-Winge",
      "Sint-Katelijne-Waver", "Sint-Katherina-Lombeek",
      "Sint-Kornelis-Horebeke", "Sint-Kruis", "Sint-Kruis-Winkel",
      "Sint-Kwintens-Lennik", "Sint-Lambrechts-Herk",
      "Sint-Lambrechts-Woluwe", "Sint-Laureins", "Sint-Laureins-Berchem"
      , "Sint-Lenaarts", "Sint-Lievens-Esse", "Sint-Lievens-Houtem",
      "Sint-Margriete", "Sint-Margriete-Houtem", "Sint-Maria-Horebeke",
      "Sint-Maria-Latem", "Sint-Maria-Lierde",
      "Sint-Maria-Oudenhove-Brakel", "Sint-Maria-Oudenhove-Zottegem",
      "Sint-Martens-Bodegem", "Sint-Martens-Latem",
      "Sint-Martens-Leerne", "Sint-Martens-Lennik",
      "Sint-Martens-Lierde", "Sint-Martens-Voeren", "Sint-Michiels",
      "Sint-Niklaas", "Sint-Pauwels", "Sint-Pieters-Kapelle",
      "Sint-Pieters-Leeuw", "Sint-Pieters-Rode", "Sint-Pieters-Voeren",
      "Sint-Pieters-Woluwe", "Sint-Rijkers", "Sint-Stevens-Woluwe",
      "Sint-Truiden", "Sint-Ulriks-Kapelle", "Sippenaeken", "Sirault",
      "Sivry", "Sivry-Rance", "Sleidinge", "Slijpe", "Slins", "Sluizen",
      "Smeerebbe-Vloerzegem", "Smetlede", "Smuid", "Snaaskerke",
      "Snellegem", "Soheit-Tinlot", "Sohier", "Soignies", "Soiron",
      "Solre-Saint-G\u00e9ry", "Solre-sur-Sambre", "Sombreffe",
      "Somme-Leuze", "Sommethonne", "Sommi\u00e8re", "Somz\u00e9e",
      "Sorinne-la-Longue", "Sorinnes", "Sor\u00e9e", "Sosoye",
      "Sougn\u00e9-Remouchamps", "Soulme", "Soumagne", "Soumoy",
      "Sourbrodt", "Souvret", "Sovet", "Soy", "Soye", "Spa", "Spalbeek",
      "Spermalie", "Spiennes", "Spiere", "Spiere-Helkijn", "Spontin",
      "Spouwen", "Sprimont", "Spy", "Stabroek", "Staden", "Stalhille",
      "Stambruges", "Stave", "Stavele", "Stavelot", "Steendorp",
      "Steenhuffel", "Steenhuize-Wijnhuize", "Steenkerke", "Steenkerque"
      , "Steenokkerzeel", "Stekene", "Stembert", "Stene", "Sterrebeek",
      "Stevoort", "Stokrooie", "Stoumont", "Straimont", "Strijpen",
      "Strijtem", "Strombeek-Bever", "Str\u00e9e", "Str\u00e9e-lez-Huy",
      "Str\u00e9py-Bracquegnies", "Stuivekenskerke", "Suarl\u00e9e",
      "Sugny", "Surice", "Suxy", "S\u00e9lange", "Tailles",
      "Taintignies", "Tamines", "Tarcienne", "Tavier", "Taviers",
      "Tavigny", "Tellin", "Templeuve", "Temploux", "Temse",
      "Tenneville", "Teralfene", "Terhagen", "Termes", "Ternat",
      "Tertre", "Tervuren", "Terwagne", "Tessenderlo", "Testelt",
      "Teuven", "Theux", "Thiaumont", "Thieu", "Thieulain", "Thieusies",
      "Thimister", "Thimister-Clermont", "Thimougies", "Thim\u00e9on",
      "Thines", "Thirimont", "Thisnes", "Thommen", "Thon",
      "Thorembais-Saint-Trond", "Thorembais-les-B\u00e9guines",
      "Thoricourt", "Thuillies", "Thuin", "Thulin", "Thumaide",
      "Thy-le-Bauduin", "Thy-le-Chateau", "Thynes", "Thys", "Tiegem",
      "Tielen", "Tielrode", "Tielt", "Tielt-Winge", "Tienen",
      "Tign\u00e9e", "Tihange", "Tildonk", "Tilff", "Tillet", "Tilleur",
      "Tillier", "Tilly", "Tinlot", "Tintange", "Tintigny", "Tisselt",
      "Toernich", "Tohogne", "Tollembeek", "Tongeren", "Tongerlo",
      "Tongre-Notre-Dame", "Tongre-Saint-Martin", "Tongrinne",
      "Tontelange", "Torgny", "Torhout", "Tourinne",
      "Tourinnes-Saint-Lambert", "Tournai", "Tournay", "Tourpes",
      "Transinne", "Trazegnies", "Treignes", "Trembleur", "Tremelo",
      "Trivi\u00e8res", "Trogn\u00e9e", "Trois-Ponts", "Trooz", "Tubize"
      , "Turnhout", "Ucimont", "Uikhoven", "Uitbergen", "Uitkerke",
      "Ukkel", "Ulbeek", "Upigny", "Ursel", "Vaalbeek", "Val-Meer",
      "Vance", "Varendonk", "Varsenare", "Vaucelles", "Vaulx",
      "Vaulx-lez-Chimay", "Vaux-Chavanne", "Vaux-et-Borset",
      "Vaux-lez-Rosi\u00e8res", "Vaux-sous-Ch\u00e8vremont",
      "Vaux-sur-S\u00fbre", "Vechmaal", "Vedrin", "Veerle",
      "Velaine-sur-Sambre", "Velaines", "Veldegem", "Veldwezelt",
      "Vellereille-le-Sec", "Vellereille-les-Brayeux", "Velm", "Velroux"
      , "Veltem-Beisem", "Velzeke-Ruddershove", "Vencimont", "Vergnies",
      "Verlaine", "Verl\u00e9e", "Verrebroek", "Vertrijk", "Verviers",
      "Vesqueville", "Veulen", "Veurne", "Vezin", "Vezon", "Viane",
      "Vichte", "Vielsalm", "Viemme", "Viersel", "Vierset-Barse",
      "Vierves-sur-Viroin", "Viesville", "Vieux-Genappe",
      "Vieux-Waleffe", "Vieuxville", "Villance", "Ville-Pommeroeul",
      "Ville-en-Hesbaye", "Ville-sur-Haine", "Villerot",
      "Villers-Deux-Eglises", "Villers-Notre-Dame", "Villers-Perwin",
      "Villers-Poterie", "Villers-Saint-Amand", "Villers-Saint-Ghislain"
      , "Villers-Saint-Sim\u00e9on", "Villers-Sainte-Gertrude",
      "Villers-aux-Tours", "Villers-devant-Orval", "Villers-en-Fagne",
      "Villers-l\'Ev\u00eaque", "Villers-la-Bonne-Eau",
      "Villers-la-Loue", "Villers-la-Tour", "Villers-la-Ville",
      "Villers-le-Bouillet", "Villers-le-Gambon", "Villers-le-Peuplier",
      "Villers-le-Temple", "Villers-lez-Heest", "Villers-sur-Lesse",
      "Villers-sur-Semois", "Vilvoorde", "Vinalmont", "Vinderhoute",
      "Vinkem", "Vinkt", "Virelles", "Virginal-Samme", "Viroinval",
      "Virton", "Vissenaken", "Vis\u00e9", "Vitrival", "Vivegnis",
      "Vivy", "Vladslo", "Vlamertinge", "Vlekkem", "Vleteren",
      "Vlezenbeek", "Vliermaal", "Vliermaalroot", "Vlierzele",
      "Vlijtingen", "Vlimmeren", "Vlissegem", "Vloesberg",
      "Vodec\u00e9e", "Vodel\u00e9e", "Voeren", "Vogen\u00e9e",
      "Volkegem", "Vollezele", "Von\u00eache", "Voorde", "Voormezele",
      "Voort", "Voroux-Goreux", "Voroux-lez-Liers", "Vorselaar",
      "Vorsen", "Vorst", "Vosselaar", "Vosselare", "Vossem", "Vottem",
      "Vrasene", "Vremde", "Vreren", "Vresse-sur-Semois", "Vroenhoven",
      "Vucht", "Vurste", "Vyle-et-Tharoul", "Waanrode", "Waarbeke",
      "Waardamme", "Waarloos", "Waarmaarde", "Waarschoot", "Waasmont",
      "Waasmunster", "Waasten", "Wachtebeke", "Wadelincourt",
      "Wagnel\u00e9e", "Waha", "Waillet", "Wakken", "Walcourt", "Walem",
      "Walhain", "Walhain-Saint-Paul", "Walhorn", "Walsbets",
      "Walshoutem", "Waltwilder", "Wambeek", "Wancennes", "Wandre",
      "Wanferc\u00e9e-Baulet", "Wange", "Wangenies", "Wanlin", "Wanne",
      "Wannebecq", "Wannegem-Lede", "Wansin", "Wanze", "Wanzele",
      "Warchin", "Warcoing", "Wardin", "Waregem", "Waremme",
      "Waret-l\'Ev\u00eaque", "Waret-la-Chauss\u00e9e", "Warisoulx",
      "Warnant", "Warnant-Dreye", "Warquignies", "Warsage",
      "Warz\u00e9e", "Wasmes", "Wasmes-Audemez-Briffoeil", "Wasmuel",
      "Wasseiges", "Waterland-Oudeman", "Waterloo",
      "Watermaal-Bosvoorde", "Watervliet", "Watou", "Wattripont",
      "Waudrez", "Waulsort", "Wauthier-Braine", "Waver", "Wavreille",
      "Wayaux", "Ways", "Webbekom", "Wechelderzande", "Weelde", "Weerde"
      , "Weert", "Wegnez", "Weillen", "Weismes", "Welden", "Welkenraedt"
      , "Welle", "Wellen", "Wellin", "Wemmel", "Wenduine", "Werbomont",
      "Werchter", "Werken", "Werm", "Wervik", "Wespelaar", "Westende",
      "Westerlo", "Westkapelle", "Westkerke", "Westmalle",
      "Westmeerbeek", "Westouter", "Westrem", "Westrozebeke",
      "Westvleteren", "Wetteren", "Wevelgem", "Wez-Velvain", "Wezemaal",
      "Wezembeek-Oppem", "Wezeren", "Wibrin", "Wichelen", "Widooie",
      "Wiekevorst", "Wielsbeke", "Wierde", "Wiers", "Wiesme", "Wieze",
      "Wihogne", "Wih\u00e9ries", "Wijchmaal", "Wijer", "Wijgmaal",
      "Wijnegem", "Wijshagen", "Wijtschate", "Wilderen", "Willaupuis",
      "Willebringen", "Willebroek", "Willemeau", "Willerzie", "Wilrijk",
      "Wilsele", "Wilskerke", "Wimmertingen", "Winenne", "Wingene",
      "Winksele", "Wintershoven", "Witry", "Wodecq", "Woesten",
      "Wolkrange", "Wolvertem", "Wommelgem", "Wommersom", "Wonck",
      "Wondelgem", "Wontergem", "Wortegem", "Wortegem-Petegem", "Wortel"
      , "Woubrechtegem", "Woumen", "Wulpen", "Wulvergem", "Wulveringem",
      "Wuustwezel", "W\u00e9pion", "W\u00e9ris", "Xhendelesse",
      "Xhendremael", "Xhoris", "Yern\u00e9e-Fraineux",
      "Yves-Gomez\u00e9e", "Yvoir", "Zaffelare", "Zandbergen", "Zande",
      "Zandhoven", "Zandvliet", "Zandvoorde-Oostende",
      "Zandvoorde-Zonnebeke", "Zarlardinge", "Zarren", "Zaventem",
      "Zedelgem", "Zeebrugge", "Zegelsem", "Zele", "Zelem", "Zellik",
      "Zelzate", "Zemst", "Zepperen", "Zerkegem", "Zevekote",
      "Zeveneken", "Zeveren", "Zevergem", "Zichem",
      "Zichen-Zussen-Bolder", "Zillebeke", "Zingem", "Zoerle-Parwijs",
      "Zoersel", "Zolder", "Zomergem", "Zonhoven", "Zonnebeke",
      "Zonnegem", "Zottegem", "Zoutenaaie", "Zoutleeuw", "Zuidschote",
      "Zuienkerke", "Zulte", "Zulzeke", "Zutendaal", "Zwalm", "Zwevegem"
      , "Zwevezele", "Zwijnaarde", "Zwijndrecht", "Z\u00e9trud-Lumay",
      "l\'Escaill\u00e8re"
    ),

    provinces = c(
      "Antwerpen", "Henegouwen", "Limburg", "Luik", "Luxemburg", "Namen",
      "Oost-Vlaanderen", "Vlaams-Brabant", "Waals-Brabant", "West-Vlaanderen"),

    street_name_formats = '{first_name}{street_suffix}',

    street_address_formats = '{street_name} {building_number}',


    address_formats = c(
      "{street_address}\n{postcode}\n{city}",
      "{street_address}\n{postcode} {city}")
  ),

  public = list(
    province = function(){
      return(private$random_element(private$provinces))
    },

    city = function(){
      return(private$random_element(private$cities))
    }
  )
)
# phone_number -----------------------------------
phone_number_nl_BE = R6Class(
  "phone_number_nl_BE",
  inherit = phone_number_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '0### ######',
      '0## #######',
      '+32### ######',
      '+32## #######',
      '+32(0)### ######',
      '+32(0)## #######',
      '(0###) ######',
      '(0##) #######',
      '0###-######',
      '0##-#######',
      '+32###-######',
      '+32##-#######',
      '+32(0)###-######',
      '+32(0)##-#######',
      '(0###)-######',
      '(0##)-#######'
    )
  )
)
# ssn ------------------------------------------
ssn_nl_BE = R6Class(
  "ssn_nl_BE",
  inherit = ssn_init,
  cloneable = FALSE,
  private = list(
    vat_id_formats = 'BE##########',
    checksum = function(digits){
      # see http://nl.wikipedia.org/wiki/Burgerservicenummer (in Dutch)
      res = 97 - (digits %% 97)
    }
  ),

  public = list(
    ssn = function(){
      # Returns a 11 digits Belgian SSN called "rijksregisternummer" as a string
      # The first 6 digits represent the birthdate with (in order) year, month and day.
      # The second group of 3 digits is represents a sequence number (order of birth).
      # It is even for women and odd for men.
      # For men the range starts at 1 and ends 997, for women 2 until 998.
      # The third group of 2 digits is a checksum based on the previous 9 digits (modulo 97).
      # Divide those 9 digits by 97, subtract the remainder from 97 and that's the result.
      # For persons born in or after 2000, the 9 digit number needs to be proceeded by a 2
      # (add 2000000000) before the division by 97.

      # Generate a date (random)
      mydate = (date_time_init$new())$date()

      elms = str_split(mydate, "-")[[1]]
      # Adjust for year 2000 if necessary
      above = str_sub(elms[1], 1, 1) == "2"
      # Only keep the last 2 digits of the year

      elms[1] = str_sub(elms[1], 3, 4)
      # Simulate the gender/sequence - should be 3 digits
      rint = private$random_int(1, 998)
      # Right justify sequence and append to list
      seq_str = sprintf("%03d", rint)
      elms = c(elms, seq_str)
      # Now convert list to an integer so the checksum can be calculated
      date_as_int = as.integer(str_c(elms, collapse = ""))
      if (above) date_as_int = date_as_int + 2000000000

      # Generate checksum
      s = private$checksum(date_as_int)
      s_rjust = sprintf("%02d", s)
      elms = c(elms, s_rjust)
      return(str_c(elms, collapse = ""))
    },

    vat_id = function(){
      # http://ec.europa.eu/taxation_customs/vies/faq.html#item_11
      # :return: A random Belgian VAT ID
      return(private$bothify(private$random_element(private$vat_id_formats)))
    }
  )
)

# profile ------------------------------------
profile_nl_BE = R6Class(
  "profile_nl_BE",
  inherit = profile_init,
  cloneable = FALSE,
  public = list(
    simple_profile = function(sex) {
      # Generates a basic profile with personal informations
      SEX = c("F", "M")
      if (missing(sex)) {
        sex = sample(SEX, 1)
      }
      if (!(sex %in% SEX)) {
        sex = sample(SEX, 1)
      }

      name = ifelse(sex == "F",
                    (person_en_US$new())$name_female(),
                    (person_en_US$new())$name_male())
      temp = list(
        "username" = (internet_en_US$new())$user_name(),
        "name" = name,
        "sex" = sex,
        "address" = (address_nl_BE$new())$address(),
        "mail" = (internet_en_US$new())$free_email(),
        "birthdate" = (date_time_init$new())$date_of_birth()
      )
      return(temp)
    },

    profile = function(fields, sex) {
      # Generates a complete profile.
      # If "fields" is not empty, only the fields in the list will be returned

      if (missing(fields)) fields = c()

      field = list(
        "job" = (job_init$new())$job(),
        "company" = (company_en_US$new())$company(),
        "ssn" = (ssn_nl_BE$new())$ssn(),
        "residence" = (address_nl_BE$new())$address(),
        "current_location" = c((geo_init$new())$latitude(),
                               (geo_init$new())$longitude()),
        "blood_group" = sample(c(
          "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"), 1),
        "website" = replicate(sample(seq(4), 1), (internet_en_US$new())$url())
      )

      field = append(field, self$simple_profile(sex))
      # field selection

      if (length(fields)) {
        nms = intersect(names(field), fields)
        field = field[nms]
      }
      return(field)
    }

  )
)


