# bank -----------------------------------------
bank_nl_NL = R6Class(
  "bank_nl_NL",
  inherit = bank_init,
  cloneable = FALSE,
  private = list(
    bban_format = '????##########',
    country_code = 'NL'
  )
)
# person -----------------------------------
person_nl_NL = R6Class(
  "person_nl_NL",
  inherit = person_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '{first_name_male} {last_name}',
      '{first_name_male} {last_name}',
      '{first_name_male} {last_name}',
      '{first_name_male} {last_name}-{last_name}',
      '{first_name_female} {last_name}',
      '{first_name_female} {last_name}',
      '{first_name_female} {last_name}',
      '{first_name_female} {last_name}-{last_name}'),

    first_names_male = c(
      'Aaron', 'Abel', 'Adam', 'Aiden', 'Alex', 'Alexander', 'Ali', 'Amin',
      'Amir', 'Arie', 'Aron', 'Arthur', 'Ayden', 'Ayoub', 'Bart', 'Bas',
      'Bastiaan', 'Beau', 'Ben', 'Benjamin', 'Berat', 'Berend', 'Bilal',
      'Bjorn', 'Boaz', 'Boris', 'Bradley', 'Bram', 'Brent', 'Brian', 'Bryan',
      'Cas', 'Casper', 'Chris', 'Colin', 'Collin', 'Cornelis', 'Daan',
      'Damian', 'Dani', 'Daniel', 'Dani\u00ebl', 'Dave', 'David', 'Dean', 'Dex',
      'Dion', 'Dirk', 'Duuk', 'Dylan', 'Dylano', 'Elias', 'Emir', 'Faas',
      'Fabian', 'Fedde', 'Felix', 'Finn', 'Florian', 'Floris', 'Gerrit',
      'Giel', 'Gijs', 'Giovanni', 'Guus', 'Hamza', 'Hendrik', 'Hidde',
      'Hugo', 'Ian', 'Ibrahim', 'Imran', 'Ivan', 'Jack', 'Jacob', 'Jake',
      'James', 'Jamie', 'Jan', 'Jari', 'Jason', 'Jasper', 'Jay', 'Jayden',
      'Jayson', 'Jelle', 'Jelte', 'Jens', 'Jesper', 'Jesse', 'Jim', 'Jip',
      'Job', 'Joep', 'Joey', 'Johannes', 'Jonas', 'Jonathan', 'Joost',
      'Jordy', 'Joris', 'Jorn', 'Jort', 'Joshua', 'Jo\u00ebl', 'Jules', 'Julian',
      'Julius', 'Jurre', 'Justin', 'Kai', 'Kay', 'Keano', 'Kevin', 'Kian',
      'Kick', 'Koen', 'Kyan', 'Kyano', 'Lars', 'Laurens', 'Lenn', 'Leon',
      'Levi', 'Lex', 'Liam', 'Loek', 'Lorenzo', 'Luc', 'Luca', 'Lucas',
      'Luka', 'Lukas', 'Luke', 'Luuk', 'Maarten', 'Mads', 'Marijn',
      'Marinus', 'Mark', 'Mart', 'Mason', 'Mathijs', 'Mats', 'Matthias',
      'Matthijs', 'Maurits', 'Max', 'Maxim', 'Mees', 'Mehmet', 'Melle',
      'Merijn', 'Micha', 'Michael', 'Mick', 'Mika', 'Mike', 'Milan', 'Milo',
      'Mohamed', 'Mohammed', 'Morris', 'Muhammed', 'Mustafa', 'Nathan',
      'Naud', 'Nick', 'Niek', 'Niels', 'Noah', 'Noud', 'Nout', 'Olaf',
      'Olivier', 'Oscar', 'Owen', 'Pepijn', 'Philip', 'Pieter', 'Pim',
      'Quinn', 'Quinten', 'Raf', 'Rafael', 'Ravi', 'Rayan', 'Rens', 'Rick',
      'Rik', 'Riley', 'Roan', 'Robin', 'Rowan', 'Ruben', 'Ryan', 'Sam',
      'Sami', 'Samuel', 'Sander', 'Sebastiaan', 'Sem', 'Senn', 'Senna',
      'Sep', 'Sepp', 'Seth', 'Siem', 'Sil', 'Simon', 'Sjoerd', 'Stan',
      'Stef', 'Stefan', 'Sten', 'Stijn', 'Sven', 'Teun', 'Thijmen', 'Thijn',
      'Thijs', 'Thom', 'Thomas', 'Ties', 'Tijmen', 'Tijn', 'Tijs', 'Tim',
      'Timo', 'Tobias', 'Tom', 'Tristan', 'Twan', 'Tycho', 'Tygo', 'Tyler',
      'Valentijn', 'Victor', 'Vigo', 'Vince', 'Vincent', 'Wesley', 'Wessel',
      'Willem', 'Wout', 'Wouter', 'Xavi', 'Yassin', 'Youssef', 'Yusuf',
      'Zakaria'),

    first_names_female = c(
      "Aaliyah", "Adriana", "Aim\u00e9e", "Alicia", "Alyssa", "Amber",
      "Amelia", "Amina", "Amira", "Amy", "Am\u00e9lie", "Angelina",
      "Anna", "Annabel", "Anne", "Annemijn", "Anouk", "Ashley", "Aya",
      "Aylin", "Azra", "Bente", "Benthe", "Bibi", "Bo", "Britt",
      "Carlijn", "Catharina", "Cato", "Ceylin", "Charlotte",
      "Chlo\u00e9", "Chlo\u00eb", "Cornelia", "Dana", "Danique",
      "Daphne", "Demi", "Dewi", "Dina", "Ecrin", "Elena", "Elif", "Elin"
      , "Eline", "Elisa", "Elisabeth", "Elise", "Eliza", "Elizabeth",
      "Elize", "Ella", "Emily", "Emma", "Esila", "Esmee", "Esm\u00e9e",
      "Esther", "Eva", "Evelien", "Evi", "Evie", "Evy", "Fabi\u00ebnne",
      "Fatima", "Fay", "Faye", "Feline", "Fem", "Femke", "Fenna",
      "Fenne", "Fien", "Fiene", "Fleur", "Floor", "Floortje",
      "Frederique", "F\u00e9line", "Guusje", "Hailey", "Hanna", "Hannah"
      , "Helena", "Ilse", "Imke", "Inaya", "Indy", "Iris", "Isa",
      "Isabel", "Isabella", "Isabelle", "Ise", "Isis", "Ivy", "Ize",
      "Jade", "Janna", "Janne", "Jasmijn", "Jayda", "Jaylinn", "Jenna",
      "Jennifer", "Jente", "Jet", "Jill", "Jinthe", "Johanna", "Jolie",
      "Jolijn", "Josephine", "Joy", "Jo\u00eblle", "Julia", "Julie",
      "Juliette", "Juul", "Karlijn", "Kate", "Kaylee", "Kayleigh",
      "Kiki", "Kim", "Kyara", "Kyra", "Lana", "Lara", "Laura", "Lauren",
      "Leah", "Lena", "Lieke", "Lieve", "Lily", "Lina", "Linde",
      "Lindsey", "Linn", "Lisa", "Lisanne", "Lise", "Liv", "Livia",
      "Liz", "Liza", "Lize", "Lizz", "Lizzy", "Loes", "Lois", "Lola",
      "Lot", "Lotte", "Louise", "Lo\u00efs", "Lucy", "Luna", "Lynn",
      "Maaike", "Maartje", "Madelief", "Maja", "Mara", "Mare", "Maria",
      "Marit", "Maryam", "Maud", "Maya", "Megan", "Meike", "Melissa",
      "Merel", "Merle", "Mette", "Mia", "Michelle", "Mila", "Milou",
      "Mirte", "Mirthe", "Myrthe", "Nadia", "Nadine", "Naomi", "Nienke",
      "Nikki", "Nina", "Ninthe", "Nisa", "Noa", "Noor", "Noortje",
      "Nora", "Norah", "Nova", "No\u00eblle", "Nynke", "Olivia",
      "Phileine", "Pien", "Pippa", "Pleun", "Puck", "Puk", "Quinty",
      "Renske", "Robin", "Romy", "Roos", "Rosa", "Rosalie", "Saar",
      "Sam", "Sanne", "Sara", "Sarah", "Selena", "Selina", "Senna",
      "Sienna", "Silke", "Sofia", "Sofie", "Sophia", "Sophie", "Stella",
      "Sterre", "Suus", "Suze", "Sylvie", "Tara", "Tess", "Tessa",
      "Tirza", "Vaj\u00e8n", "Valerie", "Veerle", "Vera", "Victoria",
      "Yara", "Yasmin", "Yasmine", "Yfke", "Yinthe", "Zara", "Zeynep",
      "Zoey", "Zo\u00eb"
    ),

    first_names = c(
      "Aaron", "Abel", "Adam", "Aiden", "Alex", "Alexander", "Ali",
      "Amin", "Amir", "Arie", "Aron", "Arthur", "Ayden", "Ayoub", "Bart"
      , "Bas", "Bastiaan", "Beau", "Ben", "Benjamin", "Berat", "Berend",
      "Bilal", "Bjorn", "Boaz", "Boris", "Bradley", "Bram", "Brent",
      "Brian", "Bryan", "Cas", "Casper", "Chris", "Colin", "Collin",
      "Cornelis", "Daan", "Damian", "Dani", "Daniel", "Dani\u00ebl",
      "Dave", "David", "Dean", "Dex", "Dion", "Dirk", "Duuk", "Dylan",
      "Dylano", "Elias", "Emir", "Faas", "Fabian", "Fedde", "Felix",
      "Finn", "Florian", "Floris", "Gerrit", "Giel", "Gijs", "Giovanni",
      "Guus", "Hamza", "Hendrik", "Hidde", "Hugo", "Ian", "Ibrahim",
      "Imran", "Ivan", "Jack", "Jacob", "Jake", "James", "Jamie", "Jan",
      "Jari", "Jason", "Jasper", "Jay", "Jayden", "Jayson", "Jelle",
      "Jelte", "Jens", "Jesper", "Jesse", "Jim", "Jip", "Job", "Joep",
      "Joey", "Johannes", "Jonas", "Jonathan", "Joost", "Jordy", "Joris"
      , "Jorn", "Jort", "Joshua", "Jo\u00ebl", "Jules", "Julian",
      "Julius", "Jurre", "Justin", "Kai", "Kay", "Keano", "Kevin",
      "Kian", "Kick", "Koen", "Kyan", "Kyano", "Lars", "Laurens", "Lenn"
      , "Leon", "Levi", "Lex", "Liam", "Loek", "Lorenzo", "Luc", "Luca",
      "Lucas", "Luka", "Lukas", "Luke", "Luuk", "Maarten", "Mads",
      "Marijn", "Marinus", "Mark", "Mart", "Mason", "Mathijs", "Mats",
      "Matthias", "Matthijs", "Maurits", "Max", "Maxim", "Mees",
      "Mehmet", "Melle", "Merijn", "Micha", "Michael", "Mick", "Mika",
      "Mike", "Milan", "Milo", "Mohamed", "Mohammed", "Morris",
      "Muhammed", "Mustafa", "Nathan", "Naud", "Nick", "Niek", "Niels",
      "Noah", "Noud", "Nout", "Olaf", "Olivier", "Oscar", "Owen",
      "Pepijn", "Philip", "Pieter", "Pim", "Quinn", "Quinten", "Raf",
      "Rafael", "Ravi", "Rayan", "Rens", "Rick", "Rik", "Riley", "Roan",
      "Robin", "Rowan", "Ruben", "Ryan", "Sam", "Sami", "Samuel",
      "Sander", "Sebastiaan", "Sem", "Senn", "Senna", "Sep", "Sepp",
      "Seth", "Siem", "Sil", "Simon", "Sjoerd", "Stan", "Stef", "Stefan"
      , "Sten", "Stijn", "Sven", "Teun", "Thijmen", "Thijn", "Thijs",
      "Thom", "Thomas", "Ties", "Tijmen", "Tijn", "Tijs", "Tim", "Timo",
      "Tobias", "Tom", "Tristan", "Twan", "Tycho", "Tygo", "Tyler",
      "Valentijn", "Victor", "Vigo", "Vince", "Vincent", "Wesley",
      "Wessel", "Willem", "Wout", "Wouter", "Xavi", "Yassin", "Youssef",
      "Yusuf", "Zakaria", "Aaliyah", "Adriana", "Aim\u00e9e", "Alicia",
      "Alyssa", "Amber", "Amelia", "Amina", "Amira", "Amy",
      "Am\u00e9lie", "Angelina", "Anna", "Annabel", "Anne", "Annemijn",
      "Anouk", "Ashley", "Aya", "Aylin", "Azra", "Bente", "Benthe",
      "Bibi", "Bo", "Britt", "Carlijn", "Catharina", "Cato", "Ceylin",
      "Charlotte", "Chlo\u00e9", "Chlo\u00eb", "Cornelia", "Dana",
      "Danique", "Daphne", "Demi", "Dewi", "Dina", "Ecrin", "Elena",
      "Elif", "Elin", "Eline", "Elisa", "Elisabeth", "Elise", "Eliza",
      "Elizabeth", "Elize", "Ella", "Emily", "Emma", "Esila", "Esmee",
      "Esm\u00e9e", "Esther", "Eva", "Evelien", "Evi", "Evie", "Evy",
      "Fabi\u00ebnne", "Fatima", "Fay", "Faye", "Feline", "Fem", "Femke"
      , "Fenna", "Fenne", "Fien", "Fiene", "Fleur", "Floor", "Floortje",
      "Frederique", "F\u00e9line", "Guusje", "Hailey", "Hanna",
      "Hannah", "Helena", "Ilse", "Imke", "Inaya", "Indy", "Iris", "Isa"
      , "Isabel", "Isabella", "Isabelle", "Ise", "Isis", "Ivy", "Ize",
      "Jade", "Janna", "Janne", "Jasmijn", "Jayda", "Jaylinn", "Jenna",
      "Jennifer", "Jente", "Jet", "Jill", "Jinthe", "Johanna", "Jolie",
      "Jolijn", "Josephine", "Joy", "Jo\u00eblle", "Julia", "Julie",
      "Juliette", "Juul", "Karlijn", "Kate", "Kaylee", "Kayleigh",
      "Kiki", "Kim", "Kyara", "Kyra", "Lana", "Lara", "Laura", "Lauren",
      "Leah", "Lena", "Lieke", "Lieve", "Lily", "Lina", "Linde",
      "Lindsey", "Linn", "Lisa", "Lisanne", "Lise", "Liv", "Livia",
      "Liz", "Liza", "Lize", "Lizz", "Lizzy", "Loes", "Lois", "Lola",
      "Lot", "Lotte", "Louise", "Lo\u00efs", "Lucy", "Luna", "Lynn",
      "Maaike", "Maartje", "Madelief", "Maja", "Mara", "Mare", "Maria",
      "Marit", "Maryam", "Maud", "Maya", "Megan", "Meike", "Melissa",
      "Merel", "Merle", "Mette", "Mia", "Michelle", "Mila", "Milou",
      "Mirte", "Mirthe", "Myrthe", "Nadia", "Nadine", "Naomi", "Nienke",
      "Nikki", "Nina", "Ninthe", "Nisa", "Noa", "Noor", "Noortje",
      "Nora", "Norah", "Nova", "No\u00eblle", "Nynke", "Olivia",
      "Phileine", "Pien", "Pippa", "Pleun", "Puck", "Puk", "Quinty",
      "Renske", "Robin", "Romy", "Roos", "Rosa", "Rosalie", "Saar",
      "Sam", "Sanne", "Sara", "Sarah", "Selena", "Selina", "Senna",
      "Sienna", "Silke", "Sofia", "Sofie", "Sophia", "Sophie", "Stella",
      "Sterre", "Suus", "Suze", "Sylvie", "Tara", "Tess", "Tessa",
      "Tirza", "Vaj\u00e8n", "Valerie", "Veerle", "Vera", "Victoria",
      "Yara", "Yasmin", "Yasmine", "Yfke", "Yinthe", "Zara", "Zeynep",
      "Zoey", "Zo\u00eb"
    ),

    last_names = c(
      "'s Gravensande", "Aalts", "Aarden", "Aarts", "Adelaar",
      "Adriaansen", "Adriaensdr", "Adriaense", "Adryaens", "Aeije",
      "Aelftrud van Wessex", "Aertsz", "Alpaidis", "Amalrada", "Ansems",
      "Appelman", "Arens", "Arent", "Ariens", "Ariens Ansems", "Arnold"
      , "Arts", "Aschman", "Backer", "Bakker", "Barents", "Bartels",
      "Bastiaanse", "Bastiaense", "Bave", "Becht", "Beekman", "Beernink"
      , "Beijring", "Bekbergen", "Bellemans", "Belpere", "Beourgeois",
      "Berends", "Berendse", "Bernaards", "Bertho", "Bezemer",
      "Bierstraten", "Bijlsma", "Billung", "Blaak", "Blees",
      "Bleijenberg", "Blewanus", "Bloemendaal", "Blokland", "Blom",
      "Blom", "Blonk", "Boddaugh", "Boer", "Boer", "Boers", "Boeser",
      "Boetet", "Bolkesteijn", "Booden", "Boogaerts", "Borman", "Bos",
      "Bos", "Bosch", "Bosch", "Bosman", "Boudewijns", "Bouhuizen",
      "Bourgondiu00eb, van", "Bouthoorn", "Bouwhuisen", "Brandon",
      "Brands", "Brandt", "Bresse", "Bresu00e9", "Breugelensis",
      "Briere", "Brievingh", "Brisee", "Brizee", "Broeckx", "Broeders",
      "Broek", "Broekhoven", "Broeshart", "Bronder", "Brouwer",
      "Brouwer", "Bruggeman", "Brugman", "Bruijne van der Veen",
      "Brumleve", "Bruynzeels", "Bud", "Buijs", "Butselaar",
      "Bu00f6kenkamp", "Cadefau", "Cammel", "Cant", "Carnotte", "Charon"
      , "Chevresson", "Chotzen", "Chrodtrud", "Claassen", "Claesdr",
      "Claesner", "Coenen", "Coolen", "Coret", "Coret-Coredo",
      "Coreth von und zu Coredo und Starkenberg", "Cornelisse", "Cornelissen",
      "Cornelisz", "Corstiaens", "Cosman", "Courtier", "Dachgelder",
      "Dachgeldt", "Dachgelt", "David", "Dekker", "Dekker", "Demmendaal"
      , "Dennenberg", "Die Bont", "Diesbergen", "Dijkman", "Dijkstra",
      "Dircken", "Dirksen", "Dirven", "Doesburg", "Doorhof", "Doornhem",
      "Dorsman", "Doyle", "Draaisma", "Dries", "Driessen", "Drysdale",
      "Dubois", "Duivenvoorden", "Eckhardt", "Eelman", "Eerden",
      "Ehlert", "Eijkelboom", "Elberts", "Elbertse", "Ellis",
      "Elsemulder", "Elsenaar", "Emmen", "Engels", "Erhout", "Ernst",
      "Estey", "Everde", "Evers", "Everts", "Fechant", "Feenstra",
      "Feltzer", "Ferran", "Fiere", "Flink", "Fortuyn", "Frankhuizen",
      "Franu00e7ois", "Franu00e7oise", "Fredriks", "Fremie", "Frerichs",
      "Freshour", "Friehus", "Furda", "Galenzone", "Galijn", "Garret",
      "Geerling", "Geerts", "Geertsen", "Geldens", "Gellemeyer", "Gemen"
      , "Geneart", "Genefaas", "Gepa van Bourgondiu00eb", "Gerrits",
      "Gerritse", "Gerritsen", "Gervais", "Ghoerle", "Giselmeyer",
      "Glasses", "Gnodde", "Goderts", "Godfrey van Alemanniu00eb",
      "Goedhart", "Goudriaan", "Govarts", "Goyaerts van Waderle",
      "Greij", "Groen", "Groenendaal", "Groenestein", "Grondel",
      "Groote", "Gruijl", "Guit", "Haack", "Haengreve", "Hagendoorn",
      "Hak", "Hakker", "Haneberg", "Hanegraaff", "Haring", "Haselaar",
      "Hazenveld", "Heere", "Heerkens", "Heerschop", "Hehl", "Heijman",
      "Heijmans", "Heijmen", "Heinrichs", "Hekker", "Hellevoort",
      "Helmerhorst", "Hemma van Allemaniu00eb", "Hendricks", "Hendriks",
      "Hendriks", "Hendrikse", "Henric van den Nuwenhuse",
      "Heribert van Laon", "Hermans", "Hermans", "Hexspoor", "Heymans", "Heyne",
      "Hoedemakers", "Hoeks", "Hoekstra", "Hoelen", "Hoes", "Hofman",
      "Hollander", "Holthuis", "Hondeveld", "Honing", "Hoogers",
      "Hoppenbrouwer", "Horrocks", "Houdijk", "Huberts", "Huel",
      "Huijben", "Huijbrechts", "Huijs", "Huijzing", "Huisman",
      "Huisman", "Huls", "Hulshouts", "Hulskes", "Hulst", "Huurdeman",
      "Hu00f6ning", "Jaceps", "Jacobi", "Jacobs", "Jacobs", "Jacquot",
      "Jans", "Jansdr", "Janse", "Jansen", "Jansen", "Jansen", "Jansse",
      "Janssen", "Janssen", "Janssens", "Jasperdr.", "Jdotte", "Jeggij"
      , "Jekel", "Jerusalem", "Jochems", "Jones", "Jonker", "Jonkman",
      "Joosten", "Jorlink", "Jorrisen", "Jurrijens", "Kallen", "Kalman",
      "Kamp", "Kamper", "Karels", "Kas", "Kathagen", "Keijser",
      "Keijzer", "Keltenie", "Kerkhof", "Ketel", "Ketting",
      "Kirpenstein", "Kisman", "Kleibrink", "Kleijse", "Klein", "Klerks"
      , "Kleybrink", "Klomp Jan", "Kloppert", "Knoers", "Knuf", "Koeman"
      , "Kof", "Kok", "Kok", "Kolen", "Kolster", "Koning", "Konings",
      "Koret", "Korsman", "Korstman", "Kort", "Kortman", "Kosten",
      "Koster", "Koster", "Krabbe", "Kramer", "Kremer", "Kriens",
      "Kronenberg", "Kruns", "Kuijpers", "Kuijpers", "Kuilenburg",
      "Kuiper", "Kuipers", "Kuit", "Kunen", "Kwaadland", "Ku00f6ster",
      "Labado", "Laffray", "Lafleur", "Lage", "Lagerweij", "Lambers",
      "Lambregt", "Lamore", "Lamotte", "Langevoort", "Lankle", "Lansink"
      , "Lathrope", "Latier", "Le Grand", "Le Marec", "Leene", "Leguit",
      "Lelijveld", "Lemmens", "Lensen", "Lether", "Levesque",
      "Lieshout", "Ligtvoet", "Lijn", "Lind", "Linschoten", "Lips",
      "Loep", "Lommert", "Lonen", "Loreal", "Lorreijn", "Louws",
      "Luboch", "Lucas", "Luitgardis van Neustriu00eb", "Luster",
      "Lutterveld", "Maas", "Maas", "Maaswinkel", "Mahieu", "Mallien",
      "Mangel", "Manne", "Mansveld", "Mansvelt", "Marceron", "Marchal",
      "Marchand", "Martel", "Martens", "Martens", "Massa", "Mater",
      "Mathieu", "Mathol", "Mathurin", "Matthews", "Meeres", "Meeusen",
      "Meijer", "Meijer", "Meis", "Melet", "Mens", "Mercks", "Merckx",
      "Merkx", "Meyer", "Meyer", "Michiels", "Michielsen", "Middelkoop",
      "Mijsberg", "Miltenburg", "Miner", "Moenen", "Moensendijk",
      "Moet", "Mol", "Mol", "Molegraaf", "Molen", "Molenaar", "Momberg",
      "Mosley", "Mudden", "Muijs", "Mulder", "Mulder", "Mulders",
      "Muller", "Nedermeijer", "Nek", "Neuteboom", "Neuzerling",
      "Niermann", "Nieuwstraten", "Nihoe", "Nijman", "Nollee",
      "Noordijk", "Oda", "Oemencs", "Oennen", "Olthof", "Olykan", "Ooms"
      , "Oosterhek", "Oosterhout", "Oostveen", "Opmans", "Osterhoudt",
      "Otte", "Otto", "Oude Heer", "Ouwel", "Ouwerkerk", "Overdijk",
      "Overeem", "Oversteeg", "Paillet", "Palman", "Pasman",
      "Passchiers", "Pastoors", "Pauwels", "Peeters", "Perck", "Perkins"
      , "Peronne", "Perrono", "Persijn", "Peters", "Peterse",
      "Phillipsen", "Pierson", "Pieters", "Pieters van der Maes",
      "Pison", "Poncelet", "Ponci", "Pons", "Post", "Post", "Postma",
      "Potters", "Pratt", "Prins", "Prinsen", "Puig", "Rackham",
      "Rademaker", "Ramaker", "Recer", "Recers", "Rehorst", "Reijers",
      "Reimes", "Rek", "Remmers", "Ridder", "Riem", "Rietveld",
      "Rijcken", "Rijks", "Rijn", "Rijntjes", "Rippey", "Risma",
      "Robbrechts Bruijne", "Roessink", "Romijn", "Roodesteijn", "Room",
      "Roose", "Roosenboom", "Rotteveel", "Roukes", "Rousselet",
      "Rouwenhorst", "Rouwhorst", "Rubben", "Ruijs", "Rutten", "Salet",
      "Sam", "Sanders", "Sanders", "Sarneel", "Sas", "Saxo", "Scardino",
      "Schagen", "Schakelaar", "Scharroo", "Schatteleijn", "Scheer",
      "Scheffers", "Schellekens", "Schelvis", "Schenk", "Schenkel",
      "Scherms", "Schiffer", "Schilt", "Schipper", "Schokman",
      "Scholten", "Scholten", "Schotte", "Schouten", "Schrant", "Schrik"
      , "Schroeff", "Schulten", "Schuurmans", "Schuylenborch",
      "Schwartsbach", "Scuylenborchs", "Segerszoen", "Serra", "Sestig",
      "Shupe", "Simonis", "Simons", "Sire", "Sitters", "Slaetsdochter",
      "Slagmolen", "Slingerland", "Smeets", "Smit", "Smit", "Smith",
      "Smits", "Smits", "Soos", "Spaan", "Spanhaak", "Speijer", "Spier",
      "Spies", "Spiker", "Spreeuw", "Sprong", "Spruit", "Spruyt",
      "Stamrood", "Stange", "Steenbakkers", "Steenbeek", "Steinmeiern",
      "Sterkman", "Stettyn", "Stichter", "Stinis", "Stoffel",
      "Stoffelsz", "Stook", "Strijker", "Strik", "Stuivenberg",
      "Suijker", "Symons", "Takkelenburg", "Tammerijn", "Tamsma",
      "Terry", "Teunissen", "Texier", "Thatcher", "The Elder", "Thomas",
      "Thout", "Tielemans", "Tillmanno", "Timmerman", "Timmermans",
      "Timmermans", "Tins", "Tirie", "Totwiller", "Tuithof",
      "Uit de Willigen", "Uittenbosch", "Ulrich", "Unruoch Hunerik", "Uphaus",
      "Uphuis", "Uphus", "VI", "Vaessen", "Vallenduuk", "Van Bragt",
      "Vandenbergh", "Vastenhouw", "Veenendaal", "Veenstra", "Vegt",
      "Velderman", "Veltman", "Verbeeck", "Verbeek", "Verbeek",
      "Verboom", "Verbruggen", "Verda", "Vergeer", "Verhaar", "Verhagen"
      , "Verharen", "Verheij", "Verheuvel", "Verhoeven", "Verhoeven",
      "Verkade", "Vermeulen", "Vermeulen", "Verschuere", "Verschut",
      "Versluijs", "Vertoor", "Vertooren", "Vervoort", "Verwoert",
      "Vial", "Vierdag", "Vignon", "Vink", "Visser", "Volcke",
      "Voortman", "Vos", "Vos", "Vrancken", "Waardeloo", "Wagenvoort",
      "Walsteijn", "Walter", "Waltrade Walderade", "Weeldenburg",
      "Weerdenburg", "Weijland", "Weijters", "Welf", "Wendt", "Wensen",
      "Werdes", "Werl-Arnsberg, van", "West-Franciu00eb, van",
      "Westerbeek", "Westerburg", "Westermann", "Wever", "Weyland",
      "Weylant", "Wigman", "Wijland", "Wilcken", "Wildschut", "Willems",
      "Willems", "Willems van Lier", "Willemsen", "Willemsen",
      "Wilmont", "Wilson", "Winnrich", "Winters", "Wipstrik", "Wolffel",
      "Wolfsdr", "Wolfswinkel", "Wolters", "Wolters", "Wolzak",
      "Wooning", "Woudenberg", "Wouters", "Wouters van Eijndhoven",
      "Woutersz", "Wright", "Wunderink", "Wutke", "Zaal", "Zeemans",
      "Zeldenrust", "Zevenboom", "Zijlemans", "Zijlmans", "Zuidweg",
      "Zuijdveld", "Zwart", "Zwijsen", "d' Heripon", "de Backer",
      "de Beer", "de Bock", "de Boer", "de Boer", "de Bont", "de Bruijn",
      "de Bruijn", "de Bruin", "de Bruin", "de Bruyn", "de Graaf",
      "de Graaf", "de Gratie", "de Groot", "de Groot", "de Grote",
      "de Gruijl", "de Gruijter", "de Gruil", "de Grunt", "de Gruson",
      "de Haan", "de Haas", "de Heer", "de Hoog", "de Hoogh", "de Jager",
      "de Jode Vastraedsd", "de Jong", "de Jong", "de Jonge", "de Kale",
      "de Keijser", "de Keijzer", "de Kok", "de Koning", "de Koning",
      "de Korte", "de Lange", "de Leeuw", "de Man", "de Marduras",
      "de Mol", "de Nijs", "de Pauw", "de Plantard", "de Reede", "de Roo",
      "de Roos", "de Ruiter", "de Smit", "de Strigter", "de Swart",
      "de Vos", "de Vries", "de Vries", "de Vroege", "de Vrome", "de Werd",
      "de Wit", "de Wit", "de la Fleche", "den Buytelaar", "den Haag",
      "den Teuling", "der Kijnder", "die Bont", "die Pelser",
      "die Witte", "le Briel", "le Floch", "le Gallen", "le Guellec",
      "le Gulcher", "le Luc", "le Matelot", "ter Waarbeek", "van 't Erve",
      "van 't Houteveen", "van 't Riet", "van 't Wel", "van Alenburg",
      "van Allemaniu00eb", "van Amstel", "van Arkel", "van Arnsberg",
      "van Asten", "van Baalen", "van Beaumont", "van Beeck",
      "van Beeck Beeckmans", "van Beek", "van Beek", "van Beieren",
      "van Bentheim", "van Bergen", "van Berkel", "van Berkum",
      "van Bernicia", "van Boulogne", "van Boven", "van Bovene",
      "van Bovenen", "van Brenen", "van Breugel", "van Breukeleveen",
      "van Breukelveen", "van Bruchem", "van Brunswijk", "van Bunschoten",
      "van Buuren", "van Clootwijck", "van Cuijck", "van Daal",
      "van Dagsburg", "van Dalem", "van Dam", "van Dam", "van Dijk",
      "van Dijk", "van Dillen", "van Dokkum", "van Dommelen", "van Dongen",
      "van Dongen", "van Dooren", "van Doorn", "van Drenthe",
      "van Duivenvoorde", "van Duvenvoirde", "van Duyvenvoorde", "van Eck",
      "van Egisheim", "van Embden", "van Emmelen", "van Engeland",
      "van Engelen", "van Enschot", "van Es", "van Este", "van Evelingen",
      "van Formbach", "van Gastel", "van Geenen", "van Geest",
      "van Geffen", "van Gelder", "van Gemert", "van Gent", "van Ghoerle",
      "van Gils", "van Ginkel", "van Ginneke", "van Goerle", "van Gorp",
      "van Grinsven", "van Grondelle", "van Haarlem", "van Haeften",
      "van Hagen", "van Ham", "van Hamaland", "van Haspengouw",
      "van Haspengouw Hesbaye", "van Hemert", "van Henegouwen", "van Herstal"
      , "van Heusden", "van Hoevel en van Zwindrecht", "van Holland",
      "van Hostaden", "van Hulten", "van Jumiu00e8ge", "van Kasteelen",
      "van Kempen", "van Klaarwater", "van Kuijc",
      "van Kuijc van Malsen", "van Kusen", "van Laar", "van Laarhoven", "van Landen",
      "van Laon", "van Leeuwen", "van Leeuwen", "van Leuven",
      "van Liendert", "van Limburg", "van Loon", "van Loon", "van Lucel",
      "van Luin", "van Luinenburg", "van Luxemburg", "van Luyssel",
      "van Maaren", "van Maasgouw", "van Mare", "van Metz", "van Mil",
      "van Mispelen", "van Mook", "van Munster", "van Nederlotharingen",
      "van Nes", "van Nimwegen", "van Noordeloos", "van Noort",
      "van Northeim", "van Nus", "van Ochten", "van Oirschot", "van Olst",
      "van Ommeren", "van Ooste", "van Oosten", "van Oostendorp",
      "van Ooyen", "van Opper-Lotharingen", "van Orleans", "van Oudewater",
      "van Parijs", "van Poppel", "van Praagh", "van Rheineck",
      "van Riet", "van Rijnsbergen", "van Rijthoven", "van Roijen",
      "van Rooij", "van Rossum", "van Saksen", "van Salm", "van Salmen",
      "van Santen", "van Schevinghuizen", "van Schweinfurt", "van Soest"
      , "van Spreeuwel", "van Spreuwel", "van Straaten", "van Stralen",
      "van Suinvorde", "van Susa", "van Tours", "van Tuijl", "van Veen",
      "van Velthoven", "van Velzen", "van Venrooy", "van Verdun",
      "van Vermandois", "van Vlaanderen", "van Vliet", "van Voorhout",
      "van Voorst", "van Waas", "van Wallaert", "van Wassenaar", "van Wel",
      "van Wessex", "van Westfalen", "van Wickerode", "van Wijk",
      "van Wijland", "van Zwaben", "van de Berg", "van de Biesenbos",
      "van de Biezenbos", "van de Brink", "van de Coterlet", "van de Darnau",
      "van de Eerenbeemt", "van de Elzas", "van de Greef",
      "van de Klashorst", "van de Kooij", "van de Leemput", "van de Noordmark",
      "van de Pavert", "van de Plas", "van de Pol", "van de Veen",
      "van de Velde", "van de Velden", "van de Ven", "van de Ven",
      "van de Wal", "van de Water", "van de Weterink", "van de Wiel",
      "van den Assem", "van den Berg", "van den Berg", "van den Bergh",
      "van den Bosch", "van den Brand", "van den Brink", "van den Brink",
      "van den Broek", "van den Broek", "van den Corput",
      "van den Eerenbeemt", "van den Eijssel", "van den Henst", "van den Heuvel",
      "van den Hoek", "van den Nieuwenhuijsen", "van den Nuwenhijsen",
      "van den Nuwenhuijzen", "van den Nuwenhuysen",
      "van den Nyeuwenhuysen", "van den Oever", "van den Pol", "van den Velde",
      "van den Velden", "van den Wittenboer", "van der Avoirt",
      "van der Berg", "van der Brink", "van der Flaas", "van der Heiden",
      "van der Heijden", "van der Heijden", "van der Heyden",
      "van der Hoeven", "van der Horst", "van der Horst", "van der Kaay",
      "van der Kint", "van der Klein", "van der Klijn", "van der Laan",
      "van der Laar", "van der Laarse", "van der Lede", "van der Leek",
      "van der Linden", "van der Linden", "van der Loo", "van der Maath",
      "van der Maes", "van der Mast", "van der Meer", "van der Meulen",
      "van der Noot", "van der Plas", "van der Ploeg", "van der Pluijm",
      "van der Pol", "van der Pouw", "van der Sande", "van der Schuijt"
      , "van der Sloot", "van der Smeede", "van der Spaendonc",
      "van der Spaendonck", "van der Stael", "van der Stael de Jonge",
      "van der Steen", "van der Strigt", "van der Veen", "van der Veiver",
      "van der Velde", "van der Velden", "van der Ven", "van der Wal",
      "van der Zijl", "van het Heerenveen"
    )
  )
)

# company ----------------------------------------------
company_nl_NL = R6Class(
  "company_nl_NL",
  inherit = company_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_nl_NL$new())$.__enclos_env__$private$first_names,
    first_name = (person_nl_NL$new())$first_name,

    last_names = (person_nl_NL$new())$.__enclos_env__$private$last_names,
    last_name = (person_nl_NL$new())$last_name,

    formats = c(
      '{last_name} {company_suffix}',
      '{last_name} & {last_name}',
      '{company_prefix} {last_name}',
      '{large_company}'),

    company_prefixes = c('Stichting', 'Koninklijke', 'Royal'),

    company_suffixes = c('BV', 'NV', 'Groep'),

    # Source: https://www.mt.nl/management/reputatie/mt-500-2018-de-lijst/559930
    large_companies = c(
      "Shell", "Coolblue", "ASML", "Ahold", "Tata Steel", "KLM",
      "Bol.com", "BP Nederland", "De Efteling", "Eneco", "De Persgroep"
      , "ING", "Royal HaskoningDHV", "Randstad", "Google", "Ikea",
      "Rockwool", "BAM", "Achmea", "Damen Shipyard", "ABN Amro",
      "Remeha Group", "TenneT", "Coca-Cola", "Van Leeuwen Buizen",
      "Wavin", "Rabobank", "AkzoNobel", "Arcadis", "AFAS", "Cisco",
      "DAF Trucks", "DHL", "Hanos", "Boon Edam", "BMW Nederland",
      "The Greenery", "Dutch Flower Group", "Koninklijke Mosa", "Yacht",
      "Rituals", "Microsoft", "Esso", "3W Vastgoed", "Deloitte",
      "Corio", "Voortman Steel Group", "Agrifirm", "Makro Nederland",
      "Nederlandse Publieke Omroep", "De Alliantie", "Heijmans",
      "McDonalds", "ANWB", "Mediamarkt", "Kruidvat",
      "Van Merksteijn Steel", "Dura Vermeer", "Alliander", "Unilever", "Enexis",
      "Berenschot", "Jumbo", "Technische Unie",
      "Havenbedrijf Rotterdam", "Ballast Nedam", "RTL Nederland", "Talpa Media",
      "Blauwhoed Vastgoed", "DSM", "Ymere", "Witteveen+Bos", "NS",
      "Action", "FloraHolland", "Heineken", "Nuon", "EY", "Dow Benelux"
      , "Bavaria", "Schiphol", "Holland Casino", "Binck bank", "BDO",
      "HEMA", "Alphabet Nederland", "Croon Elektrotechniek",
      "ASR Vastgoed ontwikkeling", "PwC", "Mammoet", "KEMA", "IBM",
      "A.S. Watson", "KPMG", "VodafoneZiggo", "YoungCapital", "Triodos Bank",
      "Aviko", "AgruniekRijnvallei", "Heerema", "Accenture", "Aegon",
      "NXP", "Breman Installatiegroep", "Movares Groep", "Q-Park",
      "FleuraMetz", "Sanoma", "Bakker Logistiek", "VDL Group", "Bayer",
      "Boskalis", "Nutreco", "Dell", "Brunel", "Exact", "Manpower",
      "Essent", "Canon", "ONVZ Zorgverzekeraar",
      "Telegraaf Media Group", "Nationale Nederlanden", "Andus Group",
      "Den Braven Group", "ADP", "ASR", "ArboNed", "Plieger", "De Heus Diervoeders"
      , "USG People", "Bidvest Deli XL", "Apollo Vredestein",
      "Tempo-Team", "Trespa", "Janssen Biologics", "Starbucks",
      "PostNL", "Vanderlande", "FrieslandCampina", "Constellium",
      "Huisman", "Abbott", "Koninklijke Boom Uitgevers",
      "Bosch Rexroth", "BASF", "Audax", "VolkerWessels", "Hunkem\u00f6ller",
      "Athlon Car Lease", "DSW Zorgverzekeraar", "Mars",
      "De Brauw Blackstone Westbroek", "NDC Mediagroep", "Bluewater", "Stedin",
      "Feenstra", "Wuppermann Staal Nederland", "Kramp", "SABIC",
      "Iv-Groep", "Bejo Zaden", "Wolters Kluwer", "Nyrstar holding",
      "Adecco", "Tauw", "Robeco", "Eriks", "Allianz Nederland Groep",
      "Driessen", "Burger King", "Lekkerland", "Van Lanschot",
      "Brocacef", "Bureau Veritas", "Relx", "Path\u00e9 Bioscopen",
      "Bosal", "Ardagh Group", "Maandag", "Inalfa", "Atradius",
      "Capgemini", "Greenchoice", "Q8 (Kuwait Petroleum Europe)",
      "ASM International", "Van der Valk", "Delta Lloyd", "GlaxoSmithKline",
      "ABB", "Fabory, a Grainger company",
      "Veen Bosch & Keuning Uitgeversgroep", "CZ", "Plus",
      "RET Rotterdam", "Loyens & Loeff",
      "Holland Trading", "Archer Daniels Midland Nederland",
      "Ten Brinke", "NAM", "DAS", "Samsung Electronics Benelux",
      "Koopman International", "TUI", "Lannoo Meulenhoff", "AC Restaurants",
      "Stage Entertainment", "Acer", "HDI Global SE", "Detailresult",
      "Nestle", "GVB Amsterdam", "Dekamarkt", "Dirk", "MSD", "Arriva",
      "Baker Tilly Berk", "SBM Offshore", "TomTom", "Fujifilm", "B&S",
      "BCC", "Gasunie", "Oracle Nederland", "Astellas Pharma", "SKF",
      "Woningstichting Eigen Haard", "Rijk Zwaan", "Chubb", "Fugro",
      "Total", "Rochdale", "ASVB", "Atos", "Acomo", "KPN",
      "Van Drie Group", "Olympia uitzendbureau", "Bacardi Nederland",
      "JMW Horeca Uitzendbureau", "Warner Bros/Eyeworks",
      "Aalberts Industries", "SNS Bank", "Amtrada Holding", "VGZ", "Grolsch",
      "Office Depot", "De Rijke Group", "Bovemij Verzekeringsgroep",
      "Coop Nederland", "Eaton Industries", "ASN", "Yara Sluiskil",
      "HSF Logistics", "Fokker", "Deutsche Bank", "Sweco",
      "Univ\u00e9 Groep", "Koninklijke Wagenborg", "Strukton", "Conclusion",
      "Philips", "In Person", "Fluor", "Vroegop-Windig", "ArboUnie",
      "Centraal Boekhuis", "Siemens", "Connexxion", "Fujitsu",
      "Consolid", "AVR Afvalverwerking", "Brabant Alucast", "Centric",
      "Havensteder", "Novartis", "Booking.com", "Menzis",
      "Frankort & Koning Groep", "Jan de Rijk", "Brand Loyalty Group",
      "Ohra Verzekeringen", "Terberg Group", "Cloetta", "Holland & Barrett",
      "Enza Zaden", "VION", "Woonzorg Nederland", "T-Mobile", "Crucell"
      , "NautaDutilh", "BNP Paribas", "NIBC Bank", "VastNed",
      "CCV Holland", "IHC Merwede", "Neways", "NSI N.V.", "Deen", "Accor",
      "HTM", "ITM Group", "Ordina", "D\u00fcmmen Orange", "Optiver",
      "Zara", "L\'Oreal Nederland B.V.", "Vinci Energies",
      "Suit Supply Topco", "Sita", "Vos Logistics", "Altran", "St. Clair",
      "BESI", "Fiat Chrysler Automobiles", "UPS", "Jacobs", "Emt\u00e9"
      , "TBI", "De Bijenkorf", "Aldi Nederland", "Van Wijnen", "Vitens"
      , "De Goudse Verzekeringen", "SBS Broadcasting", "Sandd", "Omron"
      , "Sogeti", "Alfa Accountants & Adviseurs", "Harvey Nash",
      "Stork", "Glencore Grain", "Meijburg & Co", "Honeywell", "Meyn",
      "Ericsson Telecommunicatie", "Hurks", "Mitsubishi", "GGN",
      "CGI Nederland", "Staples Nederland", "Denkavit International",
      "Ecorys", "Rexel Nederland", "A. Hakpark", "DuPont Nederland",
      "CBRE Group", "Bolsius", "Marel", "Metro",
      "Flynth Adviseurs en Accountants", "Kropman Installatietechniek", "Kuijpers",
      "Medtronic", "Cefetra", "Simon Loos", "Citadel Enterprises",
      "Intergamma", "Ceva Logistics", "Beter Bed", "Subway", "Gamma",
      "Karwei", "Varo Energy", "APM Terminals", "Center Parcs",
      "Brenntag Nederland", "NFI", "Hoogvliet", "Van Gansewinkel",
      "Nedap", "Blokker", "Perfetti Van Melle", "Vestia",
      "Kuehne + Nagel Logistics", "Rensa Group", "NTS Group",
      "Joh. Mourik & Co. Holding", "Mercedes-Benz", "DIT Personeel",
      "Verkade", "Hametha",
      "Vopak", "IFF", "Pearle", "Mainfreight", "De Jong & Laan", "DSV"
      , "P4People", "Mazars", "Cargill", "Ten Brinke Groep",
      "Alewijnse", "Agio Cigars", "Peter Appel Transport", "Syngenta",
      "Avery Dennison", "Accon AVM", "Vitol", "Vermaat Groep", "BMC",
      "Alcatel-Lucent", "Maxeda DIY", "Equens", "Van Gelder Groep",
      "Emerson Electric Nederland", "Bakkersland", "Specsavers", "E.On"
      , "Landal Greenparks", "IMC Trading", "Barentz Group", "Epson",
      "Raet", "Van Oord", "Thomas Cook Nederland", "SDU uitgevers",
      "Nedschroef", "Linde Gas", "Ewals Cargo Care",
      "Theodoor Gilissen", "TMF Group", "Cornelis Vrolijk",
      "Jan Linders Supermarkten", "SIF group", "BT Nederland", "Kinepolis",
      "Pink Elephant", "General Motors Nederland", "Carlson Wagonlit",
      "Bruna", "Docdata", "Schenk Tanktransport", "WPG", "Peak-IT",
      "Martinair", "Reesink", "Elopak Nederland", "Fagron N.V.",
      "OVG Groep", "Ford Nederland", "Multi Corporation", "Simac", "Primark"
      , "Tech Data Nederland", "Vleesgroothandel Zandbergen",
      "Raben Group", "Farm Frites", "Lib\u00e9ma", "Caldic", "Portaal",
      "Syntus", "Jacobs DE", "Stena Line", "The Phone House",
      "Interfood Group", "Thales", "Teva Pharmaceuticals",
      "RFS Holland", "Aebi Schmidt Nederland",
      "Rockwell Automation Nederland", "Engie Services", "Hendrix Genetics", "Qbuzz",
      "Unica", "2SistersFoodGroup", "Ziut", "Munckhof Groep",
      "Spar Holding", "Samskip", "Continental Bakeries", "Sligro", "Merck",
      "Foot Locker Europe", "Unit4", "PepsiCo", "Sulzer", "Tebodin",
      "Value8", "Boels", "DKG Groep", "Bruynzeel Keukens",
      "Janssen de Jong Groep", "ProRail", "Solid Professionals", "Hermes Partners"
    )
  ),
  public = list(
    large_company = function(){
      return(private$random_element(private$large_companies))
    },

    company_prefix = function(){
      return(private$random_element(private$company_prefixes))
    }
  )
)

# address ----------------------------------------
address_nl_NL = R6Class(
  "address_nl_NL",
  inherit = address_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_nl_NL$new())$.__enclos_env__$private$first_names,
    last_names = (person_nl_NL$new())$.__enclos_env__$private$last_names,
    first_name = (person_nl_NL$new())$first_name,
    last_name = (person_nl_NL$new())$last_name,

    building_number_formats = c('#', '##', '###', '#', '##', '###'),

    street_suffixes = c(
      'baan', 'boulevard', 'dreef', 'hof', 'laan', 'pad',
      'ring', 'singel', 'steeg', 'straat', 'weg'),

    # the 4 digit numerical part of Dutch postcodes is between 1000 and 9999;
    # see http://nl.wikipedia.org/wiki/Postcode#Postcodes_in_Nederland
    postcode_formats = c('%###??', '%### ??'),

    city_formats = '{city}',

    # countries are from http://nl.wikipedia.org/wiki/ISO_3166-1
    countries = c(
      "Afghanistan", "Albani\u00eb", "Algerije", "Amerikaans-Samoa",
      "Amerikaanse Maagdeneilanden", "Andorra", "Angola", "Anguilla",
      "Antarctica", "Antigua en Barbuda", "Argentini\u00eb",
      "Armeni\u00eb", "Aruba", "Australi\u00eb", "Azerbeidzjan",
      "Bahama\'s", "Bahrein", "Bangladesh", "Barbados", "Belgi\u00eb",
      "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
      "Bonaire, Sint Eustatius en Saba", "Bosni\u00eb en Herzegovina", "Botswana",
      "Bouveteiland", "Brazili\u00eb",
      "Brits Indische Oceaanterritorium", "Britse Maagdeneilanden", "Brunei",
      "Bulgarije", "Burkina Faso", "Burundi", "Cambodja", "Canada",
      "Centraal-Afrikaanse Republiek", "Chili", "China",
      "Christmaseiland", "Cocoseilanden", "Colombia", "Comoren",
      "Congo-Brazzaville", "Congo-Kinshasa", "Cookeilanden",
      "Costa Rica", "Cuba", "Cura\u00e7ao", "Cyprus", "Denemarken", "Djibouti",
      "Dominica", "Dominicaanse Republiek", "Duitsland", "Ecuador",
      "Egypte", "El Salvador", "Equatoriaal-Guinea", "Eritrea",
      "Estland", "Ethiopi\u00eb", "Faer\u00f6er", "Falklandeilanden",
      "Fiji", "Filipijnen", "Finland", "Frankrijk", "Frans-Guyana",
      "Frans-Polynesi\u00eb", "Franse Zuidelijke en Antarctische Gebieden",
      "Gabon", "Gambia", "Georgi\u00eb", "Ghana", "Gibraltar"
      , "Grenada", "Griekenland", "Groenland", "Guadeloupe", "Guam",
      "Guatemala", "Guernsey", "Guinee", "Guinee-Bissau", "Guyana",
      "Ha\u00efti", "Heard en McDonaldeilanden", "Honduras", "Hongarije"
      , "Hongkong", "IJsland", "Ierland", "India", "Indonesi\u00eb",
      "Irak", "Iran", "Isra\u00ebl", "Itali\u00eb", "Ivoorkust",
      "Jamaica", "Japan", "Jemen", "Jersey", "Jordani\u00eb",
      "Kaaimaneilanden", "Kaapverdi\u00eb", "Kameroen", "Kazachstan",
      "Kenia", "Kirgizi\u00eb", "Kiribati",
      "Kleine Pacifische eilanden van de Verenigde Staten", "Koeweit",
      "Kroati\u00eb", "Laos",
      "Lesotho", "Letland", "Libanon", "Liberia", "Libi\u00eb",
      "Liechtenstein", "Litouwen", "Luxemburg", "Macau",
      "Macedoni\u00eb", "Madagaskar", "Malawi", "Maldiven",
      "Maleisi\u00eb", "Mali", "Malta", "Man", "Marokko",
      "Marshalleilanden", "Martinique", "Mauritani\u00eb", "Mauritius",
      "Mayotte", "Mexico", "Micronesia", "Moldavi\u00eb", "Monaco",
      "Mongoli\u00eb", "Montenegro", "Montserrat", "Mozambique",
      "Myanmar", "Namibi\u00eb", "Nauru", "Nederland", "Nepal",
      "Nicaragua", "Nieuw-Caledoni\u00eb", "Nieuw-Zeeland", "Niger",
      "Nigeria", "Niue", "Noord-Korea", "Noordelijke Marianen",
      "Noorwegen", "Norfolk", "Oeganda", "Oekra\u00efne", "Oezbekistan",
      "Oman", "Oost-Timor", "Oostenrijk", "Pakistan", "Palau",
      "Palestina", "Panama", "Papoea-Nieuw-Guinea", "Paraguay", "Peru",
      "Pitcairneilanden", "Polen", "Portugal", "Puerto Rico", "Qatar",
      "Roemeni\u00eb", "Rusland", "Rwanda", "R\u00e9union",
      "Saint Kitts en Nevis", "Saint Lucia", "Saint Vincent en de Grenadines",
      "Saint-Barth\u00e9lemy", "Saint-Pierre en Miquelon",
      "Salomonseilanden", "Samoa", "San Marino",
      "Sao Tom\u00e9 en Principe", "Saoedi-Arabi\u00eb", "Senegal", "Servi\u00eb",
      "Seychellen", "Sierra Leone", "Singapore", "Sint Maarten",
      "Sint-Helena, Ascension en Tristan da Cunha", "Sint-Maarten",
      "Sloveni\u00eb", "Slowakije", "Soedan", "Somali\u00eb", "Spanje",
      "Spitsbergen en Jan Mayen", "Sri Lanka", "Suriname", "Swaziland",
      "Syri\u00eb", "Tadzjikistan", "Taiwan", "Tanzania", "Thailand",
      "Togo", "Tokelau", "Tonga", "Trinidad en Tobago", "Tsjaad",
      "Tsjechi\u00eb", "Tunesi\u00eb", "Turkije", "Turkmenistan",
      "Turks- en Caicoseilanden", "Tuvalu", "Uruguay", "Vanuatu",
      "Vaticaanstad", "Venezuela", "Verenigd Koninkrijk",
      "Verenigde Arabische Emiraten", "Verenigde Staten", "Vietnam",
      "Wallis en Futuna", "Westelijke Sahara", "Wit-Rusland", "Zambia", "Zimbabwe",
      "Zuid-Afrika", "Zuid-Georgia en de Zuidelijke Sandwicheilanden",
      "Zuid-Korea", "Zuid-Soedan", "Zweden", "Zwitserland", "\u00c5land"
    ),

    # cities are taken from the BAG "woonplaats";
    # in this case the 8-Mar-2014 extract;
    # see http://data.nlextract.nl/bag/csv/
    cities = c(
      "\'s Gravenmoer", "\'s-Graveland", "\'s-Gravendeel",
      "\'s-Gravenhage", "\'s-Gravenpolder", "\'s-Gravenzande",
      "\'s-Heer Abtskerke", "\'s-Heer Arendskerke",
      "\'s-Heer Hendrikskinderen", "\'s-Heerenberg", "\'s-Heerenbroek",
      "\'s-Heerenhoek", "\'s-Hertogenbosch", "\'t Goy", "\'t Haantje",
      "\'t Harde", "\'t Loo Oldebroek", "\'t Veld", "\'t Waar",
      "\'t Zand", "\'t Zandt", "1e Exlo\u00ebrmond", "2e Exlo\u00ebrmond",
      "2e Valthermond", "Aadorp", "Aagtekerke", "Aalden", "Aalsmeer",
      "Aalsmeerderbrug", "Aalst", "Aalsum", "Aalten", "Aardenburg",
      "Aarlanderveen", "Aarle-Rixtel", "Aartswoud", "Abbega", "Abbekerk"
      , "Abbenbroek", "Abbenes", "Abcoude", "Achlum", "Achterveld",
      "Achthuizen", "Achtmaal", "Acquoy", "Adorp", "Aduard",
      "Aerdenhout", "Aerdt", "Afferden", "Afferden L", "Agelo",
      "Akersloot", "Akkrum", "Akmarijp", "Albergen", "Alblasserdam",
      "Alde Leie", "Aldeboarn", "Aldtsjerk", "Alem", "Alkmaar",
      "Allingawier", "Almelo", "Almen", "Almere", "Almkerk", "Alphen",
      "Alphen aan den Rijn", "Alteveer", "Alteveer gem Hoogeveen",
      "Altforst", "Ambt Delden", "Ameide", "Amen", "America",
      "Amerongen", "Amersfoort", "Ammerstol", "Ammerzoden", "Amstelhoek"
      , "Amstelveen", "Amstenrade", "Amsterdam",
      "Amsterdam-Duivendrecht", "Andel", "Andelst", "Anderen", "Andijk",
      "Ane", "Anerveen", "Anevelde", "Angeren", "Angerlo", "Anjum",
      "Ankeveen", "Anloo", "Anna Paulowna", "Annen",
      "Annerveenschekanaal", "Ansen", "Apeldoorn", "Appelscha",
      "Appeltern", "Appingedam", "Arcen", "Arkel", "Arnemuiden",
      "Arnhem", "Arri\u00ebn", "Arum", "Asch", "Asperen", "Assen",
      "Assendelft", "Asten", "Augsbuurt", "Augustinusga", "Austerlitz",
      "Avenhorn", "Axel", "Azewijn", "Baaiduinen", "Baaium", "Baak",
      "Baambrugge", "Baard", "Baarland", "Baarle-Nassau", "Baarlo",
      "Baarn", "Baars", "Babberich", "Babyloni\u00ebnbroek",
      "Bad Nieuweschans", "Badhoevedorp", "Baexem", "Baflo", "Bakel",
      "Bakhuizen", "Bakkeveen", "Balgoij", "Balinge", "Balk", "Balkbrug"
      , "Balloo", "Ballo\u00ebrveld", "Ballum", "Baneheide", "Banholt",
      "Bant", "Bantega", "Barchem", "Barendrecht", "Barger-Compascuum",
      "Barneveld", "Barsingerhorn", "Basse", "Batenburg", "Bathmen",
      "Bavel", "Bavel AC", "Bears", "Bedum", "Beegden", "Beek",
      "Beek en Donk", "Beekbergen", "Beemte Broekland", "Beers NB", "Beerta",
      "Beerze", "Beerzerveld", "Beesd", "Beesel", "Beets",
      "Beetsterzwaag", "Beilen", "Beinsdorp", "Belfeld", "Bellingwolde",
      "Belt-Schutsloot", "Beltrum", "Bemelen", "Bemmel",
      "Beneden-Leeuwen", "Bennebroek", "Bennekom", "Benneveld",
      "Benningbroek", "Benschop", "Bentelo", "Benthuizen", "Bentveld",
      "Berg en Dal", "Berg en Terblijt", "Bergambacht", "Bergeijk",
      "Bergen (NH)", "Bergen L", "Bergen aan Zee", "Bergen op Zoom",
      "Bergentheim", "Bergharen", "Berghem", "Bergschenhoek", "Beringe",
      "Berkel en Rodenrijs", "Berkel-Enschot", "Berkenwoude",
      "Berkhout", "Berlicum", "Berltsum", "Bern", "Best", "Beugen",
      "Beuningen", "Beuningen Gld", "Beusichem", "Beutenaken",
      "Beverwijk", "Biddinghuizen", "Bierum", "Biervliet",
      "Biest-Houtakker", "Biezenmortel", "Biggekerke", "Bilthoven",
      "Bingelrade", "Bitgum", "Bitgummole", "Bladel", "Blankenham",
      "Blaricum", "Blauwestad", "Blauwhuis", "Bleiswijk", "Blesdijke",
      "Bleskensgraaf ca", "Blessum", "Blije", "Blijham", "Blitterswijck"
      , "Bloemendaal", "Blokker", "Blokzijl", "Boazum", "Bocholtz",
      "Bodegraven", "Boekel", "Boelenslaan", "Boer", "Boerakker",
      "Boesingheliede", "Boijl", "Boksum", "Bolsward", "Bontebok",
      "Boornbergum", "Boornzwaag", "Borculo", "Borger",
      "Borgercompagnie", "Borgsweer", "Born", "Borne", "Bornerbroek",
      "Bornwird", "Borssele", "Bosch en Duin", "Boschoord", "Boskoop",
      "Bosschenhoofd", "Botlek Rotterdam", "Bourtange", "Boven-Leeuwen",
      "Bovenkarspel", "Bovensmilde", "Boxmeer", "Boxtel", "Braamt",
      "Brakel", "Brandwijk", "Brantgum", "Breda", "Bredevoort",
      "Breedenbroek", "Breezand", "Breezanddijk", "Breskens",
      "Breukelen", "Breukeleveen", "Brielle", "Briltil", "Britsum",
      "Britswert", "Broek", "Broek in Waterland", "Broek op Langedijk",
      "Broekhuizen", "Broekhuizenvorst", "Broekland", "Broeksterwald",
      "Bronkhorst", "Bronneger", "Bronnegerveen", "Brouwershaven",
      "Bruchem", "Brucht", "Bruchterveld", "Bruinehaar", "Bruinisse",
      "Brummen", "Brunssum", "Bruntinge", "Buchten", "Budel",
      "Budel-Dorplein", "Budel-Schoot", "Buggenum", "Buinen",
      "Buinerveen", "Buitenkaag", "Buitenpost", "Bunde", "Bunne",
      "Bunnik", "Bunschoten-Spakenburg", "Burdaard", "Buren",
      "Burgerbrug", "Burgerveen", "Burgh-Haamstede", "Burgum",
      "Burgwerd", "Burum", "Bussum", "Buurmalsen", "Cadier en Keer",
      "Cadzand", "Callantsoog", "Capelle aan den IJssel", "Castelre",
      "Castenray", "Casteren", "Castricum", "Chaam", "Clinge",
      "Coevorden", "Colijnsplaat", "Collendoorn", "Colmschate",
      "Cornwerd", "Cothen", "Creil", "Cromvoirt", "Cruquius", "Cuijk",
      "Culemborg", "Daarle", "Daarlerveen", "Dalem", "Dalen",
      "Dalerpeel", "Dalerveen", "Dalfsen", "Dalmsholte", "Damwald",
      "Darp", "De Bilt", "De Blesse", "De Bult", "De Cocksdorp",
      "De Falom", "De Glind", "De Goorn", "De Groeve", "De Heen",
      "De Heurne", "De Hoeve", "De Kiel", "De Klomp", "De Knipe", "De Koog",
      "De Krim", "De Kwakel", "De Lier", "De Meern", "De Moer",
      "De Mortel", "De Pol", "De Punt", "De Rijp", "De Rips",
      "De Schiphorst", "De Steeg", "De Tike", "De Veenhoop", "De Waal",
      "De Weere", "De Westereen", "De Wilgen", "De Wilp", "De Zilk",
      "Dearsum", "Dedemsvaart", "Dedgum", "Deelen", "Deest", "Deil",
      "Deinum", "Delden", "Delfgauw", "Delfstrahuizen", "Delft",
      "Delfzijl", "Delwijnen", "Demen", "Den Andel", "Den Bommel",
      "Den Burg", "Den Dolder", "Den Dungen", "Den Ham", "Den Helder",
      "Den Hoorn", "Den Horn", "Den Hout", "Den Ilp", "Den Oever",
      "Den Velde", "Denekamp", "Deurne", "Deurningen", "Deursen-Dennenburg",
      "Deurze", "Deventer", "Didam", "Dieden", "Diemen", "Diepenheim",
      "Diepenveen", "Dieren", "Diessen", "Diever", "Dieverbrug",
      "Diffelen", "Dijken", "Dinteloord", "Dinxperlo", "Diphoorn",
      "Dirkshorn", "Dirksland", "Dodewaard", "Doenrade", "Doesburg",
      "Doetinchem", "Doeveren", "Doezum", "Dokkum", "Doldersum",
      "Domburg", "Donderen", "Dongen", "Dongjum", "Doniaga",
      "Donkerbroek", "Doorn", "Doornenburg", "Doornspijk", "Doorwerth",
      "Dordrecht", "Dorst", "Drachten", "Drachten-Azeven",
      "Drachtstercompagnie", "Dreischor", "Drempt", "Dreumel",
      "Driebergen-Rijsenburg", "Drieborg", "Driebruggen", "Driehuis NH",
      "Driehuizen", "Driel", "Driewegen", "Driezum", "Drijber",
      "Drimmelen", "Drogeham", "Drogteropslagen", "Drongelen", "Dronryp"
      , "Dronten", "Drouwen", "Drouwenermond", "Drouwenerveen", "Drunen"
      , "Druten", "Duiven", "Duivendrecht", "Duizel", "Dussen",
      "Dwingeloo", "Eagum", "Earnewald", "Easterein", "Easterlittens",
      "Eastermar", "Easterwierrum", "Echt", "Echteld", "Echten",
      "Echtenerbrug", "Eck en Wiel", "Eckelrade", "Edam", "Ede",
      "Ederveen", "Ee", "Eede", "Eefde", "Eelde", "Eelderwolde",
      "Eemdijk", "Eemnes", "Eemshaven", "Een", "Een-West", "Eenrum",
      "Eenum", "Eerbeek", "Eersel", "Ees", "Eesergroen", "Eeserveen",
      "Eesterga", "Eesveen", "Eethen", "Eext", "Eexterveen",
      "Eexterveenschekanaal", "Eexterzandvoort", "Egchel",
      "Egmond aan Zee", "Egmond aan den Hoef", "Egmond-Binnen", "Eibergen",
      "Eijsden", "Eindhoven", "Einighausen", "Ekehaar", "Elahuizen",
      "Elburg", "Eldersloo", "Eleveld", "Elim", "Elkenrade", "Ell",
      "Ellecom", "Ellemeet", "Ellertshaar", "Ellewoutsdijk", "Elp",
      "Elsendorp", "Elshout", "Elsloo", "Elspeet", "Elst", "Elst Ut",
      "Emmeloord", "Emmen", "Emmer-Compascuum", "Empe", "Emst",
      "Engwierum", "Enkhuizen", "Ens", "Enschede", "Enspijk", "Enter",
      "Enumatil", "Epe", "Epen", "Eppenhuizen", "Epse", "Erica",
      "Erichem", "Erlecom", "Erm", "Ermelo", "Erp", "Esbeek", "Esch",
      "Escharen", "Espel", "Est", "Etten", "Etten-Leur",
      "Europoort Rotterdam", "Eursinge", "Everdingen", "Evertsoord", "Ewijk",
      "Exloo", "Exlo\u00ebrveen", "Exmorra", "Eygelshoven", "Eys",
      "Ezinge", "Farmsum", "Feanwalden", "Feerwerd", "Feinsum",
      "Ferwert", "Ferwoude", "Fijnaart", "Finsterwolde", "Firdgum",
      "Fleringen", "Fluitenberg", "Fochteloo", "Follega", "Folsgare",
      "Formerum", "Foudgum", "Foxhol", "Foxwolde", "Franeker",
      "Frederiksoord", "Friens", "Frieschepalen", "Froombosch",
      "Gaanderen", "Gaast", "Gaastmeer", "Galder", "Gameren", "Gapinge",
      "Garderen", "Garmerwolde", "Garminge", "Garnwerd", "Garrelsweer",
      "Garsthuizen", "Garyp", "Gassel", "Gasselte", "Gasselternijveen",
      "Gasselternijveenschemond", "Gastel", "Gasteren", "Gauw",
      "Geelbroek", "Geerdijk", "Geersdijk", "Geertruidenberg",
      "Geervliet", "Gees", "Geesbrug", "Geesteren", "Geeuwenbrug",
      "Geffen", "Geijsteren", "Geldermalsen", "Gelderswoude", "Geldrop",
      "Geleen", "Gellicum", "Gelselaar", "Gemert", "Gemonde",
      "Genderen", "Gendringen", "Gendt", "Genemuiden", "Gennep",
      "Gerkesklooster", "Gersloot", "Geulle", "Giesbeek", "Giessen",
      "Giessenburg", "Gieten", "Gieterveen", "Giethmen", "Giethoorn",
      "Gilze", "Ginnum", "Glane", "Glimmen", "Godlinze", "Goedereede",
      "Goes", "Goingarijp", "Goirle", "Goor", "Gorinchem", "Gorredijk",
      "Gorssel", "Gouda", "Gouderak", "Goudriaan", "Goudswaard",
      "Goutum", "Go\u00ebnga", "Go\u00ebngahuizen", "Graauw",
      "Grafhorst", "Graft", "Gramsbergen", "Grashoek", "Grathem",
      "Grave", "Greonterp", "Grevenbicht", "Griendtsveen", "Grijpskerk",
      "Grijpskerke", "Groede", "Groenekan", "Groeningen", "Groenlo",
      "Groesbeek", "Groessen", "Groet", "Grolloo", "Groningen",
      "Gronsveld", "Groot-Ammers", "Grootebroek", "Grootegast",
      "Grootschermer", "Grou", "Grubbenvorst", "Gulpen", "Guttecoven",
      "Gytsjerk", "Haaften", "Haaksbergen", "Haalderen", "Haaren",
      "Haarle", "Haarlem", "Haarlemmerliede", "Haarlo", "Haarsteeg",
      "Haarzuilens", "Haastrecht", "Haelen", "Hagestein", "Haghorst",
      "Haler", "Halfweg", "Hall", "Halle", "Hallum", "Halsteren",
      "Handel", "Hank", "Hansweert", "Hantum", "Hantumeruitburen",
      "Hantumhuizen", "Hapert", "Haps", "Harbrinkhoek", "Hardenberg",
      "Harderwijk", "Hardinxveld-Giessendam", "Haren", "Haren Gn",
      "Harfsen", "Harich", "Haringhuizen", "Harkema", "Harkstede",
      "Harlingen", "Harmelen", "Harreveld", "Harskamp", "Hartwerd",
      "Haskerdijken", "Haskerhorne", "Hasselt", "Hattem",
      "Hattemerbroek", "Haule", "Haulerwijk", "Hauwert", "Havelte",
      "Havelterberg", "Hazerswoude-Dorp", "Hazerswoude-Rijndijk",
      "Hedel", "Hedikhuizen", "Hee", "Heeg", "Heel", "Heelsum",
      "Heelweg", "Heemserveen", "Heemskerk", "Heemstede", "Heenvliet",
      "Heerde", "Heerenveen", "Heerewaarden", "Heerhugowaard",
      "Heerjansdam", "Heerle", "Heerlen", "Heesbeen", "Heesch",
      "Heesselt", "Heeswijk-Dinther", "Heeten", "Heeze", "Hegebeintum",
      "Hegelsom", "Hei- en Boeicop", "Heibloem", "Heide", "Heijen",
      "Heijenrath", "Heijningen", "Heikant", "Heilig Landstichting",
      "Heiligerlee", "Heiloo", "Heinenoord", "Heinkenszand", "Heino",
      "Hekelingen", "Hekendorp", "Helden", "Helenaveen", "Hellendoorn",
      "Hellevoetsluis", "Hellouw", "Hellum", "Helmond", "Helvoirt",
      "Hem", "Hemelum", "Hemmen", "Hempens", "Hemrik",
      "Hendrik-Ido-Ambacht", "Hengelo", "Hengelo (Gld)", "Hengevelde",
      "Hengstdijk", "Hensbroek", "Herbaijum", "Herkenbosch", "Herkingen"
      , "Hernen", "Herpen", "Herpt", "Herten", "Hertme", "Herveld",
      "Herwen", "Herwijnen", "Heteren", "Heukelom", "Heukelum", "Heumen"
      , "Heusden", "Heveadorp", "Heythuysen", "Hezingen", "Hiaure",
      "Hichtum", "Hidaard", "Hierden", "Hieslum", "Hijken", "Hijum",
      "Hilaard", "Hillegom", "Hilvarenbeek", "Hilversum", "Hindeloopen",
      "Hinnaard", "Hippolytushoef", "Hitzum", "Hobrede",
      "Hoedekenskerke", "Hoek", "Hoek van Holland", "Hoenderloo",
      "Hoensbroek", "Hoenzadriel", "Hoevelaken", "Hoeven", "Hoge Hexel",
      "Hollandsche Rading", "Hollandscheveld", "Hollum", "Holsloot",
      "Holten", "Holthees", "Holtheme", "Holthone", "Holtum", "Holwerd",
      "Holwierde", "Hommerts", "Homoet", "Honselersdijk", "Hoofddorp",
      "Hoofdplaat", "Hoog Soeren", "Hoog-Keppel", "Hoogblokland",
      "Hooge Mierde", "Hooge Zwaluwe", "Hoogeloon", "Hoogenweg",
      "Hoogerheide", "Hoogersmilde", "Hoogeveen", "Hoogezand",
      "Hooghalen", "Hoogkarspel", "Hoogland", "Hooglanderveen",
      "Hoogmade", "Hoogvliet Rotterdam", "Hoogwoud", "Hoorn", "Hoornaar"
      , "Hoornsterzwaag", "Horn", "Hornhuizen", "Horssen", "Horst",
      "Houten", "Houtigehage", "Houwerzijl", "Huijbergen",
      "Huis ter Heide", "Huisduinen", "Huisseling", "Huissen", "Huizen",
      "Huizinge", "Hulsberg", "Hulsel", "Hulshorst", "Hulst", "Hulten",
      "Hummelo", "Hunsel", "Hurdegaryp", "Hurwenen", "H\u00fans",
      "IJhorst", "IJlst", "IJmuiden", "IJsselham", "IJsselmuiden",
      "IJsselstein", "IJzendijke", "IJzendoorn", "Idaerd",
      "Idsegahuizum", "Idskenhuizen", "Idzega", "Iens", "Ilpendam",
      "Indijk", "Ingber", "Ingelum", "Ingen", "It Heidenskip", "Itens",
      "Ittervoort", "Jaarsveld", "Jabeek", "Jannum", "Jellum", "Jelsum",
      "Jirnsum", "Jislum", "Jisp", "Jistrum", "Jonkerslan",
      "Jonkersvaart", "Joppe", "Jorwert", "Joure", "Jouswier", "Jubbega"
      , "Julianadorp", "Jutrijp", "Kaag", "Kaard", "Kaatsheuvel",
      "Kalenberg", "Kallenkote", "Kamerik", "Kampen", "Kamperland",
      "Kamperveen", "Kantens", "Kapel Avezaath", "Kapel-Avezaath",
      "Kapelle", "Kapellebrug", "Katlijk", "Kats", "Kattendijke",
      "Katwijk", "Katwijk NB", "Katwoude", "Kedichem", "Keent",
      "Keijenborg", "Kekerdom", "Kelpen-Oler", "Kerk Avezaath",
      "Kerk-Avezaath", "Kerkdriel", "Kerkenveld", "Kerkrade",
      "Kerkwerve", "Kerkwijk", "Kessel", "Kesteren", "Kiel-Windeweer",
      "Kilder", "Kimswerd", "Kinderdijk", "Kinnum", "Klaaswaal",
      "Klarenbeek", "Klazienaveen", "Klazienaveen-Noord",
      "Klein Zundert", "Klijndijk", "Klimmen", "Kloetinge", "Klooster Lidlum",
      "Kloosterburen", "Kloosterhaar", "Kloosterzande", "Klundert",
      "Knegsel", "Koarnjum", "Kockengen", "Koedijk", "Koekange",
      "Koewacht", "Kolderwolde", "Kolham", "Kolhorn", "Kollum",
      "Kollumerpomp", "Kollumerzwaag", "Kommerzijl", "Koningsbosch",
      "Koningslust", "Koog aan de Zaan", "Koolwijk", "Kootstertille",
      "Kootwijk", "Kootwijkerbroek", "Kornhorn", "Kornwerderzand",
      "Kortehemmen", "Kortenhoef", "Kortgene", "Koudekerk aan den Rijn",
      "Koudekerke", "Koudum", "Koufurderrige", "Krabbendijke",
      "Kraggenburg", "Kreileroord", "Krewerd", "Krimpen aan de Lek",
      "Krimpen aan den IJssel", "Kring van Dorth", "Krommenie",
      "Kronenberg", "Kropswolde", "Kruiningen", "Kruisland",
      "Kudelstaart", "Kuinre", "Kuitaart", "Kwadendamme", "Kwadijk",
      "Kwintsheul", "K\u00fbbaard", "Laag Zuthem", "Laag-Keppel",
      "Laag-Soeren", "Lage Mierde", "Lage Vuursche", "Lage Zwaluwe",
      "Lageland", "Lambertschaag", "Lamswaarde", "Landerum", "Landgraaf"
      , "Landhorst", "Landsmeer", "Langbroek", "Langedijke",
      "Langelille", "Langelo", "Langenboom", "Langerak", "Langeveen",
      "Langeweg", "Langezwaag", "Langweer", "Laren", "Lathum",
      "Lattrop-Breklenkamp", "Lauwersoog", "Lauwerzijl", "Ledeacker",
      "Leek", "Leende", "Leens", "Leerbroek", "Leerdam", "Leermens",
      "Leersum", "Leeuwarden", "Legemeer", "Leiden", "Leiderdorp",
      "Leidschendam", "Leimuiden", "Leimuiderbrug", "Lekkerkerk",
      "Lekkum", "Lellens", "Lelystad", "Lemele", "Lemelerveld",
      "Lemiers", "Lemmer", "Lengel", "Lent", "Leons", "Lepelstraat",
      "Lettelbert", "Lettele", "Leunen", "Leur", "Leusden", "Leuth",
      "Leutingewolde", "Leuvenheim", "Leveroy", "Lewedorp", "Lexmond",
      "Lichtaard", "Lichtenvoorde", "Liempde", "Lienden",
      "Lierderholthuis", "Lieren", "Lierop", "Lies", "Lieshout",
      "Liessel", "Lievelde", "Lieveren", "Lijnden", "Limbricht",
      "Limmen", "Linde", "Linden", "Linne", "Linschoten", "Lioessens",
      "Lippenhuizen", "Lisse", "Lisserbroek", "Lith", "Lithoijen",
      "Lobith", "Lochem", "Loenen", "Loenen aan de Vecht", "Loenersloot"
      , "Loerbeek", "Lollum", "Lomm", "Longerhouw", "Loo Gld", "Loon",
      "Loon op Zand", "Loosbroek", "Loosdrecht", "Loozen", "Lopik",
      "Lopikerkapel", "Loppersum", "Losdorp", "Losser", "Lottum",
      "Lo\u00ebnga", "Lucaswolde", "Luddeweer", "Luinjeberd", "Lunteren"
      , "Lutjebroek", "Lutjegast", "Lutjewinkel", "Luttelgeest",
      "Lutten", "Luttenberg", "Luxwoude", "Luyksgestel", "Lytsewierrum",
      "Maarheeze", "Maarn", "Maarsbergen", "Maarssen", "Maartensdijk",
      "Maasbommel", "Maasbracht", "Maasbree", "Maasdam", "Maasdijk",
      "Maashees", "Maasland", "Maassluis", "Maastricht",
      "Maastricht-Airport", "Maasvlakte Rotterdam", "Macharen", "Made",
      "Makkinga", "Makkum", "Malden", "Mander", "Manderveen", "Mantgum",
      "Mantinge", "Maren-Kessel", "Margraten", "Maria Hoop",
      "Mariahout", "Mariaparochie", "Marijenkampen", "Mari\u00ebnberg",
      "Mari\u00ebnheem", "Mari\u00ebnvelde", "Markelo", "Marken",
      "Markenbinnen", "Marknesse", "Marle", "Marrum", "Marsum", "Marum",
      "Marwijksoord", "Mastenbroek", "Matsloot", "Maurik", "Mechelen",
      "Medemblik", "Meeden", "Meedhuizen", "Meerkerk", "Meerlo",
      "Meerssen", "Meerstad", "Meeuwen", "Megchelen", "Megen", "Meijel",
      "Melderslo", "Melick", "Meliskerke", "Melissant", "Menaam",
      "Mensingeweer", "Meppel", "Meppen", "Merkelbeek", "Merselo",
      "Meteren", "Meterik", "Metslawier", "Mheer", "Middelaar",
      "Middelburg", "Middelharnis", "Middelie", "Middelstum",
      "Middenbeemster", "Middenmeer", "Midlaren", "Midlum", "Midsland",
      "Midwolda", "Midwolde", "Midwoud", "Miedum", "Mierlo", "Mijdrecht"
      , "Mijnsheerenland", "Mildam", "Milheeze", "Mill",
      "Millingen aan de Rijn", "Milsbeek", "Minnertsga", "Mirns", "Moddergat",
      "Moerdijk", "Moergestel", "Moerkapelle", "Moerstraten",
      "Molenaarsgraaf", "Molenhoek", "Molenschot", "Molkwerum",
      "Monnickendam", "Monster", "Montfoort", "Montfort", "Mook",
      "Mookhoek", "Moordrecht", "Moorveld", "Morra", "Muiden",
      "Muiderberg", "Munnekeburen", "Munnekezijl", "Munstergeleen",
      "Muntendam", "Mussel", "Musselkanaal", "M\u00fbnein", "Naaldwijk",
      "Naarden", "Nagele", "Nederasselt", "Nederhemert",
      "Nederhorst den Berg", "Nederland", "Nederweert", "Nederweert-Eind", "Neede",
      "Neer", "Neerijnen", "Neeritter", "Neerkant", "Neerlangel",
      "Neerloon", "Nes", "Netersel", "Netterden", "Niawier",
      "Nibbixwoud", "Niebert", "Niehove", "Niekerk", "Nietap",
      "Nieuw Annerveen", "Nieuw Beerta", "Nieuw Heeten", "Nieuw Namen",
      "Nieuw Scheemda", "Nieuw- en Sint Joosland", "Nieuw-Amsterdam",
      "Nieuw-Balinge", "Nieuw-Beijerland", "Nieuw-Buinen",
      "Nieuw-Dordrecht", "Nieuw-Lekkerland", "Nieuw-Roden",
      "Nieuw-Schoonebeek", "Nieuw-Vennep", "Nieuw-Vossemeer",
      "Nieuw-Weerdinge", "Nieuwaal", "Nieuwdorp", "Nieuwe Niedorp",
      "Nieuwe Pekela", "Nieuwe Wetering", "Nieuwe-Tonge", "Nieuwebrug",
      "Nieuwediep", "Nieuwegein", "Nieuwehorne", "Nieuwendijk",
      "Nieuwer Ter Aa", "Nieuwerbrug aan den Rijn", "Nieuwerkerk",
      "Nieuwerkerk aan den IJssel", "Nieuweroord", "Nieuwersluis",
      "Nieuweschoot", "Nieuwkoop", "Nieuwkuijk", "Nieuwland",
      "Nieuwlande", "Nieuwlande Coevorden", "Nieuwleusen", "Nieuwolda",
      "Nieuwpoort", "Nieuwstadt", "Nieuwveen", "Nieuwvliet", "Niezijl",
      "Niftrik", "Nigtevecht", "Nij Altoenae", "Nij Beets", "Nijbroek",
      "Nijeberkoop", "Nijega", "Nijehaske", "Nijeholtpade",
      "Nijeholtwolde", "Nijelamer", "Nijemirdum", "Nijensleek",
      "Nijetrijne", "Nijeveen", "Nijhuizum", "Nijkerk", "Nijkerkerveen",
      "Nijland", "Nijlande", "Nijmegen", "Nijverdal", "Nispen", "Nisse"
      , "Nistelrode", "Noardburgum", "Nooitgedacht", "Noorbeek",
      "Noord-Scharwoude", "Noord-Sleen", "Noordbeemster", "Noordbroek",
      "Noordeinde", "Noordeinde Gld", "Noordeloos", "Noorden",
      "Noordgouwe", "Noordhoek", "Noordhorn", "Noordlaren",
      "Noordscheschut", "Noordwelle", "Noordwijk", "Noordwijkerhout",
      "Noordwolde", "Nootdorp", "Norg", "Notter", "Nuenen", "Nuis",
      "Nuland", "Numansdorp", "Nunhem", "Nunspeet", "Nuth", "Nutter",
      "Obbicht", "Obdam", "Ochten", "Odijk", "Odiliapeel", "Odoorn",
      "Odoornerveen", "Oeffelt", "Oegstgeest", "Oene", "Oentsjerk",
      "Offingawier", "Oh\u00e9 en Laak", "Oijen", "Oirlo", "Oirsbeek",
      "Oirschot", "Oisterwijk", "Okkenbroek", "Olburgen", "Oldeberkoop",
      "Oldebroek", "Oldeholtpade", "Oldeholtwolde", "Oldehove",
      "Oldekerk", "Oldelamer", "Oldemarkt", "Oldenzaal", "Oldenzijl",
      "Oldeouwer", "Oldetrijne", "Olst", "Olterterp", "Ommel", "Ommen",
      "Ommeren", "Onderdendam", "Onna", "Onnen", "Onstwedde", "Ooij",
      "Ooltgensplaat", "Oost West en Middelbeers", "Oost-Graftdijk",
      "Oost-Souburg", "Oostburg", "Oostdijk", "Oosteind", "Oosterbeek",
      "Oosterbierum", "Oosterblokker", "Oosterend", "Oosterhesselen",
      "Oosterhout", "Oosterland", "Oosterleek", "Oosternieland",
      "Oosternijkerk", "Oosterstreek", "Oosterwijk", "Oosterwijtwerd",
      "Oosterwolde", "Oosterwolde Gld", "Oosterzee", "Oosthem",
      "Oosthuizen", "Oostkapelle", "Oostknollendam", "Oostrum",
      "Oostvoorne", "Oostwold", "Oostwoud", "Oostzaan", "Ootmarsum",
      "Opeinde", "Opende", "Ophemert", "Opheusden", "Opijnen", "Oploo",
      "Opmeer", "Oppenhuizen", "Opperdoes", "Oranje", "Oranjewoud",
      "Orvelte", "Ospel", "Oss", "Ossendrecht", "Ossenisse",
      "Ossenwaard", "Ossenzijl", "Oterleek", "Otterlo", "Ottersum",
      "Ottoland", "Oud Ade", "Oud Annerveen", "Oud Gastel",
      "Oud Ootmarsum", "Oud Zuilen", "Oud-Alblas", "Oud-Beijerland",
      "Oud-Vossemeer", "Ouddorp", "Oude Meer", "Oude Niedorp",
      "Oude Pekela", "Oude Wetering", "Oude Willem", "Oude-Tonge",
      "Oudebildtzijl", "Oudega", "Oudehaske", "Oudehorne", "Oudelande",
      "Oudemirdum", "Oudemolen", "Oudenbosch", "Oudendijk", "Oudenhoorn"
      , "Ouderkerk aan de Amstel", "Ouderkerk aan den IJssel",
      "Oudeschans", "Oudeschild", "Oudeschip", "Oudeschoot", "Oudesluis"
      , "Oudewater", "Oudezijl", "Oudheusden", "Oudkarspel", "Oudorp",
      "Oudwoude", "Ouwerkerk", "Ouwster-Nijega", "Ouwsterhaule",
      "Overasselt", "Overberg", "Overdinkel", "Overlangel", "Overloon",
      "Overschild", "Overslag", "Overveen", "Ovezande", "Paasloo",
      "Paesens", "Pannerden", "Panningen", "Papekop", "Papendrecht",
      "Papenhoven", "Papenvoort", "Parrega", "Paterswolde", "Peest",
      "Peins", "Peize", "Peperga", "Pernis Rotterdam", "Persingen",
      "Pesse", "Petten", "Philippine", "Piaam", "Piershil",
      "Pieterburen", "Pietersbierum", "Pieterzijl", "Pijnacker",
      "Pingjum", "Plasmolen", "Poederoijen", "Poeldijk", "Polsbroek",
      "Poortugaal", "Poortvliet", "Poppenwier", "Posterholt",
      "Prinsenbeek", "Puiflijk", "Punthorst", "Purmer", "Purmerend",
      "Purmerland", "Puth", "Putte", "Putten", "Puttershoek", "Raalte",
      "Raamsdonk", "Raamsdonksveer", "Raard", "Radewijk",
      "Radio Kootwijk", "Raerd", "Randwijk", "Ransdaal", "Rasquert",
      "Ravenstein", "Ravenswaaij", "Ravenswoud", "Readtsjerk",
      "Reah\u00fbs", "Reduzum", "Reek", "Reeuwijk", "Reijmerstok",
      "Reitsum", "Rekken", "Renesse", "Renkum", "Renswoude", "Ressen",
      "Retranchement", "Reusel", "Reutum", "Reuver", "Rha", "Rheden",
      "Rhee", "Rheeze", "Rheezerveen", "Rhenen", "Rhenoy", "Rhoon",
      "Ridderkerk", "Ried", "Riel", "Rien", "Riethoven", "Rietmolen",
      "Rijen", "Rijkevoort", "Rijkevoort-De Walsert", "Rijnsaterwoude",
      "Rijnsburg", "Rijpwetering", "Rijs", "Rijsbergen", "Rijsenhout",
      "Rijssen", "Rijswijk", "Rijswijk (GLD)", "Rijswijk (NB)",
      "Rilland", "Rinsumageast", "Ritthem", "Rockanje", "Roden",
      "Roderesch", "Roderwolde", "Roelofarendsveen", "Roermond", "Rogat"
      , "Roggel", "Rohel", "Rolde", "Roodeschool", "Roosendaal",
      "Roosteren", "Rosmalen", "Rossum", "Roswinkel", "Rotstergaast",
      "Rotsterhaule", "Rotterdam", "Rotterdam-Albrandswaard",
      "Rottevalle", "Rottum", "Rouveen", "Rozenburg", "Rozendaal",
      "Rucphen", "Ruigahuizen", "Ruinen", "Ruinerwold", "Rumpt",
      "Rutten", "Ruurlo", "Ryptsjerk", "Saaksum", "Saasveld",
      "Saaxumhuizen", "Sambeek", "Sandfirden", "Santpoort-Noord",
      "Santpoort-Zuid", "Sappemeer", "Sas van Gent", "Sassenheim",
      "Sauwerd", "Schagen", "Schagerbrug", "Schaijk", "Schalkhaar",
      "Schalkwijk", "Schalsum", "Schardam", "Scharendijke", "Scharmer",
      "Scharnegoutum", "Scharsterbrug", "Scharwoude", "Scheemda",
      "Scheerwolde", "Schellinkhout", "Schelluinen", "Schermerhorn",
      "Scherpenisse", "Scherpenzeel", "Schettens", "Scheulder",
      "Schiedam", "Schiermonnikoog", "Schijf", "Schijndel",
      "Schildwolde", "Schimmert", "Schin op Geul", "Schinnen",
      "Schinveld", "Schipborg", "Schiphol", "Schiphol-Rijk",
      "Schipluiden", "Schokland", "Schoondijke", "Schoonebeek",
      "Schoonhoven", "Schoonloo", "Schoonoord", "Schoonrewoerd",
      "Schoorl", "Schore", "Schouwerzijl", "Schraard", "Schuinesloot",
      "Sebaldeburen", "Sellingen", "Serooskerke", "Sevenum", "Sexbierum"
      , "Sibculo", "Sibrandabuorren", "Sibrandah\u00fbs", "Siddeburen",
      "Siebengewald", "Siegerswoude", "Sijbekarspel", "Silvolde",
      "Simonshaven", "Simpelveld", "Sinderen", "Sint Agatha",
      "Sint Annen", "Sint Anthonis", "Sint Geertruid", "Sint Hubert",
      "Sint Jansklooster", "Sint Jansteen", "Sint Joost", "Sint Kruis",
      "Sint Maarten", "Sint Maartensbrug", "Sint Maartensvlotbrug",
      "Sint Nicolaasga", "Sint Odili\u00ebnberg", "Sint Pancras",
      "Sint Philipsland", "Sint-Annaland", "Sint-Maartensdijk",
      "Sint-Michielsgestel", "Sint-Oedenrode", "Sintjohannesga",
      "Sirjansland", "Sittard", "Skingen", "Slagharen", "Slappeterp",
      "Sleen", "Sleeuwijk", "Slenaken", "Sliedrecht", "Slijk-Ewijk",
      "Slijkenburg", "Slochteren", "Slootdorp", "Sloten", "Sluis",
      "Sluiskil", "Smakt", "Smalle Ee", "Smallebrugge", "Smilde",
      "Snakkerburen", "Sneek", "Snelrewaard", "Snikzwaag", "Soerendonk",
      "Soest", "Soesterberg", "Someren", "Sommelsdijk",
      "Son en Breugel", "Sondel", "Sonnega", "Spaarndam",
      "Spaarndam gem. Haarlem", "Spanbroek", "Spanga", "Spankeren", "Spannum",
      "Spaubeek", "Spier", "Spierdijk", "Spijk", "Spijk Gn",
      "Spijkenisse", "Spijkerboor", "Sprang-Capelle", "Sprundel", "Spui"
      , "St. Willebrord", "St.-Annaparochie", "St.-Jacobiparochie",
      "Stad aan \'t Haringvliet", "Stadskanaal", "Stampersgat",
      "Standdaarbuiten", "Staphorst", "Starnmeer", "Startenhuizen",
      "Stavenisse", "Stavoren", "Stedum", "Steenbergen", "Steendam",
      "Steenderen", "Steenenkamer", "Steensel", "Steenwijk",
      "Steenwijkerwold", "Stegeren", "Steggerda", "Stein", "Stellendam",
      "Sterksel", "Stevensbeek", "Stevensweert", "Steyl",
      "Stieltjeskanaal", "Stiens", "Stitswerd", "Stokkum", "Stolwijk",
      "Stompetoren", "Stoutenburg", "Stoutenburg Noord", "Stramproy",
      "Streefkerk", "Striep", "Strijbeek", "Strijen", "Strijensas",
      "Stroe", "Stroobos", "Stuifzand", "Sumar", "Surhuisterveen",
      "Surhuizum", "Susteren", "Suwald", "Swalmen", "Sweikhuizen",
      "Swichum", "Swifterbant", "Swolgen", "Taarlo", "Teeffelen",
      "Teerns", "Tegelen", "Ten Boer", "Ten Post", "Ter Aar", "Ter Aard"
      , "Ter Apel", "Ter Apelkanaal", "Ter Heijde", "Ter Idzard",
      "Terband", "Terborg", "Terheijden", "Terherne", "Terhole",
      "Terkaple", "Termunten", "Termunterzijl", "Ternaard", "Terneuzen",
      "Teroele", "Terschuur", "Tersoal", "Terwispel", "Terwolde",
      "Teteringen", "Teuge", "Thesinge", "Tholen", "Thorn", "Tiel",
      "Tiendeveen", "Tienhoven", "Tienray", "Tijnje", "Tilburg",
      "Tilligte", "Tinallinge", "Tinte", "Tirns", "Tjalhuizum",
      "Tjalleberd", "Tjerkgaast", "Tjerkwerd", "Tjuchem", "Tolbert",
      "Toldijk", "Tolkamer", "Tollebeek", "Tonden", "Toornwerd",
      "Tricht", "Triemen", "Tripscompagnie", "Tubbergen", "Tuil",
      "Tuitjenhorn", "Tuk", "Tull en \'t Waal", "Twello", "Twijzel",
      "Twijzelerheide", "Twisk", "Tynaarlo", "Tytsjerk", "Tzum",
      "Tzummarum", "Ubbena", "Ubbergen", "Uddel", "Uden", "Udenhout",
      "Uffelte", "Ugchelen", "Uitdam", "Uitgeest", "Uithoorn",
      "Uithuizen", "Uithuizermeeden", "Uitwellingerga", "Uitwijk",
      "Ulestraten", "Ulft", "Ulicoten", "Ulrum", "Ulvenhout",
      "Ulvenhout AC", "Ureterp", "Urk", "Urmond", "Ursem",
      "Ursem gem. S", "Usquert", "Utrecht", "Vaals", "Vaassen", "Valburg",
      "Valkenburg", "Valkenswaard", "Valthe", "Valthermond", "Varik",
      "Varsselder", "Varsseveld", "Vasse", "Veelerveen", "Veen",
      "Veendam", "Veenendaal", "Veenhuizen", "Veeningen", "Veenklooster"
      , "Veenoord", "Veere", "Veessen", "Vegelinsoord", "Veghel",
      "Velddriel", "Velden", "Veldhoven", "Velp", "Velsen-Noord",
      "Velsen-Zuid", "Velserbroek", "Ven-Zelderheide", "Venebrugge",
      "Venhorst", "Venhuizen", "Venlo", "Venray", "Vessem", "Vethuizen",
      "Veulen", "Vianen", "Vianen NB", "Vierakker", "Vierhouten",
      "Vierhuizen", "Vierlingsbeek", "Vierpolders", "Vijfhuizen",
      "Vijlen", "Vilsteren", "Vinkega", "Vinkel", "Vinkenbuurt",
      "Vinkeveen", "Visvliet", "Vlaardingen", "Vlagtwedde", "Vledder",
      "Vledderveen", "Vleuten", "Vlieland", "Vlierden", "Vlijmen",
      "Vlissingen", "Vlist", "Vlodrop", "Voerendaal", "Vogelenzang",
      "Vogelwaarde", "Volendam", "Volkel", "Vollenhove",
      "Vondelingenplaat Rotterdam", "Voorburg", "Voorhout",
      "Voorschoten", "Voorst", "Voorthuizen", "Vorchten", "Vorden",
      "Vorstenbosch", "Vortum-Mullem", "Vragender", "Vredenheim",
      "Vredepeel", "Vreeland", "Vries", "Vriescheloo", "Vriezenveen",
      "Vroomshoop", "Vrouwenakker", "Vrouwenparochie", "Vrouwenpolder",
      "Vught", "Vuren", "Waaksens", "Waal", "Waalre", "Waalwijk",
      "Waarde", "Waardenburg", "Waarder", "Waardhuizen", "Waarland",
      "Waaxens", "Wachtum", "Waddinxveen", "Wadenoijen", "Wagenberg",
      "Wagenborgen", "Wageningen", "Walem", "Walsoorden", "Wamel",
      "Wanneperveen", "Wanroij", "Wanssum", "Wapenveld", "Wapse",
      "Wapserveen", "Warder", "Warffum", "Warfhuizen", "Warfstermolen",
      "Warmenhuizen", "Warmond", "Warns", "Warnsveld", "Warstiens",
      "Warten", "Waskemeer", "Waspik", "Wassenaar", "Wateren",
      "Watergang", "Waterhuizen", "Wateringen", "Waterlandkerkje",
      "Waverveen", "Wedde", "Weerselo", "Weert", "Weesp",
      "Wehe-den Hoorn", "Wehl", "Weidum", "Weiteveen", "Wekerom", "Well", "Well L"
      , "Wellerlooi", "Welsum", "Wemeldinge", "Wenum Wiesel", "Wergea",
      "Werkendam", "Werkhoven", "Wernhout", "Wervershoof", "Wesepe",
      "Wessem", "West-Graftdijk", "West-Terschelling", "Westbeemster",
      "Westbroek", "Westdorp", "Westdorpe", "Westendorp", "Westerbeek",
      "Westerbork", "Westerbroek", "Westeremden", "Westergeest",
      "Westerhaar-Vriezenveensewijk", "Westerhoven", "Westerland",
      "Westerlee", "Westernieland", "Westervelde", "Westervoort",
      "Westerwijtwerd", "Westhem", "Westhoek", "Westkapelle",
      "Westknollendam", "Westmaas", "Westwoud", "Westzaan", "Wetering",
      "Weteringbrug", "Wetsens", "Wetsinge", "Weurt", "Wezep", "Wezup",
      "Wezuperbrug", "Wichmond", "Wier", "Wierden", "Wieringerwaard",
      "Wieringerwerf", "Wierum", "Wijchen", "Wijckel", "Wijdenes",
      "Wijdewormer", "Wijhe", "Wijk aan Zee", "Wijk bij Duurstede",
      "Wijk en Aalburg", "Wijlre", "Wijnaldum", "Wijnandsrade",
      "Wijnbergen", "Wijngaarden", "Wijnjewoude", "Wijster",
      "Wilbertoord", "Wildervank", "Wilhelminadorp", "Wilhelminaoord",
      "Willemsoord", "Willemstad", "Wilnis", "Wilp", "Wilsum", "Winde",
      "Windraak", "Winkel", "Winneweer", "Winschoten", "Winssen",
      "Winsum", "Wintelre", "Winterswijk", "Winterswijk Brinkheurne",
      "Winterswijk Corle", "Winterswijk Henxel", "Winterswijk Huppel",
      "Winterswijk Kotten", "Winterswijk Meddo", "Winterswijk Miste",
      "Winterswijk Ratum", "Winterswijk Woold", "Wirdum", "Wirdum Gn",
      "Wissenkerke", "Witharen", "Witmarsum", "Witte Paarden",
      "Wittelte", "Wittem", "Witteveen", "Wiuwert", "Wjelsryp",
      "Woensdrecht", "Woerden", "Woerdense Verlaat", "Wognum",
      "Woldendorp", "Wolfheze", "Wolphaartsdijk", "Wolsum", "Woltersum",
      "Wolvega", "Wommels", "Wons", "Workum", "Wormer", "Wormerveer",
      "Woubrugge", "Woudbloem", "Woudenberg", "Woudrichem", "Woudsend",
      "Wouw", "Wouwse Plantage", "Wyns", "Wytgaard", "Walterswald",
      "Wanswert", "Yde", "Yerseke", "Ypecolsga", "Ysbrechtum",
      "Ysselsteyn", "Zaamslag", "Zaandam", "Zaandijk", "Zalk",
      "Zaltbommel", "Zandberg", "Zandeweer", "Zandhuizen", "Zandpol",
      "Zandvoort", "Zeddam", "Zeegse", "Zeeland", "Zeerijp", "Zeewolde",
      "Zegge", "Zegveld", "Zeijen", "Zeijerveen", "Zeijerveld", "Zeist"
      , "Zelhem", "Zenderen", "Zennewijnen", "Zetten", "Zevenaar",
      "Zevenbergen", "Zevenbergschen Hoek", "Zevenhoven", "Zevenhuizen",
      "Zierikzee", "Zieuwent", "Zijderveld", "Zijdewind", "Zijldijk",
      "Zoelen", "Zoelmond", "Zoetermeer", "Zoeterwoude", "Zonnemaire",
      "Zorgvlied", "Zoutelande", "Zoutkamp", "Zuid-Beijerland",
      "Zuid-Scharwoude", "Zuidbroek", "Zuiddorpe", "Zuidermeer",
      "Zuiderwoude", "Zuidhorn", "Zuidlaarderveen", "Zuidland",
      "Zuidlaren", "Zuidoostbeemster", "Zuidschermer", "Zuidveen",
      "Zuidveld", "Zuidvelde", "Zuidwolde", "Zuidzande", "Zuilichem",
      "Zuna", "Zundert", "Zurich", "Zutphen", "Zuurdijk", "Zwaag",
      "Zwaagdijk-Oost", "Zwaagdijk-West", "Zwaanshoek", "Zwagerbosch",
      "Zwammerdam", "Zwanenburg", "Zwartebroek", "Zwartemeer",
      "Zwartewaal", "Zwartsluis", "Zweeloo", "Zweins", "Zwiggelte",
      "Zwijndrecht", "Zwinderen", "Zwolle", "de Hoef", "de Lutte",
      "de Wijk", "de Woude"
    ),

    provinces = c(
      'Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen',
      'Limburg', 'Noord-Brabant', 'Noord-Holland', 'Overijssel', 'Utrecht',
      'Zeeland', 'Zuid-Holland'),

    street_name_formats = '{first_name}{street_suffix}',

    street_address_formats = '{street_name} {building_number}',

    address_formats = "{street_address}\n{postcode}\n{city}"
  ),

  public = list(
    province = function(){
      return(private$random_element(private$provinces))
    },

    city = function(){
      return(private$random_element(private$cities))
    }
  )
)

# phone_number -----------------------------------------
phone_number_nl_NL = R6Class(
  "phone_number_nl_NL",
  inherit = phone_number_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '0### ######',
      '0## #######',
      '+31### ######',
      '+31## #######',
      '+31(0)### ######',
      '+31(0)## #######',
      '(0###) ######',
      '(0##) #######',
      '0###-######',
      '0##-#######',
      '+31###-######',
      '+31##-#######',
      '+31(0)###-######',
      '+31(0)##-#######',
      '(0###)-######',
      '(0##)-#######'
    )
  )
)
# ssn -----------------------------------------
ssn_nl_NL = R6Class(
  "ssn_nl_NL",
  inherit = ssn_init,
  cloneable = FALSE,
  private = list(
    vat_id_formats = 'NL#########B##'
  ),

  public = list(
    ssn = function(){
      factors = c(9, 8, 7, 6, 5, 4, 3, 2, -1)
      # Returns a 9 digits Dutch SSN called "burgerservicenummer (BSN)".
      # the Dutch "burgerservicenummer (BSN)" needs to pass the "11-proef",
      # which is a check digit approach; this function essentially reverses
      # the checksum steps to create a random valid BSN (which is 9 digits).
      while (TRUE) {
        # create an array of first 8 elements initialized randomly
        digits = sample(seq(0, 9), 8)
        # sum those 8 digits according to (part of) the "11-proef"
        s = sum(digits * factors[1:8])
        # determine the last digit to make it qualify the test
        digits = c(digits, ((s %% 11) %% 10))
        # repeat steps until it does qualify the test
        if ((sum(digits * factors) %% 11) == 0) break

      }
      bsn = str_c(digits, collapse = "")
      return(bsn)
    },

    vat_id = function(){
      # http://ec.europa.eu/taxation_customs/vies/faq.html#item_11
      # :return: A random Dutch VAT ID
      return(private$bothify(private$random_element(private$vat_id_formats)))
    }
  )
)


# credit_card -----------------
credit_card_nl_NL = R6Class(
  "credit_card_nl_NL",
  inherit = credit_card_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_nl_NL$new())$.__enclos_env__$private$first_names,
    first_name = (person_nl_NL$new())$first_name,
    last_names = (person_nl_NL$new())$.__enclos_env__$private$last_names,
    last_name = (person_nl_NL$new())$last_name
  )
)


# profile   ------------
profile_nl_NL = R6Class(
  "profile_nl_NL",
  inherit = profile_init,
  cloneable = FALSE,
  public = list(
    simple_profile = function(sex) {
      # Generates a basic profile with personal informations
      SEX = c("F", "M")
      if (missing(sex)) {
        sex = sample(SEX, 1)
      }
      if (!(sex %in% SEX)) {
        sex = sample(SEX, 1)
      }

      name = ifelse(sex == "F",
                    (person_nl_NL$new())$name_female(),
                    (person_nl_NL$new())$name_male())
      temp = list(
        "username" = (internet_en_US$new())$user_name(),
        "name" = name,
        "sex" = sex,
        "address" = (address_nl_NL$new())$address(),
        "mail" = (internet_en_US$new())$free_email(),
        "birthdate" = (date_time_init$new())$date_of_birth()
      )
      return(temp)
    },

    profile = function(fields, sex) {
      # Generates a complete profile.
      # If "fields" is not empty, only the fields in the list will be returned

      if (missing(fields)) fields = c()

      field = list(
        "job" = (job_init$new())$job(),
        "company" = (company_nl_NL$new())$company(),
        "ssn" = (ssn_nl_NL$new())$ssn(),
        "residence" = (address_nl_NL$new())$address(),
        "current_location" = c((geo_init$new())$latitude(),
                               (geo_init$new())$longitude()),
        "blood_group" = sample(c(
          "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"), 1),
        "website" = replicate(sample(seq(4), 1), (internet_en_US$new())$url())
      )

      field = append(field, self$simple_profile(sex))
      # field selection

      if (length(fields)) {
        nms = intersect(names(field), fields)
        field = field[nms]
      }
      return(field)
    }

  )
)





