# person -----------------------------------
person_sl_SI = R6Class(
  'person_sl_SI',
  inherit = person_init,
  cloneable = FALSE,
  private = list(
    formats = '{first_name} {last_name}',
    first_names_male = c(
      "Franc",
      "Janez",
      "Anton",
      "Ivan",
      "Jo\u017eef",
      "Andrej",
      "Marko",
      "Marjan",
      "Peter",
      "Milan",
      "Stanislav",
      "Matej",
      "Toma\u017e",
      "Branko",
      "Bojan",
      "Robert",
      "Bo\u0161tjan",
      "Matja\u017e",
      "Gregor",
      "Luka",
      "Martin",
      "Rok",
      "Boris",
      "Du\u0161an",
      "Igor",
      "Miha",
      "Dejan",
      "David",
      "Uro\u0161",
      "Simon",
      "Jure",
      "Bla\u017e",
      "\u0160tefan",
      "Jan",
      "Drago",
      "Darko",
      "Klemen",
      "Nejc",
      "\u017diga",
      "Jernej",
      "Miran",
      "Aleksander",
      "Roman",
      "Vladimir",
      "Matic",
      "Tadej",
      "Sre\u010dko",
      "Slavko",
      "Mirko",
      "Janko",
      "\u017dan",
      "Miroslav",
      "Borut",
      "Alojzij",
      "Damjan",
      "Stanko",
      "Alja\u017e",
      "An\u017ee",
      "Danijel",
      "Mihael",
      "Matija",
      "Jaka",
      "Marijan",
      "Rudolf",
      "Alen",
      "Jakob",
      "Viktor",
      "Domen",
      "Sa\u0161o",
      "Iztok",
      "Goran",
      "Tilen",
      "Pavel",
      "Zvonko",
      "Edvard",
      "Zdravko",
      "Danilo",
      "Matev\u017e",
      "Rajko",
      "Ludvik",
      "Zlatko",
      "Fran\u010di\u0161ek",
      "Bogdan",
      "Gorazd",
      "Samo",
      "Leon",
      "Dragan",
      "Emil",
      "Josip",
      "Nik",
      "Ciril",
      "Sandi",
      "Benjamin",
      "Vid",
      "Albin",
      "Franci",
      "Sebastjan",
      "Silvo",
      "Leopold",
      "Kristjan",
      "Tim",
      "Filip",
      "Damijan",
      "Erik",
      "Viljem",
      "Vincenc",
      "\u017deljko",
      "Damir",
      "Aljo\u0161a",
      "Karel",
      "Daniel",
      "Dominik",
      "Milo\u0161",
      "Stojan",
      "Franjo",
      "Valentin",
      "Davorin",
      "Maks",
      "Timotej",
      "Ladislav",
      "Niko",
      "Mark",
      "Nikola",
      "Bogomir",
      "Sa\u0161a",
      "Vlado",
      "Karl",
      "Zdenko",
      "Grega",
      "Stjepan",
      "Davor",
      "Kristijan",
      "Ernest",
      "Maksimiljan",
      "Avgust",
      "Sebastijan",
      "Aleksandar",
      "Lovro",
      "Ivo",
      "Rado",
      "Tine",
      "Adolf",
      "Gal",
      "Valter",
      "Elvis",
      "Jasmin",
      "Ervin",
      "Jani",
      "Izidor",
      "Nenad",
      "Anej",
      "Petar",
      "Maj",
      "Metod",
      "Albert",
      "Bruno",
      "Radovan",
      "Nikolaj",
      "Feliks",
      "Karol",
      "Bernard",
      "Jo\u0161ko",
      "Rafael",
      "Edin",
      "Aleks",
      "Cvetko",
      "Rudi",
      "Miro",
      "Hasan",
      "Slobodan",
      "Mirsad"
    ),

    first_names_female = c(
      "Marija",
      "Ana",
      "Irena",
      "Maja",
      "Mojca",
      "Jo\u017eefa",
      "Mateja",
      "Nata\u0161a",
      "Jo\u017eica",
      "Barbara",
      "Ivana",
      "Andreja",
      "Nina",
      "Petra",
      "Katja",
      "Sonja",
      "Milena",
      "Katarina",
      "Tatjana",
      "Anja",
      "Alenka",
      "Tanja",
      "Martina",
      "Vesna",
      "Tina",
      "Angela",
      "Ur\u0161ka",
      "Antonija",
      "Anica",
      "Kristina",
      "Dragica",
      "Nada",
      "Olga",
      "\u0160pela",
      "Darja",
      "Marjeta",
      "Tja\u0161a",
      "Eva",
      "Ljudmila",
      "Simona",
      "Vida",
      "Sara",
      "Zdenka",
      "Alojzija",
      "Lidija",
      "Suzana",
      "Marta",
      "Nika",
      "Sabina",
      "Silva",
      "Veronika",
      "\u0160tefanija",
      "Stanislava",
      "Darinka",
      "Karmen",
      "Ne\u017ea",
      "Brigita",
      "Anita",
      "Aleksandra",
      "Pavla",
      "Cvetka",
      "Metka",
      "Nevenka",
      "Monika",
      "Rozalija",
      "Natalija",
      "Slavica",
      "Marjana",
      "Branka",
      "Jasmina",
      "Vera",
      "Ema",
      "Sa\u0161a",
      "Ma\u0161a",
      "Lara",
      "Lucija",
      "Tamara",
      "Bernarda",
      "Danijela",
      "Klavdija",
      "Erika",
      "Romana",
      "Mira",
      "Jasna",
      "Klara",
      "Kaja",
      "Jelka",
      "Polona",
      "Julijana",
      "Valerija",
      "Sandra",
      "Matilda",
      "Tadeja",
      "Valentina",
      "Mihaela",
      "Amalija",
      "Albina",
      "Breda",
      "Karolina",
      "Sanja",
      "Teja",
      "Ines",
      "Zofija",
      "Ksenija",
      "Laura",
      "Cecilija",
      "Patricija",
      "Magdalena",
      "Manca",
      "Viktorija",
      "Maru\u0161a",
      "Vanja",
      "Vlasta",
      "Justina",
      "Nu\u0161a",
      "Emilija",
      "Melita",
      "Ljubica",
      "Lana",
      "Marica",
      "Gordana",
      "Marinka",
      "Polonca",
      "Nadja",
      "Milka",
      "\u017diva",
      "Ur\u0161a",
      "Damjana",
      "Hana",
      "Tea",
      "Marijana",
      "Julija",
      "Ajda",
      "Nastja",
      "Milica",
      "Alja",
      "\u0160tefka",
      "Slavka",
      "Jerneja",
      "Nives",
      "Du\u0161anka",
      "Andrejka",
      "Irma",
      "Pia",
      "Jelena",
      "Marjanca",
      "Miroslava",
      "Lilijana",
      "Stanka",
      "Mirjam",
      "Neja",
      "Jolanda",
      "Zora",
      "Zvonka",
      "Hermina",
      "Rebeka",
      "Hedvika",
      "Blanka",
      "Larisa",
      "Erna",
      "Anka",
      "Roza",
      "Liljana",
      "Magda",
      "Daniela",
      "Jerica",
      "Taja",
      "Iris",
      "Adrijana",
      "Jadranka"
    ),

    first_names = c(
      "Franc",
      "Janez",
      "Anton",
      "Ivan",
      "Jo\u017eef",
      "Andrej",
      "Marko",
      "Marjan",
      "Peter",
      "Milan",
      "Stanislav",
      "Matej",
      "Toma\u017e",
      "Branko",
      "Bojan",
      "Robert",
      "Bo\u0161tjan",
      "Matja\u017e",
      "Gregor",
      "Luka",
      "Martin",
      "Rok",
      "Boris",
      "Du\u0161an",
      "Igor",
      "Miha",
      "Dejan",
      "David",
      "Uro\u0161",
      "Simon",
      "Jure",
      "Bla\u017e",
      "\u0160tefan",
      "Jan",
      "Drago",
      "Darko",
      "Klemen",
      "Nejc",
      "\u017diga",
      "Jernej",
      "Miran",
      "Aleksander",
      "Roman",
      "Vladimir",
      "Matic",
      "Tadej",
      "Sre\u010dko",
      "Slavko",
      "Mirko",
      "Janko",
      "\u017dan",
      "Miroslav",
      "Borut",
      "Alojzij",
      "Damjan",
      "Stanko",
      "Alja\u017e",
      "An\u017ee",
      "Danijel",
      "Mihael",
      "Matija",
      "Jaka",
      "Marijan",
      "Rudolf",
      "Alen",
      "Jakob",
      "Viktor",
      "Domen",
      "Sa\u0161o",
      "Iztok",
      "Goran",
      "Tilen",
      "Pavel",
      "Zvonko",
      "Edvard",
      "Zdravko",
      "Danilo",
      "Matev\u017e",
      "Rajko",
      "Ludvik",
      "Zlatko",
      "Fran\u010di\u0161ek",
      "Bogdan",
      "Gorazd",
      "Samo",
      "Leon",
      "Dragan",
      "Emil",
      "Josip",
      "Nik",
      "Ciril",
      "Sandi",
      "Benjamin",
      "Vid",
      "Albin",
      "Franci",
      "Sebastjan",
      "Silvo",
      "Leopold",
      "Kristjan",
      "Tim",
      "Filip",
      "Damijan",
      "Erik",
      "Viljem",
      "Vincenc",
      "\u017deljko",
      "Damir",
      "Aljo\u0161a",
      "Karel",
      "Daniel",
      "Dominik",
      "Milo\u0161",
      "Stojan",
      "Franjo",
      "Valentin",
      "Davorin",
      "Maks",
      "Timotej",
      "Ladislav",
      "Niko",
      "Mark",
      "Nikola",
      "Bogomir",
      "Sa\u0161a",
      "Vlado",
      "Karl",
      "Zdenko",
      "Grega",
      "Stjepan",
      "Davor",
      "Kristijan",
      "Ernest",
      "Maksimiljan",
      "Avgust",
      "Sebastijan",
      "Aleksandar",
      "Lovro",
      "Ivo",
      "Rado",
      "Tine",
      "Adolf",
      "Gal",
      "Valter",
      "Elvis",
      "Jasmin",
      "Ervin",
      "Jani",
      "Izidor",
      "Nenad",
      "Anej",
      "Petar",
      "Maj",
      "Metod",
      "Albert",
      "Bruno",
      "Radovan",
      "Nikolaj",
      "Feliks",
      "Karol",
      "Bernard",
      "Jo\u0161ko",
      "Rafael",
      "Edin",
      "Aleks",
      "Cvetko",
      "Rudi",
      "Miro",
      "Hasan",
      "Slobodan",
      "Mirsad",
      "Marija",
      "Ana",
      "Irena",
      "Maja",
      "Mojca",
      "Jo\u017eefa",
      "Mateja",
      "Nata\u0161a",
      "Jo\u017eica",
      "Barbara",
      "Ivana",
      "Andreja",
      "Nina",
      "Petra",
      "Katja",
      "Sonja",
      "Milena",
      "Katarina",
      "Tatjana",
      "Anja",
      "Alenka",
      "Tanja",
      "Martina",
      "Vesna",
      "Tina",
      "Angela",
      "Ur\u0161ka",
      "Antonija",
      "Anica",
      "Kristina",
      "Dragica",
      "Nada",
      "Olga",
      "\u0160pela",
      "Darja",
      "Marjeta",
      "Tja\u0161a",
      "Eva",
      "Ljudmila",
      "Simona",
      "Vida",
      "Sara",
      "Zdenka",
      "Alojzija",
      "Lidija",
      "Suzana",
      "Marta",
      "Nika",
      "Sabina",
      "Silva",
      "Veronika",
      "\u0160tefanija",
      "Stanislava",
      "Darinka",
      "Karmen",
      "Ne\u017ea",
      "Brigita",
      "Anita",
      "Aleksandra",
      "Pavla",
      "Cvetka",
      "Metka",
      "Nevenka",
      "Monika",
      "Rozalija",
      "Natalija",
      "Slavica",
      "Marjana",
      "Branka",
      "Jasmina",
      "Vera",
      "Ema",
      "Sa\u0161a",
      "Ma\u0161a",
      "Lara",
      "Lucija",
      "Tamara",
      "Bernarda",
      "Danijela",
      "Klavdija",
      "Erika",
      "Romana",
      "Mira",
      "Jasna",
      "Klara",
      "Kaja",
      "Jelka",
      "Polona",
      "Julijana",
      "Valerija",
      "Sandra",
      "Matilda",
      "Tadeja",
      "Valentina",
      "Mihaela",
      "Amalija",
      "Albina",
      "Breda",
      "Karolina",
      "Sanja",
      "Teja",
      "Ines",
      "Zofija",
      "Ksenija",
      "Laura",
      "Cecilija",
      "Patricija",
      "Magdalena",
      "Manca",
      "Viktorija",
      "Maru\u0161a",
      "Vanja",
      "Vlasta",
      "Justina",
      "Nu\u0161a",
      "Emilija",
      "Melita",
      "Ljubica",
      "Lana",
      "Marica",
      "Gordana",
      "Marinka",
      "Polonca",
      "Nadja",
      "Milka",
      "\u017diva",
      "Ur\u0161a",
      "Damjana",
      "Hana",
      "Tea",
      "Marijana",
      "Julija",
      "Ajda",
      "Nastja",
      "Milica",
      "Alja",
      "\u0160tefka",
      "Slavka",
      "Jerneja",
      "Nives",
      "Du\u0161anka",
      "Andrejka",
      "Irma",
      "Pia",
      "Jelena",
      "Marjanca",
      "Miroslava",
      "Lilijana",
      "Stanka",
      "Mirjam",
      "Neja",
      "Jolanda",
      "Zora",
      "Zvonka",
      "Hermina",
      "Rebeka",
      "Hedvika",
      "Blanka",
      "Larisa",
      "Erna",
      "Anka",
      "Roza",
      "Liljana",
      "Magda",
      "Daniela",
      "Jerica",
      "Taja",
      "Iris",
      "Adrijana",
      "Jadranka"
    ),

    last_names = c(
      "Novak",
      "Horvat",
      "Krajnc",
      "Kova\u010di\u010d",
      "Zupan\u010di\u010d",
      "Kova\u010d",
      "Poto\u010dnik",
      "Mlakar",
      "Vidmar",
      "Kos",
      "Golob",
      "Turk",
      "Bo\u017ei\u010d",
      "Zupan",
      "Koro\u0161ec",
      "Bizjak",
      "Hribar",
      "Kotnik",
      "Rozman",
      "Petek",
      "petek",
      "Kastelic",
      "Kolar",
      "Ho\u010devar",
      "\u017dagar",
      "\u017eagar",
      "Ko\u0161ir",
      "Koren",
      "Klemen\u010di\u010d",
      "Zajc",
      "Medved",
      "Knez",
      "Zupanc",
      "Pirc",
      "Hrovat",
      "Pavli\u010d",
      "Kuhar",
      "kuhar",
      "Lah",
      "Zorko",
      "Sever",
      "Majcen",
      "Jerman",
      "Babi\u010d",
      "Toma\u017ei\u010d",
      "Erjavec",
      "Jereb",
      "Kranjc",
      "Rupnik",
      "Perko",
      "Lesjak",
      "Breznik",
      "Pe\u010dnik",
      "Pavlin",
      "Dolenc",
      "Vidic",
      "Furlan",
      "Logar",
      "Tom\u0161i\u010d",
      "Jenko",
      "Jane\u017ei\u010d",
      "ribi\u010d",
      "\u017dnidar\u0161i\u010d",
      "\u010cerne",
      "Ma\u010dek",
      "Le\u0161nik",
      "Fras",
      "Marolt",
      "Jelen",
      "Gregori\u010d",
      "Blatnik",
      "Pintar",
      "Miheli\u010d",
      "Kokalj",
      "Bezjak",
      "Leban",
      "Cerar",
      "\u010ceh",
      "\u010deh",
      "Jug",
      "Vidovi\u010d",
      "Rus",
      "Kobal",
      "Primo\u017ei\u010d",
      "Kocjan\u010di\u010d",
      "Dolinar",
      "Lazar",
      "Kolenc",
      "Nemec",
      "Kolari\u010d",
      "Lavri\u010d",
      "Kodri\u010d",
      "Kosi",
      "Mrak",
      "Debeljak",
      "Tav\u010dar",
      "\u017di\u017eek",
      "Krivec",
      "Zver",
      "Likar",
      "\u017dibert",
      "Jarc",
      "Vodopivec",
      "Kramberger",
      "Miklav\u010di\u010d",
      "Skok",
      "Toplak",
      "Petrovi\u010d",
      "Hribernik",
      "Leskovar",
      "Stopar",
      "Simoni\u010d",
      "Bla\u017ei\u010d",
      "Er\u017een",
      "Sitar",
      "Gorenc",
      "\u017deleznik",
      "\u0160inkovec",
      "Jamnik",
      "Javornik",
      "Bukovec",
      "Hozjan",
      "Ram\u0161ak",
      "Filipi\u010d",
      "Ko\u010devar",
      "Dem\u0161ar",
      "Volk",
      "volk",
      "Gomboc",
      "\u010cuk",
      "Ili\u0107",
      "Kokol",
      "Bregar",
      "Su\u0161nik",
      "Pintari\u010d",
      "Gorjup",
      "Jovanovi\u0107",
      "Mavri\u010d",
      "Kramar",
      "Lebar",
      "Rutar",
      "Ko\u017eelj",
      "Popovi\u0107",
      "Rajh",
      "Hod\u017ei\u0107",
      "Ro\u017eman",
      "Resnik",
      "\u0160mid",
      "Kumer",
      "Godec",
      "Bergant",
      "Poga\u010dnik",
      "Zemlji\u010d",
      "Hafner",
      "Tratnik",
      "Ro\u017ei\u010d",
      "Cvetko",
      "Ambro\u017ei\u010d",
      "Bevc",
      "Mlinari\u010d",
      "Mlinar",
      "Jeri\u010d",
      "Kalan",
      "Markovi\u010d",
      "\u0160u\u0161tar",
      "Bajc",
      "Kau\u010di\u010d",
      "Dolin\u0161ek",
      "Zalokar",
      "Pirnat",
      "Zorman",
      "Zakraj\u0161ek",
      "\u0160trukelj"
    )
  )
)

# company -------------------------------------
company_sl_SI = R6Class(
  "company_sl_SI",
  inherit = company_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_sl_SI$new())$.__enclos_env__$private$first_names,
    last_names = (person_sl_SI$new())$.__enclos_env__$private$last_names,
    first_name = (person_sl_SI$new())$first_name,
    last_name = (person_sl_SI$new())$last_name,

    formats = c(
      '{last_name} {company_suffix}',
      '{first_name} {last_name} s.p.'
    ),

    company_suffixes = c('d.o.o.', 'd.d.')
  )
)

# date_time --------------------------------
date_time_sl_SI = R6Class(
  "date_time_sl_SI",
  inherit = date_time_init,
  cloneable = FALSE,
  private = list(
    DAY_NAMES = c(
      "0" = "Nedelja",
      "1" = "Ponedeljek",
      "2" = "Torek",
      "3" = "Sreda",
      "4" = "\u010cetrtek",
      "5" = "Petek",
      "6" = "Sobota"
    ),

    MONTH_NAMES = c(
      "01" = "Januar",
      "02" = "Februar",
      "03" = "Marec",
      "04" = "April",
      "05" = "Maj",
      "06" = "Junij",
      "07" = "Julij",
      "08" = "Avgust",
      "09" = "September",
      "10" = "Oktober",
      "11" = "November",
      "12" = "December"
    )
  )
)
# address ---------------------------------------
address_sl_SI = R6Class(
  "address_sl_SI",
  inherit = address_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_sl_SI$new())$.__enclos_env__$private$first_names,
    last_names = (person_sl_SI$new())$.__enclos_env__$private$last_names,
    first_name = (person_sl_SI$new())$first_name,
    last_name = (person_sl_SI$new())$last_name,

    city_formats = '{city_name}',

    street_name_formats = '{street_name}',
    street_address_formats = '{street_name} {building_number}',
    address_formats = '{street_address}\n{postcode} {city}',

    building_number_formats = c('###', '##', '#', '#a', '#b', '#c'),

    postcode_formats = '####',

    cities = c(
      "Ajdov\u0161\u010dina",
      "Bled",
      "Bovec",
      "Bre\u017eice",
      "Celje",
      "Cerknica",
      "\u010crnomelj",
      "Dom\u017eale",
      "Dravograd",
      "Gornja Radgona",
      "Gornji Grad",
      "Grosuplje",
      "Hrastnik",
      "Idrija",
      "Ilirska Bistrica",
      "Izola",
      "Jesenice",
      "Kamnik",
      "Kobarid",
      "Ko\u010devje",
      "Koper",
      "Kostanjevica na Krki",
      "Kranj",
      "Kr\u0161ko",
      "La\u0161ko",
      "Lenart v Slovenskih goricah",
      "Lendava",
      "Litija",
      "Ljubljana",
      "Ljutomer",
      "Logatec",
      "Maribor",
      "Medvode",
      "Menge\u0161",
      "Metlika",
      "Me\u017eica",
      "Murska Sobota",
      "Nova Gorica",
      "Novo mesto",
      "Ormo\u017e",
      "Piran",
      "Postojna",
      "Prevalje",
      "Ptuj",
      "Rade\u010de",
      "Radovljica",
      "Ravne na Koro\u0161kem",
      "Ribnica",
      "Roga\u0161ka Slatina",
      "Ru\u0161e",
      "Sevnica",
      "Se\u017eana",
      "Slovenj Gradec",
      "Slovenska Bistrica",
      "Slovenske Konjice",
      "\u0160empeter pri Gorici",
      "\u0160entjur",
      "\u0160kofja Loka",
      "\u0160o\u0161tanj",
      "Tolmin",
      "Trbovlje",
      "Trebnje",
      "Tr\u017ei\u010d",
      "Turni\u0161\u010de",
      "Velenje",
      "Vipava",
      "Vipavski Kri\u017e",
      "Vi\u0161nja Gora",
      "Vrhnika",
      "Zagorje ob Savi",
      "\u017dalec",
      "\u017delezniki",
      "\u017diri"
    ),

    streets = c(
      "Abramova ulica",
      "Adami\u010deva ulica",
      "Adami\u010d-Lundrovo nabre\u017eje",
      "Ajdov\u0161\u010dina",
      "Ale\u0161eva ulica",
      "Ale\u0161ov\u010deva ulica",
      "Alja\u017eeva ulica",
      "Ambro\u017eev trg",
      "Ameri\u0161ka ulica",
      "Andri\u0107eva ulica",
      "An\u017eurjeva ulica",
      "Apihova ulica",
      "Argentinska ulica",
      "Arharjeva cesta",
      "Arkova ulica",
      "Arta\u010deva ulica",
      "A\u0161ker\u010deva cesta",
      "Av\u010dinova ulica",
      "Avse\u010deva ulica",
      "Avstrijska ulica",
      "Av\u0161i\u010deva cesta",
      "A\u017emanova ulica",
      "Babi\u010deva ulica",
      "Badjurova ulica",
      "Balinarska pot",
      "Baragova ulica",
      "Barjanska cesta",
      "Bavdkova ulica",
      "Baznikova ulica",
      "Bazovi\u0161ka ulica",
      "Beethovnova ulica",
      "Bela\u010deva ulica",
      "Belja\u0161ka ulica",
      "Ber\u010di\u010deva ulica",
      "Ber\u010donova pot",
      "Berdajsova ulica",
      "Bernekerjeva ulica",
      "Bernikova ulica",
      "Betettova cesta",
      "Bezen\u0161kova ulica",
      "Be\u017eigrad",
      "Bi\u010devje",
      "Bile\u010danska ulica",
      "Biten\u010deva ulica",
      "Bizjakova ulica",
      "Bizjanova ulica",
      "Bizov\u0161ki \u0161tradon",
      "Blasnikova ulica",
      "Blasov breg",
      "Bleiweisova cesta",
      "Boben\u010dkova ulica",
      "Bobrova ulica",
      "Bognarjeva pot",
      "Bohinj\u010deva ulica",
      "Bohori\u010deva ulica",
      "Boletova ulica",
      "Bolgarska ulica",
      "Borovni\u0161ka ulica",
      "Bor\u0161tnikov trg",
      "Borutova ulica",
      "Bo\u017ei\u010deva ulica",
      "Brankova ulica",
      "Bratinova ulica",
      "Bratislavska cesta",
      "Bratov Jakopi\u010dev ulica",
      "Bratov Kunovarjev ulica",
      "Bravni\u010darjeva ulica",
      "Brdnikova ulica",
      "Breg",
      "Bregarjeva ulica",
      "Breznikova ulica",
      "Brglezov \u0161tradon",
      "Brilejeva ulica",
      "Brodarjev trg",
      "Brodska cesta",
      "Burnikova ulica",
      "Cankarjev vrh",
      "Cankarjevo nabre\u017eje",
      "Carja Du\u0161ana ulica",
      "Celar\u010deva ulica",
      "Celjska ulica",
      "Celov\u0161ka cesta",
      "Cerkni\u0161ka ulica",
      "Cerutova ulica",
      "Cesta Andreja Bitenca",
      "Cesta Ceneta \u0160tuparja",
      "Cesta Dolomitskega odreda",
      "Cesta II. grupe odredov",
      "Cesta Ljubljanske brigade",
      "Cesta na Bellevue",
      "Cesta na Bokalce",
      "Cesta na Brinovec",
      "Cesta na Brod",
      "Cesta na Je\u017eah",
      "Cesta na Kope",
      "Cesta na Laze",
      "Cesta na Loko",
      "Cesta na Mesarico",
      "Cesta na Ozare",
      "Cesta na Poljane",
      "Cesta na Prevoje",
      "Cesta na Urh",
      "Cesta na Vrhovce",
      "Cesta slov. kme\u010dkih uporov",
      "Cesta Ur\u0161ke Zatlerjeve",
      "Cesta v Dvor",
      "Cesta v Gameljne",
      "Cesta v Hrastje",
      "Cesta v hrib",
      "Cesta v Kle\u010de",
      "Cesta v Kostanj",
      "Cesta v Legarico",
      "Cesta v Mestni log",
      "Cesta v Pe\u010dale",
      "Cesta v Prod",
      "Cesta v Ro\u017eno dolino",
      "Cesta v \u0160martno",
      "Cesta v Zeleni log",
      "Cesta v Zgornji log",
      "Cesta vstaje",
      "Cesta 24. junija",
      "Cesta 25 talcev",
      "Cesta 27. aprila",
      "Chengdujska cesta",
      "Chopinov prehod",
      "Cigaletova ulica",
      "Cilen\u0161kova ulica",
      "Cimermanova ulica",
      "Cimpermanova ulica",
      "Cizejeva ulica",
      "Clevelandska ulica",
      "Colnarjeva ulica",
      "Cvetli\u010dna pot",
      "\u010campova ulica",
      "\u010can\u017eekova ulica",
      "\u010cargova ulica",
      "\u010cebelarska ulica",
      "\u010cehova ulica",
      "\u010cepelnikova ulica",
      "\u010cepovanska ulica",
      "\u010cerinova ulica",
      "\u010cernigojeva ulica",
      "\u010cerniv\u010deva ulica",
      "\u010cervanova ulica",
      "\u010cevljarska ulica",
      "\u010ci\u017emanova ulica",
      "\u010copova ulica",
      "\u010crna pot",
      "\u010crnu\u0161ka cesta",
      "\u010crtomirova ulica",
      "\u010cu\u010dkova ulica",
      "Dajnkova ulica",
      "Dalmatinova ulica",
      "Danile Kumarjeve ulica",
      "De\u010dkova ulica",
      "De\u010dmanova ulica",
      "Delakova ulica",
      "Dem\u0161arjeva cesta",
      "Der\u010deva ulica",
      "Dergan\u010deva ulica",
      "Dermotova ulica",
      "Detelova ulica",
      "Devinska ulica",
      "Devova ulica",
      "Divjakova ulica",
      "Do proge",
      "Dobraj\u010deva ulica",
      "Dobrdobska ulica",
      "Dolenjska cesta",
      "Dolgi breg",
      "Dolgi most",
      "Dolharjeva ulica",
      "Dolinarjeva ulica",
      "Dolin\u0161kova ulica",
      "Dolni\u010darjeva ulica",
      "Dolomitska ulica",
      "Drabosnjakova ulica",
      "Draga",
      "Draveljska ulica",
      "Dra\u017ego\u0161ka ulica",
      "Drenikov vrh",
      "Drenikova ulica",
      "Dunajska cesta",
      "Dvojna ulica",
      "Dvorakova ulica",
      "Dvorni trg",
      "Eipprova ulica",
      "Ellerjeva ulica",
      "Emonska cesta",
      "Erbe\u017enikova ulica",
      "Erjav\u010deva cesta",
      "Fabianijeva ulica",
      "Fani Grumove ulica",
      "Ferberjeva ulica",
      "Filipi\u010deva ulica",
      "Flaj\u0161manova ulica",
      "Flandrova ulica",
      "Forsterjeva ulica",
      "Franketova ulica",
      "Frankopanska ulica",
      "Frenkova pot",
      "Fri\u0161kovec",
      "Funtkova ulica",
      "Fu\u017einska cesta",
      "Gabrov trg",
      "Ga\u010da",
      "Gali\u010deva ulica",
      "Galjevica",
      "Gallusovo nabre\u017eje",
      "Gasilska cesta",
      "Gasparijeva ulica",
      "Ga\u0161per\u0161i\u010deva ulica",
      "Gerbi\u010deva ulica",
      "Gestrinova ulica",
      "Glavarjeva ulica",
      "Gledali\u0161ka stolba",
      "Glin\u0161ka ulica",
      "Glin\u0161kova plo\u0161\u010dad",
      "Glonarjeva ulica",
      "Gmajnice",
      "Gobarska pot",
      "Gode\u017eeva ulica",
      "Gola Loka",
      "Golarjeva ulica",
      "Goljarjeva pot",
      "Golouhova ulica",
      "Gori\u0161ka ulica",
      "Gorjan\u010deva ulica",
      "Gorjupova ulica",
      "Gornji Rudnik I",
      "Gornji Rudnik II",
      "Gornji Rudnik III",
      "Gornji trg",
      "Gorope\u010dnikova ulica",
      "Gortanova ulica",
      "Gospodinjska ulica",
      "Gosposka ulica",
      "Gosposvetska cesta",
      "Govekarjeva ulica",
      "Gozdna pot",
      "Grablovi\u010deva ulica",
      "Gradi\u0161\u010de",
      "Gradnikova ulica",
      "Grafenauerjeva ulica",
      "Grajski drevored",
      "Grajzerjeva ulica",
      "Gramozna pot",
      "Grassellijeva ulica",
      "Gregor\u010di\u010deva ulica",
      "Gregorinova ulica",
      "Grintov\u0161ka ulica",
      "Grobeljca",
      "Grobeljska pot",
      "Groharjeva cesta",
      "Groznikova ulica",
      "Gr\u0161ka ulica",
      "Gr\u0161ko",
      "Gruberjevo nabre\u017eje",
      "Grudnovo nabre\u017eje",
      "Gub\u010deva ulica",
      "Gunceljska cesta",
      "Gustin\u010darjeva ulica",
      "Gustin\u010di\u010deva ulica",
      "Hacetova ulica",
      "Hafnerjeva ulica",
      "Hajdrihova ulica",
      "Hauptmanca",
      "Hladilni\u0161ka pot",
      "Hladnikova cesta",
      "Hleb\u010deva ulica",
      "Hotimirova ulica",
      "Hradeckega cesta",
      "Hranilni\u0161ka ulica",
      "Hribarjevo nabre\u017eje",
      "Hribernikova ulica",
      "Hribovska pot",
      "Hrva\u0161ka ulica",
      "Hrvatski trg",
      "Hubadova ulica",
      "Hudourni\u0161ka pot",
      "Idrijska ulica",
      "Igri\u0161ka ulica",
      "Ile\u0161i\u010deva ulica",
      "Ilov\u0161ki \u0161tradon",
      "Industrijska cesta",
      "Ingli\u010deva ulica",
      "Italijanska ulica",
      "Izletni\u0161ka ulica",
      "I\u017eanska cesta",
      "Jak\u010deva ulica",
      "Jakhljeva ulica",
      "Jakopi\u010dev drevored",
      "Jakopi\u010devo sprehajali\u0161\u010de",
      "Jak\u0161i\u010deva ulica",
      "Jalnova ulica",
      "Jamova cesta",
      "Jane\u017ei\u010deva cesta",
      "Janova ulica",
      "Jan\u0161eva ulica",
      "Jar\u010deva ulica",
      "Jarnikova ulica",
      "Jar\u0161e",
      "Jar\u0161ka cesta",
      "Javor\u0161kova ulica",
      "Jazbe\u010deva pot",
      "Jelin\u010di\u010deva ulica",
      "Jenkova ulica",
      "Jensenova ulica",
      "Jerajeva ulica",
      "Jeranova ulica",
      "Jesenkova ulica",
      "Jesihov \u0161tradon",
      "Jezerska ulica",
      "Je\u017ea",
      "Je\u017eica",
      "Jo\u0161kov \u0161tradon",
      "Jur\u010di\u010dev trg",
      "Jur\u010dkova cesta",
      "Juri\u010deva ulica",
      "Juvanova ulica",
      "K reaktorju",
      "Kadilnikova ulica",
      "Kajuhova ulica",
      "Kalingerjeva ulica",
      "Kalinova ulica",
      "Kaminova ulica",
      "Kamni\u0161ka ulica",
      "Kamnogori\u0161ka cesta",
      "Kan\u010deva ulica",
      "Kanonijeva cesta",
      "Kantetova ulica",
      "Kapusova ulica",
      "Kardeljeva plo\u0161\u010dad",
      "Karingerjeva ulica",
      "Karunova ulica",
      "Kastel\u010deva ulica",
      "Ka\u0161eljska cesta",
      "Kavadarska cesta",
      "Kav\u010di\u010deva ulica",
      "Kav\u0161kova ulica",
      "Kek\u010deva ulica",
      "Kermaunerjeva ulica",
      "Kernova cesta",
      "Ker\u0161evanova ulica",
      "Ker\u017ei\u010deva ulica",
      "Kettejeva ulica",
      "Kladezna ulica",
      "Klan\u010darjeva ulica",
      "Kle\u010de",
      "Klemenova ulica",
      "Kleparska steza",
      "Klju\u010davni\u010darska ulica",
      "Klunova ulica",
      "Kme\u010dka pot",
      "Knafljev prehod",
      "Knezov \u0161tradon",
      "Knezova ulica",
      "Knobleharjeva ulica",
      "Koblarjeva ulica",
      "Kocbekova ulica",
      "Kocenova ulica",
      "Kocjanova ulica",
      "Ko\u010denska ulica",
      "Kodrova ulica",
      "Kogojeva ulica",
      "Kogov\u0161kova ulica",
      "Kokaljeva ulica",
      "Kolarjeva ulica",
      "Kolesarska pot",
      "Kole\u0161eva ulica",
      "Kolinska ulica",
      "Kolmanova ulica",
      "Kolodvorska ulica",
      "Komanova ulica",
      "Komenskega ulica",
      "Kongresni trg",
      "Kopali\u0161ka ulica",
      "Kopitarjeva ulica",
      "Kopna pot",
      "Koprska ulica",
      "Koreninova ulica",
      "Koro\u0161ka ulica",
      "Korotanska ulica",
      "Kosan\u010deva ulica",
      "Koseskega ulica",
      "Kose\u0161ka cesta",
      "Kosma\u010deva ulica",
      "Kosova ulica",
      "Kosovelova ulica",
      "Ko\u0161irjeva ulica",
      "Kotnikova ulica",
      "Kova\u010deva ulica",
      "Kova\u0161ka ulica",
      "Kovinarska ulica",
      "Kozakova ulica",
      "Kozinova ulica",
      "Kozlarjeva pot",
      "Ko\u017eeljeva ulica",
      "Krakovski nasip",
      "Kraljeva ulica",
      "Kranerjeva ulica",
      "Kra\u0161ka ulica",
      "Kratka pot",
      "Kratka steza",
      "Kregarjeva ulica",
      "Kreljeva ulica",
      "Krem\u017earjeva ulica",
      "Krimska ulica",
      "Kri\u0161tofova ulica",
      "Kriva pot",
      "Krivec",
      "Kri\u017eevni\u0161ka soteska",
      "Kri\u017ena ulica",
      "Krm\u010deva ulica",
      "Krmeljeva ulica",
      "Kropova ulica",
      "Kro\u0161ljeva ulica",
      "Krovska ulica",
      "Kro\u017ena pot",
      "Kr\u017ei\u010deva ulica",
      "Kudrova ulica",
      "Kuhljeva cesta",
      "Kumerdejeva ulica",
      "Kumerjeve ulica",
      "Kumrov\u0161ka ulica",
      "Kurilni\u0161ka ulica",
      "Kurirska ulica",
      "Kusoldova ulica",
      "Ku\u0161trinova ulica",
      "Kuzeletova ulica",
      "Kuzmi\u010deva ulica",
      "Lahova pot",
      "Lajov\u010deva ulica",
      "Laknerjeva ulica",
      "Lakotence",
      "Lampetova ulica",
      "Lamutova ulica",
      "Langusova ulica",
      "Latinski trg",
      "Lavrinova ulica",
      "Layerjeva ulica",
      "Lazarjeva ulica",
      "Legatova ulica",
      "Leme\u017eeva ulica",
      "Lepi pot",
      "Lepodvorska ulica",
      "Leskovi\u010deva ulica",
      "Letali\u0161ka cesta",
      "Levarjeva ulica",
      "Levi\u010dnikova ulica",
      "Levstikov trg",
      "Levstikova ulica",
      "Linhartov podhod",
      "Linhartova cesta",
      "Lipahova ulica",
      "Litijska cesta",
      "Litostrojska cesta",
      "Livada",
      "Livarska ulica",
      "Lo\u010dnikarjeva ulica",
      "Lon\u010darska steza",
      "Lorenzova cesta",
      "Lovren\u010di\u010deva ulica",
      "Lovska ulica",
      "Lov\u0161etova ulica",
      "Lubejeva ulica",
      "Luize Pesjakove ulica",
      "Luna\u010dkova ulica",
      "Ma\u010dja steza",
      "Ma\u010dkov kot",
      "Ma\u010dkova ulica",
      "Mad\u017earska ulica",
      "Magistrova ulica",
      "Maistrova ulica",
      "Majaronova ulica",
      "Majde Vrhovnikove ulica",
      "Majorja Lavri\u010da ulica",
      "Makucova ulica",
      "Mala ulica",
      "Mala vas",
      "Malejeva ulica",
      "Malen\u0161kova ulica",
      "Malgajeva ulica",
      "Mali \u0161tradon",
      "Mali trg",
      "Malnarjeva ulica",
      "Mar\u010denkova ulica",
      "Marenti\u010deva ulica",
      "Mare\u0161ka pot",
      "Marice Kova\u010deve ulica",
      "Marincljeva ulica",
      "Marinov\u0161eva cesta",
      "Maroltova ulica",
      "Martina Krpana ulica",
      "Martin\u010deva ulica",
      "Martinova ulica",
      "Maru\u0161i\u010deva ulica",
      "Masarykova cesta",
      "Matjanova pot",
      "Matja\u017eeva ulica",
      "Maurerjeva ulica",
      "Mazov\u010deva pot",
      "Med hmeljniki",
      "Medarska ulica",
      "Medenska cesta",
      "Medve\u0161\u010dkova ulica",
      "Mekin\u010deva ulica",
      "Melikova ulica",
      "Mencingerjeva ulica",
      "Mer\u010dnikova ulica",
      "Merosodna ulica",
      "Mesesnelova ulica",
      "Mestni trg",
      "Me\u0161kova ulica",
      "Metelkova ulica",
      "Miheli\u010deva cesta",
      "Mihov \u0161tradon",
      "Miklav\u010deva ulica",
      "Miklo\u0161i\u010deva cesta",
      "Miku\u017eeva ulica",
      "Mil\u010detova pot",
      "Mire Lenardi\u010deve ulica",
      "Mirje",
      "Mirna pot",
      "Mislejeva ulica",
      "Mizarska pot",
      "Mladinska ulica",
      "Mlake",
      "Mlinska pot",
      "Mo\u010dnikova ulica",
      "Mokr\u0161ka ulica",
      "Molekova ulica",
      "Mo\u0161kri\u010deva ulica",
      "Mrharjeva ulica",
      "Mrzelova ulica",
      "Murkova ulica",
      "Murnikova ulica",
      "Murnova ulica",
      "Muzejska ulica",
      "Na cveta\u010di",
      "Na delih",
      "Na dolih",
      "Na gaju",
      "Na gmajni",
      "Na Her\u0161i",
      "Na jami",
      "Na klan\u010dku",
      "Na Koro\u0161ci",
      "Na Palcah",
      "Na po\u017earu",
      "Na produ",
      "Na Rojah",
      "Na Stolbi",
      "Na Stra\u0161ki vrh",
      "Na Trati",
      "Na \u017dalah",
      "Nade Ov\u010dakove ulica",
      "Nadgori\u0161ka cesta",
      "Nahlikova ulica",
      "Nahtigalova ulica",
      "Nano\u0161ka ulica",
      "Nazorjeva ulica",
      "Neboti\u010dnikov prehod",
      "Nedohova ulica",
      "Njego\u0161eva cesta",
      "Nova ulica",
      "Novakova pot",
      "Novakova ulica",
      "Novi trg",
      "Novinarska ulica",
      "Novo naselje",
      "Novo Polje, cesta I",
      "Novo Polje, cesta III",
      "Novo Polje, cesta IV",
      "Novo Polje, cesta V",
      "Novo Polje, cesta VI",
      "Novo Polje, cesta VII",
      "Novo Polje, cesta X",
      "Novo Polje, cesta XI",
      "Novo Polje, cesta XII",
      "Novo Polje, cesta XIV",
      "Novo Polje, cesta XIX",
      "Novo Polje, cesta XVI",
      "Novo Polje, cesta XVII",
      "Novo Polje, cesta XXI",
      "Novo Polje, cesta XXIII",
      "Novosadska ulica",
      "Ob daljnovodu",
      "Ob dolenjski \u017eeleznici",
      "Ob Farjevcu",
      "Ob Ljubljanici",
      "Ob Meja\u0161u",
      "Ob potoku",
      "Ob pristanu",
      "Ob Savi",
      "Ob studencu",
      "Ob zdravstvenem domu",
      "Ob zeleni jami",
      "Ob zelenici",
      "Ob \u017eici",
      "Obirska ulica",
      "Obre\u017ena steza",
      "Obrije",
      "Ocvirkova ulica",
      "Ogrin\u010deva ulica",
      "Oki\u0161kega ulica",
      "Omahnova ulica",
      "Omej\u010deva ulica",
      "Omersova ulica",
      "Ora\u017enova ulica",
      "Orlova ulica",
      "Osenjakova ulica",
      "Osojna pot",
      "Osojna steza",
      "Oster\u010deva ulica",
      "Ov\u010dakova ulica",
      "Pahorjeva ulica",
      "Palmejeva ulica",
      "Papirni\u0161ka pot",
      "Park Ajdov\u0161\u010dina",
      "Park Arturo Toscanini",
      "Parmova ulica",
      "Parmska cesta",
      "Partizanska ulica",
      "Pavlov\u010deva ulica",
      "Pav\u0161i\u010deva ulica",
      "Pe\u010darjeva ulica",
      "Pe\u010dnik",
      "Pe\u010dnikova ulica",
      "Pegamova ulica",
      "Per\u010deva ulica",
      "Peri\u0161ka cesta",
      "Perkova ulica",
      "Per\u0161inova cesta",
      "Pesarska cesta",
      "Pestotnikova ulica",
      "Pe\u0161\u010dena pot",
      "Petkova ulica",
      "Petkov\u0161kovo nabre\u017eje",
      "Petr\u010deva ulica",
      "Pilonova ulica",
      "Pionirska pot",
      "Pipanova pot",
      "Pirnatova ulica",
      "Planinska cesta",
      "Planin\u0161kova ulica",
      "Ple\u010dnikov podhod",
      "Plemljeva ulica",
      "Ple\u0161i\u010deva ulica",
      "Pleter\u0161nikova ulica",
      "Plo\u010danska ulica",
      "Pod akacijami",
      "Pod bregom",
      "Pod bresti",
      "Pod bukvami",
      "Pod Debnim vrhom",
      "Pod gabri",
      "Pod gozdom",
      "Pod hrasti",
      "Pod hribom",
      "Pod hru\u0161ko",
      "Pod jel\u0161ami",
      "Pod jezom",
      "Pod je\u017eami",
      "Pod Kamno gorico",
      "Pod klancem",
      "Pod lipami",
      "Pod topoli",
      "Pod Tran\u010do",
      "Pod turnom",
      "Pod vrbami",
      "Podgornikova ulica",
      "Podgorska cesta",
      "Podgrajska cesta",
      "Podjunska ulica",
      "Podlimbarskega ulica",
      "Podmil\u0161\u010dakova ulica",
      "Podro\u017eni\u0161ka pot",
      "Podsmre\u0161ka cesta",
      "Poduti\u0161ka cesta",
      "Poga\u010darjev trg",
      "Pohlinova ulica",
      "Poklukarjeva ulica",
      "Polakova ulica",
      "Polan\u0161kova ulica",
      "Poljanska cesta",
      "Polje",
      "Polje, cesta I",
      "Polje, cesta II",
      "Polje, cesta III",
      "Polje, cesta VI",
      "Polje, cesta VIII",
      "Polje, cesta X",
      "Polje, cesta XIV",
      "Polje, cesta XL",
      "Polje, cesta XLII",
      "Polje, cesta XLVI",
      "Polje, cesta XVI",
      "Polje, cesta XVIII",
      "Polje, cesta XXII",
      "Polje, cesta XXIV",
      "Polje, cesta XXVI",
      "Polje, cesta XXX",
      "Polje, cesta XXXII",
      "Polje, cesta XXXIV",
      "Polje, cesta XXXVIII",
      "Poljedelska ulica",
      "Poljska pot",
      "Porentova ulica",
      "Posavskega ulica",
      "Postojnska ulica",
      "Pot do \u0161ole",
      "Pot Draga Jakopi\u010da",
      "Pot heroja Trtnika",
      "Pot k igri\u0161\u010du",
      "Pot k ribniku",
      "Pot k Savi",
      "Pot k sejmi\u0161\u010du",
      "Pot k studencu",
      "Pot na Breje",
      "Pot na Drenikov vrh",
      "Pot na Golovec",
      "Pot na goro",
      "Pot na Gradi\u0161\u010de",
      "Pot na Gri\u010d",
      "Pot na Labar",
      "Pot na mah",
      "Pot na most",
      "Pot na Orle",
      "Pot na Visoko",
      "Pot na Zdu\u0161e",
      "Pot Rde\u010dega kri\u017ea",
      "Pot v bor\u0161t",
      "Pot v \u010ce\u017eelj",
      "Pot v dolino",
      "Pot v Gori\u010dico",
      "Pot v hribec",
      "Pot v mejah",
      "Pot v Mlake",
      "Pot v Podgorje",
      "Pot v Zeleni gaj",
      "Pot za Brdom",
      "Pot za razori",
      "Potokarjeva ulica",
      "Potr\u010deva ulica",
      "Pov\u0161etova ulica",
      "Pra\u0161nikarjeva ulica",
      "Praznikova ulica",
      "Pra\u017eakova ulica",
      "Pred Savljami",
      "Predjamska cesta",
      "Predor pod Gradom",
      "Preglov trg",
      "Prekmurska ulica",
      "Prel\u010deva ulica",
      "Preloge",
      "Premrlova ulica",
      "Preradovi\u0107eva ulica",
      "Preserska ulica",
      "Pre\u0161ernov trg",
      "Pre\u0161ernova cesta",
      "Pretnarjeva ulica",
      "Pri bor\u0161tu",
      "Pri brvi",
      "Pri malem kamnu",
      "Pri mosti\u0161\u010darjih",
      "Pribinova ulica",
      "Prijateljeva ulica",
      "Primorska ulica",
      "Prin\u010di\u010deva ulica",
      "Prisojna ulica",
      "Pri\u0161tinska ulica",
      "Privoz",
      "Proletarska cesta",
      "Prule",
      "Pru\u0161nikova ulica",
      "Prvomajska ulica",
      "P\u0161atnik",
      "P\u0161atska pot",
      "Ptujska ulica",
      "Pu\u010dnikova ulica",
      "Puharjeva ulica",
      "Puhova ulica",
      "Puhtejeva ulica",
      "Puterlejeva ulica",
      "Putrihova ulica",
      "Rai\u010deva ulica",
      "Rakovni\u0161ka ulica",
      "Raku\u0161eva ulica",
      "Ramov\u0161eva ulica",
      "Ravbarjeva ulica",
      "Ravna pot",
      "Ravnikova ulica",
      "Razgledna steza",
      "Reber",
      "Reboljeva ulica",
      "Re\u010dna ulica",
      "Regentova cesta",
      "Resljeva cesta",
      "Re\u0161ka ulica",
      "Ribi\u010di\u010deva ulica",
      "Ribji trg",
      "Ribni\u0161ka ulica",
      "Rimska cesta",
      "Rjava cesta",
      "Robbova ulica",
      "Robi\u010deva ulica",
      "Rodi\u010deva ulica",
      "Roj\u010deva ulica",
      "Romavhova ulica",
      "Rosna pot",
      "Rotarjeva ulica",
      "Rov\u0161nikova ulica",
      "Rozmanova ulica",
      "Ro\u017eanska ulica",
      "Ro\u017ei\u010deva ulica",
      "Ro\u017ena dolina, cesta I",
      "Ro\u017ena dolina, cesta III",
      "Ro\u017ena dolina, cesta IV",
      "Ro\u017ena dolina, cesta V",
      "Ro\u017ena dolina, cesta VI",
      "Ro\u017ena dolina, cesta VIII",
      "Ro\u017ena dolina, cesta X",
      "Ro\u017ena dolina, cesta XII",
      "Ro\u017ena dolina, cesta XIII",
      "Ro\u017ena dolina, cesta XV",
      "Ro\u017ena dolina, cesta XVII",
      "Ro\u017ena ulica",
      "Rudnik I",
      "Rudnik II",
      "Rudnik III",
      "Runkova ulica",
      "Ruska ulica",
      "Rutarjeva ulica",
      "Sadinja vas",
      "Sajov\u010deva ulica",
      "Samova ulica",
      "Sa\u0161kova ulica",
      "Sattnerjeva ulica",
      "Savinova ulica",
      "Savin\u0161kova ulica",
      "Savlje",
      "Savska cesta",
      "Sedejeva ulica",
      "Selanov trg",
      "Selanova ulica",
      "Setnikarjeva ulica",
      "Seunigova ulica",
      "Simon\u010di\u010deva ulica",
      "Siva pot",
      "Skapinova ulica",
      "Sketova ulica",
      "Skop\u010deva ulica",
      "Skrbin\u0161kova ulica",
      "Slape",
      "Slapnikova ulica",
      "Slav\u010dja ulica",
      "Slom\u0161kova ulica",
      "Sloven\u010deva ulica",
      "Slovenska cesta",
      "Smoletova ulica",
      "Smrekarjeva ulica",
      "Smrtnikova ulica",
      "Snebersko nabre\u017eje",
      "Sne\u017eni\u0161ka ulica",
      "Snojeva ulica",
      "Sojerjeva ulica",
      "Son\u010dna pot",
      "Sostrska cesta",
      "So\u0161ka ulica",
      "Sote\u0161ka pot",
      "Soussenska ulica",
      "Sovretova ulica",
      "Spodnji Rudnik I",
      "Spodnji Rudnik II",
      "Spodnji Rudnik III",
      "Spodnji Rudnik V",
      "Spomeni\u0161ka pot",
      "Srebrni\u010deva ulica",
      "Srednja pot",
      "Stadionska ulica",
      "Stani\u010deva ulica",
      "Stara Je\u017eica",
      "Stara slovenska ulica",
      "Stare \u010crnu\u010de",
      "Stari trg",
      "Stegne",
      "Steletova ulica",
      "Sternadova ulica",
      "Sti\u0161ka ulica",
      "Stolpni\u0161ka ulica",
      "Sto\u017eenska ulica",
      "Sto\u017eice",
      "Stra\u017earjeva ulica",
      "Streli\u0161ka ulica",
      "Stritarjeva ulica",
      "Strmeckijeva ulica",
      "Strmi pot",
      "Strni\u0161eva cesta",
      "Strossmayerjeva ulica",
      "Strugarska ulica",
      "Strupijevo nabre\u017eje",
      "Suhadol\u010danova ulica",
      "Sul\u010dja ulica",
      "Svet\u010deva ulica",
      "\u0160arhova ulica",
      "\u0160entjakob",
      "\u0160entvi\u0161ka ulica",
      "\u0160erkova ulica",
      "\u0160estova ulica",
      "\u0160ibeni\u0161ka ulica",
      "\u0160inkov \u0161tradon",
      "\u0160i\u0161enska cesta",
      "\u0160ivi\u010deva ulica",
      "\u0160kerljeva ulica",
      "\u0160kofova ulica",
      "\u0160krab\u010deva ulica",
      "\u0160landrova ulica",
      "\u0160losarjeva ulica",
      "\u0160marna gora",
      "\u0160martinska cesta",
      "\u0160martno",
      "\u0160panova pot",
      "\u0160panska ulica",
      "\u0160tajerska cesta",
      "\u0160tebijeva cesta",
      "\u0160tefan\u010deva ulica",
      "\u0160tembalova ulica",
      "\u0160tepanjska cesta",
      "\u0160tepanjsko nabre\u017eje",
      "\u0160tirnova ulica",
      "\u0160tradon \u010dez Pro\u0161co",
      "\u0160trekljeva ulica",
      "\u0160tudentovska ulica",
      "\u0160tukljeva cesta",
      "\u0160tula",
      "\u0160turmova ulica",
      "\u0160ubi\u010deva ulica",
      "\u0160umarjeva ulica",
      "\u0160vabi\u0107eva ulica",
      "\u0160varova ulica",
      "\u0160vegljeva cesta",
      "Tabor",
      "Tacenska cesta",
      "Tav\u010darjeva ulica",
      "Tbilisijska ulica",
      "Tesarska ulica",
      "Teslova ulica",
      "Tesna ulica",
      "Tesovnikova ulica",
      "Tiha ulica",
      "Tiranova ulica",
      "Tischlerjeva ulica",
      "Tivolska cesta",
      "Tkalska ulica",
      "Toba\u010dna ulica",
      "Tolminska ulica",
      "Toma\u010devo",
      "Toma\u010devska cesta",
      "Toma\u017ei\u010deva ulica",
      "Tometova ulica",
      "Tomin\u0161kova ulica",
      "Tomi\u0161eljska ulica",
      "Toplarni\u0161ka ulica",
      "Topni\u0161ka ulica",
      "Torkarjeva ulica",
      "Tratnikova ulica",
      "Travni\u0161ka ulica",
      "Trbe\u017ee",
      "Trdinova ulica",
      "Trebu\u0161akova ulica",
      "Trg francoske revolucije",
      "Trg mladih",
      "Trg mladinskih delov. brigad",
      "Trg narodnih herojev",
      "Trg prekomorskih brigad",
      "Trg republike",
      "Trg 9. maja",
      "Trinkova ulica",
      "Trnov\u010deva ulica",
      "Trnovska ulica",
      "Trpin\u010deva ulica",
      "Trstenjakova ulica",
      "Trtnikova ulica",
      "Tr\u017ea\u0161ka cesta",
      "Tr\u017ena ulica",
      "Tugomerjeva ulica",
      "Turnerjeva ulica",
      "Turnsko nabre\u017eje",
      "Udvan\u010deva ulica",
      "Ulica aktivistov",
      "Ulica Alme Sodnik",
      "Ulica Andreja Kumarja",
      "Ulica Angelce Ocepkove",
      "Ulica Angele Ljubi\u010deve",
      "Ulica borca Petra",
      "Ulica borcev za severno mejo",
      "Ulica bratov Bezlajev",
      "Ulica bratov Blan\u010d",
      "Ulica bratov Jan\u010dar",
      "Ulica bratov Komel",
      "Ulica bratov Kralji\u010d",
      "Ulica bratov Martinec",
      "Ulica bratov Novak",
      "Ulica bratov Rozmanov",
      "Ulica bratov \u0160kofov",
      "Ulica bratov U\u010dakar",
      "Ulica bratov \u017didan",
      "Ulica Du\u0161ana Kraigherja",
      "Ulica Ernesta Kramerja",
      "Ulica Franca Nebca",
      "Ulica Francke Jerasove",
      "Ulica Franja Novaka",
      "Ulica gledali\u0161\u010da BTC",
      "Ulica Goce Del\u010deva",
      "Ulica Gub\u010deve brigade",
      "Ulica Hermana Poto\u010dnika",
      "Ulica Ivana Roba",
      "Ulica Ivanke Ko\u017euh",
      "Ulica Ivice Pirjev\u010deve",
      "Ulica Janeza Pavla II.",
      "Ulica Janeza Ro\u017ei\u010da",
      "Ulica Jo\u017eeta Jame",
      "Ulica Jo\u017eeta Japlja",
      "Ulica Jo\u017eeta Mirti\u010da",
      "Ulica Konrada Babnika",
      "Ulica Koro\u0161kega bataljona",
      "Ulica Lizike Jan\u010darjeve",
      "Ulica Lojzeta Spacala",
      "Ulica Lovre Klemen\u010di\u010da",
      "Ulica Mal\u010di Beli\u010deve",
      "Ulica Marije Drakslerjeve",
      "Ulica Marije Hvali\u010deve",
      "Ulica Marje Bor\u0161nikove",
      "Ulica Marka \u0160lajmerja",
      "Ulica Milana Majcna",
      "Ulica Milke Kerinove",
      "Ulica Minke Bobnar",
      "Ulica Mirka Jurce",
      "Ulica Mirka Tom\u0161i\u010da",
      "Ulica Miroslava Turka",
      "Ulica Molni\u0161ke \u010dete",
      "Ulica na Grad",
      "Ulica Nade \u010camernikove",
      "Ulica Olge Mohorjeve",
      "Ulica padlih borcev",
      "Ulica Pari\u0161ke komune",
      "Ulica Pohorskega bataljona",
      "Ulica Polonce \u010cude",
      "Ulica prvoborcev",
      "Ulica Rezke Dragarjeve",
      "Ulica Rezke Klop\u010di\u010d",
      "Ulica Rudolfa Jane\u017ei\u010da",
      "Ulica Staneta Severja",
      "Ulica \u0160tefke Zba\u0161nikove",
      "Ulica talcev",
      "Ulica Ton\u010dke \u010ce\u010deve",
      "Ulica v Kokov\u0161ek",
      "Ulica Vide Pregar\u010deve",
      "Ulica Vladimirja Trampu\u017ea",
      "Ulica Zore Ragancinove",
      "Ulica \u017danke Erjavec",
      "Ulica 15. aprila",
      "Ulica 15. maja",
      "Ulica 24. avgusta",
      "Ulica 4. julija",
      "Ulica 7. septembra",
      "Ulica 9. junija",
      "Ur\u0161i\u010dev \u0161tradon",
      "Usnjarska ulica",
      "V \u010ce\u0161njico",
      "V dolini",
      "V Karlovce",
      "V Karlovce",
      "V Kladeh",
      "V Murglah",
      "V Sige",
      "V Varde",
      "V Zalar",
      "Vagajeva ulica",
      "Valjav\u010deva ulica",
      "Valvasorjeva ulica",
      "Vandotova ulica",
      "Va\u0161ka pot",
      "Ve\u010dna pot",
      "Vegova ulica",
      "Velebitska ulica",
      "Veliki \u0161tradon",
      "Velikov\u0161ka ulica",
      "Velnarjeva ulica",
      "Verov\u0161kova ulica",
      "Ver\u0161i\u010deva ulica",
      "Veselova ulica",
      "Videmska ulica",
      "Vidergarjeva ulica",
      "Vidi\u010deva ulica",
      "Vidovdanska cesta",
      "Vilharjev podhod",
      "Vilharjeva cesta",
      "Vinterca",
      "Vipavska ulica",
      "Vipotnikova ulica",
      "Vi\u0161ka cesta",
      "Vi\u017emarska pot",
      "Vodmatska ulica",
      "Vodmatski trg",
      "Vodna steza",
      "Vodnikova cesta",
      "Vodnikovo naselje",
      "Vodovodna cesta",
      "Vogelna ulica",
      "Vojkova cesta",
      "Volari\u010deva ulica",
      "Vo\u0161njakova ulica",
      "Vozna pot na Grad",
      "Vo\u017earski pot",
      "Vrazov trg",
      "Vrbovec",
      "Vrbska ulica",
      "Vregova ulica",
      "Vrhovci, cesta I",
      "Vrhovci, cesta II",
      "Vrhovci, cesta III",
      "Vrhovci, cesta IX",
      "Vrhovci, cesta V",
      "Vrhovci, cesta VI",
      "Vrhovci, cesta X",
      "Vrhovci, cesta XI",
      "Vrhovci, cesta XII",
      "Vrhovci, cesta XIV",
      "Vrhovci, cesta XIX",
      "Vrhovci, cesta XV",
      "Vrhovci, cesta XVII",
      "Vrhovci, cesta XVIII",
      "Vrhovci, cesta XX",
      "Vrhovci, cesta XXII",
      "Vrhovci, cesta XXVI",
      "Vrhovci, cesta XXVIII",
      "Vrhovci, cesta XXXII",
      "Vrhov\u010deva ulica",
      "Vrhovnikova ulica",
      "Vrta\u010da",
      "Vrtna ulica",
      "Vrtnarska cesta",
      "Vul\u010deva ulica",
      "Vzajemna ulica",
      "Windischerjeva ulica",
      "Wolfova ulica",
      "Za Gara\u017eami",
      "Za gasilskim domom",
      "Za Gradom",
      "Za krajem",
      "Za opekarno",
      "Za partizanskim domom",
      "Za progo",
      "Za vasjo",
      "Zadnikarjeva ulica",
      "Zadobrov\u0161ka cesta",
      "Zadru\u017ena ulica",
      "Zaj\u010deva pot",
      "Zaj\u010devi dvori",
      "Zakotnikova ulica",
      "Zalaznikova ulica",
      "Zaletelova ulica",
      "Zalo\u0161ka cesta",
      "Zarnikova ulica",
      "Zasavska cesta",
      "Zati\u0161je",
      "Zaveti\u0161ka ulica",
      "Zavr\u0161je",
      "Zba\u0161nikova ulica",
      "Zde\u0161arjeva cesta",
      "Zelena pot",
      "Zelenova ulica",
      "Zeljarska ulica",
      "Zevnikova ulica",
      "Zidarjev \u0161tradon",
      "Ziherlova ulica",
      "Zlatek",
      "Znamenjska ulica",
      "Zofke Kvedrove ulica",
      "Zoisova cesta",
      "Zupanova ulica",
      "Zvezda",
      "Zvezdarska ulica",
      "Zvezna ulica",
      "\u017dabarjeva ulica",
      "\u017dabjak",
      "\u017dalska ulica",
      "\u017daucerjeva ulica",
      "\u017deje",
      "\u017delezna cesta",
      "\u017deleznikarjeva ulica",
      "\u017derjalova ulica",
      "\u017didankova ulica",
      "\u017didovska steza",
      "\u017didovska ulica",
      "\u017divali\u010deva ulica",
      "\u017divinozdravska ulica",
      "\u017dolgerjeva ulica"
    ),

    states = c(
      "Pomurksa",
      "Podravska",
      "Koro\u0161ka",
      "Savinjska",
      "Zasavska",
      "Spodnjeposavska",
      "Jugovzhodna Slovenija",
      "Osrednjeslovenska",
      "Gorenjska",
      "Notranjsko - kra\u0161ka",
      "Gori\u0161ka",
      "Obalno - kra\u0161ka"
    ),

    countries = c(
      "Afganistan",
      "Islamska republika Afganistan",
      "Albanija",
      "Al\u017eirija",
      "Ljudska demokrati\u010dna republika Al\u017eirija",
      "Andora",
      "Angola",
      "Republika Angola",
      "Antigva in Barbuda",
      "Argentina",
      "Armenija",
      "Republika Armenija",
      "Avstralija",
      "Avstrija",
      "Azerbajd\u017ean",
      "Azerbajd\u017eanska republika",
      "Bahami",
      "Zveza Bahami",
      "Dr\u017eava Bahrajn",
      "Banglade\u0161",
      "Ljudska republika Banglade\u0161",
      "Belgija",
      "Kraljevina Belgija",
      "Belize",
      "Belorusija",
      "Benin",
      "Republika Benin",
      "Bocvana",
      "Republika Bocvana",
      "Republika Bolgarija",
      "Bolivija",
      "Republika Bolivija",
      "Brazilija",
      "Federativna republika Brazilija",
      "Brunej",
      "Burkina Faso",
      "Burundi",
      "Republika Burundi",
      "Butan",
      "Ciper",
      "Republika Ciper",
      "\u010cad",
      "Republika \u010cad",
      "\u010ce\u0161ka",
      "\u010cile",
      "Republika \u010cile",
      "\u010crna gora",
      "Republika \u010crna gora",
      "Kraljevina Danska",
      "Dominika",
      "Zveza Dominika",
      "D\u017eibuti",
      "Republika D\u017eibuti",
      "Egipt",
      "Arabska republika Egipt",
      "Republika Ekvador",
      "Ekvatorialna Gvineja",
      "Eritreja",
      "Estonija",
      "Republika Estonija",
      "Etiopija",
      "Fid\u017ei",
      "Filipini",
      "Republika Filipini",
      "Finska",
      "Republika Finska",
      "Francoska republika",
      "Gabon",
      "Gabonska republika",
      "Gambija",
      "Gana",
      "Republika Gana",
      "Gr\u010dija",
      "Helenska republika",
      "Grenada",
      "Gvajana",
      "Republika Gvajana",
      "Gvatemala",
      "Republika Gvatemala",
      "Republika Gvineja",
      "Gvineja Bissau",
      "Republika Gvineja Bissau",
      "Republika Haiti",
      "Honduras",
      "Republika Honduras",
      "Hrva\u0161ka",
      "Indija",
      "Republika Indija",
      "Indonezija",
      "Republika Indonezija",
      "Republika Irak",
      "Iran",
      "Islamska republika Iran",
      "Irska",
      "Republika Islandija",
      "Italija",
      "Italijanska republika",
      "Izrael",
      "Jamajka",
      "Japonska",
      "Jemen",
      "Republika Jemen",
      "Jordanija",
      "Ju\u017ena Afrika",
      "Republika Ju\u017ena Afrika",
      "Ju\u017ena Koreja",
      "Kambod\u017ea",
      "Kraljevina Kambod\u017ea",
      "Kamerun",
      "Republika Kamerun",
      "Katar",
      "Dr\u017eava Katar",
      "Kazahstan",
      "Republika Kazahstan",
      "Kenija",
      "Kirgizistan",
      "Kirgi\u0161ka republika",
      "Kiribati",
      "Kitajska",
      "Kolumbija",
      "Republika Kolumbija",
      "Komori",
      "Kongo",
      "Republika Kongo",
      "Demokrati\u010dna republika Kongo",
      "Republika Kostarika",
      "Kuba",
      "Republika Kuba",
      "Kuvajt",
      "Laos",
      "Lao\u0161ka ljudska demokrati\u010dna republika",
      "Latvija",
      "Lesoto",
      "Kraljevina Lesoto",
      "Libanon",
      "Libanonska republika",
      "Republika Liberija",
      "Libija",
      "Libijska arabska d\u017eamahirija",
      "Lihten\u0161tajn",
      "Kne\u017eevina Lihten\u0161tajn",
      "Litva",
      "Republika Litva",
      "Veliko vojvodstvo Luksemburg",
      "Madagaskar",
      "Republika Madagaskar",
      "Republika Mad\u017earska",
      "Makedonija",
      "Republika Makedonija",
      "Malavi",
      "Maldivi",
      "Republika Maldivi",
      "Malezija",
      "Mali",
      "Republika Mali",
      "Republika Malta",
      "Maroko",
      "Kraljevina Maroko",
      "Marshallovi otoki",
      "Mauritius",
      "Republika Mauritius",
      "Mavretanija",
      "Mehika",
      "Zdru\u017eene mehi\u0161ke dr\u017eave",
      "Mikronezija",
      "Mjanmar",
      "Zveza Mjanmar",
      "Moldavija",
      "Moldavija, Republika",
      "Kne\u017eevina Monako",
      "Mongolija",
      "Mozambik",
      "Republika Mozambik",
      "Republika Namibija",
      "Nauru",
      "Republika Nauru",
      "Nem\u010dija",
      "Nepal",
      "Kraljevina Nepal",
      "Niger",
      "Republika Niger",
      "Nigerija",
      "Nikaragva",
      "Republika Nikaragva",
      "Nizozemska",
      "Norve\u0161ka",
      "Kraljevina Norve\u0161ka",
      "Nova Zelandija",
      "Oman",
      "Pakistan",
      "Islamska republika Pakistan",
      "Palau",
      "Republika Palau",
      "Republika Panama",
      "Papua Nova Gvineja",
      "Paragvaj",
      "Peru",
      "Republika Peru",
      "Poljska",
      "Republika Poljska",
      "Portugalska republika",
      "Romunija",
      "Ruanda",
      "Republika Ruanda",
      "Ruska federacija",
      "Saint Kitts in Nevis",
      "Saint Lucia",
      "Salomonovi otoki",
      "Salvador",
      "Republika Salvador",
      "San Marino",
      "Sao Tome in Principe",
      "Demokrati\u010dna republika Sao Tome in Principe",
      "Kraljevina Saudova Arabija",
      "Sej\u0161eli",
      "Republika Sej\u0161eli",
      "Republika Senegal",
      "Severna Koreja",
      "Sierra Leone",
      "Republika Sierra Leone",
      "Singapur",
      "Sirija",
      "Sirska arabska republika",
      "Slonoko\u0161\u010dena obala",
      "Slova\u0161ka",
      "Slova\u0161ka republika",
      "Slovenija",
      "Republika Slovenija",
      "Somalska demokrati\u010dna republika",
      "Srbija",
      "Republika Srbija",
      "Sudan",
      "Republika Sudan",
      "Surinam",
      "Republika Surinam",
      "Svazi",
      "\u0160panija",
      "Kraljevina \u0160panija",
      "\u0160rilanka",
      "\u0160vedska",
      "Kraljevina \u0160vedska",
      "\u0160vica",
      "Tad\u017eikistan",
      "Republika Tad\u017eikistan",
      "Tajska",
      "Tajvan",
      "Tajvan, Provinca Kitajske",
      "Tanzanija",
      "Togo",
      "Togo\u0161ka republika",
      "Tonga",
      "Kraljevina Tonga",
      "Republika Trinidad in Tobago",
      "Tunizija",
      "Republika Tunizija",
      "Republika Tur\u010dija",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukrajina",
      "Urugvaj",
      "Vzhodna republika Urugvaj",
      "Uzbekistan",
      "Vanuatu",
      "Republika Vanuatu",
      "Vatikan",
      "Velika Britanija",
      "Zdru\u017eeno kraljestvo",
      "Venezuela",
      "Republika Venezuela",
      "Vietnam",
      "Vzhodni Timor",
      "Demokrati\u010dna republika Vzhodni Timor",
      "Samoa",
      "Neodvisna dr\u017eava Zahodna Samoa",
      "Zambija",
      "Zdru\u017eene dr\u017eave Amerike",
      "Zdru\u017eene dr\u017eave",
      "Zdru\u017eeni arabski emirati",
      "Zelenortski otoki"
    )
  ),

  public = list(
    city_name = function(){
      return(private$random_element(private$cities))
    },

    street_name = function(){
      return(private$random_element(private$streets))
    },

    state = function(){
      return(private$random_element(private$states))
    }
  )
)

# internet -----------------------------------------
internet_sl_SI = R6Class(
  "internet_sl_SI",
  inherit = internet_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_en_US$new())$.__enclos_env__$private$first_names,
    last_names = (person_en_US$new())$.__enclos_env__$private$last_names,
    first_name = (person_en_US$new())$first_name,
    last_name = (person_en_US$new())$last_name,

    first_names_female = (person_en_US$new())$.__enclos_env__$private$first_names_female,
    first_names_male = (person_en_US$new())$.__enclos_env__$private$first_names_male,
    first_name_female = (person_en_US$new())$first_name_female,
    first_name_male = (person_en_US$new())$first_name_male,

    user_name_formats = c(
      '{last_name}.{first_name_female}',
      '{last_name}.{first_name_male}',
      '{first_name_female}.{last_name}',
      '{first_name_male}.{last_name}',
      '{first_name}##'
    ),

    email_formats = '{user_name}@{free_email_domain}',

    free_email_domains = c(
      'gmail.com', 'siol.net', 'email.si', 'volja.net'
    ),

    uri_pages = c(
      'index', 'domov', 'iskanje', 'main', 'novica',
      'homepage', 'kategorija', 'registracija', 'login',
      'faq', 'o-nas', 'pogoji',
      'zasebnost', 'avtor'
    ),
    uri_paths = c(
      'app', 'main', 'wp-content', 'iskanje', 'kategorija', 'novica',
      'kategorije', 'novice', 'blog', 'komentarji', 'seznam'),
    uri_extensions = c(
      '.html', '.html', '.html', '.htm', '.htm', '.php',
      '.php', '.jsp', '.asp'
    ),

    tlds = c('si', 'com')
  ),
  public = list(
    domain_word = function() {
      company = (company_sl_SI$new())$company()
      company_elements = str_split(company, " ")[[1]]
      company = private$to_ascii(company_elements[1])
      return(private$slugify(company, allow_unicode = TRUE))
    }
  )
)
# phone_number ---------------------------------
phone_number_sl_SI = R6Class(
  "phone_number_sl_SI",
  inherit = phone_number_init,
  cloneable = FALSE,
  private = list(
    formats = c(
      '040 ### ###',
      '041 ### ###',
      '031 ### ###',
      '030 ### ###',
      '070 ### ###',
      '01 #### ###',
      '02 #### ###',
      '04 #### ###',
      '05 #### ###',
      '06 #### ###',
      '08 #### ###'
    )
  )
)
# ssn --------------------------------------
ssn_sl_SI = R6Class(
  "ssn_sl_SI",
  inherit = ssn_init,
  cloneable = FALSE,
  private = list(
    vat_id_formats = 'SI########'
  ),

  public = list(
    vat_id = function(){
      # http://ec.europa.eu/taxation_customs/vies/faq.html#item_11
      # :return: a random Slovenian VAT ID
      return(private$bothify(private$random_element(private$vat_id_formats)))
    }
  )
)

# credit_card -----------------
credit_card_sl_SI = R6Class(
  "credit_card_sl_SI",
  inherit = credit_card_init,
  cloneable = FALSE,
  private = list(
    first_names = (person_sl_SI$new())$.__enclos_env__$private$first_names,
    first_name = (person_sl_SI$new())$first_name,
    last_names = (person_sl_SI$new())$.__enclos_env__$private$last_names,
    last_name = (person_sl_SI$new())$last_name
  )
)




# profile   ------------
profile_sl_SI = R6Class(
  "profile_sl_SI",
  inherit = profile_init,
  cloneable = FALSE,
  public = list(
    simple_profile = function(sex) {
      # Generates a basic profile with personal informations
      SEX = c("F", "M")
      if (missing(sex)) {
        sex = sample(SEX, 1)
      }
      if (!(sex %in% SEX)) {
        sex = sample(SEX, 1)
      }

      name = ifelse(sex == "F",
                    (person_sl_SI$new())$name_female(),
                    (person_sl_SI$new())$name_male())
      temp = list(
        "username" = (internet_sl_SI$new())$user_name(),
        "name" = name,
        "sex" = sex,
        "address" = (address_sl_SI$new())$address(),
        "mail" = (internet_sl_SI$new())$free_email(),
        "birthdate" = (date_time_init$new())$date_of_birth()
      )
      return(temp)
    },

    profile = function(fields, sex) {
      # Generates a complete profile.
      # If "fields" is not empty, only the fields in the list will be returned

      if (missing(fields)) fields = c()

      field = list(
        "job" = (job_init$new())$job(),
        "company" = (company_sl_SI$new())$company(),
        "ssn" = (ssn_sl_SI$new())$ssn(),
        "residence" = (address_sl_SI$new())$address(),
        "current_location" = c((geo_init$new())$latitude(),
                               (geo_init$new())$longitude()),
        "blood_group" = sample(c(
          "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"), 1),
        "website" = replicate(sample(seq(4), 1), (internet_sl_SI$new())$url())
      )

      field = append(field, self$simple_profile(sex))
      # field selection

      if (length(fields)) {
        nms = intersect(names(field), fields)
        field = field[nms]
      }
      return(field)
    }

  )
)





